### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by SugarDaddii** [BluSunrize/ImmersiveEngineering#571] opened 2015-11-02 19:10 UTC
http://paste.ee/p/FiCRN

**Comment by malte0811** [comment] 2015-11-02 19:13
Duplicate of #559

**Comment by SugarDaddii** [comment] 2015-11-02 19:18
okay i see it so to fix it uninstall all ADDONS or update to forestry 4 (what not possible because of binnie mod not supporting this)

**Comment by malte0811** [comment] 2015-11-02 19:23
disabling forestry compat in the config may also fix this, but i have not tried that yet

**Comment by BluSunrize** [comment] 2015-11-02 19:30
It does fix it, others have done that.

**Closed by BluSunrize** 2015-11-02 19:30 UTC

**Comment by SugarDaddii** [comment] 2015-11-02 20:09
what do you mean with disable forestry combat? do you mean Compatibility? and all to false or what do you mean?

**Comment by theunkn0wn1** [comment] 2015-11-02 20:28
In the ``ImmersiveEngineering.config`` file, change
 ```
    # Set this to false to disable IE's built in compatability with Forestry
    B:"Enable Compatmodule: Forestry"=true
```
on line 17 to
```
    # Set this to false to disable IE's built in compatability with Forestry
    B:"Enable Compatmodule: Forestry"=false
```

**Comment by SugarDaddii** [comment] 2015-11-02 20:40
you guys are very helpfull thx you very much!
