### ISSUE TITLE
[1.16] Excavator creating crash

### ISSUE THREAD

**Issue by RXtreme** [BluSunrize/ImmersiveEngineering#5010] opened 2021-10-06 08:07 UTC
### Description of the issue:
When I try to build Excavator on 1.16.5 with ImmersiveEngineering-1.16.5-5.0.3-138 it just crashes and I can't join the world where it happens

### Crashlog:

https://pastebin.com/GNwBe84X

https://pastebin.com/HncSLchf

### Versions & Modlist
ImmersivePetroleum-1.16.5-3.3.0-6.jar
ImmersiveEngineering-1.16.5-5.0.3-138.jar
forge-1.16.5-36.2.0-universal.jar

**Comment by RXtreme** [comment] 2021-10-06 08:10
When I try to build Excavator on 1.16.5 with ImmersiveEngineering-1.16.5-5.0.3-138 it just crashes and I can't join the world where it happens
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/7291936/latest.log)
.
[crash-2021-10-06_11.03.07-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7291942/crash-2021-10-06_11.03.07-server.txt)

**Comment by malte0811** [comment] 2021-10-06 09:29
Duplicate of #4960

**Closed as completed by malte0811** 2021-10-06 09:29 UTC
Labels: duplicate
