### ISSUE TITLE
[1.15.2] Workbench make the game crash

### ISSUE THREAD

**Issue by devmasu** [BluSunrize/ImmersiveEngineering#3967] opened 2020-06-12 18:11 UTC
**Description of the issue:**
I put a blueprint into my workbench, I then my game crash, and now I play anymore because the workbench do not render each time and make MC crash. That happened on my server for my gf and me, and also in solo because I tried to re-create the crash on a new map.

I also tried with only Biome O Pleny, JEI.

IE version: 0.15-99
Forge version: 31.2.9

Here is one of my crash report! 
[crash-2020-06-12_20.06.32-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4772515/crash-2020-06-12_20.06.32-client.txt)

BTW, thank you for this mod, keep me playing MC <3

**Comment by BluSunrize** [comment] 2020-06-12 18:22
Duplicate of #3908, please use the search function next time.

**Closed as completed by BluSunrize** 2020-06-12 18:22 UTC
