### ISSUE TITLE
Engineer's toolbox destroys items

### ISSUE THREAD

**Issue by Koltanas** [BluSunrize/ImmersiveEngineering#2472] opened 2017-09-09 13:42 UTC
I'm playing in 1.12.1 and the engineers toolbox destroys any items you put in it. Immediatly after closing the UI if carried and after some time when placed.

**Comment by BluSunrize** [comment] 2017-09-09 14:19
Version Numbers.
Crashlog.
Read the blasted debug guidelines.

**Comment by Onexa02** [comment] 2017-09-10 17:23
Happens to me, too, version 0.12 - 71. Happened on my custom singleplayer modpack, but I tested it and it happens even if IE is the only mod.

**Comment by malte0811** [comment] 2017-09-10 17:48
In that case: duplicate of  #2438. It's fixed for the next release.

**Closed by malte0811** 2017-09-10 17:48 UTC
