### ISSUE TITLE
0.10-49, conflict with Tinker's Construct?

### ISSUE THREAD

**Issue by DanWehr** [BluSunrize/ImmersiveEngineering#1697] opened 2016-11-19 20:10 UTC
Upgrading my IE version to the latest 0.10-49, I get a crash that may be related to Tinker's Construct. This seems to be the most relevant bit from the crash log:

`Caused by: java.lang.NoSuchMethodError: slimeknights.tconstruct.library.materials.BowMaterialStats.<init>(FFF)V
	at blusunrize.immersiveengineering.common.util.compat.TConstructHelper.preInit(TConstructHelper.java:77)
	at blusunrize.immersiveengineering.common.util.compat.IECompatModule.doModulesPreInit(IECompatModule.java:73)
	at blusunrize.immersiveengineering.ImmersiveEngineering.preInit(ImmersiveEngineering.java:88)`

The crash during load goes away by rolling back to 0.10-48.

**Comment by BluSunrize** [comment] 2016-11-19 20:47
Yeahp.
Either you pick up the newest TCon alphas that have the new bow stuff in, or you disable the TCon module for now.
Blame @bonii-xx for making me update to his new bow stuff =P

**Comment by kragnoth** [comment] 2016-11-19 20:54
Just a question on that, has he released the latest alpha on a specific site, or do you mean the latest compiled code from tconstructs github page?  I've compiled the latest source and that works, but I prefer to use dev released alphas rather than run on compiled source that might be in the middle of a rework on code.

**Comment by BluSunrize** [comment] 2016-11-19 21:16
There is no official builds that I can link to you, because apparently previous experience with very stupid users has led boni to no longer want them linked.
There is a maven, but I won't present you with it.

**Comment by kragnoth** [comment] 2016-11-19 21:27
Yeah that is fine.  Works single player, for some reason won't load with my server config.  Found a jenkins build server for tconstruct 2.5.6.283, but that suffers from the same crash as the one I compile for the server.  Wondering if its the mantle version I need to that is causing it on the server only.

**Comment by BluSunrize** [comment] 2016-11-19 22:05
Yeah I'm working on another build that will check for TCon's version to prevent this issue from happening with current TCon versions.
I was under the assumption that this new TCon was released, but my changes were solely requested for in-team testing,

**Comment by MohammadxCoder** [comment] 2016-11-19 22:17
what Tcon version that works with the latest version of IE?

**Comment by BluSunrize** [comment] 2016-11-19 22:18
441

**Comment by MohammadxCoder** [comment] 2016-11-19 22:21
where i can get it .... i look to github for tCon .... i only can see build 424 ?

**Comment by kragnoth** [comment] 2016-11-19 22:23
441 is on the maven repo, but seems to have some code that isn't working with the server jar.  That might be me just being silly, but I'm not so sure.

**Comment by MohammadxCoder** [comment] 2016-11-19 22:24
i'm playing single player :)

**Comment by BluSunrize** [comment] 2016-11-19 22:49
btw. I forbid any links to that maven.
You can find it from within this git repo, but for the sake of boni not yelling at me for directly sharing it, I don't want anyone to link it here.
Sorry folks, I realize it sucks, but I can absolutely understand his angle. Being forced to deal with issue reports on every possible jenkins build is /not/ fun. That's why I only release builds to curse. Saves me issues on intermediate versions =P

**Comment by NEXUS2345** [comment] 2016-11-20 03:00
Just tested build 241 and 242 of Tinkers, and neither of them work on server side, so as Blu said, easiest thing to do is backdate to 0.10-48.

**Comment by BluSunrize** [comment] 2016-11-20 08:39
Yeah, the only builds that will work are 441+.
As I said, I will have a release with a version check today, but I haven't completely finished it yet.
Still ironing out kinks with JEI.

**Comment by Morpheus1101** [comment] 2016-11-20 13:17
This sound sprecisely the rror i was getting https://puu.sh/sotUF/6cb131d6ff.txt

Now goto go hunting to get new version of tcon for MMD

**Comment by BluSunrize** [comment] 2016-11-20 13:21
I wouldn't recommend putting Maven builds of TCon in a pack. That'll probably go south.
Also TCon 441 has a client access error which makes it crash on servers.

**Comment by Morpheus1101** [comment] 2016-11-20 13:39
tested using 442 with mantle form maven and yeah had server crashes, so placing an update of IE on hold till new vers of tcon is out

**Comment by BluSunrize** [comment] 2016-11-20 13:48
Or you wait for the new IE (hopefully due today) which includes a version check that should prevent it from crashing with under-versioned TCon builds =P

**Comment by Drakoflame** [comment] 2016-11-20 23:24
@BluSunrize how do I dissable the Tcon module so I can play with the "stable" versions of the mod without it crashing on startup?

**Comment by BluSunrize** [comment] 2016-11-20 23:37
wait a few minutes, fixed build is pending approval on Curse.

**Comment by BluSunrize** [comment] 2016-11-21 09:51
This is fixed now in Build 50, so: Closed!

**Closed by BluSunrize** 2016-11-21 09:51 UTC

**Comment by sandalle** [comment] 2016-11-21 19:08
Confirmed fixed in ImmersiveEngineering 0.10-50, thank you. :)
