### ISSUE TITLE
[1.10.2]Crash while browsing IE handbook

### ISSUE THREAD

**Issue by CreeperShift** [BluSunrize/ImmersiveEngineering#1533] opened 2016-10-04 07:43 UTC
Using Immersive Engineering 0.10 - 42 and 2094 Forge, we've had a few random crashes while browsing the IE handbook:

http://pastebin.com/ftccRy7W

Sadly no crash report was created, but here is the error log:

http://pastebin.com/rsTWSc79

The user in question was simply browsing through his handbook. Note that the world is relatively new, very few mods and the user join maybe ~30 minutes prior to this and has not built anything at all yet.

If you need more information, I'm happy to provide them!

**Comment by malte0811** [comment] 2016-10-04 08:03
Could you upload a mod list and the complete log (fml_client_latest or whatever it is called, in the logs folder of your MC instance) to pastebin or gist? If the log is too long for pastebin, try using gist. I have no idea what is causing this, a modlist and a full log may help.

**Comment by iPencil** [comment] 2016-10-04 08:19
Heya,

the modlist can be seen as "related projects" under the modpacks files:
https://minecraft.curseforge.com/projects/tranquility/files/2333873

We're not adding any mods manually. User did NOT have optifine installed.

Sadly I recieved the log like that, you can still see the last line of chat before that, but I guess you want to see if there are any errors during loading. I'll have to ask him to give me the full log when he logs back in tonight.

**I can however tell you that he managed to crash it again by randomly browsing through the book.**

**Comment by AEnterprise** [comment] 2016-10-04 08:28
this is the JVM itself crashing, can you ask him to update his java? that will most likely fix it

**Comment by iPencil** [comment] 2016-10-04 08:50
@AEnterprise 

He is using build 1.8.0_25-b18 which comes prepackaged with minecraft and curse. If I'm going to have to tell everyone who uses my pack to update their java manually I'm gonna have some big issues... :(

**Comment by iPencil** [comment] 2016-10-04 09:12
Okay I managed to reproduce the crash. It happens while you are on the page "Ear Defenders". I've managed to crash it 3 times so far.

As AEnterprise said updating java to the latest version helps, the crash only occurs with the prepackaged java version.


While this means that updating java will fix this issue, I don't see how it helps. You're going to have 90% of the users who stick to whatever java version that comes prepackaged. I mean the entire point of including java was so people would stop running old versions (6 & 7) AND so that people would not have to install java on their system to run minecraft. 

I'm asking you if it's at all possible to rework/make that page compatible with the prepackaged java version. Especially since all the other pages seem to work just fine. 

If you don't want to do that I will have to simply remove that page from the Manual, but that's something I only want to do as a last resort. 

There is just no way I'm going to get everyone to update their java :/

I hope you understand my point.


Also, just in case, the client log as requested:
http://creepgaming.com/fml-client-latest.log

**Comment by mindforger** [comment] 2016-10-04 10:52
i am confused, you say this is the prepackaged JRE but i found the following lines in your crashlog
`D:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u25\1677\hotspot\src\share\vm\prims\jvm.cpp` this looks like something i have seen before especially when playing MC on a MAC.

The used JRE looks like a cross compiled version (and to tell you one important thing, java8 has memory issues below Version 65 or was it 56? ) so installing a proper Java is an all time best solution.

Having an issue with the runtime itself is almost IMPOSSIBLE to understand and solve, as even when you try to debug it, you will probably never encounter the fault at any time except on this one particular PC with this one particular arrangement of mods.

You said you "reproduced" it, but what you do not tell, the same machine, another machine, which commons do they share?

**Comment by iPencil** [comment] 2016-10-04 11:08
I said it's the prepackaged version because I pulled the version from his cut off log and it's the same as the one that comes with minecraft. When I asked him what java version he has he said "none i just use mc" so I assume he didn't exactly install some weird recompiled version but simply launched MC and happened to have it prepackaged...

I know that keeping java up to date is important, I do it all the time but there are enough people out there who have no need for java except Minecraft. They will not update nor install it because minecraft comes prepackaged with it.

You say it's almost impossible to understand however I've managed to reproduce the crash in a matter of minutes on a different machine with the same modpack. I can't tell you what his machine looks like but I'm sure it's not identical to mine... the odds are simply too great. 

I'm not saying spend the next 5 years fixing it, all I'm saying is that I can reproduce it by looking at the "Ear defenders" page and it crashed me with exactly the same message on that java version. This should at least be enough to get an idea of what is happening?

I do not see any mention of x32 version of java anywhere???

**Comment by mindforger** [comment] 2016-10-04 11:26
dealing with such errors not beeing able to be reproduced is the rule, you are prooving it by showing the exception :D (in german it means "Ausnahmen bestätigen die Regel")

you linked following 
https://minecraft.curseforge.com/projects/tranquility/files/2333873
is this the exact modpack?
can you give additional hints on how you installed it to make it more reproducible?
I assume this is done with the curse profile import? But i want to be 100% sure

The hint with the x32 is an general hint, because people tend to use the big fat ass download button on the java.com download page, which estimates your OS capabilities by the browsers user agent which is mostly 32bit not 64bit and thus donwloading the wrong runtime!

**Comment by iPencil** [comment] 2016-10-04 11:38
Yeah thats the exact modpack. I installed it by searching it by name via curse. Ram and Java settings were left as default. Haven't messed with java args or anything. It's fairly small and light so I haven't had to change or adjust anything.

I think one of the reasons I was able to reproduce this is because the guy had literally not built or done anything :P We give out the manual as a starter item so he was just casually browsing it and crashed twice, the second time on purpose :P 

Ah I see :P I assumed you were referencing to the crash or something, sorry :)

Also I appreciate you taking the time to look into it! I wish we'd live in a world were everyone is capable of updating a java version but sadly it's pretty much the opposite :P

**Comment by mindforger** [comment] 2016-10-04 11:56
every one would be able, if it weren't the web designer thinking of how could i automate it with the least effort ... 

by the way the crashlog revealed to me a pretty crowded and unoptimized memory layout, if you are running this pack on a dedicated sever with only memory options and no garbage collection optimization, i'd expect you to have pretty bad ticklag from time to time?! you can open a ticket on my IE branch that i made long time ago, where i could help you out with that :)

**Comment by iPencil** [comment] 2016-10-04 12:12
Very true :P Everything is automated and it's making people dumber by the minute :P 

I haven't noticed any tick lag due to garbage collection yet, but the world is pretty new (4 days lol) so I guess that's just a matter of time. I usually run very few java arguments for garbage collection but now that you say it I totally forgot to copy those over for that server :P 

I'll open a ticket there later tonight, awfully nice of you btw :)

**Comment by AEnterprise** [comment] 2016-10-04 13:55
reproducing those errors is usualy hard as you need to have a java version that is old enough to not have it fixed yet. to repoduce it also depends on what is exactly crashing internaly, some parts of the JVM are OS dependant, others are not

**Comment by ZiggyAdventures** [comment] 2016-10-17 17:37
More data for reproduction, this time using java bundled with minecraft in Curse 1.8.0_25 

https://github.com/whatthedrunk/allthemods/issues/233

**Comment by VallenFrostweaver** [comment] 2016-10-25 14:16
Easy to reproduce crash every time when clicking next arrow at bottom of right corner of page under the "Railgun" topic. No other mods installed but Forge 12.18.2104 and IE 0.10-47

**Comment by malte0811** [comment] 2016-10-26 10:13
@VallenFrostweaver That is a different crash, it properly crashes MC instead of the JVM and is caused by the new config system. I am looking into fixing it now.
I can't reproduce the original crash though, I blame Curse for giving people a Java edition that is 2 years old (Java 8 Update 25 was published October 14, 2014 according to https://java.com/en/download/faq/release_dates.xml). I vote for closing this unless someone manages to reproduce this with up-to-date Java (Java 8 Update 111 as of October 26, 2016)

**Comment by mindforger** [comment] 2016-10-26 12:01
@malte0811 not is is old, it is also looking like an linux version, compiled for windows using mingw

**Comment by AEnterprise** [comment] 2016-10-26 12:15
maybe we could contact them asking them to provide a newer version? we do have a valid argument for it here and i'm sure this isn't the only case

**Comment by mindforger** [comment] 2016-10-26 12:37
well it's mojang and vanilla minecraft, i doubt quiet a bit they care much about the requirements of forge and mods based on forge

**Comment by jikuja** [comment] 2016-12-10 22:17
While you are asking people to update java, please, remember that Java 8u60 breaks intel GPU driver support for some users. ref: https://github.com/LWJGL/lwjgl/issues/119#issuecomment-246220393

Currenr mojang's beta launhcer is bundled with java 8u51.

**Closed** 2017-09-09 16:01 UTC
