### ISSUE TITLE
Crash onBlockRightclick

### ISSUE THREAD

**Issue by Sunekaer** [BluSunrize/ImmersiveEngineering#4623] opened 2021-02-01 14:51 UTC
### Description of the issue:
Crash on load of the world
Doesn't crash on ImmersiveEngineering-1.16.4-4.1.2-129 but does on ImmersiveEngineering-1.16.5-4.2.0-130
Create is in the crash as its doing the click but its doing the click on a create block and not IE

### Crashlog:
https://paste.sunekaer.com/uzupoxicev.rb

### Versions & Modlist
https://paste.sunekaer.com/lucikasone.css
forge 1.16.5-36.0.13

**Comment by malte0811** [comment] 2021-02-01 15:02
Duplicate of #4604

**Closed as completed by malte0811** 2021-02-01 15:02 UTC
