### ISSUE TITLE
TCon Crash

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#1438] opened 2016-09-12 17:53 UTC
When enabling support for TCon, I get this crash:
http://pastebin.com/0gei4EgK

**Comment by BluSunrize** [comment] 2016-09-12 17:59
Please search previous issues before reporting, this is a duplicate of #1431 and #1429
Will be fixed in the next release, the new TCon version clearly said that all addons would break.

**Closed by BluSunrize** 2016-09-12 17:59 UTC

**Comment by WolfieWaffle** [comment] 2016-09-12 18:07
Ok sorry
