### ISSUE TITLE
Pole mounted transformers visually connect incorrectly.

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#3211] opened 2018-09-14 23:19 UTC
![2018-09-14_18 16 54](https://user-images.githubusercontent.com/12395262/45579030-8d267a80-b84a-11e8-953d-ed79e14a5cec.png)
Using IE 0.12-85
Functionally they work fine.

**Comment by malte0811** [comment] 2018-09-17 15:17
Works just fine for me. What other mods do you have installed? If you are using Immersive Tech, they currently have a bug that could cause this (FerroO2000/Immersive-Tech#74). Is this on a server or in singleplayer?

**Comment by Voxel-Friend** [comment] 2018-09-20 22:04
Sorry for the late response. Here is the modlist: http://modlister.com/user/Voxel_Friend. No use of Immersive Tech at all in the history of this particular pack. Interesting development, either me restarting minecraft fixed the visuals, or it might have only required a world re-log. This is in singleplayer creative.

**Comment by jeijj** [comment] 2019-02-02 16:04
I have the same issue, only the other way around:
![image](https://user-images.githubusercontent.com/47276318/52166361-79ea4d80-270c-11e9-8c23-84c25581d4ce.png)
Both the LV (white) and MV (gray) wires seem to connect to the LV connector on the transformer.

**Comment by jeijj** [comment] 2019-02-02 16:18
Also, seems like a duplicate of #3033.

**Comment by LeoBeliik** [comment] 2019-02-21 22:35
This bug seems to be caused with specific setups, but basically it happens when make the connectors on the transformer to change position or if you use the transformer from the back.
  https://imgur.com/aKzpfCX

-i'm gonna use the hv transformer as example:
https://imgur.com/Dj3UoJA

First right click with the hv wire on the mv connector and connect it to a hv connector on the opposite vertex, then connect the mv wire with a mv connector (this almost always bugs)
https://imgur.com/C4kBZEz

this is just straight forward, just use the transformer normally but from behind
https://imgur.com/SNgcJk9

To clarify this always happens when you put the wires first on the transformer and then connect them to the connectors, and i tested it with only IE 12-89 and forge 14.23.5.2814

**Closed** 2019-02-25 17:37 UTC
