### ISSUE TITLE
1.16.1 Full Server Side Crash with Turrets

### ISSUE THREAD

**Issue by ScoutMaester** [BluSunrize/ImmersiveEngineering#4153] opened 2020-07-31 07:12 UTC
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
When a gun turret locks onto anything, the entire server goes down. Upon restarting it immediately crashes again.

### Crashlog:
https://pastebin.com/FziGURU6 
https://pastebin.com/rcgsLqdv
(_These are 2 separate crashes regarding the same issue_)

### Versions & Modlist
https://pastebin.com/kkZfR64b **(Modlist <Enegmatica 6, Ver 0.2.0> _(Issue Persists in Ver 0.2.3)_**
Forge Version **forge-32.0.75**

**Comment by BluSunrize** [comment] 2020-07-31 07:58
Duplicate of #4104

**Closed as completed by BluSunrize** 2020-07-31 07:58 UTC
