### ISSUE TITLE
[1.14.4] Crash with press, posible quark error?

### ISSUE THREAD

**Issue by Pixelmnkey** [BluSunrize/ImmersiveEngineering#3830] opened 2020-04-24 11:19 UTC
Hey! I'm playing Enigmatica 4 version 0.5.3 wich uses 

ImmersiveEngineering-0.14-94.jar 

I'm trying to automate the press, when I tried to break it to move once the multiblock was built, the server crashed and it gave me a single item called "Metal press" wich was placeable and rendered as only the upper part of the press (the conveyor belts and the piston part) instead of giving me the steel scaffold, tried to replicate the error and server crashed again, something related to quark? Not sure how to read the log.
[crash-2020-04-24_13.04.53-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4528539/crash-2020-04-24_13.04.53-server.txt)

**Comment by Pixelmnkey** [comment] 2020-04-24 12:03
Aparently, tossing items to a belt crashes aswell, no idea if it's a modpack issue or a mod.

**Comment by malte0811** [comment] 2020-04-24 13:06
Duplicate of #3734 for the crash, #3774 for the metal press.

In general, when you somehow get an item that is a full multiblock you should destroy it and not play around with it. They are not meant to be used for anything more than e.g. the recipe category in JEI, WAILA/TOP overlays and advancement icons.

**Closed by malte0811** 2020-04-24 13:06 UTC
