### ISSUE TITLE
Scrolling anywhere past the builders goggles in the creative menu

### ISSUE THREAD

**Issue by Rotary0** [BluSunrize/ImmersiveEngineering#5502] opened 2022-12-15 19:53 UTC
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.0.0-153.jar

### How did it happen?

Whenever I scroll down past a certain point in the creative inventory menu, which is the bar that has the steel tools and the multimeter, even in the JEI menu my game crashes. I think it may have something to do with rendering the inventory image for a specific item? or maybe a missing texture? "The game crashed whilst rendering item
Error: java.lang.IllegalStateException: null"  is the error. 

### Crash Log

The game crashed whilst rendering item Error: java.lang.IllegalStateException: null - error code: -1

**Comment by CaptainGlac1er** [comment] 2022-12-16 03:49
I am also having the issue. It appears to be the railgun item.

**Comment by AechPro** [comment] 2022-12-16 05:10
Bump. I encountered this crash as well. To reproduce just search "@immersive" in JEI and the game will crash before the search is complete. Unsure if there is more than one object in immersive engineering that triggers this error.

**Comment by mindforger** [comment] 2022-12-16 05:34
Counter-Bump ... neither one of you presented a crashlog yet

**Comment by AechPro** [comment] 2022-12-16 05:40
https://pastebin.com/em7J28KY

**Comment by mindforger** [comment] 2022-12-16 06:07
does this happen without optifine ? (a new crashlog without OF would be nice)

**Comment by AechPro** [comment] 2022-12-16 06:15
The crash does not occur without optifine.

**Comment by malte0811** [comment] 2022-12-16 07:56
Duplicate of #5492. Fixed for the next build by 9aac40731d732d1e84eac426ecd12e5435b33f5a.

**Closed as not planned by malte0811** 2022-12-16 07:56 UTC
Labels: crash 💥
