### ISSUE TITLE
Bug, Thermal Expansion creosote 1.10.2

### ISSUE THREAD

**Issue by GameKnyte** [BluSunrize/ImmersiveEngineering#1969] opened 2017-03-17 01:12 UTC
For some reason the fluid created by the coke oven is broken in texture. I can't use it to make buckets internally and when piped out it can't be used. I've tried different tanks and even the tinker tank. They all don't work.  I think this is partially related to the creosote oil added by thermal foundation causing the problem. 

For example when I look up the recipe for treated wood in JEI it only gives me a recipe containing a bucket of thermal foundation creoste oil. This bucket has the missing texture. 

I'm presently deleting and then cheating in the buckets for crafting.

**Comment by malte0811** [comment] 2017-03-17 16:14
Neither TE nor TF seem to add creosote oil and I can't find a mention of it in either config file. Are you talking about crude oil? What pack are you using?

**Comment by GameKnyte** [comment] 2017-03-17 16:18
It's a small custom pack. I don't know how to post it so others can take a look but it's information in JeI says as follows:
Creosote Oil Bucket
Temperature: 300k
Added By: Thermal Foundation
Minecraft forge

**Comment by BluSunrize** [comment] 2017-03-17 16:41
TF does add Creosote, that's absolutely correct.

I assume you added Thermal Foundation to your world after you'd already used the pack with just IE, huh?
I think there's some caching of Fluids by Forge in the world's data or smth, I just don't remember how to find or delete it.

**Comment by GameKnyte** [comment] 2017-03-17 16:45
I added them the other way around actually. Needed power transmission and I love how IE wires work.

**Comment by BluSunrize** [comment] 2017-03-17 16:52
Odd that that's still an issue.
I specifically check to see if the fluid registers properly and use the other one otherwise .~.

Wonder why this is still a problem... :/

The file in question is level.dat in the save folder btw, using an NBT editor, you *might* be able to delete DefaultFluidList.
Doesn't solve the issue at it's core however .-.

**Comment by GameKnyte** [comment] 2017-03-17 17:01
I'll back it up and then try that. I'm going to report this to Cofh as well.

**Comment by KingLemming** [comment] 2017-03-17 18:08
As I mentioned on our issue tracker, we aren't doing anything other than adding a fluid, so I'm not sure what the issue is. :/ We also check for registration and keep a pointer to the correct one.

This may be a Forge issue.

**Comment by GameKnyte** [comment] 2017-03-17 18:10
Thank you both. I just wanted to make sure you are both aware of the issue. If there's a way to properly post my pack as is let me know aonyou both can take a look.

**Comment by GameKnyte** [comment] 2017-03-17 18:10
*so you

**Comment by BluSunrize** [comment] 2017-03-17 22:15
From what I can see @KingLemming we're doing basically the same thing to register the fluids, with the single exception that I use the boolean return of registerFluid() to decide whether to replace my fluid reference. But from what I can see that really shouldn't be causing this issue.

Very weird...

**Comment by KnightMiner** [comment] 2017-03-17 22:19
Is it possible that IE's fluid registers first, then TF's fluid chooses not to register. When loading the world, the fluid list still wants TF's fluid since it loaded with only that first (thus is the entry in the cached list), but that fluid no longer exists since it detected IE's and skipped loading.

**Comment by GameKnyte** [comment] 2017-03-20 08:07
Using NBTexplorer to delet the file was successful in fixing it. The fluid is now set to the IE version.

**Comment by GameKnyte** [comment] 2017-03-20 08:08
Delete*

**Comment by BluSunrize** [comment] 2017-03-28 08:36
I'll close this, sicne I honestly dunno how to fix this. Seems like a Forge issue to me.

**Closed by BluSunrize** 2017-03-28 08:36 UTC

**Comment by Xaraxia** [comment] 2017-06-09 09:17
Realising this is closed, but for the record we've had the exact same thing. A world made with TF, and IE added later.

**Comment by rashdanml** [comment] 2017-07-07 06:52
Just out of curiosity, how would you go about fixing this for a server? Download the level.dat file (from the server), edit with NBTexplorer, re-upload, and re-start the server?

**Comment by AbieTheFishman** [comment] 2017-07-08 02:08
Had same/similar issue - not really understanding above - I gave it a shot. Downloaded NBT Explorer found the DefaultFluidlist: under Forge - and deleted the thermalfoundation:creosote entry.

Creosote works now ! -- Did notice texture is different, now darker brown - was a yellow/green/brown before. 

Regardless thanks for the tips
