### ISSUE TITLE
[1.12.2] crash - ImmersiveEngineering Core

### ISSUE THREAD

**Issue by oldGlobula** [BluSunrize/ImmersiveEngineering#3295] opened 2018-11-16 17:17 UTC
Minecraft crashed when I tried to set waypoint in VoxelMap.

**Comment by BluSunrize** [comment] 2018-11-16 17:39
I'm going to close this due to complete disregard of issue guidelines.

I'll reopen in when you provided things like CrashReport, modlist, etc.

**Closed by BluSunrize** 2018-11-16 17:39 UTC

**Comment by oldGlobula** [comment] 2018-11-16 17:45
Sorry, I thought I did it.
mods: https://imgur.com/a/gozGLNC
crash report: https://pastebin.com/yERuYzwD

**Comment by BluSunrize** [comment] 2018-11-16 17:48
Crash is caused by a conflict of Optifine and Voxelmap from the look of it, you may have to remove one of those two.

Journeymap is a very good map mod and could serve you as a replacement for Voxel.
Optifine on the other hand will probably cause you more problems with IE's rendering in the future, so removing that is just as well of an option.

**Comment by oldGlobula** [comment] 2018-11-16 17:55
> Journeymap is a very good map mod 
IDK why but when I played modpacks with it, minimap was loading very slow.
