### ISSUE TITLE
1.20.4 - Placing (spilling) Liquids close to Tanks causes multiblock structure to disappear

### ISSUE THREAD

**Issue by Sniffity** [BluSunrize/ImmersiveEngineering#5912] opened 2024-04-13 02:33 UTC
### Minecraft Version

1.20.4

### Immersive Engineering Version

11.1.0-172

### Expected Behavior

When working near a Tank Multiblock, it is possible to place blocks in the spaces left between the bases at the feet of the Tank with the multiblock persisting. If liquid is placed in these spaces, the multiblock structure should also remain. This ensures that the multiblock does not disappear if, say, a bucket of creosote oil is accidentally "placed" (spilled) when working close by, making treated palnks.

### Actual Behavior

When liquid (tested with creosote) occupies the aforementioned space, the multiblock structure disappears. One of the fence posts at the base disappears as well. I have attached an image which attempts to show this.

![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/66455728/4398a8e9-ce48-4592-83ec-ca2776ac3e0b)

Of note: Treated wood fence posts do NOT disappear if liquid is next to them -it only happens when they're part of the Tank multiblock (perhaps Silo too? did not get a chance to test).

### Steps to reproduce

1 - Build a tank multiblock
2 - Place a bucket of creosote in the ground close to it
3 - If the liquid reaches the space between the two fence posts at the bottom of the multiblock, the structure wil disappear. 

### Debug Crash Log

https://justpaste.it/duycd

**Comment by AWAKEN-1** [comment] 2024-04-16 11:50
#5906

**Comment by AWAKEN-1** [comment] 2024-04-16 11:52
More than just tanks#5906

**Comment by AWAKEN-1** [comment] 2024-04-16 11:53
More than just tanks
#5906

**Comment by BluSunrize** [comment] 2024-04-20 13:05
Duplicate of #5906

**Closed as completed by BluSunrize** 2024-04-20 13:05 UTC
Labels: bug 🐛, duplicate
