### ISSUE TITLE
[1.14.4 Alpha] Game Crashing, probably minecarts with chests

### ISSUE THREAD

**Issue by coelhobf** [BluSunrize/ImmersiveEngineering#3690] opened 2020-03-23 22:31 UTC
### Description of the issue:
The world is opening, but crashes in few movements, i've tested in two different worlds.

### Crashlog:
https://gist.github.com/coelhobf/c5833d8290a94a773685f375da77c498

### Versions & Modlist
forge-1.14.4-28.2.3.jar
Botania+r1.11-378.jar
curios-FORGE-1.14.4-1.0.6.1.jar
Hwyla-forge-1.10.6-B67_1.14.4.jar
ImmersiveEngineering-0.14-93.jar
jei-1.14.4-6.0.0.27.jar
Patchouli-1.14.4-1.1-26.jar
ProjectE-1.14.4-PE1.0.1B.jar
StorageDrawers-1.14.4-6.0.6.jar

**Comment by malte0811** [comment] 2020-03-24 05:14
Duplicate of #3678

**Closed by malte0811** 2020-03-24 05:14 UTC
