### ISSUE TITLE
Direwolf20 [1.10.2] [Game crashes] Fluid pipe error

### ISSUE THREAD

**Issue by KillTyrant** [BluSunrize/ImmersiveEngineering#2469] opened 2017-09-06 06:10 UTC
Not exactly sure of the proper format as I've never bothered reporting bugs before. However, your mod has reinvigorated my interest in minecraft again so I figured I'd at least attempt to help you play test. So please bare with my inexperience. 

Right now, I have tinkerer's construct melting down my ore. I drain that liquid into the tinkerer's basin via IE's pump+fluid pipes. I have these pipes sorting out the fluid via IE's fluid routors. In the process of setting up my third fluid (gold). I placed a pipe right after the routor to connect to the basin which would convert the liquid gold to a gold block, but the pipe connected to the adjacent sorted fluid (liquid copper) and immediately crashed the game. The instance of MC closed out without an error code so I cant really copy and paste that.  

https://pastebin.com/A7hTeVHW

*Edited to add crash report*

**Comment by malte0811** [comment] 2017-09-06 06:18
Take a look at the [contributing guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md), they explain what a bug report should look like. There should have been a link to them above the editing area when you created the issue.

**Comment by mindforger** [comment] 2017-09-06 06:30
@KillTyrant even if you claim it does not "show" errors, look at your minecraft installation and join the crashlogs folder and see if you find one with a fitting date, alternate solution would be to check the latest log in the logs folder and paste the last ... let's say 100 lines ... to pastebin or similar

**Comment by kane-thornwyrd** [comment] 2017-09-06 07:27
you can use [Gist](https://gist.github.com/)

**Comment by KillTyrant** [comment] 2017-09-06 12:44
Found the crash report.  Edited my first comment to include it. Thanks everyone.

**Comment by mindforger** [comment] 2017-09-06 12:55
wow ... you built an infinite loop with fluidsorters

you can modify the world offline(mcedit for example) and remove the pump and **fix your piping** for a quick fix
    Block location: World: (56,10,346), Chunk: (at 8,0,10 in 3,21; contains blocks 48,0,336 to 63,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

cheat in a new pump then 

but this loop issue should be dealt with at some point

can you upload pictures of your setup when you got it fixed to have an idea how you built that loop?

**Comment by malte0811** [comment] 2017-09-06 13:09
Duplicate of #2347. This is fixed in 1.12, the fix won't be backported to 1.10 though.

**Closed by malte0811** 2017-09-06 13:09 UTC

**Comment by BluSunrize** [comment] 2017-09-06 16:14
^ what he said

**Comment by KillTyrant** [comment] 2017-09-06 22:24
Thanks peeps. Sorry about the lack of attention to detail. Ill be sure to double check the change log on future potential bugs. Quick question if its alright with you guys. I noticed youre on 1.11+. Since im using an older build. Should I completely refrain from submitting bug reports?

**Comment by BluSunrize** [comment] 2017-09-06 22:32
We're on 1.12 by now.

You can still open issues, it might be things that aren't actual bugs but are easily solved by a developers explanation. However, there won't be any further releases.

**Comment by KillTyrant** [comment] 2017-09-06 22:53
Understood and thanks again. Take care.

**Comment by mindforger** [comment] 2017-09-07 05:12
you still could restore the world using my workaround

**Comment by KillTyrant** [comment] 2017-09-07 23:09
Yeah, I sniped the pipe causing the infinit loop. I'll get around this issue by turning off the pump prior to doing work on pipes.
