### ISSUE TITLE
[1.16.1] java.lang.NoSuchMethodError: net.minecraft.client.gui.screen.Screen.renderTooltip

### ISSUE THREAD

**Issue by Lanvilla** [BluSunrize/ImmersiveEngineering#4087] opened 2020-07-16 15:45 UTC
### Description of the issue:
Client crashes when you open any of the Engineer's Manual pages

### Crashlog:
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/16/20 6:31 PM
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.client.gui.screen.Screen.renderTooltip(Lcom/mojang/blaze3d/matrix/MatrixStack;Ljava/util/List;IILnet/minecraft/client/gui/FontRenderer;)V
	at blusunrize.lib.manual.gui.ManualScreen.renderTooltip(ManualScreen.java:300) ~[?:?] {re:classloading}
	at blusunrize.lib.manual.SpecialManualElements.renderHighlightedTooltip(SpecialManualElements.java:68) ~[?:?] {re:classloading}
	at blusunrize.lib.manual.ManualElementCrafting.render(ManualElementCrafting.java:237) ~[?:?] {re:classloading}
	at blusunrize.lib.manual.ManualEntry.renderPage(ManualEntry.java:111) ~[?:?] {re:classloading}
	at blusunrize.lib.manual.gui.ManualScreen.func_230430_a_(ManualScreen.java:228) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:950) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.63.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$407/701166114.call(Unknown Source) [forge-1.16.1-32.0.63.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at blusunrize.lib.manual.gui.ManualScreen.renderTooltip(ManualScreen.java:300)
	at blusunrize.lib.manual.SpecialManualElements.renderHighlightedTooltip(SpecialManualElements.java:68)
	at blusunrize.lib.manual.ManualElementCrafting.render(ManualElementCrafting.java:237)
	at blusunrize.lib.manual.ManualEntry.renderPage(ManualEntry.java:111)
	at blusunrize.lib.manual.gui.ManualScreen.func_230430_a_(ManualScreen.java:228)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327)

-- Screen render details --
Details:
	Screen name: blusunrize.lib.manual.gui.ManualScreen
	Mouse location: Scaled: (135, 81). Absolute: (407.000000, 245.000000)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Lanvilla'/143, l='ClientLevel', x=-3.97, y=67.00, z=-73.64]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,-80), Chunk: (at 0,4,0 in 0,-5; contains blocks 0,0,-80 to 15,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 663 game time, 663 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:445)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:597)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$407/701166114.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 345047728 bytes (329 MB) / 850677760 bytes (811 MB) up to 6944456704 bytes (6622 MB)
	CPUs: 4
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6656m -Xms256m -XX:PermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.63
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.63-client.jar Minecraft {minecraft@1.16.1 DONE}
		forge-1.16.1-32.0.63-universal.jar Forge {forge@32.0.63 DONE}
		ImmersiveEngineering-0.16-106.jar Immersive Engineering {immersiveengineering@0.16-106 DONE}
	Launched Version: forge-32.0.63
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
```

### Versions & Modlist
Forge 1.16.1 32.0.63
Immersive Engineering 0.16-106

**Comment by malte0811** [comment] 2020-07-16 15:53
Duplicate of #4069

**Closed as completed by malte0811** 2020-07-16 15:53 UTC
