### ISSUE TITLE
[1.12.1] Toolboxes and Hwyla crash

### ISSUE THREAD

**Issue by Johannason** [BluSunrize/ImmersiveEngineering#2519] opened 2017-09-22 07:14 UTC
Looking at a placed toolbox that contains items, with Hwyla, causes an immediate crash. That world will also instantly crash on reload, as soon as it realizes a player is still looking at the toolbox.
First encountered in multiplayer, replicated in singleplayer.
Removing Hwyla allows the world to load so the toolbox can be broken.

Not sure if this is an IE issue or a Hwyla issue, I'm somewhat new at reading crash reports. The bit that stands out to me is that Hwyla seems to be trying to read more inventory slots than the toolbox has, and that throws an error.

### Crashlog:
[crash-2017-09-22_02.24.50-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1323694/crash-2017-09-22_02.24.50-client.txt)

### Versions & Modlist
Immersive Engineering 0.12-72
forge-1.12.1-14.22.0.2475

**Comment by mindforger** [comment] 2017-09-22 07:40
has already been fixed but i believe it is not published yet :)

if you search the issues, don't forgot to include closed ones

https://github.com/BluSunrize/ImmersiveEngineering/issues/2496

**Comment by malte0811** [comment] 2017-09-22 07:40
Duplicate of #2496. Fixed for the next release.
The problem is that the placed toolbox believes it has 27 slots while the item (correctly) believes it has 23 slots. This was fine while using IE's custom item inventories, but I changed the items to use capabilities in the last release, which don't just ignore a change in the slot count.

**Closed by malte0811** 2017-09-22 07:40 UTC
