### ISSUE TITLE
[1.12] Crash on Startup 

### ISSUE THREAD

**Issue by xAlicatt** [BluSunrize/ImmersiveEngineering#3252] opened 2018-10-07 05:14 UTC
### Description of the issue:
Launched custom modpack and after some loading, it crashed.

### Crashlog:
https://paste.dimdev.org/idigeqojaf.mccrash

### Versions & Modlist
IE: 85, Forge: 2768

**Comment by malte0811** [comment] 2018-10-07 05:44
Duplicate of #3241 and about 10 other issues. Downgrade Forge for now, there will be an IE build with a fix soon.

**Closed by malte0811** 2018-10-07 05:44 UTC
