### ISSUE TITLE
[1.14.4 Alpha] Both Crates double when broken in survival (not contents however)

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#3700] opened 2020-03-26 01:05 UTC
Description of the issue:
When you break a crate in survival it drops two crates, only one crate has the contents that you put Crashlog:
no crash, just gameplay.
Versions & Modlist

ImmersiveEngineering-0.14-93-db2147a0.jar
and Forge 28.2.3
and JEI
![IE 1 14 4 Alpha Crates Duplicate](https://user-images.githubusercontent.com/62522289/77599818-6257c080-6edc-11ea-9c46-4836fe5baa83.png)

**Comment by malte0811** [comment] 2020-03-26 05:30
Duplicate of #3691

**Closed by malte0811** 2020-03-26 05:30 UTC
