### ISSUE TITLE
[blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: java.lang.NoSuchFieldException: lootEntries

### ISSUE THREAD

**Issue by vlce-versa** [BluSunrize/ImmersiveEngineering#1530] opened 2016-10-02 09:36 UTC
`11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: java.lang.NoSuchFieldException: lootEntries
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at java.lang.Class.getDeclaredField(Class.java:2062)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at blusunrize.immersiveengineering.common.EventHandler.lootLoad(EventHandler.java:162)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_176_EventHandler_lootLoad_LootTableLoadEvent.invoke(.dynamic)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:595)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1048)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:152)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:81)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at java.lang.Thread.run(Thread.java:745)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: java.lang.NoSuchFieldException: lootEntries
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at java.lang.Class.getDeclaredField(Class.java:2062)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at blusunrize.immersiveengineering.common.EventHandler.lootLoad(EventHandler.java:162)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_176_EventHandler_lootLoad_LootTableLoadEvent.invoke(.dynamic)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:595)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1048)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:152)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:81)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
[11:32:55] [Server thread/INFO] [STDERR]: [blusunrize.immersiveengineering.common.EventHandler:lootLoad:172]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by GirafiStudios** [comment] 2016-10-02 09:37
Duplicate of https://github.com/BluSunrize/ImmersiveEngineering/issues/1449

**Comment by BluSunrize** [comment] 2016-10-02 09:38
Yes. And I LITERALLY just told you to use pastebin.

**Closed by BluSunrize** 2016-10-02 09:38 UTC
