### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by VortexHD** [BluSunrize/ImmersiveEngineering#4129] opened 2020-07-23 21:12 UTC
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
My server crashes and sometimes the client as well.
Only immersive engineering blocks in the world right now are the wires.

### Crashlog:
https://pastebin.com/6yvJe9wn

### Versions & Modlist
Not sure what IE is but I'm running:
Minecraft 1.15.2
Forge 31.2.31
Mod list for the server can be found above
Client mod list is here: https://pastebin.com/RuM2qEx7

**Comment by BluSunrize** [comment] 2020-07-24 12:24
Duplicate of #4111

**Closed as completed by BluSunrize** 2020-07-24 12:24 UTC
