### ISSUE TITLE
Crusher Issue: Tinkers' Ingots [IE 0.5.4]

### ISSUE THREAD

**Issue by dirtyfargo** [BluSunrize/ImmersiveEngineering#367] opened 2015-08-29 00:01 UTC
Immersive Engineering 0.5.4

Description: In my modpack, only when run on a server, my client crashes with the report linked below if I throw an ingot from Tinkers' Construct into a Crusher. The material is still processed in the Crusher however, and on reboot of the client the resulting grit/dust will be present outside of the output of the multiblock structure.

Client Crash Report: https://gist.github.com/dirtyfargo/a5a1b6b1c3e8081a9447

Ancient Warfare 2 could also likely be the cause as it is mentioned heavily in that crash report. I wasn't sure who to report this bug to, or if it's just a dumb mistake on my behalf, but if you can confirm that it's indeed an issue caused by the AW2 mod then I will send my report that way instead =) 

Things I've tried as a solution:
- Changing the list of preferred mod ID's that results of IE processes should stem from, in the immersiveengineering.cfg, in multiple different ways
- Used IE's provided Minetweaker support to remove crusher recipes and add my own crusher output for Tinkers Ingots

More info can be provided if need be of course. Thanks for your time :)

**Comment by theunkn0wn1** [comment] 2015-08-29 00:24
`//AW2 = "Ancient Warfare 2"`
Preliminary analysis of the crash log makes it appear to be Ancient Warfare 2.  Without AW2 i was unable to reproduce the crash. This bug might be an incompatibility between IE and AW2. 

since it was an AW2 function that induced this crash, and IE just happened to own the entity that fell victim, I would suggest go and reporting this to the author of AW2

**Comment by dirtyfargo** [comment] 2015-08-29 00:30
Alright, I will report it to the author of Ancient Warfare 2 now :)

**Comment by theunkn0wn1** [comment] 2015-08-29 01:06
Unable reproduce with AW2, i commented the details in the AW2 thread.

**Comment by BluSunrize** [comment] 2015-08-29 10:25
It's definetly AW, though initialized by IE.
they can fix it by checking that the iterator is smaller than the length of the array

**Comment by theunkn0wn1** [comment] 2015-08-29 10:27
This issue has already been resolved in the latest versions of AW2. The op
was using an out of date version that has this issue.

**Closed** 2015-08-29 10:55 UTC

**Comment by dirtyfargo** [comment] 2015-08-29 12:41
I was using Ancient Warfare 2.4.112 Full, which is the latest version on Curseforge, released a few days ago. But if its definitely Ancient Warfare 2 that is very helpful, thank you! :)
