### ISSUE TITLE
[1.12.2] NullPointerException while initializing game, possible Forge issue

### ISSUE THREAD

**Issue by xenolinguist** [BluSunrize/ImmersiveEngineering#2693] opened 2017-12-26 05:08 UTC
### Description of the issue:
Game crashes during Forge initialization screen. Based on on-screen text immediately prior, this is while stitching model textures. This crash coincides with an upgraded Forge version.

### Crashlog:
https://gist.github.com/xenolinguist/9880dc518972402fb2ee55079180c4b0

### Versions & Modlist
Forge version forge-14.23.1.2581
IE version 0.12-75.jar
minimal modpack assembled using Twitch client, IE is the only selected mod.

**Comment by bookerthegeek** [comment] 2017-12-26 06:30
Duplicate of multiple issues.

Downgrade forge to 2575 till next IE release.

**Comment by malte0811** [comment] 2017-12-26 06:56
^That.
Duplicate of #2672 and a lot of others. Fixed for the next release, use forge 2575 for now.

**Closed by malte0811** 2017-12-26 06:56 UTC
