### ISSUE TITLE
[1.16.1] Crash when using the engineer's manual

### ISSUE THREAD

**Issue by Taimavar** [BluSunrize/ImmersiveEngineering#4093] opened 2020-07-17 14:44 UTC
Every time (four crashes so far) I open the engineer's manual I get a crash. Not immediately on opening, but while still in the book

Crashlog: https://pastebin.com/wTaSgaQr

forge 1.16.1-32.0.63
ImmersiveEngineering 0.16-106

**Comment by malte0811** [comment] 2020-07-17 16:05
Duplicate of #4069

**Closed as completed by malte0811** 2020-07-17 16:05 UTC
