### ISSUE TITLE
[1.15.2] Engineer's Blueprint crashes game

### ISSUE THREAD

**Issue by plucactus1** [BluSunrize/ImmersiveEngineering#3971] opened 2020-06-13 13:04 UTC
I am playing with other mods and when I put Engineer's blueprint in Engineer's workbench game crashes

https://pastebin.com/6F7J6TD1 (pastebin link crash report)

https://pastebin.com/Ax6t9Z1k (modlist) (forge version = 31.2.9)

**Comment by malte0811** [comment] 2020-06-13 13:23
Duplicate of #3908

**Closed as completed by malte0811** 2020-06-13 13:23 UTC
