### ISSUE TITLE
Broken railgun[1.12]

### ISSUE THREAD

**Issue by Dovoski** [BluSunrize/ImmersiveEngineering#2741] opened 2018-01-17 19:28 UTC
### Description of the issue:
The railgun uses ammo, and power, but fails to fire a projectile.

### Versions & Modlist
JEI, Forge, and IE itself, all of which are at 1.12.2 are the only mods used during this bug.

**Comment by malte0811** [comment] 2018-01-17 19:35
Duplicate of #2714.

**Closed by malte0811** 2018-01-17 19:35 UTC

**Comment by Dovoski** [comment] 2018-01-17 20:36
my apologies
