### ISSUE TITLE
Metal Press Mold Recipe Issues

### ISSUE THREAD

**Issue by Bunsan** [BluSunrize/ImmersiveEngineering#876] opened 2016-01-14 21:22 UTC
For version 0.7. Forge 1566.

Crafting the gear mold recipe using forestry or Railcraft gears (have not tested other mods) produces a plate mold.

NEI does not show recipe for rod mold. Trying to craft with steel plates and either iron, steel or aluminum rod produces plate mold.

**Comment by malte0811** [comment] 2016-01-15 18:02
the issue is even worse, but it may be easier to track down now: the recipe for the plate mold is accepting ANYTHING in the middle (I just successfully used an IC2 mining laser).
[This](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IERecipes.java#L506) line is preventing the rod recipes from being registered. @BluSunrize, why is that there? [This](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IERecipes.java#L485) line doesn't make sense as well, it shows the gear mold in NEI/creative if there are any plates?

**Comment by malte0811** [comment] 2016-01-15 18:57
I have found the cause, `ShapedOreRecipe` is specifically looking for an `ArrayList` in the input (instead of a general `List`). The list used in the `ArrayListMultimap` you use to temporarily store the possible inputs does not extend `ArrayList` (even though the name suggests it, I noticed that while looking at the new input array in the debugger). And if the recipe ingredient is neither an `ItemStack` nor an `ArrayList`, `ShapedOreRecipe.matches` returns `true`.
I will PR a fix for this in a minute

**Closed** 2016-01-15 19:22 UTC
