### ISSUE TITLE
Graphics Missing After Forge14.23.1.2582 Update

### ISSUE THREAD

**Issue by AnnaMayBelle** [BluSunrize/ImmersiveEngineering#2701] opened 2017-12-28 19:35 UTC
![image](https://user-images.githubusercontent.com/32752060/34421284-6173678a-ebdc-11e7-8500-7bd572a24e19.png)

This one is a doozy to try to troubleshoot because it causes no crashes and seems to be related to Forge versioning, but Immersive Engineering is the only mod I've found it to effect so far.  Everything was fine and dandy using Forge 14.23.1.2561.  However, when I updated to 14.23.1.2582, making NO additional changes, suddenly all of my capacitors turn into the purple/black checkered boxes.  In addition, the powered lanterns appear fine in-hand, but turn into purple/black checkered boxes when placed in the world.

Here's my modlist (working copy of Farms, Friends & Fiends modpack): https://pastebin.com/TGjMngSA

**Comment by malte0811** [comment] 2017-12-28 20:09
Duplicate of #2672 (sort of). It is the same issue, they just catch the exception now and replace it with a missing model. Fixed for the next release.

**Closed by malte0811** 2017-12-28 20:09 UTC
