### ISSUE TITLE
Crash with TileEntityImmersiveConnectable

### ISSUE THREAD

**Issue by MJRLegends** [BluSunrize/ImmersiveEngineering#1208] opened 2016-06-21 15:45 UTC
Has been reported on my mod pack issue tracker and here are the issues related to this crash:

https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/341
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/312

**Comment by XFactHD** [comment] 2016-06-21 16:12
On first glance this looks like some mod is fucking up the ServerStartedEvent. The only thing (I think) could be null is ImmersiveNetHandler.INSTANCE which is set in the aforementioned event.

**Comment by mindforger** [comment] 2016-06-21 16:37
it was mentioned that chickenchunks bonked this up, i personally dislike his chunklöoaders for several reasons but @BluSunrize you could probably have a round of debugging while using those buggers :D 
my hint, place them in another dimension that will probably unload or be loaded on server startup ... sometimes beeing far away is enough to let them go wild but forecefully changeing their loadstate will make em fuck up NBT states (and probably worldobj) very well

**Comment by MJRLegends** [comment] 2016-06-21 16:56
One of them seems to be related to ChunkLoaders but the first link doesn't

**Comment by AEnterprise** [comment] 2016-06-21 17:02
first one could be chickenchunks as well, this wouldn't be the first time they load a TE in the wrong dimension with invalid data

**Comment by MJRLegends** [comment] 2016-06-21 17:08
Yeah maybe i could try and get copys of the worlds related to each crash but tbh im already removing chicken chunks in the next update. Also both mods have been in the mod pack a long time so maybe recent changes could of caused it to not like chicken chunks

**Comment by mindforger** [comment] 2016-06-21 17:23
@MJRLegends you could just remove the recipe, the tool via /chunkloaders is VERY helpfull

**Comment by AEnterprise** [comment] 2016-06-21 17:30
the problem with chickenchunks is that it works most of the times but there are edge cases where it does things in the wrong order or seems to have a race condition causing data to be swapped. It is rare but once the edge case occurs it keeps heapening, probably cause it stores what to load an how, if that goes wrong one time it'll load the wrong data next the next time as well

i'm no expert on the mod though, didn't write it, just stating what i know from observations and what i heard from others

**Comment by MJRLegends** [comment] 2016-06-24 01:11
so is this issue 100% confirmed to be chickenchunks?

**Comment by Watchful1** [comment] 2016-06-27 21:38
I'm getting a similar crash and happened across this thread. http://pastebin.com/QqcGL0QP

Appears related to chunk loaders, but the pack doesn't have chickenchunks.

**Comment by Watchful1** [comment] 2016-06-27 23:52
In my case, this crash seems to be related to quarries and immersive engineering wires. But it's not triggered by it. We had a number of IE wires powering quarries for a while, then something happened and it started crashing on world load. I ended up deleting all the quarries nearby and it loaded up.

I have a feeling this isn't the last I've seen of the crash, so I'll keep posting as I narrow it down.

A null check on that line wouldn't hurt though.

**Comment by mindforger** [comment] 2016-06-28 06:57
The Quarry only loads the one chunk it is working on and its main machine part AFAIK
this way it is more easily to reproduce for dev environment @BluSunrize @malte0811 

it is highly possible that there is still some invocation of CodeChickenCode and or fastcraft

@Watchful1 can you please make a screenshot of the chunk where your quarry block is installed and check if there is any other technical or magical mod stuff in range of the quarry loaded chunks?

**Comment by Watchful1** [comment] 2016-06-29 02:20
There were a large number of other blocks in the chunk, but unfortunately I ended up deleting just about all of them to get it working.

I'll try deleting just the quarries next time it happens and see if I can get a screenshot.

**Comment by AEnterprise** [comment] 2016-06-29 06:16
@Watchful1 what kind of quarry are you using?

**Comment by Watchful1** [comment] 2016-06-29 21:59
Buildcraft quarry.

**Comment by AEnterprise** [comment] 2016-06-30 10:37
the BC quarry doesn't do anything crazy for chunkloading, just uses forge tickets so forge handles everything.

**Comment by elementalistic** [comment] 2016-07-05 09:00
We're having a similiar issue with chunk loading, though we are using FTB Skyblock Infinity with Immersive Engineering 0.7.5.  We disabled all the permanent chunk loaders we could think off, then remembered by default the Poppet Shelf also chunkloads, after we had another crash caused by it.  

Yes the server is heavily modded so may not be much point posting the above's crash report.  But here it is.
[witchery_crash.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/347356/witchery_crash.txt)

**Comment by mindforger** [comment] 2016-07-05 09:19
@elementalistic unfortunately you are using unsupported modifications
`An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported.`

**Comment by MJRLegends** [comment] 2016-07-05 11:57
Well it's cleary a issue with just forge so i dont think its because hes using thermos to why its happening

**Comment by mindforger** [comment] 2016-07-05 13:18
as far as i could now discover similar problems, and as far as i understood the stacktrace, this could be an corrupted world issue, caused maybe by how the entities are stored and loaded!
it could be an issue with corrupted tile entities with uncomplete data beeing loaded while still beeing store dbecause of asynchronous access
but this is just roughly a guess, @BluSunrize could you probably add some guards or for testing purpose some try catch around your Utils.toCC so it wont accept unfitting types and not return null?

**Comment by Watchful1** [comment] 2016-07-06 02:19
Crash happened again. Identical crash report. The chunk looked like this

![2016-07-05_21 34 49](https://cloud.githubusercontent.com/assets/1574415/16604974/bc635792-42f8-11e6-8b70-a1142f207421.png)

There were two more wire connectors where the lapis blocks are now. I deleted them and the world loaded. Notably, I did not delete the quarry, and some of the wires in the background are in the same chunk as the quarry.

Interestingly, this allowed the world to load fine in ssp, but I had to delete the remaining wire connectors in the chunk for it to load on the server.

**Comment by mindforger** [comment] 2016-07-06 05:51
just as an idea, remove fastcraft from your server for testing!

**Comment by Crazyzora** [comment] 2016-07-09 13:04
Aright so this crash is happening to me as well. Same crash log. Story time:
I have it running on a server and was getting lag issues, the server was running behind by a full minute by the time I got around to debugging it. So I restarted the server and this crash comes up when I try to relaunch it.

My current setup has me running IE cables to my BC Quarry over several chunks. I have no chunk loaders other than the BC Quarry. This isn't a problem when I'm in the game because I'm near the generator powering all of this. I am also in the mining dimension.

From my understanding of IE is that the cables can transport power over unloaded chunks, which may be causing the problem. In addition this is the first time I have had the server down, so the IE stuff was set up and connected while the server was always running.

Ideally I would like to disable the power from being transmitted over the IE cables to see if that can get the server up again without uninstalling any mods. But I am unable to figure out how to do that.

I'm going to see if I can't recreate the crash on ssp.

**Comment by UnstableCodeScarlet** [comment] 2016-07-14 03:45
I believe I had this crash before when chunkloading my Coke Oven with FTBU, Make sure you have nothing chunkloaded using that either.

**Comment by AEnterprise** [comment] 2016-07-14 07:24
for tracing this: maybe hook into the crashreport to add all data from that block and the energynet to see what is messing up?

**Comment by MJRLegends** [comment] 2016-07-14 13:36
I might try downgrading from latest version of IE and give that a go

**Comment by MJRLegends** [comment] 2016-07-18 18:44
Update on this issue, i've downgraded IE to one below latest and its still happening but i think this is a BC issue not IE so im going to downgrade BC in my mod pack and see and im going to report it on the BC issue tracker

**Comment by Robijnvogel** [comment] 2016-07-25 19:04
Like XFactHD mentioned, The nullpointer is on ImmersiveNetHandler.INSTANCE, which is declared [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.7.10/src/main/java/blusunrize/immersiveengineering/api/energy/ImmersiveNetHandler.java#L32), but where does it get initialised? Could you point out that line for me please?

**Comment by XFactHD** [comment] 2016-07-26 00:14
It gets initialized in https://github.com/BluSunrize/ImmersiveEngineering/blob/1.7.10/src/main/java/blusunrize/immersiveengineering/ImmersiveEngineering.java in public void serverStarted(FMLServerStartedEvent event)

**Comment by Robijnvogel** [comment] 2016-07-26 16:28
Ah, on server start.
So the whole issue here is that Immersive Engineering's serverStarted event seems to not get called before all chunkloading mods' serverStarted events? Or maybe some other mods load chunks in an even earlier registered event?

Why not move the initialization of "ImmersiveNetHandler.INSTANCE" to the serverStarting event instead? (Or even earlier if possible).

**Comment by mindforger** [comment] 2016-07-27 05:56
if i remember correct, the issue happens right in the middle of a already started game ... there is possibly no way that the serverstarted event did not yet get called
also there are server dependend world object instances required to be fully loaded before the nethandler can start it's work properly if i remmeber correct
what i am curious about, is there a possible chance that the instance could be purged by the GC probably?

**Comment by Robijnvogel** [comment] 2016-07-27 17:46
Garbage collection cleaning up a static variable? That would be very weird, since that such a variable could be called at any time (and from about anywhere since it's public) and therefore should never be "collected as garbage".
Unless the actual class file gets unloaded for a moment there. Can Java do this? (Probably) Does Forge do this?

Just spilling random bullshit :tongue:

**Comment by malte0811** [comment] 2016-07-27 18:00
What is weird is that this issue first popped up more than a month after the version it happened on was released, and that version did not have any changes related to chunkloading or the energy net. From looking at the commit notes, 66203b782454dd48b32a1c646bc8e4c3769f1d5c (21th of MARCH) is the last commit that looks like it might have broken something like that. And while it is possible that this crash existed for a long time but wasn't reported, a lot of FTB Infinity players used IE wires in chunkloaded areas...
I personally suspect that this is either Java messing up big time or some other mod messing up.

I haven't been following this conversation too closely, has anyone found a reproducible test case yet?

**Comment by MagicMage1238** [comment] 2016-08-09 10:07
https://forum.feed-the-beast.com/threads/ftb-ininity-server-crash.164566/


I have also run into a Crash issue (3 logs attached in above Post)

will also attach logs here and if you want a copy of the server files I can do that also just let me know.
[crash-2016-08-08_06.01.59-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/408685/crash-2016-08-08_06.01.59-server.txt)
[crash-2016-08-08_12.01.51-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/408686/crash-2016-08-08_12.01.51-server.txt)
[crash-2016-08-08_16.07.31-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/408687/crash-2016-08-08_16.07.31-server.txt)

**Comment by jinks** [comment] 2016-08-10 13:46
I seem to be running into the same issue.
I upgraded FTBInfinity from 2.4.2 to 2.6.0 and thus IE from 0.7.3 to 0.7.7. The map loads fine with the old version.

The problematic connection is: IE HV battery -> HV connector -> HV relay connector (name? - the green upside-down thingy) -> 4x HV connector on top of MFSU.
Note: The green relay connector is hanging directly adjacent to a TE resonant fluxduct but not interacting with it.

I can set up the connection in-game and it works as expected, but as soon as I stop the server I can't start it again. Chunk is loaded via Immibis' dimensional anchor.

Two crash logs, although they don't tell anything new afaict.
[crash-2016-08-10_15.19.34-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/411180/crash-2016-08-10_15.19.34-server.txt)
[crash-2016-08-10_15.25.06-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/411181/crash-2016-08-10_15.25.06-server.txt)

**Comment by Robijnvogel** [comment] 2016-08-10 13:58
Are those blocks and connectors set up across a chunk boundary?
Can you reproduce this in every world?

**Comment by MJRLegends** [comment] 2016-08-10 14:07
Something has changed and its breaking a lot of mod packs, we just need to find the cause, to if its IE or another mod or a combination of mods

**Comment by MJRLegends** [comment] 2016-08-10 14:08
So far ive tried to downgrade buildcraft and IE but not together yet but still getting it, maybe try downgrade both mods?

**Comment by jinks** [comment] 2016-08-10 14:52
> Are those blocks and connectors set up across a chunk boundary?
> Can you reproduce this in every world?

Not crossing (or even touching) any chunk borders.
Replicating the same setup in another dimension causes the same crash.

**Comment by KnightMiner** [comment] 2016-08-10 21:42
By world I think he meant save file.

**Comment by MJRLegends** [comment] 2016-08-10 22:52
Does any one know what the cause is??? and a solution???

**Comment by MJRLegends** [comment] 2016-08-10 22:52
Opps didnt mean to close it :P

**Comment by Watchful1** [comment] 2016-08-10 22:54
On a world by world basis you can MCEdit out the connectors and it will launch again. No idea how to prevent it in the first place, I'm currently limited to simply banning the connectors.

**Comment by MJRLegends** [comment] 2016-08-10 22:54
yeah thats what i've been doing

**Comment by jinks** [comment] 2016-08-11 09:18
Same here...
different setups than the crashing one work fine on the server, the crashing one works fine in single player, A few other setups also work fine. I can't really find a spot to point at and say **this** is the problem.

**Comment by Robijnvogel** [comment] 2016-08-20 13:02
Just wondering if [this](https://forum.feed-the-beast.com/threads/165546/) may be "connected" to this issue here.

**Comment by MJRLegends** [comment] 2016-08-25 12:46
@BluSunrize any thoughts?

**Comment by MJRLegends** [comment] 2016-10-10 22:47
Its a shame this will never be fixed or even fully looked at....

**Comment by mindforger** [comment] 2016-10-11 07:11
well, there is actually an issue handling this particular "INSTANCE beeing null" and some wild guesses by me were garbage collector with active -XX:CMSClassUnloadingEnabled and some very agressive GCing + bad timing cleaning the Network Handler including the INSTANCE .... and somebody, I just forgot the name, meant making the INTANCE final could work against this issue probably ... let's see where this is going, i try to link the issue here

**Comment by MJRLegends** [comment] 2016-10-11 07:44
But why does it happen in single player and we kinda need the fix added and a build released before its actually fixed

**Comment by BluSunrize** [comment] 2016-10-11 07:48
What? This is independent of Multi or SIngleplayer. Garbage collection always applies. And if it's too aggressive, that causes problems.

**Comment by MJRLegends** [comment] 2016-10-11 07:49
It happens in single player and multiplayer yeah

**Comment by MJRLegends** [comment] 2016-10-11 07:56
@blusunriae any chance we could get the fix @mindforger has in a official build for 1.7.10 so we can hopefully fix this issue

**Comment by malte0811** [comment] 2016-10-11 08:46
Just as a note, the garbage collection isn't doing anything it shouldn't be doing here (assuming this is the same as in 1.10.2). I have explained the condition under which this happens [here](https://github.com/BluSunrize/ImmersiveEngineering/issues/1555#issuecomment-252664385), I will add a few details:
 - loading chunk loaders from the save file is done in an event handler with `HIGHEST` priority for the `WorldEvent.Load`-event.
 - when the chunk is loaded, the connector TE assumes that `ImmersiveNetHandler.INSTANCE` has been initialized
 - BUT said variable is initialized in the first run of an event handler for the `WorldEvent.Load`-event without a special priority, so AFTER chunk loading for that world has been handled

Therefore `ImmersiveNetHandler.INSTANCE` is null when a chunk loader in the first loaded dimension (usually the end) loads a connector, causing this NPE.

**Comment by AEnterprise** [comment] 2016-10-11 09:10
in this case the GC indeed wasn't the problem but it could have still heapened if you got extremely close to your memory limit as it was a non final self reference, but it's been fixed so all is fine now :)

**Comment by MJRLegends** [comment] 2016-10-11 22:39
@AEnterprise well yeah its fixed if we get a build with it

**Comment by KimBruning** [comment] 2016-10-31 18:50
This PR seems to backport the fix for this. https://github.com/BluSunrize/ImmersiveEngineering/pull/1653

**Comment by MJRLegends** [comment] 2016-10-31 19:02
@KimBruning nice, it would be great if @BluSunrize can merge it and release a build so i can use it in my mod pack :P

**Closed** 2017-05-12 10:32 UTC
