### ISSUE TITLE
1.12.2 VS 0.12-75 Carrots and Potatoes wont go in Garden cloche

### ISSUE THREAD

**Issue by Daihok41** [BluSunrize/ImmersiveEngineering#2633] opened 2017-11-25 00:53 UTC
Just like the title says in VS 0.12-75 for 1.12.2 carrots and potatoes wont go in garden cloche. Reverting back to 0.12-74 fixs this.

**Comment by AcidKat** [comment] 2017-11-25 17:06
Tested this with:

Minecraft Version: 1.12.2
Forge Version: 14-23-1-2554
IE Version: 0.12-75

Potatoes and Carrots both work fine for me... this is why we post with the proper format.

**Comment by Daihok41** [comment] 2017-11-26 11:20
Yea Im going through list of mods right now see what is causing the issue funny thing is though same mod pack just updating IE from -74 to -75 broke it. I tested with just thermal mods and IE and your right it worked. But like i said all the mods together with -74 everything worked but now it doesnt. I will try and find what mod is causing the issue though.

**Comment by mindforger** [comment] 2017-11-26 12:14
oh yeah pam is overwriting the original ones

**Comment by AcidKat** [comment] 2017-11-26 15:13
You can do a quick fix for this by changing the harvestcraft config, there's an option in there somewhere to disable the vanilla crop overrides (at least until IE gets an update hopefully). ^^

**Comment by mindforger** [comment] 2017-11-26 18:12
i believe integration is on pams side to do

**Comment by Xiaminou** [comment] 2017-12-15 23:39
What changed in 75? How come it's not working now when it was working before? Nothing changed in Pam's Harvestcraft so why is it on them?
I'm not pointing fingers here, just trying to understand.

**Comment by mindforger** [comment] 2017-12-16 10:24
i have no real knowledge on what changed, but there were recipe changes on forge side that IE had to adapt, maybe that broke compatibility?!

last time i've read about crop issues there was something that pam had to adjust to make it compatible, dunno if it has to be adjusted on here side or IE side ... i was just guessing to ask on Pam's issue tracker to find the source of the issue ... that's why i write "i believe" becasue i am not sure ... did you open an iaause on pams side and linked to this issue by chance? because i can't see any hint that this topic has been linked yet

**Comment by Koltanas** [comment] 2017-12-22 14:24
Noticed the same. But there I can't find that option in the Harvestcraft config.
Another bug with Pams Harvescraft: You can't craft cheese with the Assembler.
Minecraft 1.12.1
Forge 14.22.0.2463
IE 0.12-75

**Comment by SirWindfield** [comment] 2017-12-25 10:14
The only change from 74 to 75 made to the cloche should be [this](https://github.com/BluSunrize/ImmersiveEngineering/commit/20cbdfe10d5bbbfb0643635b7816371b4ecedbba?diff=unified) commit. I couldn't find anything else in the commit history.

**Comment by joselitosn** [comment] 2017-12-27 07:25
The problem is caused as to when the recipes are added. The Industrial Fermenter and Industrial Squeezer don't have these problems because their recipes are added during the registerRecipes event.
https://github.com/BluSunrize/ImmersiveEngineering/blob/830c0ffa39b8ed7dc0c508559030819e8bceaddd/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L348

Moving the recipes from the [BelljarHandler](https://github.com/BluSunrize/ImmersiveEngineering/blob/830c0ffa39b8ed7dc0c508559030819e8bceaddd/src/main/java/blusunrize/immersiveengineering/api/tool/BelljarHandler.java#L378-L393) to the registerRecipes event fixes it.

**Closed** 2017-12-30 23:45 UTC
