### ISSUE TITLE
[1.18.1] Can't open Engineer's Manual.

### ISSUE THREAD

**Issue by JtheV** [BluSunrize/ImmersiveEngineering#5194] opened 2022-01-23 14:15 UTC
### Description of the issue:
I can't open Engineer's Manual. When I try to do it, I get a message (1 entries failed to load! Please report this as an issue with your log file!). And the log says “java.lang.IllegalStateException: Config key ores.copper.min_y does not exist”.
Tested with IE on its own, issue disappeared , it might be a conflict with another mod.

### Crashlog:
To be precise, this is part of “latest.log” rather than the crashlog.
(https://gist.github.com/JtheV/4dd62ec3d9e6ea5f4174bf873e3813d7)

### Versions & Modlist
Forge version: 39.0.20
IE version: 1.18.1-7.1.0-145

Modlist: 
https://gist.github.com/JtheV/d1d3cb525a2fe1fbfb6c816307f1b438

Thanks for help.

**Comment by BluSunrize** [comment] 2022-01-23 15:08
Yeah it must be a conflict with another mod.
The first one I would try if I were you is removing Create Crafts & Additions.

If that isn't it, then I'm afraid you'll have to do a binary search:
1. Remove half the mods, see if the issue persists
2. If that fixed it, the issue is in the removed half, if the issue is still there, it's in the remaining half.
3. Keep halving your modlist until you find it.

**Comment by JtheV** [comment] 2022-01-23 15:10
> Yeah it must be a conflict with another mod. The first one I would try if I were you is removing Create Crafts & Additions.
> 
> If that isn't it, then I'm afraid you'll have to do a binary search:
> 
>     1. Remove half the mods, see if the issue persists
> 
>     2. If that fixed it, the issue is in the removed half, if the issue is still there, it's in the remaining half.
> 
>     3. Keep halving your modlist until you find it.

Thanks for reply. I'll try it when I'm free.

**Comment by JtheV** [comment] 2022-01-23 15:54
I've found the problem. I loaded a translation file belonging to an older version by accident.
Thanks for your help. I think you can close this issue.

**Comment by malte0811** [comment] 2022-01-23 18:12
You could also have closed it yourself, since you're the one who opened it.

**Closed as completed by malte0811** 2022-01-23 18:12 UTC
