### ISSUE TITLE
[1.12.2 - ATM3 Modpack] External Heater is invisible/transparent

### ISSUE THREAD

**Issue by Drytchnath** [BluSunrize/ImmersiveEngineering#2595] opened 2017-11-08 01:00 UTC
Did a search and didn't find anything quite like this:

[https://imgur.com/lmt8t33](url)
[https://i.imgur.com/SKyA2gb.png](url)
[https://i.imgur.com/XVtVJoa.png](url)

So, as seen the External heater is visible when held but invisible when placed on any surface, Same behavior on stone, grass, etc.

As seen in the screenshots it still works and heats the furnace for me while simultaneously letting me see through the world.

Modpack: ATM 3 v4.4
ImmersiveEngineering-0.12-74
immersivepetroleum-1.12-1.1.3
immersivetech-1.12-1.3.4

Forge: 14.23.0.2517

I've removed Immersive Tech since its a bit buggy in general but made no difference so I added it back in. I am also not using optifine, fastcraft or spongecraft or torcherino

**Comment by Pek94** [comment] 2017-11-08 04:01
Same problem here, but without the modpack, here is my mod list, on minecraft 1.12.2 and Forge 14.23.0.2531, but the problem is here for more than a month:

```
[1.12]UncraftingTable-1.8-beta6.jar
AbyssalCraft-1.12.2-1.9.4.1.jar
animania-1.12.2-1.3.6.1.jar
AppleSkin-mc1.12-1.0.9.jar
AutoRegLib-1.3-15.jar
base-1.12-3.4.2.jar
Baubles-1.12-1.5.1.jar
BetterFoliage-MC1.12-2.1.10.jar
BiomesOPlenty-1.12.2-7.0.1.2305-universal.jar
Bookshelf-1.12.2-2.2.485.jar
Botania r1.10-349.jar
BrandonsCore-1.12-2.3.3.132-universal.jar
Chameleon-1.12-4.1.3.jar
ChickenChunks-1.12-2.4.0.70-universal.jar
Clumps-3.0.0.jar
CodeChickenLib-1.12-3.1.3.313-universal.jar
corpsecomplex-1.12.2-1.0.1.1.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CTM-MC1.12-0.2.3.9.jar
davincisvessels-1.12-6.337-full.jar
Draconic-Evolution-1.12-2.3.4.265-universal.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
environmentalcreepers-1.12.1-1.2.1.jar
FancyBlockParticles-1.12.2-2.3.1.jar
forestry_1.12.2-5.7.0.209.jar
Hwyla-1.8.22-B37_1.12.jar
ImmersiveEngineering-0.12-74-core.jar
ImmersiveEngineering-0.12-74.jar
InventoryTweaks-1.63.jar
JAOPCA-1.12.2-2.2.4.53.jar
jei_1.12.2-4.8.0.114.jar
jeibees-0.9.0.5-mc1.12.2.jar
jeiintegration_1.12.2-1.5.1.36.jar
journeymap-1.12.2-5.5.2b1.jar
JustEnoughResources-1.12.2-0.8.5.27.jar
LycanitesMobsComplete 1.17.3.2 [1.12.2].jar
MagicBees-1.12-3.1.7.jar
MCA-1.12.x-5.3.1-universal.jar
mods_list.txt
Morph-o-Tool-1.2-16.jar
movingworld-1.12-6.342-full.jar
NoMobSpawningOnTrees-1.2.1-mc1.12.jar
OptiFine_1.12.2_HD_U_C6.jar
Quark-r1.3-114.jar
QuickLeafDecay-MC1.12.1-1.2.4.jar
RadixCore-1.12.x-2.2.1-universal.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
Repurpose-1.0.0.8.jar
roots-2-0.103.jar
Ruins-1.12.jar
stg-1.12-1.2.1.jar
StorageDrawers-1.12.1-5.3.3.jar
UniDict-1.12.2-1.2.jar
Uppers-0.0.3.jar
WanionLib-1.12.2-1.2.jar
Wawla-1.12.2-2.5.246.jar
WorldEdit CUI Forge Edition 2-2.1.2-mf-1.12.2-14.23.0.2487.jar
worldedit-forge-mc1.12-6.1.8-dist.jar
worldutils-1.12.2-0.4.2.jar
WrapUp-1.12-1.1.3.jar
```

**Comment by malte0811** [comment] 2017-11-08 06:57
Duplicate of #2552. Fixed for the next release.

**Closed by malte0811** 2017-11-08 06:57 UTC
