### ISSUE TITLE
Crash with forge 14.23.1.2581

### ISSUE THREAD

**Issue by lebanni** [BluSunrize/ImmersiveEngineering#2686] opened 2017-12-23 17:07 UTC
### Description of the issue:
Crash at start with MC 1.12.2 client (issue not happening with server).

### Crashlog:
https://pastebin.com/tgebYiZn
fml-client : 
https://pastebin.com/n246k74H

### Versions & Modlist
MC 1.12.2
forge 14.23.1.2581
IE 0.12-75
CTM 0.2.3.9

**Comment by malte0811** [comment] 2017-12-23 17:22
Duplicate of #2672 and a few others. Fixed for the next release, use forge 2575 for now.

**Closed by malte0811** 2017-12-23 17:22 UTC

**Comment by miuirussia** [comment] 2017-12-23 18:14
Builded from source, but it still does not work

**Comment by malte0811** [comment] 2017-12-23 18:48
Do you have any other mods installed? I'm 99% certain IE won't cause this crash on the latest version (830c0ffa39b8ed7dc0c508559030819e8bceaddd).

**Comment by miuirussia** [comment] 2017-12-23 18:55
Yes, today's clean build
