### ISSUE TITLE
[1.16.1] Workbench causes crash when rendering blueprint.

### ISSUE THREAD

**Issue by Vaerys-Dawn** [BluSunrize/ImmersiveEngineering#4247] opened 2020-08-25 07:40 UTC
### Description of the issue:
* Spawned into the world with an immersive engineering workbench, the workbench had a blueprint in it.
* It will also crash if the blueprint is placed into the workbench.

This was running on a personal server, the client crashes but the server does not.

### Crashlog:
https://pastebin.com/QKS3SXK4

### Versions & Modlist
Forge: 1.16.1 forge-32.0.108
IE: 1.16.1-3.2.0-115

Modlist: https://pastebin.com/k5vNFa3i

**Comment by Vaerys-Dawn** [comment] 2020-08-25 07:44
seems similar to bug fixed in 736084b, crash seems to be different however

**Comment by BluSunrize** [comment] 2020-08-25 07:57
Is this issue reproducable? Does it keep happening?

**Comment by Vaerys-Dawn** [comment] 2020-08-25 18:57
it keeps happening on join, it affected my friend at first, it started after adding a new mod to the modpack, removing it seemed to fix it. after crashing due to another bug we had to do another mod change and then it started affecting me, i will try removing the mod i just added and see if it crashes again but if it stops crashing because of this I'm not sure what's causing it because two different mods seemed to "trigger" it.

**Comment by Vaerys-Dawn** [comment] 2020-08-25 19:16
Tested joining the server a couple of times. Crashed 3 out of 5 times, the only times I didn't crash was when I loaded single player first.

so repro steps: 
* Have IE workbench with blueprint placed in the world.
* Join server 

Temp fix:
* Load singleplayer world
* Leave and then join the multiplayer world

Looks like something doesn't load properly and is then loaded when singleplayer is loaded first.

**Comment by BluSunrize** [comment] 2020-08-27 08:24
I guess here is that due to everything being multithreaded now, the render thread tries to access the recipe before recipe loading is complete.

@malte0811 maybe we should initialize all our recipe lists as empty and then replace them during loading? That could help prevent these multiple NPEs we've seen so far.

**Comment by BluSunrize** [comment] 2020-09-13 14:54
This should be fixed in recent versions.

**Closed as completed by BluSunrize** 2020-09-13 14:54 UTC
Labels: crash 💥, 1.16.1
