### ISSUE TITLE
Coke Oven and Blast Furnace 1.16.1 server

### ISSUE THREAD

**Issue by thatguymarsha11** [BluSunrize/ImmersiveEngineering#4098] opened 2020-07-18 13:48 UTC
I tried to use both the coke oven and the blast furnace on 2 separate mod packs and they wont light or activate. For the blast furnace, I load it with charcoal and iron and the light never turns on and makes steel for me. The same thing happens with the coke oven when I put coal in it. I am having this issue on a server, as I tested it on a single player world and it works. I do not know why the server is having issues for me with this.

**Comment by BluSunrize** [comment] 2020-07-18 13:52
Duplicate of #4073

**Closed as completed by BluSunrize** 2020-07-18 13:52 UTC
