### ISSUE TITLE
[1.12.2] (0.12-75) Issue #2561 still present in latest version (bucket wheel rotation)

### ISSUE THREAD

**Issue by aerde** [BluSunrize/ImmersiveEngineering#2700] opened 2017-12-28 17:49 UTC
Upon clicking on excavator bucket wheel, it's rotating in 90 degrees. I've tried rebuilding it in different axis, but this doesn't help.

### Versions & Modlist
Immersive Engineering 0.12 - 75
Forge 14.23.1.2566
"Modern Skyblock 2" modpack
Playing on LAN singleplayer

**Comment by malte0811** [comment] 2017-12-28 19:29
Duplicate of #2561, fixed for the next release.

**Closed by malte0811** 2017-12-28 19:29 UTC

**Comment by aerde** [comment] 2017-12-28 19:35
Oh, thanks! Thought, it was already fixed, as #2561 was closed two weeks ago. 
So, estimated time of next release?

**Comment by malte0811** [comment] 2017-12-28 20:11
Probably soon-ish. It most likely isn't going to get any more accurate than that.
