### ISSUE TITLE
Breaking feedthrough insulator crashes client

### ISSUE THREAD

**Issue by HamaIndustries** [BluSunrize/ImmersiveEngineering#4904] opened 2021-07-31 23:02 UTC
### Description of the issue:
Any time I try to break a feedthrough insulator with any tool, my client crashes (not the server). This is consistent every time with any type of block. This also occurs in singleplayer + without optifine.

### Crashlog:
https://pastebin.com/AqpNeSSb
https://pastebin.com/KQQG4WkM

### Versions & Modlist
Forge version: 36.1.61
IE version: IE 1.16.5-5.0.2-137
modlist: https://pastebin.com/NYFK8CZC

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment] 2021-08-01 07:22
Duplicate of #4879

**Closed as completed by BluSunrize** 2021-08-01 07:22 UTC
