### ISSUE TITLE
[1.18.2] Engineer's Crafting table disappearing items and Metal Press can't put in "wire mold"

### ISSUE THREAD

**Issue by Liladriel** [BluSunrize/ImmersiveEngineering#5248] opened 2022-04-05 21:20 UTC
Hello 

As Topic have small problem with 1 item and 1 multiblock

- Engineer's Crafting table
I don't have any crash, "Engineer's Crafting table" work but when i have items in the table after some time [few hours~to 1 day] my item disappearing from the inside, i check vanila and from mods, same thing.

- Metal Press
Just can't put in "Metal Press mold: Wire",. "Plate", "Bullet casing" work normal

Forge 40.0.36
Minecraft 1.18.2
Mod list: basicly with without 2~4 mods "All The Mod 7" mod pack

**Comment by St-Miller** [comment] 2022-04-07 02:42
I am having the same issues.  Using a self-made mod-pack.

**Comment by malte0811** [comment] 2022-04-07 07:27
The first point (crafting table) is fixed in the commit above.

I'm unable to reproduce the second point (wire mold) in dev. So it's most likely some mod interaction. ATM7 is a pretty big pack, can you narrow it down a bit (e.g. using binary search)?

**Comment by XFactHD** [comment] 2022-04-07 09:49
ATM7 also changes a lot of recipes, mainly via KubeJS, so it might be a good idea to also report this to ATM.

**Comment by Liladriel** [comment] 2022-04-07 15:21
Malte0811 "The first point (crafting table) is fixed in the commit above."
Can i download those file? i can't edit Java file (i don't have any program for that)

For now i use all other molds but this one don't want work (metal press don't want take it from me :P)

XFactHD "ATM7 also changes a lot of recipes, mainly via KubeJS, so it might be a good idea to also report this to ATM."

I will try to report to ATM

**Comment by enigmaquip** [comment] 2022-04-10 03:07
I checked ATM7's kubejs changes and they're at the current moment only messing with recipes for plates, rods and gears with the metal press.

On a fresh instance with only:
MC 1.18.2
Forge 40.0.44
IE 1.18.2-8.0.0-146
JEI-1.18.2-9.7.0.180

I am unable to install the gear die (there are no gear recipes needed with the above set anyways), nor the wire die. I see no crafting recipes using the wire die show up in jei. I'm assuming the metal press won't let you put in a mold that has no recipe uses.

log also shows:
`[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_gold as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/rod_aluminum as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/wire_aluminum as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_lead as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_uranium as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/rod_iron as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/wire_lead as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_copper as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_aluminum as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_silver as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/wire_electrum as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/wire_steel as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_nickel as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:crafting/raw_hammercrushing_iron as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/rod_steel as it's serializer returned null
[20:58:37] [Render thread/INFO]: Skipping loading recipe immersiveengineering:metalpress/wire_copper as it's serializer returned null
`

edited to add: looking at these errors further, I checked rods and the only metal press recipe is the graphite electrode recipe

**Comment by Liladriel** [comment] 2022-04-10 06:29
Yeap Have the same problem. "KubeJS" mod change a lot of recipe. You need to make you own recipe of graphite and metal press in this mod. In my world work. I write this because i fund problem. ATM don't respond to me anyway.

**Comment by malte0811** [comment] 2022-04-10 08:38
It looks like I "accidentally" fixed that a week ago in 265b8b23852a0c2cb43a60e056fdb29e2660b5b6, which explains why I wasn't able to reproduce it in dev. We check if the relevant tags are non-empty before adding the recipes, which was completely broken on 1.18.2. I thought this only affected mod integration recipes, so I just ignored it before the release. But apparently a couple of our non-integration recipes check as well, so those currently don't work.

**Closed as completed by malte0811** 2022-04-10 08:38 UTC
