### ISSUE TITLE
[1.16.1] Won't load on latest version of Forge.

### ISSUE THREAD

**Issue by Gbergz** [BluSunrize/ImmersiveEngineering#4147] opened 2020-07-29 12:25 UTC
### Description of the issue:
IE won't load on latest version of Forge.

### Logs:
https://hastebin.com/qujovikiwo.sql

### Versions & Modlist
**Minecraft:** 1.16.1
**Forge:** 32.0.97
**IE Version:** 0.16-109
Only Mod I'm using is Immersive Engineering.

### Screenshots
![image](https://user-images.githubusercontent.com/26634554/88799660-17f69100-d1a7-11ea-9430-66a8bf1d2367.png)

**Comment by malte0811** [comment] 2020-07-29 12:32
Duplicate of #4143

**Closed as completed by malte0811** 2020-07-29 12:32 UTC
