### ISSUE TITLE
[1.12.2] Chemthrower Not Throwing

### ISSUE THREAD

**Issue by RamWerkz** [BluSunrize/ImmersiveEngineering#2736] opened 2018-01-15 17:54 UTC
I tried using fluids from Immersive Petroleum and the base IE but fluids weren't being sprayed, it takes the fluid but nothing comes out. Aside from that the modifications and pilot light work
Edit: Sorry I tried the rail-gun and it doesn't work either so it was a mod interfering with IE's projectiles, I'll get back to this later with more info.

**Comment by malte0811** [comment] 2018-01-15 18:03
Semi-duplicate of #2714 (It's caused by the same bug).

**Closed by malte0811** 2018-01-15 18:03 UTC
