### ISSUE TITLE
Crash when opening the arc furnace page in the manual

### ISSUE THREAD

**Issue by thehobojoe** [BluSunrize/ImmersiveEngineering#1722] opened 2016-11-23 05:40 UTC
```
WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-59.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal (1).jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.144-universal.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  IvToolkit (IvToolkit-1.2.8.5.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-6.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 11/22/16 12:36 AM
Description: Rendering screen

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:187)
	at net.minecraft.client.gui.Gui.func_73729_b(SourceFile:114)
	at blusunrize.lib.manual.gui.GuiButtonManualNavigation.func_146112_a(GuiButtonManualNavigation.java:37)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at blusunrize.lib.manual.gui.GuiManual.func_73863_a(GuiManual.java:243)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:187)
	at net.minecraft.client.gui.Gui.func_73729_b(SourceFile:114)
	at blusunrize.lib.manual.gui.GuiButtonManualNavigation.func_146112_a(GuiButtonManualNavigation.java:37)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at blusunrize.lib.manual.gui.GuiManual.func_73863_a(GuiManual.java:243)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: blusunrize.lib.manual.gui.GuiManual
	Mouse location: Scaled: (188, 102). Absolute: (377, 275)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
```

**Comment by mindforger** [comment] 2016-11-23 07:20
you may use the search first, you are posting a duplicate issue! ... somewhere around the 5th or 6th

**Comment by BluSunrize** [comment] 2016-11-23 12:59
^ what he said. Duplicate of #1704, at least scroll through the issues on the first page >____>

**Closed by BluSunrize** 2016-11-23 12:59 UTC
