### ISSUE TITLE
[1.15.2] ImmersiveConnectableTileEntity

### ISSUE THREAD

**Issue by atoldiago** [BluSunrize/ImmersiveEngineering#4159] opened 2020-08-02 19:24 UTC
Im relatively new to the use of Immersive Engineering. Ive been a vanilla, or softly modded, Minecraft player for many years. I apologize if my lackluster search capabilities did not reveal this issue to be addressed already. I worked with the host service to figure out why our server crashed, and have the crash-report. ([Here ](https://pastebin.com/NmrcmxUA) is the pastebin for the crash report). I use Creeperhost, and have the link they provided for the crash report, if the pastebin doesnt work.

Forge: net.minecraftforge:31.2.33

Issue: Server crashed, it seems, as a result of Immersive Engineering having an error "unloading the connectors from the mod." (Creeperhost's words).

Immersive Engineering is new to me, as stated. I havent been building with it yet, but one person on the server has been. Again, Im very sorry if this issue has been addressed. Feel free to roast and close this down, but also please redirect to where its already addressed so I can learn. Thank you for your time.

**Comment by atoldiago** [comment] 2020-08-02 20:03
It happened again, about 15 minutes ago, same issue.

**Comment by BluSunrize** [comment] 2020-08-02 21:07
Duplicate of #4152

**Closed as completed by BluSunrize** 2020-08-02 21:07 UTC
