### ISSUE TITLE
[1.14.4] Crash on Startup

### ISSUE THREAD

**Issue by Rexxios** [BluSunrize/ImmersiveEngineering#3695] opened 2020-03-25 20:46 UTC
[crash-2020-03-25_12.57.33-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4383442/crash-2020-03-25_12.57.33-client.txt)

IE version 0.14-93
Forge Version 28.2.0

Happens when I launch the game, after FML pre-loads

**Comment by basilserpent** [comment] 2020-03-25 21:04
[crash-2020-03-25_22.01.55-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4383523/crash-2020-03-25_22.01.55-client.txt)
Can corroborate this issue. Happens when launched both with and without other mods.

**Comment by basilserpent** [comment] 2020-03-25 21:12
Found a solution: Use latest Forge for 1.14.4

**Comment by BluSunrize** [comment] 2020-03-25 22:16
Yeah, which is information you two would have found out by checking the most recent closed issues.

Duplicate of #3681

Please follow the contribution guidelines and issue template, and put your crashlogs on pastebin or gist. I dislike having to download log files.

**Closed by BluSunrize** 2020-03-25 22:16 UTC
