### ISSUE TITLE
[server] [1.18.2] ore raw change with a hammer into a grit

### ISSUE THREAD

**Issue by Nakijama** [BluSunrize/ImmersiveEngineering#5319] opened 2022-06-06 10:51 UTC
Raw ores when turned into powder with a hammer in engineering`s crafting table / Craftings when pressed together with shift they block the recipe (no repeat). tested on all raw ores, you need to restart the server. And while there were items in engineering`s crafting the tables were gone. On single player I was unable to repeat this disappearance. but you have to get in and out of the game. single clicking the recipe works
![Mods](https://user-images.githubusercontent.com/91394682/172146779-1c09ea5d-44f1-472b-97f8-931dac4461f4.png)
.

**Comment by BluSunrize** [comment] 2022-06-06 16:44
Duplicate of #5275

**Closed as not planned by BluSunrize** 2022-06-06 16:44 UTC
