### ISSUE TITLE
[1.15.2] Illegal state exception while rendering engineers workbench with blueprint inserted

### ISSUE THREAD

**Issue by coalman321** [BluSunrize/ImmersiveEngineering#3937] opened 2020-06-09 00:33 UTC
### Description of the issue:
[1.15]
After placing a blueprint into the engineers workbench, the client will crashes with a rendering error. It applies to any client currently containing the affected workbench in view. 

### Crashlog:
https://gist.github.com/coalman321/5a271026310058edc53650b0a852224a

### Versions & Modlist
```
forge-1.15.2-31.2.8-client.jar Minecraft {minecraft@1.15.2 DONE}
		tombstone-4.4.0-1.15.2.jar Corail Tombstone {tombstone@4.4.0 DONE}
		ImmersiveEngineering-0.15-99.jar Immersive Engineering {immersiveengineering@0.15-99 DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		forge-1.15.2-31.2.8-universal.jar Forge {forge@31.2.8 DONE}
		Psi r1.2-82.jar Psi {psi@r1.2-80 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-384.jar Botania {botania@r1.15-384 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		create-mc1.15.2_v0.2.4a.jar Create {create@mc1.15.2_v0.2.4a+custom DONE}
		refinedstorage-1.8.4.jar Refined Storage {refinedstorage@1.8.4 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 DONE}

```

**Comment by rjrelander** [comment] 2020-06-09 03:08
Duplicated with just IE running.

[Crash Report](https://pastebin.com/KT5JPzCn)

Minecraft 1.15.2
Forge 31.2.0
Immersive Engineering 0.15-99

**Comment by DeadlySwede** [comment] 2020-06-09 03:17
Duplicated running just IE. World also crashes on reload.

[Crash Report](https://pastebin.com/NKRq37g5)

Minecraft 1.15.2
Forge 31.2.0
Immersive Engineering 0.15-99

**Comment by malte0811** [comment] 2020-06-09 04:42
Duplicate of #3908

**Closed as completed by malte0811** 2020-06-09 04:42 UTC
