### ISSUE TITLE
[1.14.4 | 0.14-93] Game is crashing after loading a minecart with chest

### ISSUE THREAD

**Issue by Johnboiii** [BluSunrize/ImmersiveEngineering#3711] opened 2020-03-26 20:56 UTC
### Description of the issue:
Minecraft is crashing after it is loading a naturally spawned minecart with a cheast or after I palce one.

### Crashlog:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/26/20 9:54 PM
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.entity.item.minecart.ChestMinecartEntity cannot be cast to net.minecraft.entity.item.minecart.MinecartEntity
	at blusunrize.immersiveengineering.client.models.ShaderMinecartModel.func_78088_a(ShaderMinecartModel.java:31) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:107) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:15) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:359) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:543) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.3.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$387/1118414398.call(Unknown Source) [forge-1.14.4-28.2.3.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at blusunrize.immersiveengineering.client.models.ShaderMinecartModel.func_78088_a(ShaderMinecartModel.java:31)
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:107)
	at net.minecraft.client.renderer.entity.MinecartRenderer.func_76986_a(SourceFile:15)

-- Entity being rendered --
Details:
	Entity Type: minecraft:chest_minecart (net.minecraft.entity.item.minecart.ChestMinecartEntity)
	Entity ID: 6
	Entity Name: Minecart with Chest
	Entity's Exact location: -4.50, 65.06, 200.50
	Entity's Block location: World: (-5,65,200), Chunk: (at 11,4,8 in -1,12; contains blocks -16,0,192 to -1,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.MinecartRenderer@373c367
	Location: 1.00,-0.94,2.00 - World: (1,-1,2), Chunk: (at 1,-1,2 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.4800042
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370)
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:359)
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:543)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['GoneVision'/266, l='MpServer', x=-5.50, y=65.00, z=198.50]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-16,64,192), Chunk: (at 0,4,0 in -1,12; contains blocks -16,0,192 to -1,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 249 game time, 249 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$387/1118414398.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 329711592 bytes (314 MB) / 1487929344 bytes (1419 MB) up to 3008888832 bytes (2869 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3228m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
		ImmersiveEngineering-0.14-93.jar Immersive Engineering {immersiveengineering@0.14-testing-8737d9a7 DONE}
	Launched Version: forge-28.2.3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.50, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz

### Versions & Modlist
minecraft 14.4 with forge 28.2.3 and IE 0.14-93

**Comment by artillect** [comment] 2020-03-27 03:22
I'm getting this issue as well, same versions of everything.

**Comment by TeamSpen210** [comment] 2020-03-27 03:49
This is a duplicate of #3678, it'll be fixed in the next released version.

**Comment by malte0811** [comment] 2020-03-27 05:33
^That.

**Closed by malte0811** 2020-03-27 05:33 UTC
