### ISSUE TITLE
Conflict of versions - Immersive Engineering and TinkersConstruct [1.12]

### ISSUE THREAD

**Issue by ircmaan** [BluSunrize/ImmersiveEngineering#2354] opened 2017-07-23 17:49 UTC
23/07/2017 20:35
"Immersive Engineering is missing mods it depends on.
Include the following mods or remove IE.
tconstruct 1.12-2.8 or above"

But on the curse now we have only Tconstruct 1.12-2.7.1.9

Aru you seriously? :)
How it is possible?
Thanx

**Comment by nightcipher** [comment] 2017-07-23 19:00
Duplicate of #2349 
A mistake was made in the dependency for tconstruct with IE version 0.12 - 68. BluSunrize is aware of the issue and a fix will be pushed to live soon.

**Closed** 2017-07-23 19:24 UTC
