### ISSUE TITLE
Crush on Startup with version 0.6.0 (forestry problem?)

### ISSUE THREAD

**Issue by tecer0** [BluSunrize/ImmersiveEngineering#561] opened 2015-11-02 03:19 UTC
ImmersiveEngineering-0.6.0.jar
immersiveintegration-0.5.4.jar
forestry_1.7.10-3.6.12.3.jar
forge-1.7.10-10.13.4.1448-1.7.10-universal.jar

no problems with v. 0.5.4

http://pastebin.com/5DVMyE3j

**Comment by theunkn0wn1** [comment] 2015-11-02 03:27
Yes, this is your Forestry out of date. Duplicate of #599

**Comment by tecer0** [comment] 2015-11-02 03:43
oh sorry, i didn't see #559
hope in binnie update for download forestry 4.

thanks.

**Comment by theunkn0wn1** [comment] 2015-11-02 03:51
No problem, you are neither the first nor likely to be the last to discover this incompatibility.

Also, there are known problems with Immersive Integration and latest versions of ImmersiveEngineering. See #555

**Comment by mindforger** [comment] 2015-11-02 07:21
this is really a big pitty ... many people won't be able to update as it would destroy the world when removing bdew stuff. Even sengir did keep up a 3.6 branch and keeps updating it because the addons are yet not updated

**Comment by theunkn0wn1** [comment] 2015-11-02 07:24
Can we get an IE build compiled against the older APIs? Or is IE dependent
on the newer one?

**Comment by mindforger** [comment] 2015-11-02 07:34
or at least the question, is there any chance of breaking something when using 3.6 and compiling it on my own?

**Comment by theunkn0wn1** [comment] 2015-11-02 07:37
I am going to attempt to build IE with 3.6, one way to find out! :3
The second question is, even if we can build to 3.6 and it does not break anything obvious, is @BluSunrize going to support it or leave it out to dry?

**Comment by Carbon-Key** [comment] 2015-11-02 13:30
Disabling Forestry compat in the config lets it start up fine, but then I realized I don't know what I'm losing when I do that. What is the built in Forestry compat in IE? I'm just curious if anyone happens to know the answer.

**Comment by mindforger** [comment] 2015-11-02 13:50
nice info, as far as i can see only 

```
		ItemStack propolis = GameRegistry.findItemStack("Forestry", "propolis", 1);
		Fluid fluidHoney = FluidRegistry.getFluid("for.honey");
		if(fluidHoney!=null)
		{
			DieselHandler.addSqueezerRecipe("dropHoney", 80, new FluidStack(fluidHoney,100), propolis);
			DieselHandler.addSqueezerRecipe("dropHoneydew", 80, new FluidStack(fluidHoney,100), null);
		}

		FuelManager.bronzeEngineFuel.put(IEContent.fluidBiodiesel, new EngineBronzeFuel(IEContent.fluidBiodiesel, 50, (int)(2500*GameMode.getGameMode().getFloatSetting("fuel.biomass.biogas")), 1));

```

honey in the squeezer and compatibility of biodiesel to biomass

**Comment by BluSunrize** [comment] 2015-11-02 15:41
Yeah I worked with forestry 4. Disable the forestry module to fix it or update it.

**Closed** 2015-11-02 18:33 UTC
