### ISSUE TITLE
[1.11.2] [59-98_2] Squeezer doesn't appear to be forming correctly

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2106] opened 2017-05-19 07:56 UTC
When attempting to form a squeezer it will briefly flash the model and then become invisible apart from the clicked barrel. The hit boxes appear to remain as if it formed.
http://i.imgur.com/vaR6iki.png

When logging back in the squeezer appears to have reverted back to its block pieces.
http://i.imgur.com/WjMlCGd.png

Edit: right clicking to access the invisble squeezer will revert the piece clicked to a block rather than access to GUI.

**Comment by mindforger** [comment] 2017-05-19 08:04
press and hold f3 + c until you forcefully crash and post that crashlog, to get a bit more insight on your setup
also two thing upfront, can you reproduce that without optifine installed (if present)
and if this is a multiplayer, is sponge present ?

**Comment by BluSunrize** [comment] 2017-05-19 08:06
I know she's not on optifine. This is Forgecraft =P

Pretty sure I know the reason for this, I'll look into it ^^

**Comment by malte0811** [comment] 2017-05-19 11:40
Blu, what jenkins build does 59-98_2 equate to? 98? 99? Something in between?
@Rosethorns you can include screenshots in the bug report by dragging&dropping them into the editting area. They won't show up in the left/editting tab, but they should be present in the right/preview tab and the finished issue.

**Comment by BluSunrize** [comment] 2017-05-19 11:44
Something closer to 99.
Sky's Jenkins broke my permission so I had to build locally, sorry 'bout that.
Also, I've fixed this, push incoming.

**Comment by BluSunrize** [comment] 2017-05-19 11:44
Fixed by https://github.com/BluSunrize/ImmersiveEngineering/commit/d7da019246ac7df29a02a2bce467c7675c4dfdcd

**Closed by BluSunrize** 2017-05-19 11:44 UTC
