### ISSUE TITLE
Chemical thrower using fluid but not producing an effect or visuals.

### ISSUE THREAD

**Issue by Sinmiru** [BluSunrize/ImmersiveEngineering#2779] opened 2018-02-13 17:08 UTC
Currently using a new pack on Curse Forge called Raven Flight, but this has been present across the last two packs I've put to together. I made the chemical thrower, filled it with creosote, and tried it out (lit and unlit) but nothing seems to come out, can hear the sound (like air leaking? if that helps, never have actually got to use it so don't know if that's part of it.) and the gauge shows the fluid is being used, but no effect or visuals at all. Tried lava and water as well but no dice. Honestly not sure if this is on your end, just wanted to drop this here in case it's a simple fix. Love the rest of the mod, especially the cloche, great job there!

**Comment by malte0811** [comment] 2018-02-13 17:17
Duplicate of #2736.

**Closed by malte0811** 2018-02-13 17:17 UTC
