### ISSUE TITLE
[1.14.4 Alpha] Crash while generating world.

### ISSUE THREAD

**Issue by Gbergz** [BluSunrize/ImmersiveEngineering#3689] opened 2020-03-23 21:22 UTC
### Description of the issue:
I was walking around the world, near a village and the game closed & crashed.

### Crashlog:
[Gist GitHub](https://gist.github.com/Gbergz/8328bb3e94fb7be2e1969b87c4810f3d)

### Versions
IE Version: 0.14-93
Forge Version: 28.2.3
MC: 1.14.4

Other Mods (modlist): 
[Gist GitHub](https://gist.github.com/Gbergz/d3a14aaf79315793318fb723029a1b9d)

**Comment by BluSunrize** [comment] 2020-03-23 22:03
Duplicate of #3678

**Closed by BluSunrize** 2020-03-23 22:03 UTC
