### ISSUE TITLE
[0.12 - 77] Crude and Improved Blast Furnaces don't output steel

### ISSUE THREAD

**Issue by counterc** [BluSunrize/ImmersiveEngineering#2843] opened 2018-03-04 16:25 UTC
I can make the multiblock structures and place coal coke blocks and iron blocks in the correct slots, upon which the flame icon lights up and a progress bar appears. However, the progress bar remains at 0%, and after a while the flame icon disappears and eats the coal coke (but not the iron) with no outputted steel block.

**Comment by Lorelando** [comment] 2018-03-04 17:32
This is a duplicate of #2823 and #2821 and has been fixed with build 78.

**Comment by BluSunrize** [comment] 2018-03-04 20:12
yup, ^ that.

**Closed by BluSunrize** 2018-03-04 20:12 UTC
