### ISSUE TITLE
Dupe bug ie-tinkers

### ISSUE THREAD

**Issue by DnTheMn** [BluSunrize/ImmersiveEngineering#1629] opened 2016-10-23 03:11 UTC
im just fordwarding this as i feel it belongs here if you don't believe so please let me know i will be making an issue on the tinkers github however i will give you time to see if its your end or something they have done if you need information please let me know

https://github.com/whatthedrunk/allthemods/issues/241

**Comment by BluSunrize** [comment] 2016-10-23 08:26
Please read the contribution guidelines.
I need to know mod versions and all that jazz.
Specifically since creosote bottles aren't even in the mod anymore. So this person is clearly running an outdated version of the mod.

**Comment by malte0811** [comment] 2016-10-23 11:45
This sounds like a duplicate of #1586 to me.

**Closed** 2016-10-25 05:11 UTC
