### ISSUE TITLE
Weird Lava And Water Bug

### ISSUE THREAD

**Issue by Asais10** [BluSunrize/ImmersiveEngineering#2483] opened 2017-09-11 16:38 UTC
When i use chemical thrower to spray water, water is dark and after few seconds normal after seconds(Again) It turns dark again (I do not have a texture pack, but i have optifine, but i disabled clearer water option, but that does not change anything) same with lava i don't know what happens with other liquids but i think the same would happen
1.12.1 0.12-72 (Version)

**Comment by ktole1999** [comment] 2017-09-11 16:44
does it do the same thing when you remove optifine?

**Comment by malte0811** [comment] 2017-09-11 16:46
I can confirm this issue, I'll take a look soon.
In general @ktole1999 is right though, you should have tried removing OF before reporting (as stated in the contributing guidelines).

**Comment by ktole1999** [comment] 2017-09-11 16:49
i sometimes have shading issues while using optifine. i just deal with it.

**Comment by Asais10** [comment] 2017-09-11 16:57
ktole1999 yes without optifine the same thing happens

**Comment by Asais10** [comment] 2017-09-12 05:36
oops i acidently closed issue

**Comment by BluSunrize** [comment] 2017-09-14 10:26
@malte0811 any luck on this or are we just gonna file it under "Minecraft's entity lighting is terrible"?

**Comment by malte0811** [comment] 2017-09-14 11:36
Neither. I didn't have any success, but mostly due to the fact that the more I tried the less I knew what it was meant to look like, esp. night vs day. And that may be related to my first lectures at Uni being exhausting.

**Comment by malte0811** [comment] 2017-09-17 10:05
I closed this in 14c667326fbf658b1865b9aa05710d1b6044c6c4. I don't know why GitHub stopped showing the commit in the closing message.

**Closed** 2017-09-17 10:04 UTC
