### ISSUE TITLE
[FTB Infinity Evolved] Crash when entering RFTools dimension

### ISSUE THREAD

**Issue by herrgutt** [BluSunrize/ImmersiveEngineering#999] opened 2016-03-07 17:11 UTC
Hey,

McJty, the creator from rftools gave me a heads up that my problem might be because of Immersive Engineering. Please have a look:
I created a fresh RFTools world and upon entering the game crashed. Now the problem is that when i am trying to reenter the game i am stuck at the 'downloading world' for 1 second before the game crashes again.

Post from [RfTools git](https://github.com/McJty/RFTools/issues/466)
Link to ftb forumpost [http://forum.feed-the-beast.com/threads/ftb-infinity-crash-after-trying-to-enter-rftools-dimension-restart-is-not-working.148066/](http://forum.feed-the-beast.com/threads/ftb-infinity-crash-after-trying-to-enter-rftools-dimension-restart-is-not-working.148066/)
Link to error log [http://pastebin.com/J9mD5RAB](http://pastebin.com/J9mD5RAB)

**Comment by malte0811** [comment] 2016-03-07 19:26
I can confirm that this is not an issue caused by RFTools, this will happen when generating specific superflat worlds as well.
I have found a fix for this, but I am not sure whether that fix would cause even more issues: What situations are there where MC tries to get the light opacity of a block that is in an `IBlockAccess` that isn't a `World` (or more general, what situations are there where MC does anything with an `IBlockAccess` that isn't a `World`) and how much would break if the return value wasn't correct in that case?

**Comment by herrgutt** [comment] 2016-03-07 20:09
Thanks for your contribution!

**Comment by BluSunrize** [comment] 2016-03-07 21:25
I actually discussed with with Jty and Player earlier this morning. Player considers it a Forge error, I'm inclined to agree. The solution approach from my side would have been a blockLoaded check, which is exactly what malte did, so that's fine. New 1.7 build might be a little bit though, since I only just did one.

**Comment by herrgutt** [comment] 2016-03-08 13:56
Ok. Thanks for the response. How do I incorporate @malte0811 solution in the mean time? 
Thanks in advance

**Comment by malte0811** [comment] 2016-03-08 14:20
Unless you are able to compile IE yourself, you can't get the actual fix until the next release is out. If @BluSunrize permits it I could make kind of a fake build of IE for you that makes all blocks from IE opaque (therefore preventing the crash), which you could use to load the world and get out of that dimension (and delete that dimension just to be sure that MC doesn't just try to load that dimension again). It wouldn't really be suited for normal playing, so you would have to change to the official build afterwards, but it would allow you to leave that dimension without doing Nbt-editing.

**Comment by BluSunrize** [comment] 2016-03-08 15:45
new build will be necessary sooner than later due to the appearance of another java triggered crash. SO new build within this week.

**Closed** 2016-03-12 23:11 UTC
