### ISSUE TITLE
[1.17.1 | #39] Client Crash Rendering Blueprint In Workbench

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#5039] opened 2021-10-15 00:21 UTC
### Description of the issue:
Client crashes when rendering blueprint in workbench. Happened on IE test server and duplicated in single player.

### Crashlog:
[Crash Log](https://pastebin.com/p57qV8ys)

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.90
Immersive Engineering 1.17.1-5.0.2-pre.231 (Build 39)
Journeymap 5.7.3rc3
Just Enough Items 8.0.0.19

**Comment by malte0811** [comment] 2021-10-15 07:15
Duplicate of #5036 (at least for the root cause)

**Closed as completed by malte0811** 2021-10-15 07:15 UTC
