### ISSUE TITLE
[1.11.2] Client Crashed. When I move slot of Capacitor Backpack in inventory, crash occur.

### ISSUE THREAD

**Issue by Piccot1214** [BluSunrize/ImmersiveEngineering#2218] opened 2017-06-22 20:22 UTC
It often occurs.
Crash log here.
https://pastebin.com/1uFhag7B

**Comment by malte0811** [comment] 2017-06-22 21:07
Duplicate of #2189 and #2184. Fixed for the next release, even though I still need to talk to someone from Forge about the cause of this.

**Closed by malte0811** 2017-06-22 21:07 UTC
