### ISSUE TITLE
Crash - Open Inventory Creative - Optifine and drill related (?)

### ISSUE THREAD

**Issue by Artemyum** [BluSunrize/ImmersiveEngineering#5494] opened 2022-11-30 20:19 UTC
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### How did it happen?

Looking at immersive inventory in creative, crash at line 14. 

drill?

Optfine related?

### Crash Log

https://gist.github.com/Artemyum/9bf3853dc97b0a31b983dec6817777cf

**Comment by malte0811** [comment] 2022-12-01 08:21
Duplicate of #5492, even though that issue has a rather useless title (I'll rename it now). In general Optifine is not supported, I'll look into fixing it if I have time for it though.

**Closed as not planned by malte0811** 2022-12-01 08:21 UTC
Labels: crash 💥
