### ISSUE TITLE
[1.14.4] Minecart shader causing crashes

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3719] opened 2020-03-28 01:11 UTC
### Description of the issue:
When loading a minecart with IE installed the game crashes [crashlog](https://pastebin.com/NFsutw3j) this is on a server, so I can't really run a minimal installation up to test

### Versions & Modlist
ImmersiveEngineering-0.14-93.jar
Forge Version: forge-28.2.3
Mod List: 
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		ImmersiveEngineering-0.14-93.jar Immersive Engineering
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty
		pamhc2crops-1.14.4-1.0.3.jar Pam's HarvestCraft 2 Crops
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila
		Pam's DesertCraft 1.14.4-1.0.0.jar Pam's DesertCraft
		jei-1.14.4-6.0.0.27.jar Just Enough Items
		forge-1.14.4-28.2.3-universal.jar Forge
		create-mc1.14.4_v0.2.1.jar Create
		AutoRegLib-1.4-35.jar AutoRegLib
		Quark-r2.0-212.jar Quark
		Clumps-4.0.1.jar Clumps
		journeymap-1.14.4-5.7.0b1.jar Journeymap
		ReAuth-1.14-3.8.0.jar ReAuth

**Comment by Rambonata** [comment] 2020-03-28 01:16
I am also having this issue.

**Comment by alexstratford** [comment] 2020-03-28 01:18
According to the discord the issue has been solved and a fix should be released tomorrow

**Comment by malte0811** [comment] 2020-03-28 05:26
Duplicate of #3678

**Closed by malte0811** 2020-03-28 05:26 UTC
