### ISSUE TITLE
Crash when open a link in the book (Manual)

### ISSUE THREAD

**Issue by Wubbbi** [BluSunrize/ImmersiveEngineering#1725] opened 2016-11-24 01:06 UTC
Hello =)

When I open the Manual Book and search for something and click on the link that redirects to the page, my game crashes. This is the Crashlog: http://pastebin.com/Y1KGnWwb

Greetings Malrama :)

**Comment by mindforger** [comment] 2016-11-24 06:29
duplicate no. 7 or 8 .. pleeeeeaaaaaase use the search first .... i mean seriously it isn't that hard to use it or just scroll down the first poage a bit it is the 15th entry at this very moment!

**Comment by BluSunrize** [comment] 2016-11-24 09:14
Yup. Duplicate of #1704

**Closed by BluSunrize** 2016-11-24 09:14 UTC
