### ISSUE TITLE
[1.16.1] Mining drill/buzzsaw crash

### ISSUE THREAD

**Issue by peessddos** [BluSunrize/ImmersiveEngineering#4210] opened 2020-08-14 04:15 UTC
Whenever i'm using mining drill or buzzsaw to destroy blocks my game crashes and world becomes unaviable to play. At the last frame before crash drill successfully destroyed blocks as i could see. I have tried using this mod standalone - same result.

Mod version is 1.16.1-3.1-112
Forge Version is 32.0.106, but also i have tried 32.0.107

https://gist.github.com/peessddos/15110356958ab4cf60fce0f6d3029ae1

**Comment by jason-s-yu** [comment] 2020-08-14 04:22
Duplicate of #4179 and fixed in 01c38a6

**Comment by BluSunrize** [comment] 2020-08-14 05:49
^ this

**Closed as completed by BluSunrize** 2020-08-14 05:49 UTC

**Comment by peessddos** [comment] 2020-08-14 09:31
> Duplicate of #4179 and fixed in [01c38a6](https://github.com/BluSunrize/ImmersiveEngineering/commit/01c38a6ba62fccfdb575f94c77e2e2439744c5a1)

So you're saying i need to edit .jar file to fix it?

**Comment by BluSunrize** [comment] 2020-08-14 10:02
No, you need to wait for the next release.

**Comment by peessddos** [comment] 2020-08-14 10:32
Ok. Thank you.
