### ISSUE TITLE
[1.16.1] [Bug] Garden Cloche soil doesn't visible

### ISSUE THREAD

**Issue by KhanhPham05** [BluSunrize/ImmersiveEngineering#4296] opened 2020-09-13 06:43 UTC
### Description

When I use garden cloche for planting sugar cane, I use the sand as it's soil, put it in the right spot of the GUI and provide for it some water and energy, garden cloche still works , sugarcane growing still animated BUT the sand isn't visible

It also happened with dirt

## Game/Mods Infomation

IE [Standard] 1.16.1-4.0.0-118
JEI 1.16.1-7.0.1.10
The One Probe 1.16.1-3.0.1-beta
Forge 32.0.108

## Images
![2020-09-13_13 34 02](https://user-images.githubusercontent.com/68932626/93012049-0cc8ba80-f5c7-11ea-8c4a-82bbe63e8303.png)
![2020-09-13_13 34 05](https://user-images.githubusercontent.com/68932626/93012050-0e927e00-f5c7-11ea-8832-02df2e556d5b.png)

**Comment by malte0811** [comment] 2020-09-13 07:15
Duplicate of #4282

**Closed as completed by malte0811** 2020-09-13 07:15 UTC
