### ISSUE TITLE
[1.10.2] Crash when Placing Fluid Pipe under Extra Utils Generator

### ISSUE THREAD

**Issue by xlxAciDxlx** [BluSunrize/ImmersiveEngineering#1825] opened 2016-12-29 15:30 UTC
After placing a fluid pipe under a Extra Utils generator, my game crashed and the world can't be loaded.

*Immersive Engineering version:* 0.10-54
*Extra Utilities 2 version:* 1.1.3a

[Crash Log](https://gist.github.com/xlxAciDxlx/f1144d44a9286a8c89aa8564619b94d5)

**Comment by FiveEYZ** [comment] 2016-12-30 03:44
one of my players just now encountered this issue

here is the crash report:
https://gist.github.com/FiveEYZ/2df35b4cd11ec7769293c5f151a88065

**Comment by BluSunrize** [comment] 2016-12-30 08:11
Duplicate of #1810

Please use the search function ;)

**Closed by BluSunrize** 2016-12-30 08:11 UTC

**Comment by FiveEYZ** [comment] 2016-12-30 08:19
yes sorry, this issue was just exactly what i was looking for and just happen to be front of my eyes :S

**Comment by xlxAciDxlx** [comment] 2016-12-30 14:52
D'oh, sorry! I apparently suck at search queries and couldn't find anything similar.
