### ISSUE TITLE
Crash on 0.6.0

### ISSUE THREAD

**Issue by ReportBot9009** [BluSunrize/ImmersiveEngineering#562] opened 2015-11-02 05:22 UTC
Here's the pastbin: http://pastebin.com/FUqFv4Ng

**I'm sorry. I didn't read through a couple at the top before posting. It looks like this is the same as #555?

My mistake if the same.

**Comment by theunkn0wn1** [comment] 2015-11-02 06:47
Yeah, same crash. A quick glance over your crashlog shows you have Immersive Integration mounted... That amongst most other IE addons have not been rebuilt for 0.6

Duplicate of #555.

Please use search before posting issues, as your issue may have been reported by someone else

**Closed** 2015-11-02 15:22 UTC
