### ISSUE TITLE
Server and game won't start because of the same error

### ISSUE THREAD

**Issue by The-Goat-HUN** [BluSunrize/ImmersiveEngineering#5317] opened 2022-06-04 12:52 UTC
Both the server and Minecraft was working before, but after a bit of hiatus, they stopped working. I literally sent my friend my mods folder, which is the same as the server's mods folder, but it works for him. I have no idea why this error started occuring. I don't want to remove the mod, it would ruin and mess up our world.

Here's the log:
https://pastebin.com/WsNXB9Mt

Version: 1.18.2

**Comment by TheRanker** [comment] 2022-06-04 15:32
ive gotten the same issue once i added twlight forest.. remove it and loads perfect. 
just to add some context here.
[crash-2022-06-04_12.55.07-fml.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/8838142/crash-2022-06-04_12.55.07-fml.txt)

**Comment by simogut** [comment] 2022-06-05 05:24
Same here, when paired with Twilight Forest. A friend is able to load the pack without removing twilight.

[https://pastebin.com/XVsS6U9a](url)

**Comment by malte0811** [comment] 2022-06-06 11:11
Duplicate of #5312

**Closed as not planned by malte0811** 2022-06-06 11:11 UTC
