### ISSUE TITLE
1.16.5 - Mining drill server bug

### ISSUE THREAD

**Issue by Acidglow** [BluSunrize/ImmersiveEngineering#4709] opened 2021-03-12 12:07 UTC
Description:
After adding a drill head and upgrades to a Mining Drill, they mysteriously disappear moments later.

Steps to Reproduce:
Add a drill head and some miscellaneous upgrades to your Mining Drill on a multiplayer server. Remove drill head and then upgrades disappear, then put drill head back and it reappears.

Then dig a bit with the drill and put it back into the workbench, and now the upgrades are gone for good.

If you hold the drill in hand and open your inventory in creative mode, then the drill resets to its basic item without any drill head or upgrades installed anymore. 

Server log:
The server does not write any issues, while this process.

**Comment by BluSunrize** [comment] 2021-03-12 12:58
Did you spawn the drill in with JEI or creative?

**Comment by Acidglow** [comment] 2021-03-12 13:07
The first one was build, the rest of them I spawned in creative

**Comment by BluSunrize** [comment] 2021-03-12 14:13
Spawned in items are known to have issues with NBT data, this is a Forge issue.

Please try to reproduce this with a freshly *crafted* drill. Try it in Multiplayer and Singleplayer and report back, please.

**Comment by Acidglow** [comment] 2021-03-12 15:14
Tried to craft the drill. 
 - The drill is intact when opening creative inventory tap.
 - Upgrades still disapear in workbench, in both gamemodes.

**Comment by OMechanicos** [comment] 2021-03-15 22:32
I can confirm the same thing. In addition to all the above when you hold it it shows that there is no fuel even though I have fueled the drill

**Comment by BluSunrize** [comment] 2021-03-15 22:46
Please provide a debug crashlog.

**Comment by Rumils** [comment] 2021-03-16 08:01
I would like to chime in and say I have also experienced the same issues.

**Comment by BluSunrize** [comment] 2021-03-16 08:20
And I would like you to provide a debug crashlog, and not flat out ignore my last reply to another person that chimed in without any worthwhile info.

**Comment by Acidglow** [comment] 2021-03-16 08:27
I don't know how to get a debug crashlog, but I will try and Google it. And post it.
I tried to make a new server, and only having IE on it, and I still have the issue, so I don't think any of my other mods are causing the issue.

**Comment by Rumils** [comment] 2021-03-16 08:31
The fuel part being the most problematic, I have never been able to get fuel to successfully go into a drill using any method. I cannot get any fuel into the drill or the buzzsaw with Valhelsia 3.2.0a on a server I am hosting. Haven't had a change to try single player yet.

**Comment by OMechanicos** [comment] 2021-03-16 08:36
I might be dumb, but to sent you a proper crashlog the game has to crash, correct? Because the logs that I can find in the folder do not contain anything of value

**Comment by BluSunrize** [comment] 2021-03-16 08:45
Hold F3+C for 10 seconds. That generates a debug crashlog.
You would know this if you actually used the issue template and didn't ignore it =)

**Comment by OMechanicos** [comment] 2021-03-16 08:56
Thanks for the tip i will do it later when the server opens again, because in singleplayer there's no problem with the drill, for me at least.

**Comment by Rumils** [comment] 2021-03-16 19:10
My apologies, I work in IT and honestly know better. It was a late night, so I just made a quick post but that is still not a good excuse. I put together the following, hopefully it is helpful.

What is the bug?
Biodiesel not going into mining drill or buzzsaw (creatived in this just to test, same issue). I also experienced the disappearing attachments discussed above but it not do any testing for that. I should note buckets and jerry cans did extract the biodiesel as expected.

What did you do to make it happen?
Initially put a mining drill into a refinery with minimal biodiesel. It moved from the top output to the bottom but still shows it as empty. Attempted creating another drill doing the same with more biodiesel in the refinery and the same issue occured. Also tried filling from a barrel and also tried a creative fuel tank (none of the other items were spawned in in creative this was just done for testing). Also tried moving away from the spawn chunk I was trying this in and still have the same issues. 

Does it happen every time you do this?
Yes, everytime in the server. Have not had a chance to try single player yet (will report back on this).

Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer?
Dedicated server, I am personally host. I am connected via LAN personally.

What other mods were installed when the bug happened?
Valhelsia 3.2.0a

For the testing below I recrafted everything ensuring nothing was brought in through creative.

Pastebin of crash report: https://pastebin.com/6c80rQe6

Pastebin of server logs at the time: https://pastebin.com/TqXHPX13

Youtube video of the issue: https://youtu.be/vYPVj2L-miw

**Comment by BluSunrize** [comment] 2021-03-16 19:19
You are two versions of IE behind. These problems were addressed in Build 133.

I'm going to close this issue under the assumption that the other two people are also using outdated versions.
If any of you can reproduce this on Build 134, feel free to open a new issue for it.

**Closed as completed by BluSunrize** 2021-03-16 19:19 UTC
