### ISSUE TITLE
Tinker Tank Duplication with Immersive Engineering

### ISSUE THREAD

**Issue by SheReyy** [BluSunrize/ImmersiveEngineering#5355] opened 2022-07-10 21:00 UTC
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.16.5-5.1.0-148.jar

### Expected Behavior

-

### Actual Behavior

-

### Steps to reproduce

This issue was discovered on 1.16.5. I've posted an issue related to this on the Tinker's Construct Github and I was told to also post it here, since the problem also applies for 1.18.
https://github.com/SlimeKnights/TinkersConstruct/issues/4935#issue-1300011549

### Debug Crash Log

-

**Comment by BluSunrize** [comment] 2022-07-11 06:42
Way to completely ignore the issue template.

If you select 1.18 as a version, at least provide the version you tested with.

**Comment by BluSunrize** [comment] 2022-07-11 06:43
There will not be a fix for 1.16.5 for this.

**Comment by SheReyy** [comment] 2022-07-11 12:20
> There will not be a fix for 1.16.5 for this.

I'm not interested in any fix for 1.16.5. I reported this here only because I was asked by the people at TC. And the 1.16.5 version was mentioned here because that was the only version this was tested on. In the TC issue I was told this will also happen on 1.18.

**Comment by SheReyy** [comment] 2022-07-11 12:21
> Way to completely ignore the issue template.
> 
> If you select 1.18 as a version, at least provide the version you tested with.

Also, there was no 1.16.5 version to select in the template.

**Comment by BluSunrize** [comment] 2022-07-11 15:24
> Also, there was no 1.16.5 version to select in the template.

![img](https://user-images.githubusercontent.com/4106382/178299469-b8106f07-6699-4f7e-9f3a-593a572102c0.png)

Yep, because support for it as ended. Says it *right above the version selector*

**Comment by SheReyy** [comment] 2022-07-11 17:14
> 

Yes, but this issue is for 1.18. That's why I selected 1.18. And this bug was never tested on any of IE's 1.18 versions.

**Comment by KnightMiner** [comment] 2022-07-11 17:23
This bug was tested on 1.18 by Shiny based on [this comment](https://github.com/SlimeKnights/TinkersConstruct/issues/4935#issuecomment-1179796371)

**Comment by BluSunrize** [comment] 2022-07-11 17:43
Oh yeah, I don't doubt that this issue exists on other versions.
In fact, we literally have a report of that, right here: #5342

Could have just added to that, this is a duplicate.
The fix is easy too, just make the recipe not work when its a stacked container, easy as that.

**Comment by BluSunrize** [comment] 2022-07-11 17:43
Closing this because it's a duplicate of #5342

**Closed as not planned by BluSunrize** 2022-07-11 17:43 UTC
Labels: bug 🐛, 1.18.2
