### ISSUE TITLE
automated workbench not completing multiblock structure

### ISSUE THREAD

**Issue by Stonewolf14** [BluSunrize/ImmersiveEngineering#5937] opened 2024-06-01 02:29 UTC
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

just to complete the multiblock structure for automated workbench

### Actual Behavior

automated workbench not complete the multiblock structure when using the engineers hammer

### Steps to reproduce

1 put the automated workbench multiblock structure to getter 2 use the engineers hammer on the slabs 3 see if it complete automated workbench multiblock structure

### Debug Crash Log

https://gist.github.com/Stonewolf14/7a818b35c9043173d30a0489d1c08fb6

**Comment by Stonewolf14** [comment] 2024-06-01 02:37
update. the book image is showing wrong and it should just work with them going in the direction of the book iv been playing immersive engineering just used the automated workbench never notice the image until now that its different

**Comment by BluSunrize** [comment] 2024-06-08 11:53
Duplicate of #5934

**Closed as completed by BluSunrize** 2024-06-08 11:53 UTC
Labels: bug 🐛
