### ISSUE TITLE
[1.12.2] Agricraft Irrigation Tank Compatibility

### ISSUE THREAD

**Issue by Gawdin** [BluSunrize/ImmersiveEngineering#3186] opened 2018-08-26 08:34 UTC
### Description of the issue:
When a fluid pump is setup with Agricraft's Irrigation tanks as the input, it causes the server to crash as soon as redstone is applied to it. The client does not crash.

### Crashlog:
[crash-2018-08-26_04.21.35-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2321357/crash-2018-08-26_04.21.35-server.txt)

### Versions & Modlist
Forge: 2705
IE: 0.12-84
Agricraft: 2.12.0-1.12.0-a5

**Comment by malte0811** [comment] 2018-08-26 08:43
Duplicate of AgriCraft/AgriCraft#1167

**Closed by malte0811** 2018-08-26 08:43 UTC
