### ISSUE TITLE
I cant put disel fuel in my mining drill.

### ISSUE THREAD

**Issue by Broskiii** [BluSunrize/ImmersiveEngineering#4695] opened 2021-03-07 05:51 UTC
When i went to put the mining drill in the refinery it wont fill it up. Im not sure why, but ive looked at a lot of videos and they all haven't told me why. There is power to the refinery and it has biodiesel but it wont charge it.
Version 1.16.5

I even use a filled jerrycan and dit doesnt work, right click a tank filled with biodiesel and the arrow goes up to F but then drops back 
down to E. Please someone tell me why this is happening.

**Comment by malte0811** [comment] 2021-03-07 06:30
Duplicate of #4691

**Closed as completed by malte0811** 2021-03-07 06:30 UTC
