### ISSUE TITLE
Crash upon loading 5.0.1-136

### ISSUE THREAD

**Issue by Bidgam** [BluSunrize/ImmersiveEngineering#4874] opened 2021-07-05 18:52 UTC
Crash, see logs please. Using: 1.16.5 MC, forge-1.16.5-36.1.32, server crash.

Had previous version and rolled back to that as it works fine.

Crash Log: https://paste.enginehub.org/aFeeQSCBj

Thanks

**Comment by malte0811** [comment] 2021-07-05 19:00
Duplicate of #4873

**Closed as completed by malte0811** 2021-07-05 19:00 UTC
