### ISSUE TITLE
1.12.2 - Strip Curtain - Crashes game

### ISSUE THREAD

**Issue by xREDF0Xx** [BluSunrize/ImmersiveEngineering#2612] opened 2017-11-13 16:07 UTC
When I try to pleace down a Strip Curtain the game crashes. After it when I try to load the map it crashes always.

Mod List:
ImmersiveEngineering-0.12-74

Error message:
The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: -2

Any ideas how to fix this?

**Comment by malte0811** [comment] 2017-11-13 16:14
1. If we didn't know this crash already the info you gave us wouldn't tell us anything.
2. Duplicate of #2560 and a bunch of other issues. Known and fixed for the next release.

**Closed by malte0811** 2017-11-13 16:14 UTC
