### ISSUE TITLE
1.12.2 Accessing Recipes Crash

### ISSUE THREAD

**Issue by tipmon** [BluSunrize/ImmersiveEngineering#3533] opened 2019-08-05 15:44 UTC
Here is the Server Log: https://pastebin.com/qEMgQX94

Here is the latest.log: https://paste.ubuntu.com/p/gxbdMrgkzP/

It has happened atleast twice now. It seems to happen when I try to access a recipe from IE. It has happened both through JEI and through the questbook used in E2E.

**Comment by BluSunrize** [comment] 2019-08-05 21:31
You really should have followed the issue template.
Produce a debug crash and link it here, that provides a mod list.

Also, does this happen every single time you access an IE recipe, or just on some of them?

**Comment by tipmon** [comment] 2019-08-05 22:37
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

Full game crash occasionally when I try to open a recipe for IE either through JEI or through the quest book provided by Enigmatica 2: Expert

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

There is no crash-reports folder. 

Here is the Server Log: https://pastebin.com/qEMgQX94

Here is the latest.log: https://paste.ubuntu.com/p/gxbdMrgkzP/

Here is the .log referenced in the server log: https://pastebin.com/pLPEx6Cy

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

Here is the mod list: https://pastebin.com/DZuV7KxZ

It was in a large modpack fyi.

**Comment by tipmon** [comment] 2019-08-06 01:18
Just crashed again in the AE2 ME terminal while scrolling. 

Paste of end of server: https://pastebin.com/H0NhfV3U

Paste of file referenced in server: https://pastebin.com/hN0kT62q

**Comment by mindforger** [comment] 2019-08-06 05:17
It is that „quads“ crash again (Access violation jvm crash), i remember you had commented on something like that in a PR but i cant find it, i only find a few issues that never got resolved due to lack of cooperation from the reporter.

**Comment by BluSunrize** [comment] 2019-08-06 09:53
All I wanted was a debug crash. Is that so much to ask for? Just hold F3+C and give me that crash log. I can do so much more with that than manual modlists and these incredibly long log files.

Now, you keep saying server log, but what you are showing definitely aren't server logs. These aren't server issues. This is your client crashing, specifically when rendering certain things.

Additionally, you said this happens occasionally, not all the time. Can you provide more insight? Is it specific items that result in the crash when you look them up, or does it seem to happen on any of them?

**Comment by tipmon** [comment] 2019-08-06 16:07
F3 + C does not do anything in my game, the list provided by F3 + Q does not list that as a command. There was no crash file, there is not crash file folder in my instance, I have no idea how to create a crash file what so ever. You are correct, that isn't a server file, I am not sure what word to use for it. Console file? It isn't really a file, it is the text that the console outputs whenever it crashes. I am using MultiMC to manage my instances and it is giving me a nice console to look at things from.

As far as I noticed, it wasn't a specific item that was causing the crash but it might have been, I just can't be sure. It happened specifically 4 times, twice while looking up a recipe in the JEI, once while looking at the quest book provided by Enigmatica 2: Expert (Notably NOT while looking at an item or recipe, simply while opening the section on IE which has some icons), and once while scrolling through my AE2 ME terminal with all my items in it.

**Comment by mindforger** [comment] 2019-08-06 18:33
You need to hold f3 + c for a few seconds to force a crash and report

**Comment by malte0811** [comment] 2019-08-06 18:54
Something you should also try is updating Java. This crash is likely caused by a bug in the JVM, and your Java version is slightly outdated. You are on build 211, the latest is 222. If you don't want to create an Oracle account you can download the JRE here: https://adoptopenjdk.net/ (choose Java 8 Hotspot, JRE if it asks whether you want that or a JDK).

**Comment by PrincessRTFM** [comment] 2019-08-07 00:09
That's a console log, not a server log - in singleplayer, it combines your server and client logs, in multiplayer they are very much distinct and separate things. F3+C is a "hidden" debug tool; you hold it for, IIRC, ten seconds and it forces your game to crash with a log that can be _very_ helpful for developers. As malte0811 said, update your Java install, but also: I noticed FoamFix in your initial log - if updating Java doesn't help, disable/remove FoamFix and try again.

**Comment by BluSunrize** [comment] 2019-08-18 14:46
Closing this.

If the issue persists after updating Java, please provide new reports in here and I'll re-open it.

**Closed by BluSunrize** 2019-08-18 14:46 UTC
