### ISSUE TITLE
Conveyer Belt Wood Scaffolding Texture Glitch

### ISSUE THREAD

**Issue by JM4877** [BluSunrize/ImmersiveEngineering#5586] opened 2023-02-22 03:13 UTC
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.1.2-159

### Expected Behavior

Wooden scaffoldings conveyor belts having normal textures on top

### Actual Behavior

![image](https://user-images.githubusercontent.com/106126319/220508231-d66a1dfa-214b-4528-a617-38c91c604282.png)
Textures on the top of the scaffolding conveyor break. This is what it looks like with Rubidium enabled, with regular scaffolding and steel scaffold conveyors for reference. Conveyor belts covered with wooden scaffolding did not have this issue in 1.19.2-9.1.2-156 with Rubidium 0.6.2 enabled.

### Steps to reproduce

1. Have Rubidium enabled
2. Load or join a world with any wooden scaffolding conveyor belts
3. Look at wooden scaffolding conveyor belt from above

### Debug Crash Log

https://gist.github.com/Festivized-Hat/62881d9a1652be7c3096511432691197

**Comment by mindforger** [comment] 2023-02-22 05:43
this looks related to https://github.com/BluSunrize/ImmersiveEngineering/issues/5579
in short try without rubidium and check for their issue or a newer version as it seems they fixed it at least in dev

**Comment by malte0811** [comment] 2023-02-22 08:12
As mindforger said, this is most likely caused by Rubidium. I'll close this issue for now, please comment on it if you can reproduce it without Rubidium (I'll reopen it in that case).

**Closed as not planned by malte0811** 2023-02-22 08:12 UTC
Labels: bug 🐛
