### ISSUE TITLE
Engineering blocks not appearing when placed

### ISSUE THREAD

**Issue by sanguis3k** [BluSunrize/ImmersiveEngineering#2424] opened 2017-08-15 18:01 UTC
I was building some of the multiblocks on a 1.12 single player world using the High Tech mods a plenty pack and I noticed when I started placing the engineering blocks or steel scaffolding they would not render at all ( not the purple / black box just empty space ) they still reacted as if they were there and they still work as part of the multi block but it made it quite hard to properly check the multiblocks were built. these were the only blocks I could find with this issue. I have optifine installed but after copying the profile over and removing optifine the problem persisted and I can't find any mod conflicts or other issues that could be causing this.

![2017-08-16_02 00 01](https://user-images.githubusercontent.com/31045330/29328876-9d662bda-8226-11e7-930f-eab5c71f1b7d.png)
![2017-08-16_02 00 05](https://user-images.githubusercontent.com/31045330/29328878-9d6ee87e-8226-11e7-9e01-b81d6e34e176.png)
![2017-08-16_02 00 10](https://user-images.githubusercontent.com/31045330/29328877-9d68e564-8226-11e7-9b4e-43a2bf3ab3c3.png)

forgot to include the modpack is running the 0.12-70 version of IE

**Comment by malte0811** [comment] 2017-08-16 09:43
Duplicate of #2401. Disable Chisel compat in the config to temporarily fix this. It will be properly fixed in the next release.

**Comment by BluSunrize** [comment] 2017-08-16 10:03
And use the search function next time >>

**Comment by sanguis3k** [comment] 2017-08-16 10:56
sorry, I used the search function but couldn't find the answer. thank you for responding

**Comment by sanguis3k** [comment] 2017-08-16 11:17
also just tested this solution and it had absolutely no effect. blocks are still invisible even after a restart and in a freshly generated world with the compat disabled

**Comment by BluSunrize** [comment] 2017-08-16 11:42
Uhm...
You are very sure that you disabled the chisel compat?
Care to upload your immersiveengineering.cfg to pastebin or gist?

**Comment by sanguis3k** [comment] 2017-08-16 13:16
https://pastebin.com/0SuYhb2r
there you go, I turned everything but chisel back on after testing it on a fresh world because I didn't want it messing with recipes or anything else in my existing world.

**Comment by BluSunrize** [comment] 2017-08-16 13:25
it wouldn't mess with recipes. All it does is change a renderpass.
You made sure to save the file and *then* start the game? Because configs are only loaded on launch, and never again after unless you close the game and restart it.

**Comment by sanguis3k** [comment] 2017-08-16 13:33
yep. saved the file then started it, made a fresh world and it happened. deleted the world and flicked all the compats back to what they are in that pastebin jumped into my existing world and it is still happening. I was considering removing chisel or disabling it then trying a fresh launch to see if that would have any effect

**Comment by BluSunrize** [comment] 2017-08-16 13:35
Yup, please give that a shot. Throw out chisel to see if it does it.

**Comment by BluSunrize** [comment] 2017-08-16 13:35
Oh, also, could you please create a forced crashlog with F3+C and put it on Pastebin?

**Comment by sanguis3k** [comment] 2017-08-16 13:44
okay just loaded it up and with chisel removed and it's all working great. no idea why this worked when disabling it didn't. did you want the crash log for the current instance with chisel removed or the previous one with chisel on?
![2017-08-16_21 43 04](https://user-images.githubusercontent.com/31045330/29366189-eba12ab6-82cb-11e7-8290-11264066377e.png)

**Comment by BluSunrize** [comment] 2017-08-16 13:55
Either works.

Are those custom textures or something? They look blurred. Are you using a resource pack?

**Comment by sanguis3k** [comment] 2017-08-16 14:04
no, that is just the defaults, I think it's because I put it on fullscreen for those screenshots, when it isn't stretched out they look normal
[2017-08-16-6.log.gz](https://github.com/BluSunrize/ImmersiveEngineering/files/1228431/2017-08-16-6.log.gz)
can't upload the log to pastebin because it's too big, so here's a zipped version

**Comment by BluSunrize** [comment] 2017-08-16 14:07
God damnit.
Thought so.

Put chisel back in and try all that again, but WITHOUT OPTIFINE. >_____>

**Comment by sanguis3k** [comment] 2017-08-16 14:17
okay that works. it's the first time I have actually had optifine cause any problems. thanks for taking the time to work through it

**Closed** 2017-08-16 14:25 UTC
Labels: duplicate
