### ISSUE TITLE
Client crash [1.10.2]

### ISSUE THREAD

**Issue by UnNinja** [BluSunrize/ImmersiveEngineering#1427] opened 2016-09-11 00:46 UTC
[Crash log](http://pastebin.com/6EAv8UMh)
user said they attempted to connect one lv to another. one of the relays had a handful of wires linked to lv connectors

**Comment by theunkn0wn1** [comment] 2016-09-11 01:31
Can you reproduce this without Optifine?

**Comment by malte0811** [comment] 2016-09-11 06:39
Duplicate of #1420, should be fixed by 3ac6c5808069de010d9880520edefc31377331db.

**Comment by BluSunrize** [comment] 2016-09-14 10:43
I'll close this then ^^

**Closed by BluSunrize** 2016-09-14 10:43 UTC
