### ISSUE TITLE
[1.16.1] Server Crash on start

### ISSUE THREAD

**Issue by muddykat-tech** [BluSunrize/ImmersiveEngineering#4091] opened 2020-07-17 13:07 UTC
### Before reporting:
Searched, found nothing

### Description of the issue:
I start the server, server log goes well until after world has been loaded. then it crashes, It seems the issue is some function was renamed or something with the forge version I'm using?

### Crashlog:
Crash [Pastebin](https://pastebin.com/fX1n9nGT)

### Versions & Modlist
Forge Version 1.16.1-32.0.68
Immersive Engineering - Version: ImmersiveEngineering-0.16-106

That's it, no other mods or anything, although it as a mention I am running a dedicated server for this, just incase it wasn't obvious.

**Comment by malte0811** [comment] 2020-07-17 13:44
Duplicate of #4083

**Closed as completed by malte0811** 2020-07-17 13:44 UTC
