### ISSUE TITLE
Duplicate item using toolbox

### ISSUE THREAD

**Issue by trollrocker** [BluSunrize/ImmersiveEngineering#5940] opened 2024-06-05 16:57 UTC
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.1.0-171

### Expected Behavior

You are unable to move the toolbox around in your inventory while it's open.

### Actual Behavior

You can move it around while it's open.

### Steps to reproduce

https://github.com/BluSunrize/ImmersiveEngineering/assets/150524478/d2372a26-60f7-4b64-b2a2-4373ef8a87cc

if the video is not working

1 Open toolbox
2 Put something inside
3 move the toolbox to another slot in your inv
4 take out the item
5 open the toolbox again and repeat

Playing on a LAN server(Radmin VPN)

### Debug Crash Log

not required

**Comment by BluSunrize** [comment] 2024-06-08 11:52
Duplicate of #5936

**Closed as completed by BluSunrize** 2024-06-08 11:52 UTC
Labels: bug 🐛
