### ISSUE TITLE
[1.16] Mining Drill crashes when in use. After coming back from crash, you will crash again upon putting it in your hand

### ISSUE THREAD

**Issue by Bohbren** [BluSunrize/ImmersiveEngineering#4191] opened 2020-08-10 05:43 UTC
As the title explains - Drill is causing crash when in use. And after first crash you get another if you scroll and put it in your main hand

Forge: net.minecraftforge:32.0.99
 
Thanks for the great mod! 

Crash reports are linked below for both instances.
[crash-2020-08-10_00.32.19-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5049199/crash-2020-08-10_00.32.19-client.txt)
[crash-2020-08-10_00.27.20-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5049200/crash-2020-08-10_00.27.20-client.txt)

**Comment by malte0811** [comment] 2020-08-10 06:09
Duplicate of #4179

**Closed as completed by malte0811** 2020-08-10 06:09 UTC
