### ISSUE TITLE
Minecart problem [1.14, forge 28.2.4]

### ISSUE THREAD

**Issue by ribs498** [BluSunrize/ImmersiveEngineering#3699] opened 2020-03-25 23:56 UTC
Minecarts with, hoppers, chests, furnaces will immediatly crash the game. only mod active is Immersive engineering 0.14-93, 1.14
crash report: https://pastebin.com/XKWmQvNb

**Comment by Rexxios** [comment] 2020-03-26 04:44
crash report: https://pastebin.com/U4HCB8zt

I second this, IE 0.14-93, MC 1.14.4

**Comment by malte0811** [comment] 2020-03-26 05:27
Duplicate of #3678

**Closed by malte0811** 2020-03-26 05:27 UTC
