### ISSUE TITLE
Chemical Throwers loaded with Liquid Concrete consume fluid on use without any further action

### ISSUE THREAD

**Issue by Drullkus** [BluSunrize/ImmersiveEngineering#2772] opened 2018-02-10 15:48 UTC
If you use Chemical Throwers by holding down the Right Mouse, the tool will consume the Liquid Concrete without expelling any fluid visually or placing any Quickdry Concrete.

![Chemthrower](https://user-images.githubusercontent.com/5010174/36063808-8bcd0550-0e36-11e8-9881-bdc8d0116f45.png)

It seems though that Chemthrower Turrets work just fine.

![Chemthrower Turret](https://user-images.githubusercontent.com/5010174/36063793-50df6f32-0e36-11e8-9dea-6040a6847d5d.png)

Immersive engineering 0.12-76, Forge 2613

**Comment by malte0811** [comment] 2018-02-10 15:59
Duplicate of #2736.

**Closed by malte0811** 2018-02-10 15:59 UTC
