### ISSUE TITLE
wires disconnect on login

### ISSUE THREAD

**Issue by tebruuls** [BluSunrize/ImmersiveEngineering#160] opened 2015-07-02 13:52 UTC
Wires seem to be disconnecting when I load up my singleplayer world. this only happens directly after game loading.

**Comment by BluSunrize** [comment] 2015-07-02 14:43
you should probably mention which version you are running.

**Comment by tebruuls** [comment] 2015-07-02 19:30
0.3.3 (latest on curseforge)

**Comment by 016Nojr** [comment] 2015-07-08 14:26
Can confirm it happens with me aswell using version 0.4.0

**Comment by BluSunrize** [comment] 2015-07-08 14:44
does it happen every time the world is un- and reloaded?
Is it in the overworld or some other dimension?

**Comment by 016Nojr** [comment] 2015-07-08 14:44
Currently in a RfTools dimension, i'll test more

**Comment by 016Nojr** [comment] 2015-07-08 14:53
Seems like it may be happening randomly, it has happened one time. Tried leaving/entering dimension both loaded/unloaded, relogging chunkloaded/unloaded. I'll try restart the game

**Comment by 016Nojr** [comment] 2015-07-08 14:59
Yup, wires diseappear after restarting the entire client. Every time. Tried overworld and RfTools dimension

**Comment by BluSunrize** [comment] 2015-07-08 15:03
Log in in the overworld, place some stuff, log out without going to RFTools dimension.
then close the client, restart and reload the world. I want to see if they persist when RFTools dimensions are never used.

**Comment by 016Nojr** [comment] 2015-07-08 18:52
Happens when only overworld is used aswell

**Comment by hron84** [comment] 2015-07-08 20:33
Same here

**Comment by BluSunrize** [comment] 2015-07-08 20:46
I blame RF tools .-.

**Comment by hron84** [comment] 2015-07-08 21:28
@BluSunrize maybe, ResonantRise (the modpack I use with IE) has RFTools. I will definitely try it out without it.

**Comment by tebruuls** [comment] 2015-07-08 21:34
I don't have rftools and it still happens though I did have rftools at one
point when IE was installed.

**Comment by BluSunrize** [comment] 2015-07-08 21:43
The thing is that I have only few people reporting it, and it works fine for most others. So I have no idea what's happening there.

**Comment by tebruuls** [comment] 2015-07-08 21:44
Just started playing on a server and its not happening there.

**Comment by hron84** [comment] 2015-07-08 22:06
@BluSunrize I think uninstalling RFTools solved my problem, at least my wires survived a save/load cycle.

**Comment by 016Nojr** [comment] 2015-07-09 20:27
With RFTools, i have to break and replace it to be able to place wires on the connectors.

**Comment by Pihrra** [comment] 2015-07-12 10:11
It's still happening for me too using IE 0.4.1
Here's my list of mods (all are at the latest versions available 2 days ago) :
- Pistronics2 (although it happened before I added it)
- Storage Drawers
- JABBA
- Botania
- AntiqueAtlas
- ChickenChunks
- All of team COFH mods (except Cofh Tweaks)

It's not consistant for me though. Sometimes I log in and they're still there sometimes not. Sometimes just going into the nether and back to the Overworld makes them disappear. I'm not 100% sure but I seem to remember once they had disappeared and I left them as is and went to the nether and back and they were back but I can't reproduce that so maybe I just remember wrong.
Also sometimes I have to break and replace the connectors and relays to be allowed to put new cables in but not always sometimes I can just put the new wires in. Very strange and inconsistant and I don't have many mods.

**Comment by tebruuls** [comment] 2015-07-12 12:25
It had not happened to me in 3 days, and then I updated to 0.4.1 and it
happened again. Though I have never had it where I had to break and replace
the connectors.

**Comment by erima** [comment] 2015-07-15 18:50
It's happened to me whenever the client is closed and opened again - fully quitting Minecraft back to the Mojang launcher. Haven't used RF Tools.

**Comment by erima** [comment] 2015-07-15 19:07
I just noticed an odd thing. I'm using LV wires for both a windmill and a watermill. The wires from my windmill to Forestry farm don't disappear, the wires going from watermill to LV capacitor, LV capacitor to Bottler, and watermill to Buildcraft water pump all do.

**Comment by hron84** [comment] 2015-07-19 07:37
Only Forestry farms are tough enough to protect our wires? Really weird :smile:

**Comment by Pihrra** [comment] 2015-07-20 11:17
Last time I logged in into my world for the first time only a portion of my wires disappeared. Until then they all disappeared or they all stayed. Some of the one that disappeared I placed the previous time I logged in some of them were there for some time before but not all the new ones were gone either. All my wires are connected from the same single source of RF so they're not all on different networks (if that makes any difference).

**Comment by llr1234567890** [comment] 2015-07-27 20:46
Is this issue going to be addressed in a newer version (in 4.4.0 I still run into this issue quite a bit)?
My mods list does not include RF Tools either.
Thanks.

**Comment by XRTA** [comment] 2015-07-28 03:50
I have same issue too, not using RF Tools. I think the wires do not disappear if they are placed in always-loaded-chunk (such as spawning point), even after shutting down and restart the game. Putting some chunk loaders near the connectors prevents the wire disconnection too.
If can't figure out what's the problem, how about adding built-in chunk loading function to the connector itself (maybe configurable in cfg file, or in-game option) as a temporary solution?

**Comment by Kazzamkablam** [comment] 2015-07-28 03:56
might be related to updating mods, both times my wires broke i was updating mods, didn't break on full shutdown and restart.

**Comment by BluSunrize** [comment] 2015-07-28 08:25
There is a new additional hook into the world saving event in the coming update, 0.5.0, which might finally do something about this.

**Comment by tebruuls** [comment] 2015-07-28 11:32
Mine Are disconnection every time now. They are in spawn chunks, I've tried
chunk loaders, and they still disconnect. They only do t if I load the
world, rewire them, quit to title, and reload the world.

**Comment by llr1234567890** [comment] 2015-08-01 16:39
Is there any time table for when we can expect to see the 0.5.0 update, or is it all up in the air? I do have to say this is an impressive mod, and if your world hooks solve the wire problem this mod will be one of my essentials.

**Comment by BluSunrize** [comment] 2015-08-01 17:18
Reminder for the future: don't ever ask a developer for ETAs. They don't like that. Trust me, I'm just as anxious to have it out there as you.
If all goes well, today/tomorrow.

**Comment by Pihrra** [comment] 2015-08-05 13:56
It's been a while since my wire disappeared so I was hopeful it wouldn't happen anymore but sadly it just did after upgrading from 0.5.0 to 0.5.1.
Once more most of the wires could just be replaced but a few connectors refused a new connection so I had to brake and replace for them to work again.

**Comment by theunkn0wn1** [comment] 2015-08-05 20:12
It seems every time I update IE all my wires vaporize, and all my HV wire connectors and breakers refuse to function without break-replacing them

**Comment by mindforger** [comment] 2015-08-07 06:36
@theunkn0wn1 unfortunately i had the same issue on an older world in which i had started with 0.1.9 compiled from source during the "rage quit"-periode :P 
i know the following will sound hard and cheaty, but removing the mod launching the world, thus killing everything existent from IE and then reinserting the mod and everything lost by creative mode seemed to work for me ... especially the problem with the HV relays not accepting any cable to be connected

**Comment by theunkn0wn1** [comment] 2015-08-07 18:12
I have all versions starting at 0.3.3 still in archive. Annoyingly the bug
only send to favor my worlds with a reasonably large IE power network.
Thankfully those worlds are all my creative test worlds thus far...

**Comment by mmermerkaya** [comment] 2015-08-08 17:59
I'm still seeing this issue with 0.5.2.

**Comment by tehbeard** [comment] 2015-08-08 18:33
I am also seeing the wiring issue in 0.5.1 (Infinity ftb pack). This morning it killed all wires, and just now logging in has killed only the wiring I placed down in a new part of my base.

**Comment by Kazzamkablam** [comment] 2015-08-10 19:25
It seems there are two variants of the bug, one where you can reconnect wires just by using them and one where you have to break everything but relays for them to work again.

**Comment by XFactHD** [comment] 2015-08-11 23:03
I am also encountering this issue but in a different way. I connected some wires over a long distance with multiple hv wire relays. Later I randomly crashed with the crash report mentioned in #302 and after that I reloaded the world but didn't try to reconnect the wires. After that I updated IE from 0.4.4 to 0.5.2 and now, no matter if I break the hv wire relays or not, I cannot reconnect them and the crash is still happening at some random points of time.

**Comment by allbliss0215** [comment] 2015-08-17 12:14
Watching this thread, coz issue still persists.

**Comment by hron84** [comment] 2015-08-17 18:16
I started to give up to work with these wires. They look cool, but coolnes is not  worth the worrying during world load. In my new world, they survived 2 save/load cycle, and boom. I'm so sad.

**Comment by theunkn0wn1** [comment] 2015-08-17 23:58
Yeah, i really LOVE the cables this mod adds.... until they vaporize at will...
the wires IE adds are quite a lot easier, in most cases, than Thermal Dynamics or EIO conduits to place over a distance. it is quite unfortunate this bug is occurring :{

**Comment by XFactHD** [comment] 2015-08-18 00:20
I downloaded a really good NBT editor today and when I get back to my computer after sleeping some hours I will try some things out by looking into the IE save data to see under which circumstances it saves and under which it does not.

**Comment by hron84** [comment] 2015-08-19 20:21
I found a reproducible case where wires disconnect: if they become "obstructed" after placing them. So, if you want to re-place them in same setup, they won't allow placing because the path is already became obstructed. So you should be careful about the path where the wires go. However, I do not say this is the main cause, just this is a reproducible way. Maybe **this** case can be omitted if wires do not check their setup during startup.

**Comment by XFactHD** [comment] 2015-08-19 23:30
@hron84 if I understand the code right, all wires are deleted on world load and then replaced from the data in the world files.

**Comment by BluSunrize** [comment] 2015-08-19 23:57
Raytracing is only done on placement, not on reload.

**Comment by theunkn0wn1** [comment] 2015-08-20 01:56
@hron84 , if that  is the case then why are *all* the cables in my world vaporizing? All but two of my cables are not obstructed by anything other than themselves and the air. Why are all my cables vaporizing when only two of them are obstructed upon world reload.


=======

It seems the cables in my test worlds only vaporize consistently if the world contained a large IE power network, in my instance it was large enough that if one inserted HV power in one end it would not come out the other with default configs, and is triggered by updating IE. the HV power lines are NOT obstructed in my test worlds.

By 'updating IE' I mean either up/downgrade IE version or replacing with same version rebuilt (with any modification)

**Comment by Pihrra** [comment] 2015-08-20 06:34
All my wiring is in the open and there are no obstructions so definitely not the cause of the problem for my case.
Also my network consisted only of 2 advanced windmills connected to 1 MV capacitor then I had MV wires start from the capacitor to a squeezer, a fermenter and a crusher last time it happened so hardly a large network that's 9 MV connectors in total and all of them were contained in 2 chunks.
It hasn't happened yet in 0.5.3 for me (but I've had less time to play).

**Comment by BluSunrize** [comment] 2015-08-20 23:02
Added anotehr saving hook, this tiem on the unload event (probably should have tried that earlier >_>)
This will be in IE 0.5.4, and /might/ fix things. Let's hope for the best.

**Comment by berinhardt** [comment] 2015-08-24 17:45
Still happens in 0.5.4

**Comment by XFactHD** [comment] 2015-08-24 18:49
I tried something today with the debug crash through "F3" + "C". Result: If the instance is saved and exited normally, the wires stay, if the client crashes after saving the game through pressing "Esc", the wires survive the reload, but if the client crashes without saving the wires through any means, the don't persist. (Tested in Singleplayer)

**Comment by mindforger** [comment] 2015-08-25 09:53
this leads also to my problem on how to hook into a crash, the onServerstopping is never fired nor the onUnload was fired properly for me ... but there is a chance, that the onUnload failes with a silently discarded exception, i will test that with @XFactHD

**Comment by XFactHD** [comment] 2015-08-25 15:35
@mindforger I know that @KingLemming had similar problems with the tesseracts. If you had saved and quitted the world to the main menu and then reentered the world without restarting the client, the tesseracts would loose all there settings and just start to void everything you throw at them. Maybe @BluSunrize, you could talk to @KingLemming to see how he worked around this Forge bug.

**Comment by mindforger** [comment] 2015-08-25 16:19
okay i just put a simple IELogger.info right at the beginning of onSave and onUnload and onServerstopping
http://pastebin.com/7NRGaRze

not does it spam the client with this event, the serverstoppping is never triggered

**Comment by cosmicdan** [comment] 2015-09-12 11:25
Heyas,

I only recently started playing this mod in a pack and encounter this issues 100% of the time.

I am familiar with Forge modding so maybe I can give some info.

I remember having a very similar issue in one of my mod experiments, where it would save my custom data perfectly fine in a dedicated server but the integrated server / single player was unreliable. It's been nearly a year since I worked on it and I don't know if it's the same issue, but I remember experimenting with the FMLServerStoppingEvent hook to get around it.

See example code here (note that it's commented out and literally does nothing, as I said it was experimental), maybe it can be used? If not, forgive my ignorance. https://github.com/cosmicdan/Imperium/blob/master/src/main/java/com/cosmicdan/imperium4x/Main.java#L103

**Comment by BluSunrize** [comment] 2015-09-12 11:57
I'm not sure if server stopping can fix this one really, mostly because I am not saving data manually, I can only mark the worlddata as dirty to be saved. We'll need to wait and see how it behaves after 0.6

**Comment by cosmicdan** [comment] 2015-09-12 12:43
I see, you're extending WorldSavedData. Well, after reading the RFTools issue, I had a hunch that it was a different mod - I just removed Aroma Backup and the wires didn't disappear after a client restart. Could be coincidence, but this isn't the first time Aroma Backup has caused world saved data issues by far.

**Comment by hron84** [comment] 2015-09-13 00:05
@cosmicdan i use AB to backup in my modpack too, and as I want to focus a bit to IE so if this causes the wire disappearing issue, I can consider to remove it. Is there any backup mod that causes less problem?

**Comment by malkuth1974** [comment] 2015-09-18 00:24
This is an issue in my lets play also.  But I have found a way around it most of the time. The trick is if you just set up a new Wire Layout to save and exit to the Menu first.. Load the game back up and then you can exit the game fully.

If you save and exit and leave the client totally (Single player only) then the new wires will not save and you will have to place them again.

Doing the work around has stopped this issue for me almost totally.  
Makes sense that this is a single player issue mostly because servers are usually on most of the time, and won't have this issue like a single player will.

**Comment by XFactHD** [comment] 2015-09-18 06:10
@malkuth1974 this is not a singleplayer only problem because a server saves the same way as the client does.

**Comment by takemehi** [comment] 2015-10-08 16:24
I encountered the same issue in the Evolving Technology modpack which runs version 0.5.4. Every time i started up the world the SAME wires were missing. After looking for some pattern i noticed that all the wires that were not connected with wire connectors on the wooden post remained unharmed while all the connections beginning from the first wooden post were destroyed.
I replaced all the wooden posts and just used wire connectors for the connections. Since then I haven't encountered the issue again. There's definately something wrong with the posts or the way the connections are made from them.

**Comment by 1skandar** [comment] 2015-10-12 19:56
Yeah, I've seen this as well in my new pack: http://forum.feed-the-beast.com/threads/1-7-10-modular-mayhem.120584/ It isn't consistent, Sometimes the wires survive, sometimes they don't. Also the wooden posts occasionally won't render the arm when clicked on by a Engineer's Hammer, you have to log out and back in to get them to render.

**Comment by tehbeard** [comment] 2015-10-14 21:50
I've just had all wires in my save disappear again. (0.5.4, Infinity mod pack)

Curiously, the uranium vein I am mining with the excavator has also reset back to full durability.

**Comment by theunkn0wn1** [comment] 2015-10-14 22:21
Yeah... that's the bug I mentioned above. Will be fixed in the next release.

**Comment by ujplays** [comment] 2015-11-21 04:51
Been having this same problem in FTB Infinity Evolved, I'll log back in after exiting properly and some wires will haves disappeared.  Today, I had a new experience, after logging in to my SP world, I found wires I had disconnected were still connected. The disconnected wires were still in my inventory.

I didn't start a new bug report since I suspect it might be related.

**Comment by BluSunrize** [comment] 2015-11-21 07:40
It's fixed for gods sake. FTB is just terribly outdated.

**Closed by BluSunrize** 2015-11-21 07:40 UTC
