### ISSUE TITLE
 connectors, relays and balloons have no texture in 1.1.5.2

### ISSUE THREAD

**Issue by panchuel** [BluSunrize/ImmersiveEngineering#3977] opened 2020-06-13 23:26 UTC
In both singleplayer and servers, the relays and connectors do not have texture, and the balloons generate light but do not have texture, I hope you can solve it

**Comment by notadevtho** [comment] 2020-06-14 01:36
Are you using Optifine? Can you show your modlist?

**Comment by panchuel** [comment] 2020-06-14 03:47
yes i am using optifine and this is my mod list

![Captura](https://user-images.githubusercontent.com/66889936/84584269-c4331280-adc7-11ea-9cfc-6efc9e5aa70c.JPG)

**Comment by BluSunrize** [comment] 2020-06-14 14:01
Use the issue template for goodness sake. Don't just *delete* it.

Also, this is quite likely a duplicate of #3956

**Closed as completed by BluSunrize** 2020-06-14 14:01 UTC
