### ISSUE TITLE
[1.12] Railgun not firing

### ISSUE THREAD

**Issue by Kasymir** [BluSunrize/ImmersiveEngineering#2749] opened 2018-01-21 19:14 UTC
Hey there,
It seems that the railgun is bugged since when you're using it, it consumes rods but doesn't fire any projectile, and makes not damage. 
Doesn't come from my modpack or versions of it since people seems to have the same issues
https://forum.feed-the-beast.com/threads/railgun-rounds-not-hitting-mobs.266946/
Is this a known bug ?

(Thanks for this wonderful mod tho !)

**Comment by malte0811** [comment] 2018-01-21 19:31
Duplicate of #2714.

**Closed by malte0811** 2018-01-21 19:31 UTC
