### ISSUE TITLE
Crate can't handle items with big NBT data

### ISSUE THREAD

**Issue by davqvist** [BluSunrize/ImmersiveEngineering#2403] opened 2017-08-07 17:11 UTC
MC 1.10.2
Forge 2316
IE 0.10.61

If you put items with a lot of NBT data in a crate, the client freezes without a crash.
To replicate install Forestry and put a lot of bees into an Apiarist's Backpack. Copy the Backpack in create with middle click and put them in, I think I froze already putting the second one in.

I don't get a crash, meaning no crash log, but the latest.log throws an error that a package exceeds max allowed data, see https://gist.github.com/davqvist/5d65bfa9d94d6358ccc5d90b4818c2c9 at 18:59:44

**Comment by BluSunrize** [comment] 2017-08-07 17:24
I mean, you'd probably get that by putting them in other comparable containers? Try Thermal's Satchels for instance. Less an IE issue, more a thing not easily avoided?

**Comment by malte0811** [comment] 2017-08-07 17:31
I'll add Forestry's backpacks to the list of blocked items in a minute, I'll also look into implementing getShareTag on the crate and the toolbox.
For a long-term solution I have a PR open at Forge, MinecraftForge/MinecraftForge#4159. It adds a method to `Item` to prevent it from being put into containers. There is currently a 3-way discussion going on about how information on the inventory should be passed to the method, no idea when the PR will be merged (if ever).

**Comment by davqvist** [comment] 2017-08-07 17:33
I don't get that issue in vanilla chests. Not sure I understand

**Comment by davqvist** [comment] 2017-08-07 17:36
Tested with AA Small Crate, no crash either, If the issue is being able to use as an item, I used a Storage Keeper on it, got the item and placed it back without problems

**Comment by davqvist** [comment] 2017-08-07 17:44
Vacuum Chest from EnderIO keeps inventory as well and doesn't crash either fyi.

**Comment by BluSunrize** [comment] 2017-08-07 17:49
It may just work somewhat differently. 
Wonder if it'd be caused by WAILA or TOP requesting the block? Might be an idea to replicate this in an instance with only IE and Forestry and nothing else.

**Comment by malte0811** [comment] 2017-08-07 17:51
I think they use `getNBTShareTag`. I'm working on it right now. I think I started implementing that when I originally made the Forge PR, but never finished.

**Comment by BluSunrize** [comment] 2017-08-07 17:54
Anyway, non-urgent, and I'm on holiday. I'll look at what you come up with in a week or so

**Comment by davqvist** [comment] 2017-08-07 18:17
Thank you.

**Closed** 2017-08-07 19:28 UTC
