### ISSUE TITLE
[1.12.2] Java.lang.IllegalStateException: Unable to get Y-rotated facing of down 

### ISSUE THREAD

**Issue by InfiniteMaximum** [BluSunrize/ImmersiveEngineering#2609] opened 2017-11-12 02:53 UTC
### Description of the issue:
Go near players house in world hosted on server and game client crashes. Crash log mentions Immersive Engineering and some other mods in the exception mentioned in crash report. Not sure which is the root cause of the problem. World and coordinates can be provided. 

### Crashlog:
https://hastebin.com/etomiwecop.coffeescript

### Versions & Modlist
Minecraft Version 1.12.2
Forge Version 1.12.2-14.23.0.2529
Modpack: EXPL Modpack V1.1.1 
Immersive Engineering-0.12-74

Additional Mods Mentioned in Exception:
Solar Flux Reborn-1.12.2-3.42r
HammerCore-1.12.2-1.9.5.2

**Comment by Xenos13** [comment] 2017-11-12 06:23
It seems like some conflict between "custom cable" from Solar Flux Reborn and "garden cloche" from IE at position 2559,86,1310

**Comment by malte0811** [comment] 2017-11-12 07:57
Duplicate of #2560, fixed for the next release.

**Closed by malte0811** 2017-11-12 07:57 UTC
