### ISSUE TITLE
[1.12.2] Illegal state while rendering Entity Bell

### ISSUE THREAD

**Issue by Tencao** [BluSunrize/ImmersiveEngineering#2607] opened 2017-11-11 17:33 UTC
### Description of the issue:
Crashes when loading a base with IE blocks present, crash report should be more specific on which block

### Crashlog:
https://paste.ee/r/SslJU

### Versions & Modlist
IE - 0.12-74
Forge - 14.23.0.2537

**Comment by malte0811** [comment] 2017-11-11 17:55
Duplicate of #2560 (Not a direct duplicate, but same category/fix). Fixed for the next release.

**Closed by malte0811** 2017-11-11 17:55 UTC

**Comment by Tencao** [comment] 2017-11-11 18:43
Sadly I've checked the recent commit, and while this fixes the crash, it definitely didn't fix the problem causing this. To show you what I mean, here's a screenshot.
https://image.prntscr.com/image/YzFbQ2pQR0usfPzJIn6WZg.png

There's a lot of ghost and duplicate models not really linked to anything.
