### ISSUE TITLE
PINK!!!

### ISSUE THREAD

**Issue by Keetarin** [BluSunrize/ImmersiveEngineering#2704] opened 2017-12-29 10:03 UTC
The LV Capacitor, MV Capacitor, HV Capacitor, Creative Capacitor, Metal Barrel, and Fluid Outlet are showing up pink... no idea why.
Tested in (with only): 
IE: 0.12 - 75
Forge: 14.23.1.2582
![2017-12-29_03 02 31](https://user-images.githubusercontent.com/6365440/34434658-bd1f0996-ec44-11e7-9fb2-4bdfb55ce864.png)
![2017-12-29_03 02 02](https://user-images.githubusercontent.com/6365440/34434659-bd334c4e-ec44-11e7-8970-c5bfe69dbe48.png)

**Comment by malte0811** [comment] 2017-12-29 10:05
Duplicate of #2672 (sort of). It is the same issue, they just catch the exception now and replace it with a missing model. Fixed for the next release.

**Closed by malte0811** 2017-12-29 10:05 UTC
