### ISSUE TITLE
Crash - HermitCraft - Maybe caused by Vertical Conveyor?

### ISSUE THREAD

**Issue by robbcrg** [BluSunrize/ImmersiveEngineering#1732] opened 2016-11-25 14:28 UTC
Let me know how I can help.

**Full CrashLog**
  http://pastebin.com/RE9rLhvP

**Synopsis:**

...
Description: Tesselating block model
 
java.lang.NullPointerException: Tesselating block model
    at blusunrize.immersiveengineering.common.blocks.metal.conveyors.ConveyorVertical.renderBottomBelt(ConveyorVertical.java:78)
    at blusunrize.immersiveengineering.common.blocks.metal.conveyors.ConveyorVertical.modifyQuads(ConveyorVertical.java:263)
    at blusunrize.immersiveengineering.client.models.ModelConveyor.func_188616_a(ModelConveyor.java:102)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:101)
....

**Comment by KnightMiner** [comment] 2016-11-25 16:08
Does this happen without Optifine?

**Comment by malte0811** [comment] 2016-11-25 16:21
Yes, happened to me in dev once or twice. This has been fixed in newer versions of IE (build 49/50). Additionally this is a duplicate of #1650.

**Comment by robbcrg** [comment] 2016-11-25 16:43
Disabling optifine lets it run a bit longer, then it crashes. I beleive
HermitCraft 1.4 is using IE 50. I will cross check that when i get back to
the system.

Also,  some conveyer textures were place holders. Rotating them with the
Hammer seemed to fix it,  then on a client restart other conveyors  went
wonky. Finally a few botinia textures went to place holders as well, they
were close to the conveyors, if that helps. . Perhaps something is
corrupted. Played many hours on this box with no issues.

**Comment by malte0811** [comment] 2016-11-25 17:21
Line 124 of your crashlog:
>     UCHIJA  immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar)

**Comment by robbcrg** [comment] 2016-11-25 18:27
So it is ... I will apply the latest V50 and see if that helps. Sorry I missed that.

**Comment by robbcrg** [comment] 2016-11-25 18:57
So V50 on server and client fixed my issue. OptiFine is even working.

**Closed** 2017-09-09 16:03 UTC
