### ISSUE TITLE
Immersive engineering connectors crashing the server

### ISSUE THREAD

**Issue by Gallaf** [BluSunrize/ImmersiveEngineering#4208] opened 2020-08-13 20:51 UTC
During my Valhesia 3 (1.16.1) server daily restart forge crashes and provides the crash log attached: 
[crash-2020-08-13_17.31.06-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5071371/crash-2020-08-13_17.31.06-server.txt)

**Comment by BluSunrize** [comment] 2020-08-13 20:57
Duplicate of #4181, didn't abide the issue template, didn't read the contribution guidelines.
Closed.

**Closed as completed by BluSunrize** 2020-08-13 20:57 UTC
