### ISSUE TITLE
Having a startup crash, can u chek it?

### ISSUE THREAD

**Issue by Akaruz64** [BluSunrize/ImmersiveEngineering#2935] opened 2018-04-11 18:42 UTC
Hey, latest forge version, testing with only Immersive, having this issue when client is starting

The game crashed whilst initializing game
Error: java.lang.ClassCastException: blusunrize.immersiveengineering.common.util.IEItemFluidHandler cannot be cast to net.minecraftforge.items.IItemHandler

Full crashlog:
https://pastebin.com/n8JureYP

Minecraft Version 1.12.2
Forge 1.12.2 - 14.23.3.2657
IE Version 0.12 - 80

**Comment by malte0811** [comment] 2018-04-11 18:49
Duplicate of #2934. Downgrade Forge by a few versions. This is a Forge issue, I'm working on it right now.

**Closed by malte0811** 2018-04-11 18:49 UTC
