### ISSUE TITLE
[1.12.2] Invisible Redstone Probe Connector + other visual issues

### ISSUE THREAD

**Issue by Tavish155** [BluSunrize/ImmersiveEngineering#2597] opened 2017-11-08 23:03 UTC
Alright, First time using github so please give me a grain of salt if my formatting is bad, but basically what I'm seeing are several visual/rendering issues within my instance of IE, the most glaring of which is that the Redstone Probe Connector is just... completely invisible. it still works, wires connect to it, it's solid, even has the bounding box and shows up fine in your hand, but when you put it down? just invisisble.

I found this to be the case in both singleplayer and on my own server.

![2017-11-08_17 49 07](https://user-images.githubusercontent.com/33500921/32579016-67de08f6-c4ad-11e7-8859-d61e40fcd6dd.png)

Additionally, The core sample drill isn't transparent where it should be(and doesn't light properly if a block is placed next to it)

![2017-11-08_17 53 35](https://user-images.githubusercontent.com/33500921/32579149-e29038bc-c4ad-11e7-9831-9be14d141f43.png)

Additionally again, The fluid inside of tanks isn't rendering. they still function correctly, but where there should be a bar, it's just a white void.

![2017-11-08_17 56 29](https://user-images.githubusercontent.com/33500921/32579243-30fab806-c4ae-11e7-947f-3309e7cd886c.png)

IE version: 0.12-74
Forge version:14.23.0.2531
I orginally found this in a lightweight modpack I was working on, but reinstanced to just with IE and found that the issue remained, even without any other mods loaded.

Thanks for looking over this, I honestly figure I'm just doing something wrong, but couldn't a fix or even any other mention of this being the case. I really just don't know what to do about it

**Comment by Xenos13** [comment] 2017-11-09 22:10
Having the same bugs.
Also, External Heater looks transparent. I have partially solved this bug with patching some ".mcmeta" files, but I have no ideas about the others.

IE 0.12-74
Forge .2529

**Comment by Nerezza** [comment] 2017-11-10 05:57
Having these same problems.

**Comment by malte0811** [comment] 2017-11-11 10:28
The silo and the heater are definitely fixed for the next release (Duplicate of #2552), the other ones are probably different instances of the same bug. If you see any of this in build 75 once it's public please put a comment here (You can comment on closed issues).

**Closed by malte0811** 2017-11-11 10:28 UTC
