### ISSUE TITLE
Items with GUI crush server and client

### ISSUE THREAD

**Issue by jarezzz** [BluSunrize/ImmersiveEngineering#3327] opened 2018-12-21 09:41 UTC
### Description of the issue:
Try to open toolbox or revolver GUI and enjoy the crush
### Crashlog:
Server crushlog https://pastebin.com/7JeEmBJN
Client crushlog https://pastebin.com/eUYGF513

### Versions & Modlist
FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar    | 
forge                | 14.23.5.2768 | 
 jei                  | 4.14.3.238
immersiveengineering | 0.12-87

**Comment by malte0811** [comment] 2018-12-21 09:44
Duplicate of #3319

**Closed by malte0811** 2018-12-21 09:44 UTC

**Comment by jarezzz** [comment] 2018-12-21 10:08
Why is it closed if it's a valid problem?

**Comment by mindforger** [comment] 2018-12-21 11:57
because it is a duplicate, read the linked issue and continue monitoring it or get the solution for your problem from there

**Comment by jarezzz** [comment] 2018-12-22 20:58
> because it is a duplicate, read the linked issue and continue monitoring it or get the solution for your problem from there

But the linked issue is closed too. It's kinda odd and frustrating.

**Comment by mindforger** [comment] 2018-12-22 23:57
No its not, it has been closed with a fix that will be released with build 88, but you may have overseen it ...
