### ISSUE TITLE
Assembler Link Crash [MC 1.10.2] [v0.10-50]

### ISSUE THREAD

**Issue by Neros64** [BluSunrize/ImmersiveEngineering#1745] opened 2016-11-28 03:51 UTC
When I click on Assembler in the Engineer's Manual my game will crash. I'm using ImmersiveEngineering-0.10-50.jar for Minecraft 1.10.2
Crash Report: [http://pastebin.com/gtrYJdbE](http://pastebin.com/gtrYJdbE)

**Comment by Zenith-One** [comment] 2016-11-28 19:52
+1 - this just happened to me as well

**Comment by BluSunrize** [comment] 2016-11-28 19:57
Duplicate of #1704, please use the search function. Also, fixed already for future releases.

**Closed by BluSunrize** 2016-11-28 19:57 UTC

**Comment by Neros64** [comment] 2016-11-28 20:14
Nothing showed up when I searched it. I had no idea their was a fixed thread either. Thank you.
