### ISSUE TITLE
[1.16.5-4.2.4-134] 

### ISSUE THREAD

**Issue by Tyronadre** [BluSunrize/ImmersiveEngineering#4862] opened 2021-06-21 09:52 UTC
Hey there, 

I have multiple problems with IE in the mod pack I'm currently playing.

1. if you put a drill or saw into the ME system, it will lose all upgrades, but the worst part, you cannot get it our without an export bus with a fuzzy card. Just nothing happens if you try to get the item out by the interface.

2. Marble from Astral sorcery won't get mined by the drill, but I guess that not your bad, because it doesn't have any Tag indicating it as a stone.

3. I don't know if this is the right place, or if I have to post it to the twilight forest page, but the shaders from TF seems to crash the client side regularly. 

4. Fluid pipes seem to break all the time if you travel with a waystone in the chunk where they are, the just stop transporting fluids, and you have to replace them every time to work properly (server only)

5. If you switch gamemode the saw and drill loose all upgrades, but keeps the shader. (server only)

6. The game crashes occasionally in the loading phase, as you can see in the crash-report

(7.) This is only a suggestion, but is it possible that every dust can be made in a crusher? (Those which are tagged with forge:dusts?) 

(8.) I don't know if this intended, but if you fill a saw or a drill in creative mode they will only empty the container, not picking up fuel, like an empty bucket (same the other way round if you try to empty a saw or drill). Since they don't work without fuel, this is a bit unfortunate, and the saw doesn't cut whole trees.

I know I have installed optifine, and the server has performant, but I can't really set up a new server and test it without it 😅, and the other crashes aren't related to any graphical bugs, so I guess optifine is fine (except 3.)?  

Here is the crash log (when it crashed in loading phase):
[crash-2021-06-21_11.05.10-fml.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6685749/crash-2021-06-21_11.05.10-fml.txt)

Edit:
I totally forgot :
There is no crafting recipe for the radiator block, is this intended?

**Comment by BluSunrize** [comment] 2021-06-21 10:11
Do *not* do compound issues. This is an issue tracker. Separate issues need separate threads.

1. Don't put your drill in an ME system then. You've learned a valueable lesson there. To my knowledge we do nothing that would cause this.
2. Yep, sure doesn't sound like our fault.
3. Twilight Forest accesses internal methods. Their fault, not ours.
4. This has been fixed, you are using an outdated version of IE.
5. This needs a separate issue, tested on IE V5.0+, with detailed instructions on how to reproduce in a minimal instance.
6. This also needs a separate issue, tested on IE V5.0+, in a minimal instance.
7. No, dynamic recipes are no longer a thing, since we moved to JSON. If you have a request for a list of metals we don't yet process, file a proper request.
8. That's Forge's behavior, not ours.

> There is no crafting recipe for the radiator block, is this intended?

Recipe exist and works fine on my end. Once again, you didn't test on the current release version in a minimal instance.

I'm closing this issue, because half of this stuff is invalid, and the rest is poorly documented. We have an issue template for a reason. Feel free to open new issues for 5 and 6, but test them properly on a current release in an instance that only has IE.

**Closed as completed by BluSunrize** 2021-06-21 10:11 UTC
