### ISSUE TITLE
[1.15.2] Industrial Hemp Seeds doesn't appear to drop from grass at all.

### ISSUE THREAD

**Issue by SCP0429Teemo** [BluSunrize/ImmersiveEngineering#4059] opened 2020-07-08 09:35 UTC
Description of the issue:
As the title says, Industrial Hemp Seeds doesn't appear to drop from grass/tallgrass at all.

Versions
IE: 0.15-103
Forge: 31.2.30
MC: 1.15.2
mods: IE
Hope it can get fixed. :)

**Comment by mindforger** [comment] 2020-07-08 10:52
https://github.com/BluSunrize/ImmersiveEngineering/issues/4046

always check closed issues too ;)

**Comment by malte0811** [comment] 2020-07-08 18:17
As noted by @mindforger, this is a duplicate of #4046. Fixed for the next IE release.

**Closed as completed by malte0811** 2020-07-08 18:17 UTC
