### ISSUE TITLE
[1.16] Wire recycle duping

### ISSUE THREAD

**Issue by Lgmrszd** [BluSunrize/ImmersiveEngineering#4761] opened 2021-04-01 15:24 UTC
### Description of the issue:
Pretty much the same as #4018
You can recycle wires (Electrum, Steel, Copper, Aluminum) in Arc Furnace in 1:1 ratio, allowing you to dupe metals (as you get 2 wires per ingot in metal press).

Happens in both multiplayer and singleplayer (had tested with only IE in singleplayer)

### Versions & Modlist
Forge: 36.1.3
Immersive Engineering: 1.16.5-4.2.4-134

**Comment by malte0811** [comment] 2021-04-01 16:24
Duplicate of  #4718, but I admit that that one is basically impossible to search for. I only found it because I knew which commit I'd fixed it in.

**Closed as completed by malte0811** 2021-04-01 16:24 UTC
