### ISSUE TITLE
[1.10.2] Crash with OptiFine

### ISSUE THREAD

**Issue by bondgb** [BluSunrize/ImmersiveEngineering#1291] opened 2016-08-22 23:13 UTC
Dunno if this is a wontfix because of OptiFine, but I get this crash when loading with it enabled:

http://pastebin.com/G1sPhxpS

**Comment by BluSunrize** [comment] 2016-08-23 06:06
It's a wontfix because Optifine ;)

**Closed by BluSunrize** 2016-08-23 06:06 UTC

**Comment by mindforger** [comment] 2016-08-23 06:15
looks like an outdated optifine version, may fix your issue

**Comment by bondgb** [comment] 2016-08-23 10:05
Found out what caused it. It's a three-way incompatability between Optifine, IE and Enchiridion. So for the record, IE boots up fine with Optifine installed.

https://github.com/sp614x/optifine/issues/244

**Comment by sp614x** [comment] 2016-09-19 16:19
The error:
[11:57:15] [Client thread/ERROR] [FML/]: Caught exception from immersiveengineering
java.lang.StackOverflowError
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]
    at net.minecraft.client.gui.FontRenderer.func_78263_a(FontRenderer.java:745) ~[bdl.class:?]
    at blusunrize.immersiveengineering.client.IEItemFontRender.getCharWidthFloat(IEItemFontRender.java:118) ~[IEItemFontRender.class:?]

It looks like IE is patching the FontRenderer to call IEItemFontRender.getCharWidthFloat(), which calls back the original method, which causes an endless loop.

Because IE and OptiFine seem to work, then most probably Enchiridion is also patching FontRenderer and causing the IE patch to generate a wrong code.

Summary:
- OptiFine changes FontRenderer (required)
- Enchiridion probably patches FontRenderer (no idea why)
- IE tries to patch the patched FontRenderer and generates invalid code causing the endless loop

Because of problems like that, the class patching should be avoided and all base class changes should be delegated to Forge. OptiFine takes care to reflect all base class changes which Forge does and to be compatible with it.

**Comment by BluSunrize** [comment] 2016-09-19 18:34
Yep. Optifine is not supported. That is why I closed hte issue =)

**Comment by sp614x** [comment] 2016-09-19 23:32
This may be a total coincidence.
OptiFine is adding a private method getCharWidthFloat() which is being called at line 745. This is absolutely safe as the private method can not be overriden by a subclass.
If IE is extending the class and adding a public method with the same name AND someone else is changing the FontRenderer method signature to public via ASM then the IE method will override the OptiFine method and it will cause the problem exactly as the stack trace shows.
Is someone changing the private FontRenderer methods to public via ASM? Forge maybe?

**Comment by BluSunrize** [comment] 2016-09-20 05:58
Neither Enchiridion nor IE patch the font renderer. We just extend it. I wish I could confirm if Optifine does indeed insert a "getCharWidthFloat" method, but since they are closed source, I can't really check.

**Comment by GirafiStudios** [comment] 2016-09-20 06:01
It was actually caused by the way Enchiridion added their ATs, fixed in https://github.com/PenguinSquad/Enchiridion/commit/1d0f19a93e17320c16ff49a6f7639ced9238ab88 :)

**Comment by BluSunrize** [comment] 2016-09-20 06:02
Shouldn't, no. ATing all fields and methods is an absolutely valid action.

**Comment by GirafiStudios** [comment] 2016-09-20 06:09
I think it was because ATing all field and methods made Enchiridion AT func_78263_a, which it don't anymore. Joshie explained it to me earlier, but I forgot!

**Comment by sp614x** [comment] 2016-09-20 08:30
Using runtime bytecode manipulation of any form (even AT), can cause all sorts of hard to understand bugs and mysterious crashes. AT is tolerated as there is no better way to do it, but it should be limited to only what is really needed.

**Comment by BluSunrize** [comment] 2016-09-20 09:31
@sp614x, if you can confirm that optifine inserts a getCharWidthFloat method with the same signature (seriously, why no visible source?), Then I will adjust my method name to present further issues of this sort

**Comment by sp614x** [comment] 2016-09-20 10:16
OptiFine adds a "private float getCharWidthFloat(char character)" to FontRenderer.
It modifies base classes (hint: Mojang property), so no visible source. You can always peek in the class files (http://jd.benow.ca/). To get the patched class files, double-click the Optifine JAR, select Extract and save the MOD file. I know it is complicated.

**Comment by BluSunrize** [comment] 2016-09-20 10:22
Sure I can decompile it. I was hoping for a solution I can easily, read and navigate =P
Forge's class patches and various other mods using ASM are visible source after all. But to each their own, I'll look into changing my signature.

**Comment by BluSunrize** [comment] 2016-09-27 14:15
https://github.com/BluSunrize/ImmersiveEngineering/commit/4b65becf09a47bc70a9f53055da06a9389526fe2

This commit changed the method name. That should help =3
