### ISSUE TITLE
[1.12.2] Guns lose bullets when placed in an inventory

### ISSUE THREAD

**Issue by andrewminer** [BluSunrize/ImmersiveEngineering#3232] opened 2018-09-26 14:24 UTC
### Description of the issue:

I've made a revolver and a set of silver bullets.  I leave it loaded and placed it on a BiblioCraft shelf for storage.  When I picked it up after logging out of the server for a time, I found that it was no longer loaded.  No empty cartridges, no bullets.  Just like it had never been loaded at all.

### Versions & Modlist

* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* Immersive Engineering: 0.12-84
* BiblioCraft: 2.4.3
* [Full Mod List](https://github.com/andrewminer/brunel/tree/master/mods)

**Comment by andrewminer** [comment] 2018-09-26 14:46
This sounds similar to #3216.

**Comment by malte0811** [comment] 2018-09-26 16:07
Duplicate of #3216. Same cause, bibliocraft somehow manages to remove the part of the item stack where the bullets (and most other things stored in IE items) are stored. It's currently the recomended place for items stored in items as far as I know.

**Closed by malte0811** 2018-09-26 16:07 UTC
