### ISSUE TITLE
Major Dupe

### ISSUE THREAD

**Issue by quinuim** [BluSunrize/ImmersiveEngineering#735] opened 2015-12-08 04:42 UTC
Step one: place blueprint in IE workbench

Step two: place and items from any mod in the workbench

Step three: have a friend break the bench or use a block breaker on a timer to break it while the interface is still open

Step four take the items out and pick up the blueprint before closing the interface

Step five replace bench and take out your items a second time

**Comment by theunkn0wn1** [comment] 2015-12-08 05:08
Was unable to reproduce . Upon the Workbench being destroyed (used a ProjRed block breaker on timer and a MFR block breaker) the GUI closed. Only one table and only one blueprint was dropped as a result. Placed several vanilla items and several mod-added items into the inventory in question and was unable to duplicate them as described. 

Tested against IE build cc3c69e
What version of IE are you testing against?

**Comment by BluSunrize** [comment] 2015-12-08 10:00
Yep this should be fixed since IE 0.6.1. Outdated version of IE is being used.

**Closed by BluSunrize** 2015-12-08 10:00 UTC
