### ISSUE TITLE
[1.14.4 0.14-93] Crash from Minecart Entity

### ISSUE THREAD

**Issue by ThomasElvangMoeller** [BluSunrize/ImmersiveEngineering#3714] opened 2020-03-27 13:26 UTC
I was generating new chunks and the game crashed.
Based on the crash report it was probably a mineshaft generating with a minecart, and the minecart crashed the game
[Crash Report](https://pastebin.com/b2riHQTX)

**Comment by malte0811** [comment] 2020-03-27 13:35
Duplicate of #3678

**Closed by malte0811** 2020-03-27 13:35 UTC
