### ISSUE TITLE
Deployer Crashing Singleplayer and Server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [BluSunrize/ImmersiveEngineering#4622] opened 2021-02-01 02:35 UTC
On my server several players have crashed the server when adding a Create Deployer. In local testing if we remove Immersive Engineering it is fine. 

We are not sure if this is a Create issue or an Immersive Engineering issue, so it is being posted on both. https://github.com/Creators-of-Create/Create/issues/980

Thank you,
CM

Minecraft: 1.16.5
Create: mc1.16.3_v0.3e
Immersive Engineering: 1.16.5-4.2.0-130
Forge: 36.0.10 or 36.0.12

Server Crash-Report
https://pastebin.com/mQSi6wzy

Mod Pack 99 Mods on the Wall:
https://www.curseforge.com/minecraft/modpacks/ninety-nine-mods-on-the-wall/files/3186210

**Comment by malte0811** [comment] 2021-02-01 08:33
Duplicate of #4604, this is an issue on our side (caused by bad documentation on Forge's side).

**Closed as completed by malte0811** 2021-02-01 08:33 UTC
