### ISSUE TITLE
Immersiveengineering crashes with Transfer nodes

### ISSUE THREAD

**Issue by xKnightGamingx** [BluSunrize/ImmersiveEngineering#2583] opened 2017-10-26 21:38 UTC
https://gist.github.com/xKnightGamingx/afbf1074208f189ff36c719abc1bb73b

**Comment by malte0811** [comment] 2017-10-31 14:41
Duplicate of #2560 and others. Should be fixed for the next release.

**Closed by malte0811** 2017-10-31 14:41 UTC
