### ISSUE TITLE
rods aren't registered in the ore dictionnary

### ISSUE THREAD

**Issue by Hypsellis** [BluSunrize/ImmersiveEngineering#1297] opened 2016-08-23 04:12 UTC
It seems that the metal rods added by Immersive Engineering aren't registered in the ore dictionnary. I can't use the same metal rods from other mods like Substratum and LightingCraft for the Immersive Engineering recipes and reverse with Immersive Engineering rods wich can't be used in the recipes of other mods.

**Comment by KnightMiner** [comment] 2016-08-23 04:19
Dupe of #1294

**Closed** 2016-08-23 06:07 UTC
