### ISSUE TITLE
crash during loading, fluid_splash cannot load

### ISSUE THREAD

**Issue by flamebane** [BluSunrize/ImmersiveEngineering#4416] opened 2020-10-31 20:28 UTC
### Description of the issue:
it gets to the proper loading stage, then crashes, giving the short crash report "The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle immersiveengineering:fluid_splash
Exit Code: -1"

### Crashlog:.
https://pastebin.com/wSATj9yN

### Versions & Modlist

ImmersiveEngineering-1.16.3-4.1.0-124
--
jei-1.16.3-7.6.0.49
--
forge-34.1.35

**Comment by malte0811** [comment] 2020-10-31 20:36
Duplicate of various other issues, including #4410, which is even pinned for better visibility! Use Forge build 25 for now.

**Closed as completed by malte0811** 2020-10-31 20:36 UTC
