### ISSUE TITLE
[1.16.5] Crash when trying to break Passthrough Insulator with a pickaxe

### ISSUE THREAD

**Issue by Guardian9978** [BluSunrize/ImmersiveEngineering#4893] opened 2021-07-23 17:26 UTC
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
I'm trying to break a Passthrough Insulator with a pickaxe and each time I try I get the following Error:
The game crashed whilst tesselating block model
Error: java.lang.NullPointerException: Tesselating block model

This was tested with only Forge and Immersive Engineering

### Crashlog:
https://pastebin.com/MkBTybH5

### Versions & Modlist
Minecraft Version: 1.16.5
Forge Version: 36.1.0
IE Version: 5.0.2-137

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by malte0811** [comment] 2021-07-23 18:40
Duplicate of #4879

**Closed as completed by malte0811** 2021-07-23 18:40 UTC
