### ISSUE TITLE
Chem thrower not outputting

### ISSUE THREAD

**Issue by ThranorBeardhammer** [BluSunrize/ImmersiveEngineering#2744] opened 2018-01-19 01:16 UTC
The chem thrower doesn't seem to do anything.  There is no output animations, no interactions with anything at all.  I have tried creosote oil, lava, and ethanol.  I have tried all three of those with the pilot light on and off as well as aiming at various wooden objects and animals.  Many different ranges also tried.  The fuel drains from the tank when right clicking but no other effects.  It has been upgraded with the larger fuel tank.  It makes the sound effect of being in use.

Survival server.
mod pack FTB Revelation.  forge 14.23.1.2587
Does not cause a crash.

**Comment by malte0811** [comment] 2018-01-19 05:54
Duplicate of #2736 (and #2714). Fixed for the next release.

**Closed by malte0811** 2018-01-19 05:54 UTC
