### ISSUE TITLE
Tinker's Construct

### ISSUE THREAD

**Issue by Zorg14** [BluSunrize/ImmersiveEngineering#1489] opened 2016-09-18 19:52 UTC
Hi) I've got an issue when trying to install Immersive Engineering and Tinker's Construct together. I'm not sure about which mod's author to write to, so I starter two new issues for both of you.

So. I have minecraft 1.10.2
forge 1.10.2-12.18.1.2088
mantle 1.10.2-1.0.0
tconstuct 1.10-2.3.3a
Immersive Engineering 0.10-42

**Comment by GirafiStudios** [comment] 2016-09-18 19:54
Duplicate of #1482 and many others. Please use the search function before reporting another time.

**Closed** 2016-09-18 20:06 UTC
