### ISSUE TITLE
Game crashes when using JEI mod and Immersive engineering

### ISSUE THREAD

**Issue by s1m7y** [BluSunrize/ImmersiveEngineering#5592] opened 2023-02-27 12:30 UTC
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.1.2-159

### How did it happen?

Game crashes when you type "im" togeather at any point into the JEI search, already reported the crash to the JEI mod, doing the same here as the crash error states immersive engineering as the problem, and if you swipe quickly between pages when you get to items from immersive engineering it happens the same

### Crash Log

https://gist.github.com/s1m7y/0766e37462e7973d7d00a00428a59213

**Comment by XFactHD** [comment] 2023-02-27 12:38
This is caused neither by JEI nor by ImmersiveEngineering, it's caused by OptiFine breaking a Forge feature and needs to be fixed by OptiFine.

**Comment by malte0811** [comment] 2023-02-27 15:14
As @XFactHD said, this needs to be fixed by Optifine.

**Closed as not planned by malte0811** 2023-02-27 15:14 UTC
Labels: crash 💥
