### ISSUE TITLE
[1.11.2][62]Compatibility issue between IE and Augmented Interactions

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2244] opened 2017-06-28 07:03 UTC
With both IE and Augmented Interactions installed. When a block is right clicked with a drill it attempts the bucket animation from Augmented Interactions.

Augmented Interactions: https://minecraft.curseforge.com/projects/augmented-interactions

Logs do not contain any error information to share. But I will be sharing this same bug with AIs issue tracker.

**Comment by BluSunrize** [comment] 2017-06-28 08:13
Duplicate of 
#2236
#2234
#2227
#2224

**Comment by BluSunrize** [comment] 2017-06-28 08:14
Lol, wrong issue I did that on.

**Comment by malte0811** [comment] 2017-06-28 08:15
Um, I think you may have mixed up the issues... This is not the assembler one.

**Comment by BluSunrize** [comment] 2017-06-28 08:16
I know, I know =P

Funky issue, anyway. The Drill does in fact have an action assigned but it's the Bow one not the Bucket one...
I don't even remember why anymore. Can probably remove that code.

**Comment by malte0811** [comment] 2017-06-28 08:40
I think this is on AI's side, but I am not certain. They seem to assume that any item containing a fluid will place that fluid on right click.

**Comment by BluSunrize** [comment] 2017-06-28 08:43
I haven't actually looked into their code, but that'd be a pretty funny reason

**Comment by malte0811** [comment] 2017-06-28 08:45
See [here](https://github.com/pau101/Augmented-Interactions/blob/1.11.2/src/main/java/com/pau101/auginter/client/interaction/type/InteractionBucketDrain.java#L26).
Issue on AI's repo: pau101/Augmented-Interactions#3

**Comment by BluSunrize** [comment] 2017-06-28 09:07
Hah! Nice.
I'll close this one then.

**Closed by BluSunrize** 2017-06-28 09:07 UTC

**Comment by Rosethorns** [comment] 2017-06-28 09:14
does it not matter who's end this is on :P I clearly stated I was posting it to both ;)

**Comment by BluSunrize** [comment] 2017-06-28 10:04
Yeah but I actually can'T do anything about this.
I mean I could, but ASMing other peoples code is very bad practice =P

**Comment by Rosethorns** [comment] 2017-06-28 12:18
was just confirming that it has absolutely nothing to  do with you ;)
