### ISSUE TITLE
[1.12] [0.12-89] Fences connecting to fake light blocks created by floodlights

### ISSUE THREAD

**Issue by gellis12** [BluSunrize/ImmersiveEngineering#3544] opened 2019-08-28 06:20 UTC
### Description of the issue:
Occasionally, treated wood fence posts will have additional limbs on sides that are not connected to other fences. This can be seen on the far left and right sides of the following screenshot:
![2019-08-27_21 53 57](https://user-images.githubusercontent.com/4123225/63828392-24c98f80-c91b-11e9-9491-5c19baeb5fae.png)

### Versions & Modlist:
Minecraft: 1.12.2
Forge: 14.23.5.2838
IE: 0.12-89
Modlist: https://pastebin.com/2kHqhkz6 (From forced crash)

**Comment by gellis12** [comment] 2019-08-29 04:30
Reopening as further testing has revealed that the issue is caused by floodlights.
Turns out fences will attempt to connect to `tile.immersiveengineering.fake_light.name`, despite the block acting the same as air in nearly every other sense.

**Comment by malte0811** [comment] 2019-08-29 06:03
Duplicate of #3447, fixed for the next release of IE.

**Closed by malte0811** 2019-08-29 06:03 UTC
