### ISSUE TITLE
[0.10-57] Crash Involving Turrets

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#1960] opened 2017-03-11 21:39 UTC
Seems to involve a ticking entity. I am unable to re-enter the world

Error: http://pastebin.com/xmsLuFdb

**Comment by BluSunrize** [comment] 2017-03-12 00:09
Yeah that's caused by tamable entities that don't have an owner.
I have fixed this (see issue #1923) but the fix isn't released yet.

You should be able to fix this temporarily by going into Minecraft Forge's config and enabling the option that removes erroring TileEntities.
This will delete the turret as you enter the world, but at least the world will be accessible again.
This issue will be fixed by the next release, until then, I'm afraid there's not much to be done.

**Comment by DrakoAlcarus** [comment] 2017-04-05 10:35
I had this issue, too. Glad to know I'm not alone. I recovered my world/turret early (I had some complex buildings I needed for reference on the world) by using MC Edit to change the entity targeting list and disabling animal, as well as deleting the wolf entity for extra precaution. 

All modded blocks appear as purple cubes with a question mark, but if you know where the culprit is, you can select Inspect Block, and changing the animal targeting value to 0. Make sure you select the base of the turret, because the top half is just a dummy, and changing the values does nothing.

**Comment by BluSunrize** [comment] 2017-05-08 20:20
closing this now, since the new release is due soon.

**Closed by BluSunrize** 2017-05-08 20:20 UTC
