### ISSUE TITLE
Fluid Pipe crash when Ender Generator placed

### ISSUE THREAD

**Issue by ShaneCourtrille** [BluSunrize/ImmersiveEngineering#1812] opened 2016-12-21 17:31 UTC
I placed an EnderIO Ender Generator next to a Fluid Pipe.  Game crashed and now can't get back on to the server.  I've tried the Forge remove erroring tiles option but that didn't have any effect.

Crashlog: https://gist.github.com/ShaneCourtrille/a5364532baf3d5f506a0fbfbb12d36fa

**Comment by BluSunrize** [comment] 2016-12-21 23:12
From what I can see, Ender IO doesn't have an "Ender Generator".
Which mod is it actually from?

**Comment by ShaneCourtrille** [comment] 2016-12-21 23:18
Sorry.  Meant to say Extra Utils.

**Comment by BluSunrize** [comment] 2016-12-22 09:27
duplicate of #1810 then, closing this.

**Closed by BluSunrize** 2016-12-22 09:27 UTC
