### ISSUE TITLE
Cannot invoke "blusunrize.immersiveengineering.common.register.IEItems$ItemRegObject.m_5456_()" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by StarskyXIII** [BluSunrize/ImmersiveEngineering#5516] opened 2022-12-30 09:55 UTC
### Minecraft Version

1.18

### Immersive Engineering Version

8.3.0-155

### Expected Behavior

I am playing on FTB StoneBlock 3 v1.5.0, I want to make a Longbow of the Heavens.
When I press move item button, it can move items in my inventory to the Crafting Grids of Extreme Crafting Table.

### Actual Behavior

I am playing on FTB StoneBlock 3 v1.5.0, I want to make a Longbow of the Heavens.
When I press move item button of REI, it only send me an error message.
``[CHAT] Internal Error: Cannot invoke "blusunrize.immersiveengineering.common.register.IEItems$ItemRegObject.m_5456_()" because the return value of "java.util.Map.get(Object)" is null``
![image](https://user-images.githubusercontent.com/71606873/210057686-9f80558b-a1a0-4f58-a339-b77ee6d54dd4.png)
![image](https://user-images.githubusercontent.com/71606873/210057702-282015b7-7581-4a16-9c5a-0349634556de.png)

### Steps to reproduce

1. press move item button of Longbow of the Heavens  recipe in Extreme Crafting Table
2. Game send an error message in chat

### Debug Crash Log

https://mclo.gs/9Zoo1T7

**Comment by malte0811** [comment] 2022-12-30 15:01
Duplicate of #5508, fixed for the next release.

**Closed as not planned by malte0811** 2022-12-30 15:01 UTC
Labels: bug 🐛
