### ISSUE TITLE
Wires don't transmit any power

### ISSUE THREAD

**Issue by Fr0sk** [BluSunrize/ImmersiveEngineering#752] opened 2015-12-10 01:22 UTC
I tried connecting a kinetic dynamo to a LV and MV wires to capacitors, EnderIO Capacitor Banks and neither charge. Even when I connect to a powered lantern, it doesn't turn on. If I put either the capacitors on top of the kinetic dynamo with the input set to bottom it does charge, so I believe it is some problem with the wires. Running IE 0.6.3 with Immersive Integration and Minecraft Forge 1.7.10 - 10.13.4.1566 (along side other mods)

**Comment by theunkn0wn1** [comment] 2015-12-10 05:32
sounds like a duplicate of #743 and the sort. Will be fixed in next release

**Closed** 2015-12-10 09:54 UTC
