### ISSUE TITLE
Pump not functioning

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#560] opened 2015-11-02 02:29 UTC
Using the current version, I am unable to use the pump to extract fluids from the world.

![2015-11-01_20 00 08](https://cloud.githubusercontent.com/assets/14304823/10873019/601e7a08-80d3-11e5-8108-28767bf3fa58.png)
This is my current setup. The pump is powered with both redstone and electricity.

Also, I've noted that the pump will not act as a fluid accelerator when connected to two metal tanks, in fact it will prevent it from transfering.

![2015-11-01_20 24 16](https://cloud.githubusercontent.com/assets/14304823/10873213/a2741310-80d6-11e5-9f7a-50b671e9d181.png)
In this setup, the fluid will not transfer between the tank with water in it and the empty tank.
Also to note, when the tanks are connected by just pipes, the water stored in the first tank will not deplete, but the water stored in the second tank will increase.

**Comment by theunkn0wn1** [comment] 2015-11-02 02:34
I cannot see from your pictures, have you used the hammer to set the inputs and outputs? The pump won't work unless they are explicitly set.

**Comment by James-T-Oudvoure** [comment] 2015-11-02 02:40
Yes, I have set the inputs and outputs for both pumps, Technically only the output for the first pump, as I'm not really sure just where the hell I put the input on that.

**Comment by theunkn0wn1** [comment] 2015-11-02 04:34
Managed to reproduce your issues in full.

Issue[1][a]: Pumps do nut function when IE's pipes separate it from the valid source tank entity.
Issue[1][b]: Pumps will not output fluid if a pipe separates it from the valid target tank entity.
Pictures of my setup are below:
![image](https://cloud.githubusercontent.com/assets/3110986/10874333/499cfd78-80d7-11e5-986f-2530c3145c26.png)
![image](https://cloud.githubusercontent.com/assets/3110986/10874342/75a33c70-80d7-11e5-8d92-e9f9acf8dc0d.png)
![image](https://cloud.githubusercontent.com/assets/3110986/10874348/83cbb39a-80d7-11e5-9ead-9aa738a4ee97.png)


Issue[2] Tanks, when filled manuallly via vanilla buckets , both accept the fluid into its tank as well as dumping the fluid into the world.

IE build 7e64713

**Comment by cobra** [comment] 2015-11-02 08:13
The first issue is not caused by the pump, but the pipes, see PR #556. The rest may be related.

@theunkn0wn1 what do you mean by issue 2? Which tanks? The IE ones? If so, I have a strong suspicion of what's happening there.

**Comment by theunkn0wn1** [comment] 2015-11-02 08:17
For issue 1 it is certainly the pipes, when I replaced the pipes with fluidducts the pump functioned as expected(correctly)

For issue 2 I was referring to the IE ones, the sheet metal tanks.

**Comment by cobra** [comment] 2015-11-02 09:20
That second one was me, not testing with water and ignoring the side check above when allowing stuff to be placed on tanks when there is no interaction with the tank -_-
Testing a fix.

**Comment by cobra** [comment] 2015-11-02 09:52
As far as I can see, all these issues have been fixed in my repo. The pipes checking the wrong direction will break a lot of stuff with configurable sides - setting opposing sides to the same input/output/nothing mode is a workaround until the fixes get pulled and a new version is built.

**Comment by Ayrrow** [comment] 2015-11-02 13:14
I am also having both of these problems.

**Closed** 2015-11-02 15:22 UTC
