### ISSUE TITLE
[1.15.2]  Industrial Hemp not fully rendering

### ISSUE THREAD

**Issue by Kukaratza** [BluSunrize/ImmersiveEngineering#3968] opened 2020-06-12 20:18 UTC
Industrial Help not fully rendering, it has white lines around it. I did press F3+C for 10 secs, Log attached. I have attached also a screenshot.
[crash-2020-06-12_13.11.54-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4773035/crash-2020-06-12_13.11.54-client.txt)
![Industrial_hemp_issue](https://user-images.githubusercontent.com/34723951/84542864-264c2480-acaf-11ea-9c6c-0529e4d4df56.png)

**Comment by malte0811** [comment] 2020-06-13 04:36
Duplicate of  #3955

**Closed as completed by malte0811** 2020-06-13 04:37 UTC
