### ISSUE TITLE
[1.12.1] External Heater has no block texture

### ISSUE THREAD

**Issue by Branjoman** [BluSunrize/ImmersiveEngineering#2613] opened 2017-11-14 18:31 UTC
When you get an external heater and place it down in the world, the block itself has no texture, instead appearing as a clear box (also allowing you to see through the world).:
[https://imgur.com/SD1j5x4](https://imgur.com/SD1j5x4)
output log:[https://pastebin.com/6Zqu02Dj](https://pastebin.com/6Zqu02Dj)

Another related issues it that in my survival world, I can't seem to get the external heater to accept power, no matter how many times I click on the face connected to the wire connector. Oddly, I can't reproduce this issue in a separate creative world.

Both these issues are on the latest release 0.12-74.

**Comment by malte0811** [comment] 2017-11-14 18:42
The first issue is a duplicate of #2552 (fixed for the next release). The second one is new though.

**Comment by Branjoman** [comment] 2017-11-15 16:13
Good to hear about the first issue. About the second one, the main problem could be that I can’t actually SEE myself toggling the connection. Especially suspicious since I can’t replicate the issue.

**Comment by Xenos13** [comment] 2017-11-15 23:58
@Branjoman, I couldn't rotate heater too, but it may be powered on. Place it on neutral block (such as cobblestone), then place connector at the front. If placing on furnace directly, connector side will be at the back.

**Comment by BluSunrize** [comment] 2017-12-31 10:15
Is the problem of powering it still existent? If so, could you provide pictures of the setup please?

**Comment by Xenos13** [comment] 2018-01-02 18:10
@BluSunrize, right-click turns the heater counter-clockwise, shift-right-click turns it clockwise. none of these actions moves the connector to the front side, but now it isn't a critical problem, I think. the heater looks correct now, so the connector is visible.
Happy New Year :)

**Comment by BluSunrize** [comment] 2018-01-02 19:14
I mean, if you rotate it, you can rotate it to face the front, can't you? It should always rotates around the side you are clicking.

**Comment by Xenos13** [comment] 2018-01-03 19:41
@BluSunrize, yes, the heater rotates around the side I am clicking. also, shift-clicking on the connector (and on the opposite side) swaps it between these sides. IE 0.12-76

**Closed** 2020-06-06 11:49 UTC
