### ISSUE TITLE
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.indexOf(Object)" because "blusunrize.immersiveengineering.api.IEApi.modPreference" is null

### ISSUE THREAD

**Issue by dimondking2016** [BluSunrize/ImmersiveEngineering#5515] opened 2022-12-27 05:33 UTC
### Minecraft Version

1.18

### Immersive Engineering Version

8.3.0-155

### How did it happen?

I was in the middle of a raid watching as my army of iron golems were fighting an army of vindicators and pillagers, It was night time and the sun started coming up just before the game crashed. I am now locked out of my world as it crashes whenever I load it.

### Crash Log

https://mclo.gs/qFcTlaN

**Comment by Proxwian** [comment] 2022-12-27 06:13
Same

**Comment by malte0811** [comment] 2022-12-27 09:13
Please upload the full log, this should not be possible unless the IE config isn't loaded for some reason. Both `logs/latest.log` and `logs/debug.log` would be useful.

**Comment by dimondking2016** [comment] 2022-12-28 02:14
So when the issue came up after uploading this I deleted the mod and all my configs and later last night I re-downloaded immersive engineering and It's working fine again.
Nonetheless here is my log and debug closest to the time of the crashes.

[debug-5.log](https://github.com/BluSunrize/ImmersiveEngineering/files/10311642/debug-5.log)
[2022-12-27-6.log](https://github.com/BluSunrize/ImmersiveEngineering/files/10311659/2022-12-27-6.log)

**Comment by dimondking2016** [comment] 2022-12-28 02:16
If the same issue comes up again I'll post the logs here.
Proxwian could you also post your logs too? The more logs the better probably.

**Comment by Proxwian** [comment] 2022-12-28 13:40
Looks like we've both have the same issue in one hour and it just disappears for now. Will keep my eye on logs next time

**Comment by ColinVaughn** [comment] 2023-01-10 09:07
issue on 1.19.2 also

**Comment by malte0811** [comment] 2023-01-13 09:08
@Proxwian are you also using CoroUtil 1.18.1-1.2.42 or above? I suspect that [this](https://github.com/Corosauce/CoroUtil/blob/7a8188ad5da1afe2ea8eba5f51d24348495f5386/src/main/java/com/corosus/modconfig/ModConfigData.java#L208-L227) code added in that release causes the issue, that would also explain why it started popping up without any relevant changes to IE.

@ColinVaughn please upload the crashlog and the full client log. The problematic code in CoroUtil is not in any 1.19.2 builds, so that can't be the issue in your case.

**Comment by malte0811** [comment] 2023-01-13 10:00
Since that code is a very plausible cause (especially as a CoroUtil config is added+loaded right when the IE config is added in the logs), and the issue seems to be random and rare-ish, I'll close this for now. If anyone runs into this crash without CoroUtil or with a fixed version (once that is available), please comment on this issue and include links to the crashlog and the full debug log.

**Closed as completed by malte0811** 2023-01-13 10:00 UTC
Labels: crash 💥

**Comment by ColinVaughn** [comment] 2023-01-14 00:34
I'm getting this crash and I don't have CoroUtil. I'll send a crash report when I get a new one.

**Comment by Proxwian** [comment] 2023-01-14 16:28
[crash-2023-01-14_23.26.29-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/10418192/crash-2023-01-14_23.26.29-server.txt)

It does not look like issue with coroutil, but IE API

**Comment by malte0811** [comment] 2023-01-14 16:40
@Proxwian The crash itself is in IE API, but the root cause of the crash is in CoroUtil. [This](https://www.curseforge.com/minecraft/mc-mods/coroutil/files/4331325) build of CoroUtil should fix it.
