### ISSUE TITLE
[Suggestion] Own Crafting for Assembler

### ISSUE THREAD

**Issue by LuxerTheGamer** [BluSunrize/ImmersiveEngineering#3209] opened 2018-09-12 19:36 UTC
Hi. Can you add own crafting (supported by CraftTweaker) for Assembler with option, which disable/enable normal crafting.
It will make assembler more useful for modpack makers.
Thanks for help.

**Comment by malte0811** [comment] 2018-09-12 19:48
Duplicate of #2886

**Closed by malte0811** 2018-09-12 19:48 UTC
