### ISSUE TITLE
The External Heater texture doesn't show in 1.12.1 

### ISSUE THREAD

**Issue by MidnightTempest** [BluSunrize/ImmersiveEngineering#2574] opened 2017-10-22 11:33 UTC
![2017-10-22_13 28 56](https://user-images.githubusercontent.com/32905735/31861443-04ce0e8e-b736-11e7-9924-af9d5a5b8e97.png)

**Comment by malte0811** [comment] 2017-10-22 11:52
This is a really bad bug report, you are missing nearly all requested info. And it is a duplicate of #2552.

**Closed by malte0811** 2017-10-22 11:52 UTC
