### ISSUE TITLE
[1.12.2] java.lang.IllegalStateException: The fluid handler blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe@24d8d5f filled inconsistently

### ISSUE THREAD

**Issue by Antaiir** [BluSunrize/ImmersiveEngineering#3515] opened 2019-07-18 13:00 UTC
### Description of the issue:

My problem occurs by playing MC 1.12.2 with "FTB Revelation" (v3.0.1)

I run a IC2 biogas power plant and using IE's fluid pipes to move the biogas around. So far all is running fine and i decided to recreate the feeding of biogas to the generators, because i like to connect all machines to my me-system (AE2).

Actually i have four identical groups of generators running (8 generators in each group, connected via 2 transformers and 1 CESU to main transformer)), feeding the energy into one main powerline. The biogas is fed from a large buffer tank (10k B iron tank from Railcraft) via a fluid pump and fluid pipes (both IE) into the generators. 

My approach for the new connection: i cutoff the fluid pipes from the buffer tank, place 1 tank (24 B, IC2) as a small buffer directly to every of the 4 groups of generators and feed this new tank via "Fluid Export Bus" from my me-system.

For the first group this worked fine and is running flawless for hours (and hours and hours ... and so on).

As soon as i try to do the same changes to the next group, the buffer is starting to fill up with biogas, and after few minutes the game is crashing to desktop with:

"Description: Ticking block entity

java.lang.IllegalStateException: The fluid handler blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe@24d8d5f filled inconsistently. Expected 50, got 49."

See full crash log here: https://pastebin.com/byb3dsLk

After the crash the save is corrupt and i have to use a backup.

I spent hours trying to find the problem, see if there is something different in that group from the first one... but i didn't find anything. As far as i can say, all generator groups are absolutely identical, and my steps for doing the changes were also exactly the same. I reproduced this several times.

There are no other blocks in range, where could be an unwanted connection by accident, so i have no idea, what may cause this crash.

The planned biogas flow is as follows:

Fermenter with Fluid Ejector (IC2) --> Fluid Pipe (IE) --> Tank (IC2, as a buffer) --> Fluid Import Bus (AE2) --> ME Storage System (AE2) --(line to the generators by using AE2 network)--> Fluid Export Bus (AE2) --> Tank with Fluid Ejector (IC2, as a buffer) --> Fluid Pipe (IE) --> Semifluid Generator (IC2)

As mentioned above, this is working fine for the first group only.

The interim setup (all other groups are still using this) is like:

Fermenter with Fluid Ejector (IC2) --> Fluid Pipe (IE) --> Tank (IC2, as a buffer) --> Fluid Import Bus (AE2) --> ME Storage System (AE2) --> Fluid Export Bus (AE2) --> Iron Tank (Multiblock from Railcraft, will be obsolete) --> Fluid Pump (IE) --> Fluid Pipe (IE) --> Semifluid Generator (IC2)

The last fluid pipe in this setup is the one i want to cutoff to replace it by the buffer tank for feeding directly from the me-storage.

Design of each of my 4 generator groups: 

4 generators surrounding 1 lv-transformer, 2 of those lv-transformers are attached to 1 CESU. 

Those CESU are connected to the next transforming stage.

### Crashlog:

Full crash log: https://pastebin.com/byb3dsLk

### Versions & Modlist

MC 1.12.2 with "FTB Revelation" (v3.0.1)

Full modlist and their version numbers should be in the crash log. Please let me know, if there is anything missing.

IE and Forge versions: 
Immersive Engineering 0.12.89
Forge 14.23.5.2836

I have no idea what could be wrong with my game. Any help or advise is appreciated.

Thanks in advance and kind regards

**Comment by mindforger** [comment] 2019-07-18 13:17
from a quick sweep over google, this seems to be in IC2's ballpark

they seem petty/picky on how some mods deal with fluids (EIO, BC, and a few more similar)

it looks like all mods deal just fine with fluids but IC2 keeps crashing because something did not went like they expect to

also they have been blamed quite a bit to not provide anything usefull with their thrown exception and it still does not telly anything usefull

**Comment by BluSunrize** [comment] 2019-07-18 13:27
duplicate of #3345

**Closed by BluSunrize** 2019-07-18 13:27 UTC

**Comment by Antaiir** [comment] 2019-07-18 13:45
> duplicate of #3345

Mh, i'm not sure if this is the same issue. Because the crash mentioned over there seems to be caused by 2 different fluids trying to enter the very same pipe. I had this one too some time ago.

My issue above doesn't involve 2 different fluids.

**Comment by malte0811** [comment] 2019-07-18 13:49
If you look at my comment on that issue you'll see that there aren't 2 fluids involved, the same fluid is being inserted into 2 sides of the same block.

**Comment by Antaiir** [comment] 2019-07-18 16:25
After some more testing it seems indeed, the source of my problem is the tank from IC2. I opened a ticket there.

Thanks.

**Comment by Antaiir** [comment] 2019-07-22 15:05
I have a response from my ticket at IC2... and they blame IE for this bug. See https://bt.industrial-craft.net/view.php?id=2566

What should i do now? Is there anything i can do to solve this problem on my own? 

regards
