### ISSUE TITLE
Inconsistent scaffolding textures on stairs

### ISSUE THREAD

**Issue by AntiBlueQuirk** [BluSunrize/ImmersiveEngineering#3202] opened 2018-09-08 07:43 UTC
### Description of the issue:
Scaffolding blocks have multiple texture variants that can be cycled through by crafting them alone. The special texture variant appears on the top of the block, while the regular scaffolding texture appears on the bottom. This applies to each type of block (block, slab, stairs), *except* when stairs are placed upside down. When stairs are placed upside down, the special texture appears on the bottom of the block. This makes designs that mix blocks and slabs with stairs look unusual, and I do not believe this is the intended behavior. (If it is, this issue can be closed.)

Stairs, blocks, and slabs:
![2018-09-08_02 29 04](https://user-images.githubusercontent.com/25140955/45251730-bd34c180-b310-11e8-83d7-b99d9fe5dac5.png)

Same arrangement, but with stairs upside down:
![2018-09-08_02 29 36](https://user-images.githubusercontent.com/25140955/45251737-d6d60900-b310-11e8-840a-7424e9fd33fe.png)

Upside down arrangement from bottom:
![2018-09-08_02 30 09](https://user-images.githubusercontent.com/25140955/45251741-e5242500-b310-11e8-95c8-26c5f83ff04e.png)

### Versions & Modlist
Minecraft: 1.12.2
Forge: 14.23.4.2760
IE: 0.12-85

**Comment by AntiBlueQuirk** [comment] 2018-09-10 06:48
A better example of why I believe this is an issue:
![2018-09-10_01 44 30](https://user-images.githubusercontent.com/25140955/45280736-2c3e2180-b49b-11e8-8ecd-983abdd079fc.png)
The platforms are built out of blocks in the back and slabs in the front, with stairs between them. On the right, the stairs lead down to the slabs. On the left, the stairs are upside down, leading up to the slabs. 

Since there is no other way to get special scaffolding textures on the bottom of the blocks, I do not believe it is intended for stairs to behave like this when upside down.

**Comment by mindforger** [comment] 2018-09-10 07:16
did you check the stairs from below? i think this is some backface culling stuff, the back face of the upside down slabs is not rendering (because the block is not meant to render the backface that you are technically not facing) 

the edge you see on the right ist technically spoken 0 pixel thick but the top face makes it look like there is an edge, without the top face rendering it would look like the left side

imho it would require to add an texture for the side when it is half to include the same border as the outline on top and bottom of the block

**Comment by AntiBlueQuirk** [comment] 2018-09-10 08:56
Here is the same arrangement from the bottom (Wool added to clearly show block boundaries):
![2018-09-10_03 52 29](https://user-images.githubusercontent.com/25140955/45287081-07eb4080-b4ad-11e8-8197-f8d83c832efe.png)

If the intended behavior is for the special scaffolding textures to render on the top, the stairs are clearly rendering incorrectly. If I had to guess, I would say that it is rendering the same model as right-side-up stairs, just rotated upside down. This is fine with vanilla stairs, since it has the same textures on each side. But these stairs have special textures on top, so simply rotating the model upside down changes which side the special textures are on.

**Comment by mindforger** [comment] 2018-09-10 10:08
oh wait i did not get the point you were talking about stairs sorry, i was fixiated to those borders looking sketchy :D sorry

**Comment by KnightMiner** [comment] 2018-09-10 13:02
Worth mentioning vanilla sandstone stairs have the same bug, bug it was closed as "works as intended" for some odd reason. It's a pretty easy fix though, just have to add a second set or models for upside down stairs with the top and bottom textures reversed

**Comment by AntiBlueQuirk** [comment] 2018-09-10 23:00
@KnightMiner Interesting. I hadn't noticed that before. Though in that case, the smooth sandstone blocks (but not slabs) show matching textures on top and bottom, so you have something to match against whether the stairs are upside down or not.

**Comment by mindforger** [comment] 2018-09-17 12:17
@malte0811 do you see any chance of giving this issue a tackle anyhow? i do not want to rush you or anything, just knowing this is not forgotten would be nice :) 

or a reason for being not fixable easily

**Comment by malte0811** [comment] 2018-09-17 12:28
It should be a fairly easy fix, but I don't know whether Blu and/or Hazard consider this a bug or intended behavior. I can see why it's annoying, but it also matches intended vanilla behavior.

**Closed** 2020-06-06 11:42 UTC
