### ISSUE TITLE
[1.12.2] Inventory Item Render crash when running IE with OptiFine

### ISSUE THREAD

**Issue by johnelder** [BluSunrize/ImmersiveEngineering#2881] opened 2018-03-16 16:50 UTC
IE is crashing the client with a rendering error. I haven;t been able to find any fixes for this issue.
To reproduce:
   Install IE and Optifine (I'm using C9) on 1.12.2
   Create a new world in creative mod.
   Open the inventory and go to the IE items tab.  Scroll down until it crashes.

The error only happens when IE and Optifine are both running.
crash-report: https://pastebin.com/Ba4gVFfv

**Comment by BluSunrize** [comment] 2018-03-16 16:59
I'm afraid Optifine is not supported by us.

**Comment by malte0811** [comment] 2018-03-16 17:02
Aside from that this is a duplicate of #2842. It is fixed for the next release.
The rendering of feedthrough connectors won't be ideal with OF, but that is harder to fix (AKA won't be fixed unless I have far too much free time).

**Closed by malte0811** 2018-03-16 17:02 UTC
