### ISSUE TITLE
Suggestion for Fluid Control

### ISSUE THREAD

**Issue by CJL48** [BluSunrize/ImmersiveEngineering#1927] opened 2017-03-02 03:08 UTC
The new mixer is great, but it has a habit of outputting the fluid that you put into it. (ie piping water in while it has a tank/pipe to automatically output into will result in the water arriving in the processing tank, and immediately going out the output port)
I would like to suggest, valves and filters.
Fluid Valve- redstone/hand to prevent flow through a pipe (currently, there is no way to automatically stop fluids from being ejected from a machine that automatically ejects fluids).
Fluid Filter- only let the specified fluid(s) through

**Comment by kane-thornwyrd** [comment] 2017-03-02 07:49
afaik this will be a big nope, but since the pipe are transferring the fluid without buffer, you can "simulate" a filter by outputing into different pre-filled buffers (understand tanks), I guess this would work.

**Comment by BluSunrize** [comment] 2017-03-02 09:34
Well, for one, the mixer only outputs a fluid if it can't find a recipe for it. As long as you keep items stocked in it to mix with the fluid, it won't output.
However, yes, the issue is known to me, I was running into it in dev and was eager to release a build so I ignored it for now.

I'll look into adding a Fluid Router, akin to the existing Item Router ^^

**Comment by BluSunrize** [comment] 2017-03-08 10:37
Fluid Router is a thing now:
https://github.com/BluSunrize/ImmersiveEngineering/commit/1da7e3625dff1932bddcb673d3d30939cfea9ed3

**Closed by BluSunrize** 2017-03-08 10:37 UTC
