### ISSUE TITLE
Crash in 1.12 | 0.12 - 64 | Server-side only

### ISSUE THREAD

**Issue by ExDomino** [BluSunrize/ImmersiveEngineering#2274] opened 2017-07-09 12:50 UTC
Minecraft : 1.12
Forge : 2405
ImmersiveEngineering : 0.12-64

Crash only server-side, doesn't crash client-side.

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.client.ClientProxy

https://pastebin.com/U6D7A1vm

**Comment by malte0811** [comment] 2017-07-09 12:56
Duplicate of #2270, fixed for the next release which will probably be released today.

**Closed by malte0811** 2017-07-09 12:56 UTC

**Comment by ExDomino** [comment] 2017-07-09 13:01
Thanks. We're looking forward this next release.
