### ISSUE TITLE
[MC 1.16.1] Crash when using Buzzsaw

### ISSUE THREAD

**Issue by Cynix32** [BluSunrize/ImmersiveEngineering#4192] opened 2020-08-10 10:12 UTC
Forge 32.0.106
Minecraft v1.16.1
IE version: ImmersiveEngineering-1.16.1-3.1-112

(I am apologizing in advance because English is not my native language, and I am new to github. I just created this account to post this issue)

Description
CRASH WHEN USING BUZZSAW

Minecraft crashed when using buzzsaw on a tree.  As soon as I broke the first block of the tree, minecraft crashes. After that, trying to get back into that world would result in a crash, basically making the world unplayable.

In my playthrough, I was playing survival and I just created the buzzsaw to clear out a dense spruce forest. Built the machineries needed to make fuel, tools, etc... Then when it was time for me to use the buzzsaw just to test how it would work. The world crashed as soon as I broke the tree.

In the crashlog and devconsole, it showed this:
https://controlc.com/85a383bf

I don't know how to read code, but I noticed OptiFine appearing multiple times on that log, so I disabled it on my next launch. Minecraft still crashed as soon as I loaded the world. Error log:
https://controlc.com/1d7c016a

So I thought that it was just that specific world was broken. I then created a fresh creative world to recreate the crash just to be sure. As soon as I did the same thing (I cut the same type of tree: Spruce), MC crashed again. Reloading the world again crashes it too, making it unplayable. Error log:
https://controlc.com/2c599dd9

The final step I did before posting this here was to do it again but with literally no other mod (aside forge) installed aside from IE (no OptiFine, JEI, no anything). It kept happening. Error log:
https://controlc.com/9fa40037

Mods that I have installed on my very first crash on the first world:
HWYLA
JEI
Mekanism
Curios
I turned off all of these on my last crash.

I am also playing Single Player, if that info helps. I really want that survival world back coz I don't want to lose my progress on my very first survival world. I also searched for a similar crash on the issues page, and the error logs seem similar to issue #4179

**Comment by Cynix32** [comment] 2020-08-10 10:17
Additional Info:
The Buzzsaw I used in all of those crashes was just a regular buzzsaw (buzzsaw + sawblade only).

**Comment by malte0811** [comment] 2020-08-10 10:21
Duplicate of #4179

**Closed as completed by malte0811** 2020-08-10 10:21 UTC
