### ISSUE TITLE
Unable to activate Bottling Machine

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BluSunrize/ImmersiveEngineering#3147] opened 2018-08-01 23:52 UTC
I've tested all Multiblocks and the Bottling Machine is the only one i cannot activate with the hammer.

i checked the constrution multiple times, rebuilt it multiple times via the Projector and Manually.
Nothing worked.

IE: 0.12-84
IP: 1.1.9
Forge: 14.23.4.2739

**Comment by BluSunrize** [comment] 2018-08-02 00:46
Providing pictures of your setup would be rather helpful.

Have you made sure that you were using normal conveyors and not the redstone-ignoring ones?

**Comment by ProxyPlayerHD** [comment] 2018-08-03 07:31
yes, i checked multiple times, and the projector only places the exact blocks required, so it would never place the redstone ignoring belts as well.


![2018-08-03_09 26 14](https://user-images.githubusercontent.com/13576843/43630024-5265347a-96ff-11e8-9fa3-39597567fbc0.png)

**Comment by BluSunrize** [comment] 2018-08-03 11:03
Works perfectly fine for me.

I can't speak for the projector, that's Flaxbeards. I just built it manually in dev and it worked no problem.

**Comment by ProxyPlayerHD** [comment] 2018-08-03 11:55
they are facing the right way. did you also test with IP installed?

it seems like the only mod that would do anything to IE so imma remove it and see it if works.

**Comment by KroinLeon** [comment] 2018-08-03 16:58
Hi, so i tested this (with only IE [12-84]) and the ones who faces the west/east won't form, taking the redstone engineering block as front.
here's a pick:
https://imgur.com/8OdtxrR

**Comment by BluSunrize** [comment] 2018-08-03 22:11
![image](https://i.imgur.com/R3pRWvK.jpg)

Worked fine for me :V
The conveyors need to be pointing in the direction of the light engineering block.

**Comment by KroinLeon** [comment] 2018-08-03 22:17
Yes, that was the issue, it seems that the projector places the conveyors wrong on that cardinal directions.. #WeirdMinecraftThings

**Comment by BluSunrize** [comment] 2018-08-04 21:41
See, and that's why I explicitely said to build it manually. The projector isn't IE, so I'm not liable for that derping up your structures.

I'll close this then, I suppose.

**Closed by BluSunrize** 2018-08-04 21:41 UTC

**Comment by mindforger** [comment] 2018-08-05 06:17
@KroinLeon please report this to immersive integration, i think there is already a similar issue there but i am on my phone and can not link the issues

**Comment by ProxyPlayerHD** [comment] 2018-08-06 12:03
but i did place everything manually multiple times. the conveyors were facing the right direction each time.

i don't understand, what was the problem then?

**Comment by BluSunrize** [comment] 2018-08-06 12:37
I dunno? Is it working for you now?

I mean, it proved wholly irreproducable from my end and you didn't provide any more instruction on reproduction or discovered edgecases...

**Comment by mindforger** [comment] 2018-08-06 12:53
@BluSunrize KroinLeon reported the holo-tool shows wrong direction, ProxyPlayer (the OP) told he had built it by hand

@ProxyPlayerHD did you place it by hand by using ther book or after the holo-tool? the holo-tool seems to show wrong directions for the conveyors

try building it in all 4 directions like KroinLeon did and try it with th conveyors in both directions

**Comment by BluSunrize** [comment] 2018-08-06 13:02
Mind, I'm very much aware. I specifically requested it to be built by hand *multiple times*
Problem is that even the initial report provides only a *single picture*, on which conveyor direction is *impossible to see* and we can't even see all layers of the structure.

Given that it worked fine for me in all 4 orientations, I was forced to chalk this up to user error, unless someone actually provides reproducible conditions and decent instructions.

**Comment by ProxyPlayerHD** [comment] 2018-08-06 13:11
well it does work now, i have no idea how i even missed the fact that the belts were simply pointing in the opposite direction.

so let me explain what i think is happening: the Projector has the conveyors in the correct direction but the rest of the structure is by default mirrored. you can confirm this by taking the projector and just mirroring the projection. the blocks on either side switch but the belts stay the same.

and i have no idea why it is mirrored by default, you can jus ttake a fresh Projector and the LEBs (Light Engineering Blocks) and Iron Sheet blocks will be on the wrong sides.

this can be fixed by either switching the blocks to fit the belt direction, or switching the belt direction to fit the blocks.
![1](https://i.imgur.com/3XxJ9AR.gif)

![2](https://i.imgur.com/8L0cyJ9.gif)

(in case they don#t load 1: https://i.imgur.com/8L0cyJ9.gifv 2: https://i.imgur.com/3XxJ9AR.gifv )

**Comment by ProxyPlayerHD** [comment] 2018-08-06 13:31
well it is easier said than done when this was literally the only structure it displays incorrectly.

**Comment by mindforger** [comment] 2018-08-06 14:57
hehe ... well at least we found the issue, now someone needs to tell the holo-thingy dev that there is something wrong

**Comment by ProxyPlayerHD** [comment] 2018-08-06 15:43
done.

**Comment by roboderpy** [comment] 2018-10-29 12:58
This is actually bug on IE side - Immersive Engineering actually doesn't accept `Ignore redstone control` belts for being used instead of regular belts.

**Comment by BluSunrize** [comment] 2018-10-29 13:01
Well no, because they aren't normal conveyor belts.
That also wasn't the issue here either, so why necropost this?

**Comment by roboderpy** [comment] 2018-10-29 15:13
That is the issue here - you can't assemble bottling machine with conveyors with redstone ignore enabled, but projector tells you can. And in common sense you also need to be able to do so, since they are just conveyors with redstone ignorance. And i bet you will get somewhat this report in future even without projector since i see most of users just craft all conveyors and set their mode to ignore redstone right after their craft.

**Comment by BluSunrize** [comment] 2018-10-29 15:42
No, given that you neglected to actually read the issue described here, the problem was caused by the conveyors facing the wrong way >_>
