### ISSUE TITLE
[1.16.1] Drill crashes game and locks user into an inescapable crash loop on rejoin

### ISSUE THREAD

**Issue by ChrisThirtle** [BluSunrize/ImmersiveEngineering#4184] opened 2020-08-08 22:00 UTC
### Description of the issue:
Using the handheld mining drill in survival caused a fatal crash, and reloading causes the person who did use it to be unable to rejoin that world due to immediately fatally crashing again. No clue if it's because of the pack I'm using right now.
When I went into a creative world to test it oddly enough the drill did not remove me from existence until I went into /gamemode survival, upon which the very first set of broken blocks crashed me again.

### Crashlog:
https://gist.github.com/ChrisThirtle/95d4c67b5a0f3241eff945ebefeda73d

### Versions
Forge version 32.0.106
Immersive Engineering v1.16.1-3.1-112
Big pile of other mods since it's a modpack but those are IE's versions, and stacktrace seems to only reference IE

**Comment by BluSunrize** [comment] 2020-08-08 22:11
Duplicate of #4179 

Please search next time

**Closed as completed by BluSunrize** 2020-08-08 22:11 UTC

**Comment by ChrisThirtle** [comment] 2020-08-08 22:14
Sorry, tried searching and missed it I guess

**Comment by mindforger** [comment] 2020-08-09 09:14
always check for closed issues too :)
