### ISSUE TITLE
[1.10.2] rendering issue 

### ISSUE THREAD

**Issue by loordgek** [BluSunrize/ImmersiveEngineering#2377] opened 2017-07-30 19:32 UTC
the water wheel seams only to happen when broken by a ticon lumberjack
![immers2](https://user-images.githubusercontent.com/4789835/28756305-0e64ae96-756c-11e7-9977-6f4bebc7f152.png)

this happens when trying to extend the posts (happens on all 3) to have a side thingy
does not happen all the time
![immers1](https://user-images.githubusercontent.com/4789835/28756306-0e64b378-756c-11e7-997b-f0c0e580a527.png)

this only happens i my world i am playing AoE 1.0.4 when i setup a test world it does not happen
this is the world download
https://1drv.ms/u/s!Ai-emKyjYKqWg6g1KpHUEh8HeUo7Zw
![immers3](https://user-images.githubusercontent.com/4789835/28756400-adfe4c40-756d-11e7-9d5d-dcf1686088cc.png)

the log from the wheel and post issue https://gist.github.com/loordgek/4a51c437049bdcbcf8255c5fabd81793

**Comment by loordgek** [comment] 2017-07-30 19:44
is the invisible posts this https://github.com/BluSunrize/ImmersiveEngineering/issues/2311#issuecomment-315616875 ??

**Comment by BluSunrize** [comment] 2017-07-30 19:44
Most of those issues should be fixed by just logging out and in again. It's just render oddities caused by rendering happening before tile sync and stuff.

Also, 1.10 isn't really supported anymore.

**Comment by winsrp** [comment] 2017-08-01 20:00
same thing happens to me with posts, in 1.12, using the hammer on the post makes things go crazy... I love those posts!! hopefully you guys manage to find a way to fix it eventually.

**Closed** 2020-06-06 11:31 UTC
