### ISSUE TITLE
Electrician villager giving negative quantity of wires

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#1526] opened 2016-10-01 01:01 UTC
As of ImmersiveEngineering-0.10-42 with forge1.10.2-12.18.1.2094
![image](https://cloud.githubusercontent.com/assets/4776032/19010596/3daabbbe-8783-11e6-83de-35198e17285c.png)

**Comment by GirafiStudios** [comment] 2016-10-01 01:04
Duplicate of https://github.com/BluSunrize/ImmersiveEngineering/issues/1470 and have already been fixed :)

**Closed** 2016-10-01 01:07 UTC
