### ISSUE TITLE
Client Crash - WyldLife - Fluid vs. EU2 Magamtic Generator

### ISSUE THREAD

**Issue by Okimo** [BluSunrize/ImmersiveEngineering#1815] opened 2016-12-22 16:37 UTC
So Crash Happen when I tried place fluid tube next to Extra Util. 2 - Magmatic Generator
Its Client Crash so server is running fine only its crashing for those who are nerby.
Looks like other instead of me they have chance to leave the area.

Crash Log MP : http://pastebin.com/xUTfQXf1
Crash Log SP : http://pastebin.com/EaUSn4MH
Video: https://www.youtube.com/watch?v=r1w0x_4cGns&feature=youtu.be

Immersive v. 0.10-52
Extra Util. 2 - 1.1.2
WyldLife -  1.2.5

**Comment by BluSunrize** [comment] 2016-12-22 17:33
duplicate of #1810

**Closed by BluSunrize** 2016-12-22 17:33 UTC
