### ISSUE TITLE
[0.12 -82] [Sevtech: Ages xPost] Getting electrocuted by phantom (broken) IE wires.

### ISSUE THREAD

**Issue by dalsio** [BluSunrize/ImmersiveEngineering#3000] opened 2018-05-19 01:24 UTC
### Description of the issue:
Reported this on the Sevtech git, was told to report it here and link back since it seems to be purely an IE problem. Original Issue: [Sevtech: Ages Issue \#2484](https://github.com/DarkPacks/SevTech-Ages/issues/2484)

>## Issue/Bug
>
>Occasionally, and I can't seem to pin down exactly why, I will take wire damage (and often die) from an IE wire I just recently broke. The wire can still exist long after it has been broken (and killed me many times). I'm 100% sure the wires are not there, since they drop into my inventory and no power is transferred through them. I'm also quite some distance from any other wires. I did some testing and it seems to happen consistently when I break the HV connector (and wire) to my [Immersive Tech] Distillation Tower (tried it on my [Immersive Petroleum] pumpjack and everything behaved normally). The wire drops on the [Immersive Tech] boiler below and where it used to be is an invisible HV-power electrocution zone. The space the connector used to occupy is unaffected. It also happened with LV wires and connectors once, but I don't have any logs from then nor do I know for sure what I did to cause it. Forcing a block update on the empty space where the connector used to be does not fix the issue, but reloading the game does.

### Crashlog:
Didn't cause a crash, but here's some latest.log files from some testing I did anyway:
1.    https://gist.github.com/dalsio/5046d570720fe01178be1267769bac16
2.    https://gist.github.com/dalsio/1751338a03cfab193dbbe720f1f10c63
3.    https://gist.github.com/dalsio/db150aa426c864a3449d123345d418d3

### Versions & Modlist
Full Sevtech 3.0.7 Modlist without additional mods (No optifine or server mods ETC.)
MC: 1.12.2
Forge: 14.23.3.2679
Immersive Engineering: 0.12 - 82
Immersive Tech: 1.3.8
Immersive Petroleum: 1.1.9

**Comment by malte0811** [comment] 2018-05-19 05:11
Duplicate of #2980 (might not look like one, but it is). Fixed for the next IE build.

**Closed by malte0811** 2018-05-19 05:11 UTC

**Comment by Exanadu** [comment] 2019-06-29 18:21
Still getting this glitch in ImmersiveEngineering-0.12-89. I am able to cut infinite duplicate ghost wires and be electrocuted by the invisible wires as well. No way to get rid of the wire even by placing blocks in place where the wire once occupied.

**Comment by LiskoSlayer63** [comment] 2020-11-03 20:46
@Exanadu Exactly the same happens to me using IE 0.12-98. Broke a HV connector but still get electrocuted even there's no wire
