### ISSUE TITLE
refinery with no ethanol input, continues to produce biodiesel

### ISSUE THREAD

**Issue by rahangar** [BluSunrize/ImmersiveEngineering#759] opened 2015-12-10 17:39 UTC
Hi Blue,

I shifted this post to GitHub as per your request.

Please see attached picture.

I'm seeing what appears to be a bug, but I'm not sure. 

 

I have a sugar cane deficit in my system, which means my refinery runs out of ethanol often.   When it does, I see an issue where refinery doesn't stop producing and outputing biodiesel.  

 
When the problem happens biodiesel level shows  11992/12000 and it is stuck there.   As a test, I removed all ethanol input to the refinery, while maintaining the plant oil coming into the refinery.  The refinery shows 0 ethanol, and full of plant oil, but the  biodiesel level remains at 11992, and generator that it feeds continues to run indefinitely.  

 

At this point, if I apply a redstone signal to the refinery, refinery tank levels don't change, but as expected, the generator tank level (getTankInfo()) starts to drop - I let the generator run out and the generator stops running.   When I remove the redstone signal, the refinery biodiesel level drops (generator is sucking it out), but the strange thing is that after a few seconds, the biodiesel part of the refinery's tank starts filling back up while the generator is still running AND there is no ethanol input at all into the refinery.  So how is the refinery making biodiesel without ethanol input?

 

Other than a bug, the only explanation that I can think of is that due to my setup, somehow ethanol and/or biodiesel is getting transferred from other sources.  

 

Here's my setup:

 

I'm not using any pipes.
I have the refinery between a fermenter and a squeezer.  The refinery is connected directly to a biodiesel generator.
If you imagine the above 4 machines making up one side of a square, I repeat the same setup (with the exception of the fermenter and squeezer) for each side of the square.   So in a nutshell, the square is made up of 4 refineries, each feeding a separate generator.  
There are a total of 2 fermenters and 2 squeezers in the setup (at the corners of the square).   The 4 refineries share the 2 fermenters and the 2 squeezers by virtue of the fermenters and squeezers being positioned in the corners of the square. 
 

Question:

Is it possible that even though there is no direct connection between the refineries, that through sharing the fermenters and squeezers, the 4 refineries are on some sort of a shared fluid network? ... or do you suspect a bug?  Any other explanation that you can think of?

Screenshot of one side:
![2015-12-10_11 25 33](https://cloud.githubusercontent.com/assets/3137077/11722838/d139d0c2-9f30-11e5-8cd1-c8aa9fcc5e42.png)

Screenshot from one corner:

![2015-12-10_11 22 57](https://cloud.githubusercontent.com/assets/3137077/11722784/62f855b6-9f30-11e5-91b8-151abc8247f2.png)

Screenshot from the opposite corner:

![2015-12-10_11 23 58](https://cloud.githubusercontent.com/assets/3137077/11722817/9c9a4464-9f30-11e5-8928-2166c45e7d8b.png)

Screenshot shows the refinery full of biodiesel after I remove the redstone signal - note:  generator is continuously running (see next screenshot).   The refinery's ethanol tank shows empty so persumably it has no ethanol because the only connected fermentor's sugar cane supply was manually removed in order to demonstrate this.

![2015-12-10_11 31 25](https://cloud.githubusercontent.com/assets/3137077/11723088/f973d2da-9f31-11e5-9906-c368e2eb8490.png)

getTankInfo() on diesel generator.
![2015-12-10_11 35 06](https://cloud.githubusercontent.com/assets/3137077/11723104/14366538-9f32-11e5-8dce-916043a3b17c.png)

**Comment by malte0811** [comment] 2015-12-11 20:24
@cobra and me have looked into this a bit. Some parts might be fixed by the commit linked above, some make no sense at all. We need you to check these things:
1. When the refinery has 11992 mB of biodiesel in and the generator has been running for a bit, try relogging (disconnecting from the server/leaving the singleplayer world and going back in). If that results in a lower amount of diesel, my commit will help.
2. Are you on a dedicated server and if you are, is that server a normal forge server (as in downloaded from files.minecraftforge.net) or some different software like cauldron?
3. Please wait for a few minutes and check whether the generator is still running. A few minutes means enough time for the generator to burn through 20 buckets of diesel.
4. What version of IE are you using?

**Comment by rahangar** [comment] 2015-12-11 22:55
Thanks for looking into it.

Regarding your questions.

1.  Not sure what you mean by logging out.   My PC is running both client and server - no external server.  Single Player.  Do you want me to do "save and quite to title"?

2.  See above.  Also,  I'm running forge 1.7.10-Forge10.13.4.1448-1.7.10 - I don't recall where I got it from - it has been a while, but it is likely to be from files.minecraftforge.net.  

3.  I waited a long time, and it seems I can reproduce it every time.  I wrote a few scripts monitoring the tanks of all 12 machines once a second.  See screenshots below e=ethanol, p=plantoil b=biodiesel... taken while all 3 excavators are running (albeit hungrily) and generating output a long time after I removed all sugarcane from the system.   The main problem seems to be at the refinery which shows full of biodiesel even though it has no ehtanol (fermenter shows 1 mb for some reason - perhaps related to the issue?)

4.  I'm using IE 0.6.2 along with some other mods.  Complete mod list below.

I downloaded and installed GitHub a while back but that's as far as I got.  I never interact with it - barely know how.  And I never got around figuring out how to get the code, compile and run it.  I can try some things if you send step-by-step instructions.

![2015-12-11_16 43 53](https://cloud.githubusercontent.com/assets/3137077/11757387/85acbcc2-a026-11e5-8713-eed0bc78c8a5.png)
. 
![2015-12-11_16 44 12](https://cloud.githubusercontent.com/assets/3137077/11757400/a4dde8d2-a026-11e5-85b4-893db6043d16.png)


08/10/2015  05:51 PM         2,526,302 appliedenergistics2-rv2-stable-10.jar
09/02/2015  09:00 PM           106,701 ChickenChunks-1.7.10-1.3.4.19-universal.j
ar
11/11/2015  05:21 PM         6,176,312 Chisel2-2.5.1.44.jar
07/12/2015  08:22 AM           145,722 CodeChickenCore-1.7.10-1.0.7.46-universal
.jar
08/24/2015  01:53 PM         1,068,485 CoFHCore-[1.7.10]3.0.3-303.jar
08/14/2015  05:36 PM           198,149 compactstorage-1.7.10-release-2.0.0.13-un
iversal.jar
07/12/2015  09:01 AM         1,397,898 ComputerCraft1.74.jar
07/17/2015  04:29 PM         1,027,045 ComputerCraftEdu1.74.jar
11/26/2015  03:41 PM           463,957 EnderCore-1.7.10-0.2.0.31_beta.jar
11/26/2015  03:41 PM         4,912,713 EnderIO-1.7.10-2.3.0.421_beta.jar
11/26/2015  03:47 PM         1,270,816 ExtraCells-1.7.10-2.2.73b129.jar
11/26/2015  03:50 PM           116,959 fastcraft-1.21.jar
11/26/2015  03:56 PM           283,132 Hats-4.0.1.jar
10/03/2015  02:47 PM           220,214 iChunUtil-4.2.2.jar
11/26/2015  03:58 PM         2,729,060 ImmersiveEngineering-0.6.2.jar
11/26/2015  03:58 PM           271,873 immersiveintegration-0.6.1.jar
08/20/2015  06:45 PM         1,542,602 journeymap-1.7.10-5.1.0-unlimited.jar
10/03/2015  02:47 PM         1,039,858 Morphing-Mod-1.7.10.jar
07/12/2015  08:22 AM           512,687 NotEnoughItems-1.7.10-1.0.5.110-universal
.jar
11/26/2015  05:45 PM        12,487,781 OpenComputers-MC1.7.10-1.5.20.38-universa
l.jar
08/24/2015  06:48 PM           862,338 OpenModsLib-1.7.10-0.8.jar
08/24/2015  06:48 PM         1,020,024 OpenPeripheral-1.7.10-AIO-5.jar
11/26/2015  04:59 PM           328,853 OpenSecurity-1.0-74.jar
11/26/2015  05:12 PM         1,420,057 ProjectRed-1.7.10-4.7.0pre9.92-Base.jar
11/26/2015  05:15 PM            83,858 ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar

11/26/2015  05:13 PM         1,654,363 ProjectRed-1.7.10-4.7.0pre9.92-Fabricatio
n.jar
11/26/2015  05:13 PM         3,912,822 ProjectRed-1.7.10-4.7.0pre9.92-Integratio
n.jar
11/26/2015  05:14 PM           632,050 ProjectRed-1.7.10-4.7.0pre9.92-Lighting.j
ar
11/26/2015  05:14 PM         2,088,848 ProjectRed-1.7.10-4.7.0pre9.92-Mechanical
.jar
11/26/2015  05:15 PM           472,590 ProjectRed-1.7.10-4.7.0pre9.92-World.jar
09/08/2015  10:59 AM           544,821 Waila-1.5.10_1.7.10.jar

**Comment by rahangar** [comment] 2015-12-11 23:11
I forgot to mention that I'm also seeing a sound glitch with the diesel generators.  The sound disappears after a while.  I see all 4 radiator fans and smoke from all 4 smoke stacks but hear no sound from any of them.  I have a lever on each all in the up position.  What's funny is that if I put the lever to the down position for one generator (say generator 1), the other 3 generators' sounds come back.  Then I put the lever back up on generator 1 the sound for generator 1 returns.  

After writing this, I started to suspect redstone connection issue, but since I don't have any redstone other than the 4 levers on the generators (nothing on refineries, fermenters, squeezers), I doubt I'm causing the problem.   But to prove it is not the levers, I will run it without any levers to see if I can reproduce the sound issue.

**Comment by cobra** [comment] 2015-12-11 23:24
yeah, save and quit to title, then go back into this world.

**Comment by rahangar** [comment] 2015-12-11 23:42
Before I save and quit, do you have anything else you want me to try while I'm quitting?  The reason I ask is that I don't quit very often due to the fact that it takes at least 20 minutes for me to get started back again because I have to go find 12 turtles handling my tree/hemp/sugarcane farms and restart them manually - never automated that part.

**Comment by rahangar** [comment] 2015-12-11 23:52
The other reason why I don't quit often is that most of the flood lights don't come back on after I restart my world.  I have to go to each one and use the hammer on it to get it to turn on.  Is that an issue and should I report that separately?

**Comment by malte0811** [comment] 2015-12-12 06:57
I think I have a rough idea of what is happening now, although i need to actually test my fix later today: the fermenter contains 1mB of ethanol (btw, thank you for sending these values). When it outputs, it tries to split that mB between both refineries, causing it to insert fluidstack with a size of 0. As @cobra and i noticed independently yesterday, the refinery will produce biodiesel even if it has less than the required 8mB of each fluid. This includes the case that one tank has 0mB of a defined fluid (which is a different state than empty). So you did actually manage to dupe biodiesel.
I think i need to go through every multiblock tileentity at some point and check for bugs.

**Comment by cobra** [comment] 2015-12-12 07:54
I'm testing that right now with the fix I wrote yesterday. That should prevent it.
@malte0811 see you on IRC, I also have some to-do entries for something like this.

**Comment by cobra** [comment] 2015-12-12 08:10
Exactly like this. The crucial bit of information was "1mB in the fermenter", that lets me reproduce this immediately. My "blind" fix for the refinery prevents this from happening, but the fermenter (and probably the squeezer as well) also need to be fixed - they can also save 50% of getTileEntity() calls.

**Comment by rahangar** [comment] 2015-12-12 16:33
Glad I was able to help.  This explains why I've advanced so much with so little sugarcane.  I think I need to quadruple my sugarcane generation now :-)

I'm assuming you don't need any more information.  Please let me know if you do.

**Closed** 2015-12-13 11:10 UTC
