### ISSUE TITLE
Coke Oven

### ISSUE THREAD

**Issue by Hunter-Sprouls** [BluSunrize/ImmersiveEngineering#2049] opened 2017-04-30 21:02 UTC
I can't get creosote oil out of the coke oven. I have tried using buckets and pump. Also railcraft isn't installed.

**Comment by theunkn0wn1** [comment] 2017-05-01 01:09
Can we please get the following information so we can properly identify the root cause of your issue:
- Version information (Java, Minecraft, IE, Forge)
- List of installed mods
- Pictures of your setup.

**Comment by Hunter-Sprouls** [comment] 2017-05-01 01:44
Here is a link to a word doc with the list
https://docs.google.com/document/d/1oP03sw9rMkyHDNUynxxZ3PmkZOqtsWWHXrcS0cqtn3I/edit?usp=sharing

**Comment by Hunter-Sprouls** [comment] 2017-05-01 01:49
Wanted to mention that this is only happening on one world.

**Comment by BluSunrize** [comment] 2017-05-01 07:32
Well, it'd help if you actually showed pictures of the pump, how it's configured and stuff...

**Comment by Hunter-Sprouls** [comment] 2017-05-01 23:28
I'm sorry BluSunrize and theunkn0wn1 I figured it out sorry to waste your time. Thanks for offering the help

**Comment by theunkn0wn1** [comment] 2017-05-01 23:33
No problem, always double check your set up :3

Btw you can close this now as the issue appears to have been resolved

**Closed** 2017-05-01 23:37 UTC
