### ISSUE TITLE
In version 1.12 immersive asks for a version of tinkers that has not been released yet

### ISSUE THREAD

**Issue by cursinorock** [BluSunrize/ImmersiveEngineering#2353] opened 2017-07-23 17:21 UTC
In version 1.12 immersive asks for a version of tinkers that has not been released yet

**Comment by cursinorock** [comment] 2017-07-23 17:23
![capturar](https://user-images.githubusercontent.com/24946430/28501460-7a74c536-6fb2-11e7-9e35-0f4ef233eb89.PNG)

**Comment by KnightMiner** [comment] 2017-07-23 17:24
Duplicate of #2349.

**Closed** 2017-07-23 17:25 UTC
