### ISSUE TITLE
[1.11.2 - 0.11-62] Assembler crash

### ISSUE THREAD

**Issue by vitraiden** [BluSunrize/ImmersiveEngineering#2227] opened 2017-06-25 19:52 UTC
Once an Assembler begins crafting it throws a NullPointerException.  This appears to happen both on singleplayer and SMP.  Crash log attached.

Crafting any recipe causes the crash.  I've tried both IE and vanilla recipes.  Setting up the crafting pattern works fine, as well as adding a partial list of ingredients to the hopper.  As soon as a complete recipe is configured and all ingredients are present and crafting begins then the machine causes the exception.

Comment [1559](https://minecraft.curseforge.com/projects/immersive-engineering?comment=1559) on the main project page also mentions this problem.

[crash-2017-06-25_14.20.01-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1100563/crash-2017-06-25_14.20.01-server.txt)

[fml-server-latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1100569/fml-server-latest.txt)

**Comment by malte0811** [comment] 2017-06-25 21:01
Duplicate of #2196 and at least 2 others. Fixed for the next release.

**Closed by malte0811** 2017-06-25 21:01 UTC
