### ISSUE TITLE
[1.12.2] Crash caught by CCL when rendering certain blocks in the manual

### ISSUE THREAD

**Issue by Rongmario** [BluSunrize/ImmersiveEngineering#3199] opened 2018-09-07 03:52 UTC
Log: https://pastebin.com/im1m822R

Mods list: http://modlister.com/user/Rongmario

**Comment by mindforger** [comment] 2018-09-07 04:13
>    at mrtjp.projectred.relocation.MovingBlockRenderDispatcher.renderBlock(renders.scala:275) [MovingBlockRenderDispatcher.class:?]

can you reproduce this without ProjectRed Relocation?

by the way ... that grim avatar :D

**Comment by malte0811** [comment] 2018-09-07 05:55
Duplicate of #3175

**Closed by malte0811** 2018-09-07 05:55 UTC
