### ISSUE TITLE
Server crash 1.10.2 - 0.10-42

### ISSUE THREAD

**Issue by TheMrCaveman** [BluSunrize/ImmersiveEngineering#1493] opened 2016-09-19 17:05 UTC
Server won't boot with ImmersiveEngineering-0.10-42

See crashreport : http://pastebin.com/gPwKkDfk

**Comment by GirafiStudios** [comment] 2016-09-19 17:20
Duplicate of #1482 and many others. Please use the search function before reporting another time.

**Comment by BluSunrize** [comment] 2016-09-19 18:33
^ that.
The search function exists, PLEASE make use of it.

**Closed by BluSunrize** 2016-09-19 18:33 UTC
