### ISSUE TITLE
Smooth Lighting crashing the game MC 1.16.4, IE 4.1.2-129

### ISSUE THREAD

**Issue by DeathFucker** [BluSunrize/ImmersiveEngineering#4596] opened 2021-01-24 18:02 UTC
### Before reporting:
Didn't see any discussion on smooth lighting.

### Description of the issue:
Game slows down then crashes the closer I get to IE objects. If I turn off smooth lighting, there is no longer a crash. Very predictable and repeatable.

### Crashlog:
Attached.
[crash-2021-01-23_16.09.34-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5862857/crash-2021-01-23_16.09.34-client.txt)

### Versions & Modlist
See crash report.

**Comment by malte0811** [comment] 2021-01-24 18:43
Duplicate of #4512. Quoting from my comment on that issue:
 > As a temporary fix you can fully disable "smooth lighting"

**Closed as completed by malte0811** 2021-01-24 18:43 UTC
