### ISSUE TITLE
The game crashed whilst tesselating block model

### ISSUE THREAD

**Issue by Razvedka2020** [BluSunrize/ImmersiveEngineering#5923] opened 2024-04-28 15:46 UTC
### Minecraft Version

1.20.4

### Immersive Engineering Version

11.1.0-172

### How did it happen?

When installing a vertical conveyor into the world.

### Crash Log

https://gist.github.com/Razvedka2020/08d2b188e331859dd2bbde783ef49d31

**Comment by BluSunrize** [comment] 2024-05-01 08:42
Duplicate of #5910

Already fixed for future releases =)

**Closed as not planned by BluSunrize** 2024-05-01 08:42 UTC
Labels: crash 💥
