### ISSUE TITLE
Crash when fluid pipes interact with ExtraUtils2 Machines

### ISSUE THREAD

**Issue by TheYeti** [BluSunrize/ImmersiveEngineering#1814] opened 2016-12-22 07:38 UTC
Placed a magmatic generator from extra utils 2, placed a fluid pipe, when trying to place a pipe that connects to the top of the generator it crashes immediately.  Loading back in produces an immediate crash again.

java.lang.NullPointerException: Unexpected error
	at java.util.Collections.addAll(Unknown Source)
	at net.minecraftforge.fluids.capability.templates.FluidHandlerConcatenate.getTankProperties(FluidHandlerConcatenate.java:55)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getAvailableConnectionByte(TileEntityFluidPipe.java:444)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getAdvancedSelectionBounds(TileEntityFluidPipe.java:555)
	at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.func_180636_a(BlockIETileProvider.java:367)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:448)
	at net.minecraft.world.World.func_147447_a(World.java:1018)
	at net.minecraft.world.World.func_72901_a(World.java:861)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:91)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:54)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:71)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_777_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Collections.addAll(Unknown Source)
	at net.minecraftforge.fluids.capability.templates.FluidHandlerConcatenate.getTankProperties(FluidHandlerConcatenate.java:55)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getAvailableConnectionByte(TileEntityFluidPipe.java:444)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getAdvancedSelectionBounds(TileEntityFluidPipe.java:555)
	at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.func_180636_a(BlockIETileProvider.java:367)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:448)
	at net.minecraft.world.World.func_147447_a(World.java:1018)
	at net.minecraft.world.World.func_72901_a(World.java:861)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:91)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:54)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:71)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_777_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheNo1Yeti'/258, l='MpServer', x=-766.51, y=56.00, z=-666.13]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-761,4,-660), Chunk: (at 7,0,12 in -48,-42; contains blocks -768,0,-672 to -753,255,-657), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Level time: 1825 game time, 1825 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TheNo1Yeti'/258, l='MpServer', x=-766.51, y=56.00, z=-666.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by BluSunrize** [comment] 2016-12-22 09:28
Duplicate of #1810 please check other reports next time and read the contribution guidelines

**Closed by BluSunrize** 2016-12-22 09:28 UTC
