### ISSUE TITLE
game crashes when i'm clicking on assembler in manual

### ISSUE THREAD

**Issue by CookieHunteRRR** [BluSunrize/ImmersiveEngineering#1718] opened 2016-11-22 15:10 UTC
link to the crashlog: https://gist.github.com/anonymous/466efa9b79a8c12d3746b7b75ed06c70
well, i'm clicked on assembler in manual
i'm was in singleplayer

**Comment by BluSunrize** [comment] 2016-11-22 15:19
Duplicate of #1704, use the search function.

**Closed by BluSunrize** 2016-11-22 15:19 UTC
