### ISSUE TITLE
[1.15.2] Crash when setting pipes next to a coke oven

### ISSUE THREAD

**Issue by Alsett** [BluSunrize/ImmersiveEngineering#4126] opened 2020-07-23 08:11 UTC
### Description of the issue:
Game crashes when I try to use the engineer's hammer on a segment of pipe which is between a coke oven, a activated pump, and a barrel. Specifically I was right-clicking the part of the pipe that is connected to the oven.
Screenshot of the moment before the crash: https://imgur.com/a/7NNxQur
After this happens I get the same crash every time I try to rejoin the same world. 
I don't have a backup of my main world, pls fix so I can go there again :( 

### Crashlog:
https://pastebin.com/3awjD8YJ
https://pastebin.com/cytSXz0T

### Versions & Modlist
Forge 31.2.31
IE 0.15-108
also tried with the latest commit I found - ImmersiveEngineering-1.15.2-3.1-2c3d2a2f

**Comment by BluSunrize** [comment] 2020-07-23 13:08
This is a duplicate of #4110
The fix has happened, but only in the 1.14 branch, which is why the latest commit of 1.15 didn't work.

**Closed as completed by BluSunrize** 2020-07-23 13:08 UTC
