### ISSUE TITLE
[1.15] Engineer's Workbench causes rendering crash when blueprint is inserted.

### ISSUE THREAD

**Issue by Gregorsharpe** [BluSunrize/ImmersiveEngineering#3966] opened 2020-06-12 15:31 UTC
### Description of the issue:
Freshly installed ImmersiveEngineering running on a forge server causes a localized hard-crash effect for any player within render distance once a blueprint (specifically tested with the Crafting Components blueprint) is inserted. The server continues to function normally when this is in effect, with no errors appearing in the log.

#### Initial crash from a client on the MC server who experienced the issue:
https://gist.github.com/Gregorsharpe/63d66048cf1564c57d60250f06e4b6e4

#### Reproduced on a fresh install with only Forge and IE in Single Player:
https://gist.github.com/Gregorsharpe/40dfd871879122ea8c4814b17189ef22

### Versions & Modlist
Immersive Engineering: **v0.15-99**
Forge: **v31.2.9**

### Additional Information
Crossposting a link to the ATM-5 modpack where I discovered other users experiencing the same problem, though they seem to have misfiled their issue against the pack itself. I've posted a link to this issue in their thread so we can all follow along and get our engineer on once this is resolved!

https://github.com/AllTheMods/ATM-5/issues/149

**Comment by malte0811** [comment] 2020-06-12 15:48
Duplicate of #3908

**Comment by BluSunrize** [comment] 2020-06-12 15:48
Duplicate of  #3908, please use the search function next time.

Maybe ATM should have not included something marked as alpha in their pack...

**Comment by BluSunrize** [comment] 2020-06-12 15:49
6 seconds inbetween me and Malte there...

**Closed as completed by BluSunrize** 2020-06-12 15:48 UTC

**Comment by Gregorsharpe** [comment] 2020-06-12 16:19
Apologies, I made the mistake of searching with the 'Crash' tag. Will be more thorough next time.

**Comment by whatthedrunk** [comment] 2020-06-13 03:22
For sure ATM is always testing the newest and we enjoy filing bug reports. Is there anyway you can add your mod to the approve list for custom builds? That would solve the issue of all the work of posting to curseforge.

**Comment by whatthedrunk** [comment] 2020-06-13 03:32
Here is the link if needed https://docs.google.com/spreadsheets/d/1lEwbJpwRVoZb8kr0OT-Wo4Yc7jAGWMGOFtfL0miCFmc/edit#gid=0

**Comment by BluSunrize** [comment] 2020-06-13 12:24
Nope!
You can have CurseForge builds, like everyone else. I don't do specialcasing for any modpacks ^_^
