### ISSUE TITLE
Garden Cloches + Mod compat

### ISSUE THREAD

**Issue by Y0ungSandwich** [BluSunrize/ImmersiveEngineering#2258] opened 2017-07-02 00:32 UTC
IE Version 0.10-61
        B:mysticalagriculture=false

Seeds from Mystical Agriculture are still able to be planted and grown. This isn't a huge issue but my pack is configured so you do not receive additional MA seeds when harvested. The Cloches ignore this and users are winding up with thousands of seeds in no time at all.

**Comment by Vahtera** [comment] 2017-07-07 20:43
Same happens with Pam's Harvestcraft (Direwolf20 FTB pack 1.11.1, MC version 1.10). Pack is configured so Pam's crops don't drop seeds (either you craft them or plant directly). Garden Cloches still output Pam's seeds directly.

**Comment by falizure** [comment] 2017-07-16 18:36
same, this is also a duplicate of some reports in #2271 including my own

**Closed** 2020-06-06 11:46 UTC
