### ISSUE TITLE
IM 1.10.2 crash

### ISSUE THREAD

**Issue by Majestyc2k1** [BluSunrize/ImmersiveEngineering#1475] opened 2016-09-17 06:48 UTC
Got the following crash when I updated my modpack to IM 0.10-41. I got the same crash with 0.10-42 also.

[http://pastebin.com/M56yq6Xf]

**Comment by KnightMiner** [comment] 2016-09-17 14:32
Duplicate of #1464. Update Tinkers or downgrade Immersive Engineering.

**Comment by BluSunrize** [comment] 2016-09-17 16:57
Correct. Also, Immersive Engineering is abbreviated to IE, not IM =P

**Closed by BluSunrize** 2016-09-17 16:57 UTC
