### ISSUE TITLE
Crash on setup

### ISSUE THREAD

**Issue by TishinaVC** [BluSunrize/ImmersiveEngineering#5513] opened 2022-12-26 00:51 UTC
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.3.0-155.jar

### How did it happen?

i went to go start the modpack after adding this

### Crash Log

https://pastebin.com/xvv8AeiM

**Comment by malte0811** [comment] 2022-12-26 12:47
Duplicate of #5509 (where you already commented).

**Closed as not planned by malte0811** 2022-12-26 12:47 UTC
Labels: crash 💥
