### ISSUE TITLE
Server Crash 1.16.5 Mod Load Error

### ISSUE THREAD

**Issue by jheilma2** [BluSunrize/ImmersiveEngineering#4658] opened 2021-02-17 20:11 UTC
Server crash this morning after one of the daily restarts. I don't think anyone was on the server when it crashed. It has an error loading IE and we only play with Valhelsia 3, 3.1.8a

https://pastebin.com/zAVqp7TC

**Comment by malte0811** [comment] 2021-03-01 10:43
Duplicate of #4636

**Closed as completed by malte0811** 2021-03-01 10:43 UTC
