### ISSUE TITLE
[1.12] -64 Server side crash on load

### ISSUE THREAD

**Issue by chrisshoes** [BluSunrize/ImmersiveEngineering#2275] opened 2017-07-09 13:09 UTC
Looks like it's trying to call some client stuff. 

Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.client.ClientProxy
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by malte0811** [comment] 2017-07-09 13:14
Duplicate of #2270 as well as 2 other issues. Fixed for the next release which will probably be released today.

**Closed by malte0811** 2017-07-09 13:14 UTC
