### ISSUE TITLE
Diesel Generator Nullpointer exception crash

### ISSUE THREAD

**Issue by ironclaw2000** [BluSunrize/ImmersiveEngineering#136] opened 2015-06-28 03:47 UTC
I am getting a crash that seems to be to do with the diesel generator when I fly away from the chunk it's in ( and while it's chunk unloads). Here is the report: 
http://openeye.openmods.info/crashes/9e5b191e7ab8ed9012312434d3510350

I was able to replicate this bug. First, I made sure that the generator was working and generating power. I then exit my base to go check on my chunk eater, and as I'm flying away from my base, the game crashes to the launcher.  I am playing with the latest version of the mod (0.3.2) in a custom ATLauncher pack.

**Comment by wafflemans** [comment] 2015-06-28 03:53
Duplicate of #131. should be fixed in next version

**Comment by BluSunrize** [comment] 2015-06-28 09:04
correct

**Closed by BluSunrize** 2015-06-28 09:04 UTC
