### ISSUE TITLE
[bug] [1.12.1] [jvm] Guide book crash after reading

### ISSUE THREAD

**Issue by hayesj1** [BluSunrize/ImmersiveEngineering#2529] opened 2017-09-27 18:58 UTC
### Description of the issue:
After spending a bit of time reading through the guide book, my jvm crashes(leaves a hs_error_pid#####.log file instead of regular minecraft crash semantics). Guaranteed to happen thus far and completely independent of the page I'm currently on. The one possible exception is the table of contents pages, although the lack of crashing on those might be sheer luck.

I give MC 6 whole gigs of RAM, but I can push it higher if that seems to be the issue. I added the IE addons today, but this I've had this issue since I started playing MC again, on 1.12.1 a week or so ago. Therefore I'll include both logs. i'm going to try a barebones profile(just Forge, IE, JEI) now.

### Crashlogs:
[Gist of logs](https://gist.github.com/hayesj1/a832429b51965d8d0997204367c8f4d0)

### Versions & Modlist
MC: 1.12.1
Forge: 1.12.1-14.22.1.2478
IE: 0.12-72
[Mod List](https://imgur.com/a/Zuhq7)

**Comment by malte0811** [comment] 2017-09-27 19:06
Duplicate of #2225. Your MC is using the Java version that comes with the MC launcher (J8 update 25), which is about 3 years old. Install a new Java version (but NOT Java 9, Forge doesn't work with that) and tell the launcher to use that.

**Closed by malte0811** 2017-09-27 19:06 UTC

**Comment by hayesj1** [comment] 2017-09-27 19:19
Thanks for your help. I don't know if this is even useful now, but before I saw your response I spent at least 3 or 4 minutes browsing the book without crashing using a clean setup and the bundled runtime.
