### ISSUE TITLE
[1.10.2] Windmill and Improved Windmill missing textures

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1378] opened 2016-09-03 17:17 UTC
IE Version: Compiled from source 1.10.2 2016/09/03

Full Minecraft Log: http://pastebin.com/BLuKDgWR

Pic: http://i.imgur.com/OxJGuTW.png

**Comment by BluSunrize** [comment] 2016-09-04 10:52
Can you actually reproduce that without a texturepack? .-.

**Comment by calloatti** [comment] 2016-09-04 20:55
Only IE mod, no resource packs loaded

http://pastebin.com/raw/2PuHEe6j

http://i.imgur.com/ohdTWkX.png

**Comment by calloatti** [comment] 2016-09-04 20:58
Found it in the log, search for "[TEXTURE ERRORS]"

```
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: The following texture errors were found.
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:   DOMAIN minecraft
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:   domain minecraft is missing 1 texture
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:     domain minecraft has 1 location:
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:       unknown resourcepack type net.minecraft.client.resources.DefaultResourcePack : Default
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:     The missing resources for domain minecraft are:
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/.png
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain minecraft
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:   DOMAIN immersiveengineering
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:   domain immersiveengineering is missing 4 textures
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:     domain immersiveengineering has 1 location:
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:       mod immersiveengineering resources at C:\MultiMC\instances\IMMERSIVE\minecraft\mods\ImmersiveEngineering-0.10-38.jar
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:     The missing resources for domain immersiveengineering are:
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks\\woodenDevice_windmill.png
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/sheetmetal_uranium.png
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks/sheetmetal_gold.png
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:       textures/blocks\\woodenDevice_windmillAdvanced.png
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: -------------------------
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain immersiveengineering
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: ==================================================
[17:46:24] [Client thread/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=```

**Comment by calloatti** [comment] 2016-09-04 21:08
The files are in the jar, so no idea what is going on here.

**Comment by BluSunrize** [comment] 2016-09-04 21:25
Yeah I think I know what caused this. Should be fixed in an upcoming push

**Comment by BluSunrize** [comment] 2016-09-04 22:22
Please check if the issue is fixed after this commit
https://github.com/BluSunrize/ImmersiveEngineering/commit/9ca9d285a5603f973455d44ff2a812c6f08f911f

**Comment by calloatti** [comment] 2016-09-05 15:21
Seems to be fixed.

ImmersiveEngineering-0.10-38.5.13b2fba.jar

LOG: http://pastebin.com/mxiVPbNN

PIC: http://i.imgur.com/klgFwsU.jpg

**Comment by BluSunrize** [comment] 2016-09-05 16:27
Wonderful!
Fixed for future releases, then

**Closed by BluSunrize** 2016-09-05 16:27 UTC
