### ISSUE TITLE
(MC 1.12) Unstable pack. Treated Wood and Thermal Tanks

### ISSUE THREAD

**Issue by MechaDom** [BluSunrize/ImmersiveEngineering#2297] opened 2017-07-12 05:44 UTC
Immersive version 0.12 - 66
When using the Thermal Expansion tank to craft Treated Wood it does not return a tank.  Tank is eaten along with all fluid left in the tank after one craft.

**Comment by BluSunrize** [comment] 2017-07-12 06:03
Uhh, pretty sure that wouldn't be my fault, I use Forge's default recipe implementation for that one.

@KingLemming, getContainerItem() returning null per chance?

**Comment by KingLemming** [comment] 2017-07-12 06:11
Forge doesn't have a default recipe implementation for that to my knowledge. I'm planning on adding one shortly.

**Comment by KingLemming** [comment] 2017-07-12 06:16
So I see that you've added the ingredient, but that's only half of the equation. You also need the recipe for it, like this:

https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/util/crafting/ShapelessFluidRecipeFactory.java

I'll be PRing proper Fluid Ingredients and Recipes to Forge here shortly.

**Comment by BluSunrize** [comment] 2017-07-12 06:21
The Ingredient does the match.
The leftover materials are determined by `ForgeHooks.defaultRecipeGetRemainingItems` which in turn calls getContainerItem on the items. The tanks should probably implement that?
I have a custom recipe for this and I used to use it (because other mods didn't do that containering properly either). I was hoping to get away without it this time, but I guess it's still needed.

**Comment by KingLemming** [comment] 2017-07-12 06:23
The problem is that means getContainerItem() is entirely responsible for calling the drain. And it has no way of knowing how much the drain should be.

Bit of a corner case possibly, but this is why it should be fully codified in Forge. Blame Forge for the strange FluidHandlerItem interactions.

**Comment by BluSunrize** [comment] 2017-07-12 06:24
Well we both agreed to the point that Forge fluids are beyond wonky =P
I'll chuck this back into my custom recipes then, I already have the factories registered since they have some other uses.

Will be fixed soon.

**Comment by KingLemming** [comment] 2017-07-12 06:25
Cool deal. This just adds to the mounting pile of evidence that Fluids and Recipes need some PR love. Will ping you when I submit it.

**Comment by BluSunrize** [comment] 2017-07-12 06:27
Cheers! Though I probably won't need it, will I? =P

**Comment by KingLemming** [comment] 2017-07-12 06:35
No, you won't. I won't either, strictly speaking, but we better get this figured out.

**Closed** 2017-07-12 08:30 UTC
