### ISSUE TITLE
Crusher doesn't start

### ISSUE THREAD

**Issue by Alessandro2501** [BluSunrize/ImmersiveEngineering#2582] opened 2017-10-26 06:33 UTC
I built a Crusher and I connected it to an windmill. The machine is full of energy but when i try to crush ores it doesn't start. I tried also to build it into a new world with the same energy configuration and it works. Why not in my world?

**Comment by BluSunrize** [comment] 2017-10-26 09:06
Pictures. version number.

Read the guidlines.

**Comment by Pek94** [comment] 2017-10-31 23:08
Same issue here, minecraft 1.12.2 and IE 0.12-74

![2017-10-31_23 55 32](https://user-images.githubusercontent.com/33269173/32252931-6dadd218-be98-11e7-83b6-5c1121a306b5.png)

**Comment by volfster** [comment] 2017-11-03 18:20
Same version of MC and IE, had a Crusher setup with an HV capacitor. Curiously, if I destroy and rebuild the crusher AND remove and replace the HV capacitor, it appears to work again. HOWEVER, if I leave the chunk (I wandered to the other side of the room), then the Crusher stops working again. Looking through the logs, I'm not spotting anything related to IE at all. (Attached picture shows the crusher with full power and ore dropped into it, but not operating)

![2017-11-03_14 14 12](https://user-images.githubusercontent.com/33036476/32389570-6cd223b6-c0a1-11e7-8be7-261f48c6bae8.png)

**Comment by mindforger** [comment] 2017-11-03 19:28
>so it's as if it doesn't recognize any ores

that  why blu asked you to

>Read the guidlines.

you will find out that you might have to add more informations  like installed mods, modified configs and so on, maybe you have another mod modifying the ore to dust recipes ... one can not know without infos :D

**Comment by volfster** [comment] 2017-11-03 20:44
I see, I was simply adding on information (I'm not the OP nor the other person in this thread, so I don't know if they have the same mods or not).

[minecraft, mcp, FML, forge, foamfixcore, adchimneys, additionalbanners, ae2stuff, animania, applecore, appliedenergistics2, autoreglib, backtools, baubles, bdlib, bedrockbgone, bibliocraft, bloodmoon, bonfires, bonsaitrees, botania, chameleon, chisel, chiselsandbits, codechickenlib, cofhcore, cofhworld, cookingforblockheads, extendedrenderer, coroutil, configmod, craftstudioapi, ctm, ptrmodellib, props, dynamictrees, extrautils2, farseek, foamfix, forgeendertech, ftbl, ftbu, gravestone, waila, ichunutil, immcraft, immersiveengineering, immersivepetroleum, immersivetech, inventorypets, inventorytweaks, ironchest, jehc, jei, journeymap, mantle, missing_pieces, morpheus, nex, nei, harvestcraft, platforms, quantumstorage, quark, randomthings, reborncore, redstoneflux, refinedstorage, roguelike, shetiphiancore, signpost, spiceoflife, storagedrawers, streams, tconstruct, thermaldynamics, thermalexpansion, thermalfoundation, tcomplement, tinkertoolleveling, twilightforest, unidict, unlimitedchiselworks, wailaharvestability, wanionlib, wawla, wearablebackpacks, yabba, zombieawareness

I can pull up the exact versions of each one if needed (this is just grabbing the list from the logs). Additionally, I can try running it alone on a separate instance to see if I can replicate the problem.

**Comment by Pek94** [comment] 2017-11-03 21:06
I indeed have UniDict installed, i will try without it.
I didn't find where are these guidelines, i tried to find them before replying this post, without success.

**Comment by mindforger** [comment] 2017-11-04 10:04
just open a new one without submitting, there is a yellow boxed link at the top or open the contributions file in the main project folder, it's a text file with an alternate file ending, don't bother about that

yes versions are impotant to replicate the issue, can you serve a batch of version numbers with MC version, forge version and mod version in a minimal setup to reproduce it? and also consider to open an issue with unidict if you are sure it is an offender for this bug and link it ere for tracking :) thank you

**Comment by volfster** [comment] 2017-11-04 14:40
Minecraft 1.12.2
Forge 14.23.0.2522
IE 0.12-74 OR IE 0.12-73
UniDict 1.12.2-10
WanionLib 1.12.2-1.0

Running only those two together (with either version of IE specified) causes the issue to be replicated. Diabling UniDict fixes the issue.

You can find the bug report for UniDict here: [(https://github.com/WanionCane/UniDict/issues/40)]

**Comment by WanionCane** [comment] 2017-11-04 16:19
sorry guys, this was an UniDict issue and has been fixed in the latest UniDict release (1.12.2-1.1).

**Comment by malte0811** [comment] 2017-11-04 16:51
I'll close this then. Does that apply to #2588 as well?

**Closed by malte0811** 2017-11-04 16:51 UTC

**Comment by Vulkanus-Maximus** [comment] 2024-07-15 19:39
G'day!

I am now having the same issue. I know this is marked as completed but I'm still hoping for a fix; 
There is power (full 32 kFE) and levered to ON, but the Crusher is not crushing cobble stone blocks (nor any other blocks), not any ores, and jumping into it does not even harm me.
I tested the Crusher out both on my survival world and on my creative world, but unfortunately to no avail.
Modpack: DeceasedCraft - Modern Zombie Apocalypse:
Game Version: 1.18.2
forge: 40.2.4
Picture:

![2024-07-15_14 36 52](https://github.com/user-attachments/assets/0f50d2c7-ebcb-4167-bb6b-1cd592e5ce13)

**Comment by mindforger** [comment] 2024-07-17 04:42
This issue is 1.12 you are on 1.18 both are ancient and out of support, dont necro pls you did not read the other answers even as it looks like
