### ISSUE TITLE
[1.16.1] Kiln - Ticking block entity - Crash Server

### ISSUE THREAD

**Issue by Haddadmj** [BluSunrize/ImmersiveEngineering#4090] opened 2020-07-17 10:46 UTC
### Description of the issue:
I was trying to make bronze in Kiln by mixing copper dust and tin ingots although the recipe is not valid "I tested it on single player no crash", on the server i'm playing on it crashes.

### Crashlog:
[Crashlog](https://hastebin.com/hibukuqaku.pl)

### Versions & Modlist
[Modlist](https://hastebin.com/agibifekec.css)
IE version:0.16-106
Forge Version:32.0.66
Minecraft Version:1.16.1

**Comment by BluSunrize** [comment] 2020-07-17 10:54
Duplicate of #4073

**Closed as completed by BluSunrize** 2020-07-17 10:54 UTC
