### ISSUE TITLE
Java crash when looking at Engineering Book

### ISSUE THREAD

**Issue by erindalc** [BluSunrize/ImmersiveEngineering#2703] opened 2017-12-29 03:24 UTC
### Description of the issue:
Sometimes when opening and browsing the IE manual. I can't find a definitive trigger for the crash.

### Crashlog:
No normal Minecraft crash log. 

Forge log: https://gist.github.com/erindalc/e712a6e9dad9ff83aac1b4681e438c73

Java error files below. Please let me know if you need anything else.

https://gist.github.com/erindalc/ffab18d719b5f89f74752e90966dec5d

https://gist.github.com/erindalc/48a194e9f6860dc0e469b7c3216207a1

### Versions & Modlist
Minecraft: 1.12.2
Forge: 14.23.1.2570
IE:  0.12-75
ATM3 v5.5 with a couple of added mods, none relevant to IE.

**Comment by malte0811** [comment] 2017-12-29 07:55
Duplicate of #2662. Read my comment there for a fix.

**Closed by malte0811** 2017-12-29 07:55 UTC

**Comment by erindalc** [comment] 2017-12-29 08:57
Oh I even looked through recent closed issues too.

Bug seems solved, thanks malte.
