### ISSUE TITLE
Immersive drill giving back machines version 0.12-79-core

### ISSUE THREAD

**Issue by Thill199** [BluSunrize/ImmersiveEngineering#2902] opened 2018-03-20 21:33 UTC
forge version 14.23.2624 immersive core version 0.12-79-core the drill gives back the industrial squeezer multi block when broken.

**Comment by BluSunrize** [comment] 2018-03-20 22:26
Duplicate of #2891, use the search function next time please.

**Closed by BluSunrize** 2018-03-20 22:26 UTC
