### ISSUE TITLE
[0.10-50] Crash GUI manual with Chisel

### ISSUE THREAD

**Issue by TDarkShadow** [BluSunrize/ImmersiveEngineering#1713] opened 2016-11-22 02:53 UTC
Crash Report; https://gist.github.com/TDarkShadow/83fcdbaa6e59fe7dfda9b21ff47c791f

Only these mods installed;
- (Chisel-MC1.10.2-0.0.7.3.jar)
- (ImmersiveEngineering-0.10-50.jar)

Crashing when checking the manual for structures which contain slabs. (Arc Furnace and Assembler)
Similarly to #1704 

Fixes I tried and worked;
- Downgrading to 0.10-48

**Comment by BluSunrize** [comment] 2016-11-22 09:26
Duplicate of #1704

**Closed by BluSunrize** 2016-11-22 09:26 UTC
