### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lifetoanother** [BluSunrize/ImmersiveEngineering#2694] opened 2017-12-26 16:12 UTC
I am trying to create a small modpack for myself, but I keep running into the NullPointerException whenever I try to install Immersive Engineering. I am on forge 14.23.1.2581 and am on 0.12 - 75 for this mod.

https://pastebin.com/btFEDuHs

Thanks for your time.

**Comment by malte0811** [comment] 2017-12-26 16:16
Duplicate of #2672 and a lot of others. Fixed for the next release, use forge 2575 for now.

**Closed by malte0811** 2017-12-26 16:16 UTC
