### ISSUE TITLE
[1.16.1] Repeated crashing

### ISSUE THREAD

**Issue by FnordMan** [BluSunrize/ImmersiveEngineering#4077] opened 2020-07-14 23:27 UTC
Modpack: All The Mods 6
Mod version: 0.16-106
Started in 0.11 when immersive was added and continues even when I updated to 0.13
Can happen seemingly at any time, haven't spotted any pattern yet. 

[crash-2020-07-14_18.24.03-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4921988/crash-2020-07-14_18.24.03-server.txt)

**Comment by petalited** [comment] 2020-07-14 23:54
I got seemingly the same crash consistently when opening the options menu while in-game. When removing the mod I'm able to open options fine but if I re-add the mod I get a server crash when I click on options in the escape menu. Thought maybe this might help in fixing. Thanks.

**Comment by BluSunrize** [comment] 2020-07-15 07:04
1) This is a duplicate of #4067, please search recent issues next time before filing a new one
2) Please respect the issue template next time and upload your logs to pastebin, gist or similar sites.

**Closed as completed by BluSunrize** 2020-07-15 07:04 UTC
