### ISSUE TITLE
[1.16.5] Crash during Feedthrough connectors breaking

### ISSUE THREAD

**Issue by ZigTheHedge** [BluSunrize/ImmersiveEngineering#4892] opened 2021-07-22 08:37 UTC
Game crashes when trying to remove feed-though connection multiblock.

MC: 1.16.5
Forge: 36.1.32
IE: 5.0.2-137

Crashlog: https://pastebin.com/eBncV3bz

Happens when starting to break the multiblock in survival (works fine in creative though).

**Comment by malte0811** [comment] 2021-07-22 12:49
Duplicate of #4879

**Closed as completed by malte0811** 2021-07-22 12:49 UTC
