### ISSUE TITLE
[1.16.1] Immersive Engineering won't let the game launch!

### ISSUE THREAD

**Issue by BunCat09** [BluSunrize/ImmersiveEngineering#4172] opened 2020-08-05 09:42 UTC
### Description of the issue:
I launch the game, everything is normal but when it finishes loading it encounters an error - ![javaw_HmZZuSs5Th](https://user-images.githubusercontent.com/57318309/89397551-a96e8180-d718-11ea-9710-ee6f90f336f8.png)
 - And it won't let the game to launch. So i can't even see the main menu. I tried several forge versions. I can give more information as needed or if i forgot something(Device Specs etc.).  
----------------------------------------------------
### _**The game doesn't crash!**_
-----------------------------------------------
### Crashlog:
I have no crashlog but the game gives me this: https://pastebin.com/63Cz3sks
----------------------------------------------------
### Versions & Modlist
Modlist: https://pastebin.com/THBGQ5aZ
IE Version: 0.16-109
Forge Version/s: 32.0.106 , 32.0.99, 32.0.98

**Comment by malte0811** [comment] 2020-08-05 09:54
Duplicate of #4143

**Closed as completed by malte0811** 2020-08-05 09:54 UTC

**Comment by BunCat09** [comment] 2020-08-05 11:13
ok i searched for this in the issues but i see that i searched wrong. Thanks
