### ISSUE TITLE
1.18.2 Optifine related crash

### ISSUE THREAD

**Issue by Esseit** [BluSunrize/ImmersiveEngineering#5253] opened 2022-04-12 20:12 UTC
### Description of the issue:
Game loads and launches to menu just fine, however Game crashes once the game attempts to load the world visually on screen, preparing chunks and such during loading screen goes as normal until just after the 100% completion point. Once IE is removed from the instance the game launches normally. 

To note, game with this exact set up minus optifine runs just fine using Rubidium and Oculus, models render incorrectly but that is on the prior two mods to sort out. Optifine seems to have done something in 1.18.2 that does not agree with IE, unsure if there is anything you can or would want to do about it but better to report than stay silent.

### Crashlog:
crash log of issue. https://pastebin.com/A78Y2bYm

### Versions & Modlist
forge version 40.0.45, IE version 1.18.2-8.0.0-146

**Comment by mindforger** [comment] 2022-04-12 20:28
https://github.com/BluSunrize/ImmersiveEngineering/issues/5247

**Comment by BluSunrize** [comment] 2022-04-13 06:52
Duplicate of #5247

**Closed as completed by BluSunrize** 2022-04-13 06:52 UTC
Labels: duplicate, Optifine / Oculus
