### ISSUE TITLE
1.12 Server Crash

### ISSUE THREAD

**Issue by Aalwein** [BluSunrize/ImmersiveEngineering#2281] opened 2017-07-09 20:37 UTC
Jumped on the first 1.12 download as soon as you added it because I love IE, but sadly I can't get my private home server going with it. Works in single player but not on server.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  LoadingPlugin (Quark-r1.2-100.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 7/9/17 4:32 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.client.ClientProxy
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.client.ClientProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	... 31 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5c371e13 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 37 more
Caused by: java.lang.RuntimeException: Attempted to load class blusunrize/immersiveengineering/client/ClientProxy for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3937708408 bytes (3755 MB) / 4277534720 bytes (4079 MB) up to 4277534720 bytes (4079 MB)
	JVM Flags: 7 total; -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -Xms4096M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2406 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (ForgeMod.jar) 
	UC	forge{14.21.1.2406} [Minecraft Forge] (ForgeMod.jar) 
	UC	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UC	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UC	uncraftingtable{1.8-beta3} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta3.jar) 
	UC	actuallyadditions{1.12-r114} [Actually Additions] (ActuallyAdditions-1.12-r114.jar) 
	UC	akashictome{1.2-9} [Akashic Tome] (AkashicTome-1.2-9.jar) 
	UC	jei{4.7.1.74} [Just Enough Items] (jei_1.12-4.7.1.74.jar) 
	UC	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UC	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UC	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UC	morphtool{1.2-15} [Morph-o-Tool] (Morph-o-Tool-1.2-15.jar) 
	UC	quark{r1.2-100} [Quark] (Quark-r1.2-100.jar) 
	UC	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UC	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UC	betterbedrockgen{6.0.1} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.0.jar) 
	UC	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UC	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UC	biomesoplenty{7.0.0.2288} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2288-universal.jar) 
	UC	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UC	chameleon{1.12-4.1.1} [Chameleon] (Chameleon-1.12-4.1.1.jar) 
	UC	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UC	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UC	redstoneflux{2.0.0} [Redstone Flux] (RedstoneFlux-1.12-2.0.0.1-universal.jar) 
	UC	cofhcore{4.3.1} [CoFH Core] (CoFHCore-1.12-4.3.1.6-universal.jar) 
	UC	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.5-universal.jar) 
	UC	darkutils{${version}} [Dark Utilities] (DarkUtils-1.12-1.6.156.jar) 
	UC	forestry{5.4.3.128} [Forestry] (forestry_1.12-5.4.3.128.jar) 
	UC	eleccore{1.8.428} [ElecCore] (ElecCore-1.12-1.8.428.jar) 
	UC	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.12-1.4.8beta1.jar) 
	UC	dsurround{3.4.6.0} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UC	endercompass{1.2.6.1} [Ender Compass] (EnderCompass-1.12-1.2.6.1.jar) 
	UC	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UC	endertanks{1.6.0.1} [EnderTanks] (endertanks-1.12.0-1.6.0.1.jar) 
	UC	enderutilities{0.7.1} [Ender Utilities] (enderutilities-1.12.0-0.7.1.jar) 
	UC	energyconverters{1.0.0.1} [Energy Converters] (energyconverters_1.12-1.0.0.1.jar) 
	UC	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UC	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UC	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UC	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UC	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UC	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UC	harvest{1.12-1.2.3-15} [Harvest] (Harvest-1.12-1.2.3-15.jar) 
	UC	theoneprobe{1.4.11} [The One Probe] (theoneprobe-1.12-1.4.11.jar) 
	UE	immersiveengineering{0.12-64} [Immersive Engineering] (ImmersiveEngineering-0.12-64.jar) 
	UC	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UC	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UC	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UC	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UC	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UC	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UC	randomthings{4.0.2} [Random Things] (RandomThings-MC1.12-4.0.2.jar) 
	UC	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UC	reborncore{3.2.3.83} [Reborn Core] (RebornCore-1.12-3.2.3.83-universal.jar) 
	UC	reccomplex{1.4.4} [Recurrent Complex] (RecurrentComplex-1.4.4.jar) 
	UC	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.5.jar) 
	UC	refinedstorage{1.5.8} [Refined Storage] (refinedstorage-1.5.8.jar) 
	UC	rftools{6.10} [RFTools] (rftools-1.12-6.10beta3.jar) 
	UC	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02beta1.jar) 
	UC	simpleoregen{4.0.6} [Simple Ore Generation] (SimpleOreGeneration-4.0.6 mc 1.12.jar) 
	UC	lteleporters{1.11.2-2.1.5} [Simple Teleporters] (simpleteleporters-1.12-2.1.5.jar) 
	UC	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.4.25.jar) 
	UC	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UC	thermalfoundation{2.3.1} [Thermal Foundation] (ThermalFoundation-1.12-2.3.1.5-universal.jar) 
	UC	thermaldynamics{2.3.1} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.1.6-universal.jar) 
	UC	thermalexpansion{5.3.1} [Thermal Expansion] (ThermalExpansion-1.12-5.3.1.6-universal.jar) 
	UC	torchmaster{1.4.3.8} [TorchMaster] (torchmaster_1.12-1.4.3.8.jar) 
	UC	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UC	xnet{1.3.4.3} [XNet] (xnet-1.12-1.3.4.3.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
LoadingPlugin (Quark-r1.2-100.jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (RandomThings-MC1.12-4.0.2.jar)
  lumien.randomthings.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by malte0811** [comment] 2017-07-09 20:43
1. Put your crashlog on pastebin or gist.github.com.
2. Duplicate of #2270 and about 7 others. The fix will probably be published later today.

**Closed by malte0811** 2017-07-09 20:43 UTC
