### ISSUE TITLE
Item Router not filtering in 1.10.2

### ISSUE THREAD

**Issue by andrewmellinger** [BluSunrize/ImmersiveEngineering#1894] opened 2017-02-11 15:08 UTC
First off I am really enjoying this mod.  I like the feel as well as utility. Obviously a lot of time and effort has gone into it, and it shows.

I've never used the item router before (successfully) but it doesn't behave as expected.  First off, it looks weird where each direction shows "d" instead of the direction symbol and it seems to ignore filter settings. The d makes me think it didn't initialize properly.  Someone else is seeing the same issue and has a nice set of screen shots here:

http://imgur.com/a/p1NY9

I am using Immersive Engineering 0.10-54 via FTB Sky Factory 3.

Thanks for any help!

**Comment by malte0811** [comment] 2017-02-11 15:47
I can confirm that it is not filtering properly (I'll look into that right now). The letters are working for me though, I will look at the code and see whether there is some obvious case in which this can happen later.

**Comment by malte0811** [comment] 2017-02-11 16:46
I was wrong, the router seems to be working correctly after all, I just forgot conveyor belts depend on NBT data. I just tested this in SF3 (which is a pain if you have "just" 8GB of RAM, 1.7 GB of swap space used) and everything is working fine for me. Unless you can narrow it down a bit I won't be able to do anything here.

**Comment by andrewmellinger** [comment] 2017-02-11 18:06
My particular setup is the item filter with two chests ( black and white ) and I am trying to filter basic items like diamonds and emeralds.  It always seems to round-robin them no matter what I do. I'll try to get some more repro steps and search through the logs.  What does the "d" mean instead of the directions?

**Comment by BluSunrize** [comment] 2017-02-13 08:28
Update your version of IE. The router is actually working, but the letters in the gui are messed up and the router in world is rotated wrongly. The white face should be facing up. Both these issues were fixed in build 55.

**Comment by andrewmellinger** [comment] 2017-02-13 21:36
Thanks!  I'll try see if I can test this out tonight.

**Comment by BluSunrize** [comment] 2017-02-23 12:20
Closed, due to lack of further responses. Also, pretty sure I fixed this anyway.

**Closed by BluSunrize** 2017-02-23 12:20 UTC
