### ISSUE TITLE
How to pipe the liquid(biodiesel) into the diesel generator without other mods help?

### ISSUE THREAD

**Issue by Joccob** [BluSunrize/ImmersiveEngineering#300] opened 2015-08-10 12:04 UTC
Like I said, I didn't find any effective ways to pipe the liquid into the generator. I have to add some other tech mods such as TE or EIO in order to accomplish this. I wonder if there is any future plans to add pipes or anything else for liquid transportation?
I really like IE's unique style, but at the same time it  is kinda hard for me to realize some automation only by IE......

**Comment by bakaxyf** [comment] 2015-08-10 12:10
https://github.com/BluSunrize/ImmersiveEngineering/issues/189#issuecomment-118855594

**Comment by mindforger** [comment] 2015-08-10 12:32
please use search first before opening an duplicate issue

duplicate of #259 

would you please close this issue by yourself as it will not be closed by anybody else because of what bakaxyf saind :)

**Closed** 2015-08-10 15:15 UTC
