### ISSUE TITLE
IE crash with newer Forge.

### ISSUE THREAD

**Issue by madhatr** [BluSunrize/ImmersiveEngineering#2684] opened 2017-12-22 22:23 UTC
IE 0.12.74 and 75 both crash with forge 1.12.2-14.23.1.2581

[crash-2017-12-22_15.19.48-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1583584/crash-2017-12-22_15.19.48-client.txt)

**Comment by kchou94** [comment] 2017-12-23 04:29
I've been having a crash during load that I narrowed down to IE as well.  I saw in another issue report that it is recommended to stick to v2575 of Forge right now.  Hope this helps.

**Comment by malte0811** [comment] 2017-12-23 06:49
Duplicate of #2672 and a few others. Fixed for the next release, use forge 2575 for now.

**Closed by malte0811** 2017-12-23 06:49 UTC
