### ISSUE TITLE
[1.19.2] Engenieer's Workbench BLueprint Crash

### ISSUE THREAD

**Issue by ErdnusBuddha** [BluSunrize/ImmersiveEngineering#5632] opened 2023-03-28 09:58 UTC
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2-9.2.0-162

### How did it happen?

Place the Engineer's Workbench next to a wall (i dont know if this is necessary) and insert a BLueprint (i used the Metal Press Molds) 

The game should crash immediately.
Same when the chunk is loaded by a player

### Crash Log

crash-2023-03-28_11.11.14-client.txt

### Alternative Crash Log Post 

https://pastebin.com/rsgkCyhR

**Comment by mindforger** [comment] 2023-03-28 10:33
your crashlog is a line of text, try paste it on pastebin.com and link the paste here then

**Comment by Smallbomb78v** [comment] 2023-03-29 21:37
Same issue --> https://pastebin.com/xQbYjpMV

**Comment by mindforger** [comment] 2023-03-30 03:32
Can you reproduce without rubidium and occulus?

**Comment by ErdnusBuddha** [comment] 2023-03-31 00:12
i have tried it without shader enabled

**Comment by BluSunrize** [comment] 2023-03-31 08:35
Then provide us a crashlog without those, otherwise this issue is invalid.

**Comment by lenianiva** [comment] 2023-04-02 21:10
Here's a log without Rubidium and Oculus: [link](https://paste.ee/p/ZuYQP).

For my case when I enabled
```
enableVBO = true
```
in the client config, the game stopped crashing. This prevents the windmill from being rendered in certain shaders, however, and the blueprint flickers in the corner of the table rather than the centre.

**Comment by mindforger** [comment] 2023-04-03 04:13
>rubidium-0.6.2a.jar                               |Rubidium 

This crashlog still contains rubidium and occulus

**Comment by BluSunrize** [comment] 2023-04-03 19:05
I'm closing this.
Shaders are not supported, and the issue with VBOs will be fixed in the next release. Use the search function next time.

**Closed as not planned by BluSunrize** 2023-04-03 19:05 UTC
Labels: crash 💥

**Comment by lenianiva** [comment] 2023-04-04 04:29
> > rubidium-0.6.2a.jar                               |Rubidium
> 
> This crashlog still contains rubidium and occulus

Could you take a look at [this one](https://paste.ee/p/wbtTT)? I had rubidium, iris, and oculus explicitly disabled:
```
  [❌] iris-mc1.19.2-1.5.2.jar (disabled)
  [❌] oculus-mc1.19.2-1.2.8a.jar (disabled)
  [❌] rubidium-0.6.2a.jar (disabled)
```

**Comment by BluSunrize** [comment] 2023-04-04 07:00
No. I already closed this. The issue is resolved, turn VBOs on or wait for next release.
