### ISSUE TITLE
[1.14.4] Crusher won't accept most ores

### ISSUE THREAD

**Issue by NerdimusPrime** [BluSunrize/ImmersiveEngineering#3758] opened 2020-04-05 21:02 UTC
### Description of the issue:
Crusher will only run when either lapis or redstone ore, or quartz blocks, are tossed in. No other ore in either vanilla or IE will work.

### Versions & Modlist
IE 0.14-94
Forge 28.2.3

**Comment by BluSunrize** [comment] 2020-04-05 21:39
Duplicate of #3731, fixed for next release.

Please use the search function next time.

**Closed by BluSunrize** 2020-04-05 21:39 UTC

**Comment by NerdimusPrime** [comment] 2020-04-05 22:01
Sorry, I only searched for crusher in open issues. Next time I'll search in all issues.
