### ISSUE TITLE
Crusher sound/animation issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#346] opened 2015-08-20 19:49 UTC
@BluSunrize Managed to repo #63....
Rather than necro that old issue I am creating a new issue thread.

Issue: Crusher continues to act in its 'working' state after power is terminated
=========================

If the crusher is processing an item when it looses power, it continues to act in its 'working' state, animation, sounds, and particle affects

Steps to reproduce:
-----------------
[1] Build Crusher MB correctly
[2] supply Crusher with power
[3] supply crusher with items to process such as iron ore)
[4] cut power to Crusher while it is still processing the item
[5] observe

Version data:
-----------------
[IE version 0.5.3](https://github.com/BluSunrize/ImmersiveEngineering/commit/9200be056b205f7680314b9a0c9504c0cfd505f3)
FTB Infinity Version 1.9.0 custom botania

**Comment by cobra** [comment] 2015-08-20 20:51
I already looked a bit into it, here's what I found so far:
- without power, the client doesn't ever get updated when the "active" field is changed after the crusher finishes processing.
- adding some power connection masks this because RF causes updates
- removing `if(update)` or replacing it with `if(true)` in https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCrusher.java#L215 fixes this as well

I could not yet find when or where something is missing an update trigger.

**Comment by malte0811** [comment] 2015-08-24 19:02
I believe that I have fixed this in the last two commits of https://github.com/malte0811/ImmersiveEngineering/tree/fix-1. The first one fixes it running (animation) when the power buffer is empty but the item is not completly processed, the second one fixes it running after the item has finished processing if no power is supplied. The client update containing the data for the particles was being sent after processing rather than before, which set `active` to true and `process` to 1 client sided

**Comment by cobra** [comment] 2015-08-25 09:33
I didn't yet look into your second commit for the sync problems, but I took a different route for stopping the animation and sound. I checked whether there was any energy consumed in https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCrusher.java#L139 and changed the state accordingly without adding yet another field to check.

I have to test the whole a bit later, especially your update changes.

**Comment by cobra** [comment] 2015-08-29 20:16
I'm just looking into this whole mess again and now it doesn't stop at all, even with an active energy cell feeding power into it. This was on e27d71d, without any modifications. Either my dev setup is somehow broken or a recent change broke this even more - I still have to check this.

I then pulled in some of your syncing changes (excluding the whole hasPower stuff for now) manually, added my own changes and debug switches to turn each change on and off individually, but nothing seems to work yet. Only updating every damn time helps, which doesn't look like an acceptable solution.

I'm already considering rewriting the whole updateEntity code, possibly using a finite state machine.

**Comment by cobra** [comment] 2015-08-30 17:57
tested in singleplayer:
0.5.3.2 from curse: stops after processing
0.5.4 from curse: doesn't stop ever
bisecting confirms my suspicions, 5f393fb is the culprit creating this regression. Looks like @BluSunrize tidied up a bit too eagerly.

**Comment by malte0811** [comment] 2015-08-30 18:30
It is still the same problem, only that it is more noticeable since the crusher does not get updated every tick when energy is provided any more. My second commit (malte0811@562a040387f29f4d618f5d142640495b7f75c23f) still seems to fix this in my dev instance. 
Btw, I agree that your solution for the `hasEnergy` stuff is better, i already suspected that there was a cleaner fix when i commited that code.

**Comment by cobra** [comment] 2015-08-31 14:53
Poked around again - yep, your fix still works. I don't fully understand why the normal update mechanism doesn't work as it should without the addBlockEvent call, but at least this helps ¯\\\_(ツ)\_/¯
I would've pulled it, but you committed in the wrong order and I couldn't be bothered to do that amount of git plumbing to preserve your commit, so I did the same thing myself (and credited you). :P
I added my solution for stopping the crusher when it's out of energy; it now also consumes energy when damaging mobs, which it did for free until now. I assume this wasn't intended.

Find the whole stuff [in my repo](https://github.com/cobra/ImmersiveEngineering/tree/fixCrusherIssues) - feel free to pull. I'll create a PR later unless someone finds a new bug or has other objections.

**Comment by malte0811** [comment] 2015-08-31 15:05
I can try to explain it:
When the server sends the itemstack info for the partikels, the crusher get turned on client sided (https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCrusher.java#L399) and process is set to 1. In the old code the crusher was sending the partikel stack after the processing finished (That is why the partikels appeared after processing finished). This packet arrived after the nbt packet that told the crusher to turn off, therefore turning it back on in the same tick. i changed it so the partikle packet gets send when processing is started (which is probably what was supposed to happan anyways). The `addBlockEvent` in `receiveEnergy` was updating the crusher every tick, therefore the crusher was probably running one tick longer than inteded client side, but getting stopped after that tick

**Comment by cobra** [comment] 2015-09-01 12:38
Oh right. I even looked at that code some time ago and thought about modifying that to stop the animation and sound, but have forgotten about that client-side state modification by now m)

**Comment by cobra** [comment] 2015-09-04 12:00
@BluSunrize you can close this now.

**Comment by BluSunrize** [comment] 2015-09-04 12:53
Thank you all for the work you did on this =)

**Closed by BluSunrize** 2015-09-04 12:53 UTC
