### ISSUE TITLE
[1.16.3] IE crashing on startup with latest Forge

### ISSUE THREAD

**Issue by elowanut** [BluSunrize/ImmersiveEngineering#4412] opened 2020-10-30 17:15 UTC
# Description of the issue:
IE is causing a fatal error on client load with the latest version of forge (34.1.35). The error type is listed as " Rendering overlay" for what it's worth. Tested with only Forge+IE. 

I see that you have commented on Curseforge that Forge should be downgraded to 34.1.25. I'm filing this issue report as a reminder, and also because other mods are starting to pop up with 34.1.35 minimum requirements (like BoP).

### Crashlog:
[crash-2020-10-30_13.01.06-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5466564/crash-2020-10-30_13.01.06-client.txt)

### Versions & Modlist
**Forge:** 34.1.35
**IE:** ImmersiveEngineering-1.16.3-4.1.0-124

**Comment by BluSunrize** [comment] 2020-10-30 17:31
Duplicate of #4410, please search next time.

**Closed as completed by BluSunrize** 2020-10-30 17:31 UTC

**Comment by elowanut** [comment] 2020-10-30 18:24
My apologies. I did search, but only in open issues. Since the issue is live (i.e. it is increasingly difficult to stay in 34.1.25, if you're operating in a multi-mod ecosystem), it didn't occur to me to check the closed issues.

Thanks for all your hard work on this mod.
