### ISSUE TITLE
Diesel Generator sounds

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#337] opened 2015-08-20 03:17 UTC
Issue: Diesel Generator's 'working' sound continues to play after satisfying energy demand
---------------
If the power demand on the network zeros while the Diesel Generator(s) are running, their 'working' sound continues to play while the 'working' animation and power output stops.

Steps to reproduce:
------------
[1] correctly build a Diesel Generator
[2] provide Diesel Generator with fuel
[2] hook it through a breaker into a power network with demand
[3] close breaker
[4] Allow Diesel Generator to begin running
[5] open breaker

Action
-----------------
Removing power demand on network containing a Diesel Generator as a supplier

Expected result
------------------
Diesel Generator would return from its 'work' state to its 'idle' state

Actual result
--------------
Diesel Generator's animation returns to 'idle' state, but it's sound affect remains in the 'work' state.

Version data
==============
[IE version 0.5.3](https://github.com/BluSunrize/ImmersiveEngineering/commit/9200be056b205f7680314b9a0c9504c0cfd505f3)
FTB Infinity version 1.9.0 custom botania

**Comment by cobra** [comment] 2015-08-20 09:53
is this the same as #119?

**Comment by theunkn0wn1** [comment] 2015-08-20 16:16
Yeah, that issue is really old and I did not think anyone would thank me for necroing it. But yes, it is similar to #119. However, i do recall being affected by that one, and it is not exactly the same.

#119 IIRC caused the same MB (such as the crusher) to loop its sounds to infinity, sometimes playing the same sounds multiple times from the same source. so far, this issue (#337) only seems to affect the Diesel generator in one way, in the method mentioned in my OP

**Comment by cobra** [comment] 2015-08-20 18:21
I could reproduce this by quickly toggling the breaker a lot of times, to me this looks identical to #119. I couldn't reproduce it yet with my hack active. I'll push it to my repo (and post the link in this place), so you can test as well. Please note that my hack ensures that each sound is played for a certain amount of time (at the moment 20 ticks), so you'll hear the generator for a bit longer than expected when you switch it on and then off immediately afterwards. It should shut off without any delay when letting the generator run for more than one second.

**Comment by theunkn0wn1** [comment] 2015-08-20 18:26
Go ahead, i would like to try your hack

**Comment by cobra** [comment] 2015-08-20 18:32
Pushed.
Note: I didn't pull the remove-update-calls-commit yet to avoid any influence of that.

**Comment by theunkn0wn1** [comment] 2015-08-20 18:33
your fork right, cobra/ImmersiveEngineering ?

**Comment by theunkn0wn1** [comment] 2015-08-20 18:54
OK, built to your 'SoundGlitchWorkaround' and tested it.
no joy. Issue persists

**Comment by cobra** [comment] 2015-08-20 19:04
Have you tested the original issue from #119 (consume very little energy to run the generator in stutter mode) with this fix? Do you still get duplicate/orphaned sounds when using my workaround?

Back to the breaker problem: have you tried increasing blusunrize.immersiveengineering.common.util.IESound#minPlayTicks? I guess 40, maybe 60 ticks should really be enough time for the sound system to catch up even in bad cases.

**Comment by theunkn0wn1** [comment] 2015-08-20 19:35
The original issue as far as i can tell was with the crusher.
 Just tested the crusher sound issue... Result: issue there persists
in fact, the crushers remain in their 'working' animation, particle affects, and sounds persist after power feed to them is terminated

============================

I still get orphaned sounds coming from my Diesel generators when i have more than one on the network with little network demand, when only one of the generators needs to be running to satisfy the demand

=============
Tried setting `blusunrize.immersiveengineering.common.util.IESound#minPlayTicks` to 60.
result: still get orphaned/duplicate sounds being emitted from the generators

**Comment by cobra** [comment] 2015-08-20 19:56
Yeah, the crushers seem to have another problem with updating their state on the client sometimes, I've already been trying to track that down.

The sound isses are getting weirder and somewhat heisenbuggy. The weird thing is that I could reproduce your problem (not immediately, but it happened after some time) and fix it for me. What version of java are you running? (OS was irrelevant for me, same result on win7 and debian 8.1)

**Comment by theunkn0wn1** [comment] 2015-08-20 20:00
Windows 10 (x64) 
my JRE is Version 8 Update 51 
4.25 GB RAM allocated

**Comment by cobra** [comment] 2015-08-20 21:23
I don't see any significant differences. I hope it's not some weird hardware related stuff, but I don't expect this to be the case with both Debian and Windows acting the same way. (off topic: update java. 8u60 is the current one, but doesn't change anything for me regarding IE)

**Comment by theunkn0wn1** [comment] 2015-08-20 21:31
Grugh.. i just updated Java.... I am now up-to-date. How can hardware possibly change the way the JRE runs?

**Comment by BluSunrize** [comment] 2015-08-20 21:39
Just as a heads up: I'm aware of this error and of #346, but I won't fix them in the upcoming (today) IE 0.5.4. This is because my vacation limits me to a laptop that isn't very good for testing this stuff. I'll tend to it when Im home. In the meantime, I'm very appreciative of all the info you fellas are digging up on these issues. I'm happy to have some code savvy people on my issue tracker :D

**Comment by cobra** [comment] 2015-08-21 12:19
Do you have an idea what's going wrong with the sounds and the crusher sync?
No need to stress yourself, both issues are rather cosmetic annoyances and not breaking everything.
Digging through other peoples' more or less undocumented code to find bugs is a fun exercise for me. Also, I don't like using software with bugs I could fix myself. Win-win!

**Comment by theunkn0wn1** [comment] 2015-08-21 17:03
OK, something i have noticed is this bug seems to only occur if there is **more than one** of the given sound-emitting device within earshot, however this can occur with only one device.

I suspect somewhere along the line a duplicate sound source is spawned, and is not properly cleaned up. My test setup consists of 3 diesel generators, all outputs bound with HV wire connectors leading into  three connectors. the connectors are then drawn through a breaker to the outside circuit.

When the breaker is in the 'closed' position all the generators run. I have noticed at about 1.5 seconds into the run a fourth sound source becomes audible. this same source seems to become orphaned and remains audible even after the machine returns to its 'idle' state.

If needed i can record the issue as it occurs if that would help track down this

**Comment by BluSunrize** [comment] 2015-10-12 11:45
I'm just gonna asume this is fixed with a lot of the other desync things .-.

**Closed by BluSunrize** 2015-10-12 11:45 UTC

**Comment by cobra** [comment] 2015-10-12 11:57
Sound is still glitching around sometimes (not very often), but I haven't been able to reproduce it reliably enough for debugging. I suspect some issues with the sound system itself, maybe thread-related.

**Comment by cobra** [comment] 2015-10-17 08:21
Interesting. Buffing the crusher to 1000 RF/t makes it leak sounds like crazy.

**Comment by cobra** [comment] 2015-10-17 08:46
I'm debugging this once again. Seems like the sounds don't get removed by minecraft, the list of tickable sounds is not empty when it should be. I'll update this with more information once I have it.

**Comment by cobra** [comment] 2015-10-17 09:34
Ha! I finally found and fixed the cause of ALL these sound related problems. It was a problem in IE's code after all, and what a sneaky and ugly one. Delete this `!` in [IESound.java:L114](https://github.com/BluSunrize/ImmersiveEngineering/blob/1f5d0aabe96c45762842800f98d0c60ddf7ba528/src/main/java/blusunrize/immersiveengineering/common/util/IESound.java#L114) everything is fine. I was polishing the command handling a bit further, so I'll just add this and PR all of this later.

**Comment by BluSunrize** [comment] 2015-10-17 09:39
But that check exists to stop sounds from originating from removed blocks...

**Comment by cobra** [comment] 2015-10-17 09:40
yep, I just realized while testing that I was a bit too fast. Still seems like there's a problem somewhere around this.

**Comment by cobra** [comment] 2015-10-17 17:41
@BluSunrize I've got two questions about [ClientProxy.java:L510](https://github.com/BluSunrize/ImmersiveEngineering/blob/1f5d0aabe96c45762842800f98d0c60ddf7ba528/src/main/java/blusunrize/immersiveengineering/client/ClientProxy.java#L510):
- why is this if independent of the upper `if` with `sound!=null`?
- what did you want to catch with the `!ClientUtils.mc().getSoundHandler().isSoundPlaying(sound)` part?

I split this `if` from line 510 into `if(sound==null)` and `else if(!ClientUtils.mc().getSoundHandler().isSoundPlaying(sound))` with identical content allowing me to breakpoint the conditions individually.
I noticed that the `!ClientUtils.mc().getSoundHandler().isSoundPlaying(sound)` condition is very, very rarely true, very hard to trigger reproducibly, and that the return value of `isSoundPlaying(sound)` can change directly after calling it. This means that 
````
if(tileActive)
{
	if(sound==null)
	{
		…
	}
	else if(!ClientUtils.mc().getSoundHandler().isSoundPlaying(sound))
	{
		if(ClientUtils.mc().getSoundHandler().isSoundPlaying(sound))
			IELogger.info("WTF?");
		…
	}
````
will produce log output. Also, this will overwrite an existing sound with a newly generated one.

**Comment by cobra** [comment] 2015-10-25 10:34
As far as I can see, I've solved this now. There have two issues:
- leaking sounds when opening/closing the chat line or pausing/resuming the game: minecraft calls `SoundHandler.pauseSounds` and `SoundHandler.resumeSounds` when doing this. `SoundManager.resumeAllSounds` will stupidly resume all sounds, including those which have been stopped already and thus leak sounds. Setting the sound's `donePlaying` to true and `volume` to zero (just to avoid short ugly noise spikes until the  finally removes the sound it just resumed instead of removing it immediately) allows the SoundManager to clean up this mess automatically. Calling `SoundHandler.stopSound(sound)` apparently isn't enough, as this doesn't remove the sound from the internal `playingSounds` Map (blame mojang, I guess).
- two machines near each other could make IE generate two sounds and losing track of one by overwriting the one already present in the soundMap. (see the comment above)
