### ISSUE TITLE
[1.10.2] [FIXED FOR FUTURE RELEASES] Manual Crashes - VertexBuffer State Exception

### ISSUE THREAD

**Issue by hron84** [BluSunrize/ImmersiveEngineering#1704] opened 2016-11-20 21:55 UTC
No OptiFine, no BetterFPS, no other rendering messer mod.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-59.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 11/20/16 10:23 PM
Description: Rendering screen

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:187)
	at net.minecraft.client.gui.Gui.func_73729_b(SourceFile:114)
	at blusunrize.lib.manual.gui.GuiButtonManualNavigation.func_146112_a(GuiButtonManualNavigation.java:37)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at blusunrize.lib.manual.gui.GuiManual.func_73863_a(GuiManual.java:243)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:187)
	at net.minecraft.client.gui.Gui.func_73729_b(SourceFile:114)
	at blusunrize.lib.manual.gui.GuiButtonManualNavigation.func_146112_a(GuiButtonManualNavigation.java:37)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:71)
	at blusunrize.lib.manual.gui.GuiManual.func_73863_a(GuiManual.java:243)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: blusunrize.lib.manual.gui.GuiManual
	Mouse location: Scaled: (287, 301). Absolute: (574, 369)
	Screen size: Scaled: (640, 486). Absolute: (1280, 972). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['hron84'/54, l='MpServer', x=131.66, y=65.00, z=245.92]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6413444 game time, 4908895 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 42 total; [EntityMooshroom['Mooshroom'/779467, l='MpServer', x=73.95, y=65.00, z=237.14], EntityChicken['Chicken'/783112, l='MpServer', x=92.11, y=65.00, z=239.48], EntitySheep['Sheep'/544780, l='MpServer', x=79.52, y=65.00, z=236.41], EntityMooshroom['Mooshroom'/779279, l='MpServer', x=72.85, y=65.00, z=236.50], EntityVillager['Villager'/786504, l='MpServer', x=73.26, y=65.00, z=218.69], EntityPig['Pig'/545613, l='MpServer', x=85.77, y=65.00, z=239.49], EntityChicken['Chicken'/783437, l='MpServer', x=91.99, y=65.00, z=236.39], EntityRabbit['Rabbit'/800394, l='MpServer', x=97.50, y=65.00, z=234.72], EntityVillager['Villager'/786188, l='MpServer', x=72.65, y=65.00, z=230.33], EntityRabbit['Rabbit'/795332, l='MpServer', x=97.61, y=65.00, z=235.45], EntitySheep['Sheep'/780165, l='MpServer', x=83.35, y=65.00, z=239.24], EntityRabbit['Rabbit'/788572, l='MpServer', x=98.10, y=65.00, z=238.15], EntityChicken['Chicken'/783000, l='MpServer', x=93.49, y=65.00, z=239.02], EntityRabbit['Rabbit'/799263, l='MpServer', x=98.28, y=65.00, z=234.99], EntityChicken['Chicken'/625245, l='MpServer', x=91.61, y=65.00, z=239.49], EntityPig['Pig'/780959, l='MpServer', x=87.97, y=65.00, z=235.74], EntityPig['Pig'/477470, l='MpServer', x=88.83, y=65.00, z=235.07], EntityVillager['Villager'/787797, l='MpServer', x=67.02, y=65.00, z=228.80], EntityVillager['Villager'/786833, l='MpServer', x=71.20, y=65.00, z=229.13], EntityMooshroom['Mooshroom'/619671, l='MpServer', x=73.39, y=65.00, z=237.91], EntityRabbit['Rabbit'/788396, l='MpServer', x=98.32, y=65.00, z=235.71], EntitySheep['Sheep'/479910, l='MpServer', x=82.08, y=65.00, z=236.26], EntityChicken['Chicken'/625515, l='MpServer', x=91.58, y=65.00, z=236.84], EntityRabbit['Rabbit'/788782, l='MpServer', x=97.56, y=65.00, z=238.16], EntityItem['item.item.feather'/813998, l='MpServer', x=94.61, y=65.00, z=236.53], EntityMooshroom['Mooshroom'/619810, l='MpServer', x=77.15, y=65.00, z=239.19], EntityPig['Pig'/780900, l='MpServer', x=88.95, y=65.00, z=235.95], EntityChicken['Chicken'/783460, l='MpServer', x=92.81, y=65.00, z=236.76], EntityChicken['Chicken'/772665, l='MpServer', x=91.98, y=65.00, z=236.12], EntityVillager['Villager'/787134, l='MpServer', x=70.66, y=65.00, z=228.31], EntityVillager['Villager'/787454, l='MpServer', x=71.30, y=65.00, z=230.48], EntityVillager['Villager'/796217, l='MpServer', x=70.68, y=65.00, z=219.52], EntityPlayerSP['hron84'/54, l='MpServer', x=131.66, y=65.00, z=245.92], EntityPig['Pig'/504816, l='MpServer', x=89.88, y=65.00, z=236.10], EntityRabbit['Rabbit'/788219, l='MpServer', x=97.12, y=65.00, z=235.87], EntitySheep['Sheep'/503358, l='MpServer', x=80.84, y=65.00, z=238.28], EntitySheep['Sheep'/619568, l='MpServer', x=83.89, y=65.00, z=236.68], EntityMooshroom['Mooshroom'/503484, l='MpServer', x=73.28, y=65.00, z=238.90], EntityMooshroom['Mooshroom'/544885, l='MpServer', x=76.38, y=65.00, z=235.07], EntityItem['item.item.feather'/825265, l='MpServer', x=94.11, y=65.00, z=239.76], EntityRabbit['Rabbit'/800370, l='MpServer', x=99.27, y=65.00, z=234.72], EntitySheep['Sheep'/780020, l='MpServer', x=82.90, y=65.00, z=235.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 186595240 bytes (177 MB) / 1814036480 bytes (1730 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2116 68 mods loaded, 68 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2116.jar) 
	UCHIJAAAA	Forge{12.18.2.2116} [Minecraft Forge] (forge-1.10.2-12.18.2.2116.jar) 
	UCHIJAAAA	exnihiloomnia{1.1.8} [Ex Nihilo Omnia] (exnihiloomnia-1.1.8.jar) 
	UCHIJAAAA	excompressum{2.0.54} [Ex Compressum] (ExCompressum_1.10.2-2.0.54.jar) 
	UCHIJAAAA	immersiveengineering{0.10-49} [Immersive Engineering] (ImmersiveEngineering-0.10-49.jar) 
	UCHIJAAAA	JEI{3.13.3.382} [Just Enough Items] (jei_1.10.2-3.13.3.382.jar) 
	UCHIJAAAA	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Psi{r1.0-41} [Psi] (Psi-r1.0-41.jar) 
	UCHIJAAAA	Quark{r1.0-59} [Quark] (Quark-r1.0-59.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UCHIJAAAA	betterquesting{1.3.161} [Better Questing] (BetterQuesting-1.3.161.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJAAAA	Botania{r1.9-338} [Botania] (Botania r1.9-338.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.8} [Chameleon] (Chameleon-1.10-2.1.8.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	CharsetLib{0.3.0-pre15} [â€˝] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetAudio{0.3.0-pre15} [â™«] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetDecoration{0.3.0-pre15} [âš?] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJAAAA	NashornLib{1.9.4-1.8.77-1.3.1} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.1.8.jar) 
	UCHIJAAAA	craftingharmonics{1.9.4_1.10_1.10.2-1.5.7} [Crafting Harmonics] (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar) 
	UCHIJAAAA	cyberware{beta-0.2.3} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.3.jar) 
	UCHIJAAAA	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UCHIJAAAA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.0.0.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.2.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	Lockdown{${mod_version}} [Lockdown] (Lockdown-1.10.2-5.0.0-universal.jar) 
	UCHIJAAAA	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.9} [Morpheus] (Morpheus-1.10.2-3.1.9.jar) 
	UCHIJAAAA	mxtune{0.3.1.0-dev.7} [mxTune] (mxtune-1.10.2-0.3.1.0-dev.7.jar) 
	UCHIJAAAA	mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader] (Mychunkloader-1.9.4-1.10.2-03.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJAAAA	ProjectE{1.10.2-PE1.0.6B} [ProjectE] (ProjectE-1.10.2-PE1.0.6B.jar) 
	UCHIJAAAA	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.4.6} [Storage Drawers] (StorageDrawers-1.10.2-3.4.6.jar) 
	UCHIJAAAA	refinedstorage{1.2.4} [Refined Storage] (refinedstorage-1.2.4.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCHIJAAAA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJAAAA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJAAAA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.6.6-46} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.6-46.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCHIJAAAA	bq_standard{1.3.92} [Standard Expansion] (StandardExpansion-1.3.92.jar) 
	UCHIJAAAA	totemic{1.9.4-0.7.9.1} [Totemic] (Totemic-1.9.4-0.7.9.1.jar) 
	UCHIJAAAA	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-59.jar)
  vazkii.quark.base.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: forge-12.18.2.2116
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD Athlon(tm) 64 X2 Dual Core Processor 5200+
```

Btw, if you can link some screnshot from this page (how assembler can be built) it would be nice 'til this will be fixed.

**Comment by BluSunrize** [comment] 2016-11-20 22:38
Could I ask you to please try and replicate this without Mekanism?

**Comment by b0bst3r** [comment] 2016-11-21 01:01
Replicated http://pastebin.ubuntu.com/23509563/ without mekanism

**Comment by BluSunrize** [comment] 2016-11-21 09:00
What the....weeeeeird.
Chisel Compat was introduced in 48, so I could see it crashing from there on, but 49+?
I'll look into it. Thanks for figuring out the mod.

**Comment by b0bst3r** [comment] 2016-11-21 09:47
Without looking in to this perhaps you'd know off the top of your head but are the pages which crash are the only ones with half slabs in the models?

**Comment by BluSunrize** [comment] 2016-11-21 09:49
Well the assembler is the only reporting that particular crash yet.
Try the Arc Furnace, that also features halfslabs.

**Comment by b0bst3r** [comment] 2016-11-21 10:03
Yeah I have already it's in my report above that also crashes as got the arc furnace page from another issue so I tried it.

**Comment by BluSunrize** [comment] 2016-11-21 10:12
Oh, woops. I completely overlooked that, my bad ^^"

As I said, I'll look into this later today.

**Comment by BluSunrize** [comment] 2016-11-21 13:19
Weird. I am unable to reproduce this in my test environment, using Chisel 1.10.2-0.0-7.3 myself, however, using the same version of chisel, I can reproduce it in a compiled environment.

Wat.

**Comment by BluSunrize** [comment] 2016-11-21 21:20
And now I can't replicate it in an obfuscated environment anymore either!
Yay for edgecase issues!

**Comment by Jamdog** [comment] 2016-11-22 07:19
Just came here to report this too, as it happened to me on a HermitPack 1.4.0 server while viewing the Improved Furnace assembler page in the manual (top of the Heavy Machines section).  I asked someone else on the server to check it, and they crashed too.

Versions installed in HermitPack 1.4.0 are: 

- Immersive Engineering 0.10-48
- Chisel MC 1.10.2 0.0.7.3

If it helps, the 2 crash reports are here:

- http://hastebin.com/joleyetoge.tex
- http://hastebin.com/uravovotol.tex

**Comment by mindforger** [comment] 2016-11-22 07:54
interesting, i don't know if you had a deep look into these dumps

>Current CompileTask:
C2:11425644 56190       4       blusunrize.lib.manual.gui.GuiManual::func_73863_a

>ParOldGen       total 2796544K, used 2608569K [0x00000006c0000000, 0x000000076ab00000, 0x000000076ab00000)
  object space 2796544K, 93% used [0x00000006c0000000,0x000000075f36e660,0x000000076ab00000)

>ParOldGen       total 2796544K, used 2747594K [0x00000006c0000000, 0x000000076ab00000, 0x000000076ab00000)
  object space 2796544K, 98% used [0x00000006c0000000,0x0000000767b32ad0,0x000000076ab00000)

both crashes indicate a recompile of one of your classes while on very hig used memory situations
unfortunately my knowledge in reading those dumps is very weak

but looking on all the class checks and the recompile events i strongly tend to think the garbage collector removed/unloaded some classes and the recompilation just ran out of memory

**Comment by malte0811** [comment] 2016-11-22 20:26
I think dc3b707752a05afad9af2bd7c9741a9617b0b874 fixed this, at least the lightning rod one was caused by the missing null check when rendering hv caps and all other crashes I have seen are with multiblocks including TE's.

**Comment by BluSunrize** [comment] 2016-11-22 20:27
How would that cause an unfinished Vertex buffer though? :/

**Comment by malte0811** [comment] 2016-11-22 20:44
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/ManualPageMultiblock.java#L219
The line after that one throws an NPE, which is caught and silently logged. I only noticed this because a breakpoint after that for-loop wasn't triggering. It would probably be a good idea to stop drawing if an exception was thrown while drawing, I will implement that on thursday or friday if you haven't done so by then.

**Comment by BluSunrize** [comment] 2016-11-22 20:47
haaaaa!
Well slap me with bread and call me a sandwich!
Well spotted, I shall look into fixing that (and credit you of course).
Cheers!

**Comment by BrisingrAerowing** [comment] 2016-11-23 18:14
I am getting this with the squeezer page as well. Just FYI.

And BTW, @BluSunrize, are you from the US South? I rarely hear that kind of phrasing outside of that region?

**Comment by malte0811** [comment] 2016-11-23 18:27
Yes, this happens with any multiblock page that has a block from IE on it that normaly contains a TileEntity. And Blu is from Germany, just like me.

**Comment by BluSunrize** [comment] 2016-11-24 17:41
@BrisingrAerowing Nope. From Germany. Just thought it was a fun way of saying that I fucked up =P

**Comment by viveleroi** [comment] 2016-11-24 23:03
Had this same crash while trying view the Squeezer entry in the manual. It's a custom pack but I do have many popular mods, including Chisel.

Log: https://pste.me/#/bRIhe

**Comment by RolanDecoy** [comment] 2016-11-26 07:52
Similar crash when trying to open the Lightning Rod entry in the manual:

[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: net.minecraft.util.ReportedException: Tesselating block in world
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:65)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at blusunrize.immersiveengineering.api.ManualPageMultiblock.renderPage(ManualPageMultiblock.java:220)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at blusunrize.lib.manual.gui.GuiManual.func_73863_a(GuiManual.java:223)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[08:42:53] [Client thread/INFO]: [blusunrize.immersiveengineering.api.ManualPageMultiblock:renderPage:249]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[08:42:53] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[08:42:53] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.getExtendedState(BlockIETileProvider.java:204)
[08:42:53] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
[08:42:53] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:53)
[08:42:53] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 21 more

Things I noticed, the use of AppleCore and the mention of codechickencore in the stacktrace.

Other notables:

at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Already building!

and 

at blusunrize.lib.manual.gui.GuiButtonManualNavigation.func_146112_a(GuiButtonManualNavigation.java:37) ~[GuiButtonManualNavigation.class:?]

**Comment by RolanDecoy** [comment] 2016-11-26 08:38
@viveleroi Mod specific issue; Also happens when no other mods are installed. Anywho, I think they traced the problem, now all that rests is a solution ;-)

**Comment by BluSunrize** [comment] 2016-11-26 08:43
Yeah I've written a fix, it's jsut unpushed atm.

**Comment by viveleroi** [comment] 2016-11-26 16:26
I appreciate it, I'm eager for the fix. It happens with the Arc Furnace entry and at this point is like playing the lottery, I don't know which entry will crash me. Sadly the manual seems to be the only source of accurate recipes - nearly all videos I find are for the older versions and the few wiki pages I find are wrong or poorly displayed.

**Comment by BrisingrAerowing** [comment] 2016-11-26 23:25
@BluSunrize Ah, OK. Southerners have a lot of phrases like that. I find some of them quite funny.

**Comment by BrisingrAerowing** [comment] 2016-11-26 23:27
@viveleroi Try the [FTB Wiki](http://ftb.gamepedia.com/Immersive_Engineering), it seems to be up-to-date. I am using it for the diagrams on how to build things, and so far they work.

I use the FTB wiki quite a bit for various mods, actually.

**Comment by hron84** [comment] 2016-11-30 12:16
Do you plan to put this fix under the tree?

**Comment by BluSunrize** [comment] 2016-11-30 12:23
No, I plan to release it when I'm done with everything else I'm doing ;)

**Comment by hron84** [comment] 2016-11-30 12:26
@BluSunrize OK-OK, no hurry. You doing amazing job, especially the new conveyor-placing system, but I also love the whole mod! Do your things on your way!

**Comment by hron84** [comment] 2016-12-02 11:24
Someone can help me what Assembler uses for steel scaffolding slopes instead under 1.10? Because they aren't a part of the 1.10 version.

**Comment by BluSunrize** [comment] 2016-12-02 12:11
Iron Sheetmetal slabs.
Also, this issue is resolved, so I'll close it.

**Closed by BluSunrize** 2016-12-02 12:11 UTC

**Comment by hron84** [comment] 2016-12-02 12:15
Thanks.
