### ISSUE TITLE
[1.12.2] visually glitch

### ISSUE THREAD

**Issue by TheSnowyChickens** [BluSunrize/ImmersiveEngineering#2973] opened 2018-04-28 14:25 UTC
### Description of the issue:
I think you can see it. xD (Only the outherside are real squeezer)
It happends if I join the world or the RFTools world.

![2018-04-28_16 14 24](https://user-images.githubusercontent.com/29357962/39397454-9f44a0d8-4aff-11e8-97cb-4e07bdef341f.png)

It can stand in the context with this issue, that I reported too : https://github.com/BluSunrize/ImmersiveEngineering/issues/2699

### Versions & Modlist
Use this crash report from another crash, in the list from the crash is a completely mod list with all my mods + forge and MC stuff. (this crash report is from a Thermal crash today) :
https://paste.dimdev.org/saluqigepa.txt

And yes, I tried it with and without optifine.

**Comment by BluSunrize** [comment] 2018-04-28 14:44
Does the issue persist after reloading the block renders? (F3+A)

**Comment by TheSnowyChickens** [comment] 2018-04-28 17:40
I needed to dismantle the block (the second light engineering block, where we can connect the power).
The "clone" has a break animation, so I think the specified light engineering block saved the whole machine pattern. 
I forgot to F3 + A, but I often reload the world and its not disappeared. (I could walk through the "clone")

**Comment by xy795** [comment] 2018-05-15 21:48
I experienced the same glitch. Looks like in my case only the Arc Furnace, wooden posts and wire connectors/relays are affected in just one chunk. I also have other IE multiblocks and other parts elsewhere in the world which are not affected and as you can see in the pictures below only some connectors and relays are rotated strange (also my squeezer looks normal). If I break the structure and re-form it again the bug is gone till I relog in the world or travel far enough to reload it. Also F3+A makes no difference for this.

Some (maybe) interesting sidenote: In the same chunk where IE parts compleately freak out no chisel&bit blocks and AE Glass Cables are visible and multiblocks from modular machinery appear like the block is not formed (altough it is formed). I don't know if this is caused by the glitchy IE stuff or it is another mod what makes IE go crazy.

Screenshots:

The Arc Furnace is normally rotated 90 degrees counterclockwise than the multiple ghost ones which are rendered.
![2018-05-15_23 19 02](https://user-images.githubusercontent.com/16350102/40085064-95f57b5e-5899-11e8-80e5-735cac81c3a7.png)
![2018-05-15_23 19 54](https://user-images.githubusercontent.com/16350102/40085066-9631705a-5899-11e8-9e0e-7a62048b748a.png)
![2018-05-15_23 19 33](https://user-images.githubusercontent.com/16350102/40085065-96140e7a-5899-11e8-8b13-359f7191b3fd.png)

**Comment by Rsslone** [comment] 2018-06-01 04:17
Also having this same problem on the modpack im building. There is also a weird glitch in the manual.
https://i.imgur.com/O1I4IJb.png

**Comment by DralinZero** [comment] 2018-06-19 17:23
I'm also affected by this glitch. I'm running Sevtech 3.0.8. It is affecting connectors/relays/multibocks/cloches/waterwheel and also engineering blocks are flickering when unforming the multiblocks.
Refined Storage cables also seem to be affected (rotated wrong and some not showing connections)

Screenshots with chunk boundries shown (all the same chunk)

![screen1](https://user-images.githubusercontent.com/40402192/41613519-16a3f088-73f6-11e8-824b-f187da8d99e7.jpg)
![screen2](https://user-images.githubusercontent.com/40402192/41613520-16bd0d34-73f6-11e8-8215-2fd5e568d14f.jpg)
![screen3](https://user-images.githubusercontent.com/40402192/41613522-16daf2ea-73f6-11e8-87e3-ee5a2e9b148a.jpg)

**Comment by Wuestengecko** [comment] 2019-07-25 12:39
Hi, I too am experiencing this issue, and I have made a possibly interesting observation. (All my tests happened on single player worlds.)

When pressing F3 and looking at an IE multiblock, in the bottom right corner you see some information like

```
immersiveengineering:metal_multiblock
_0multiblockslave: true
_1dynamicrender: false
boolean0: false
facing: west
type: silo
```

For any given multiblock structure, all except one block (the origin block) have `_0multiblockslave: true`. With silos and tanks, this origin block is the bottom center one where you connect output belts/pipes and the redstone signal.

I've noticed that, if such a visual glitch appears, for every glitched model there is a block which has `_0multiblockslave` erroneously set to `false`. The `facing` parameter seems to be set randomly and does not necessarily match the origin's and the other slaves' `facing`. This is most easily observable in a glitched silo or tank, as the origin and all other blocks are easily accessible without having to break any (which would destroy this information). Which blocks are glitched seems to be completely random and changes every time I go back to the main menu and reload the world. Reloading chunks with `F3 + A` multiple times does not change anything, the issue persists with the glitched models at the exact same locations.

![2019-07-25_13 41 44](https://user-images.githubusercontent.com/1579756/61872199-04a14d80-aee3-11e9-902f-4890cfe98001.png)

I was able to reproduce it with only Forge + IE, however when I originally created that world I was using a few other mods as well (~25 total). The issue occurs both with and without Optifine installed.

*Side note*: Not only which ones, but also how many glitched blocks there are in total can change drastically between quit/reload cycles. There are times when almost every single block of every single machine has the glitch, and there are times when only that one excavator far off in the distance has a single glitch and nothing else. Also, it is not limited to large machines, but can affect ones as small as the Garden Cloche and transformers.

**Comment by BluSunrize** [comment] 2019-07-25 15:26
Could you please provide a detailed way of reproducing that with *only* Forge and IE, in a new world? 
Any other evidence is inconclusive.

**Comment by TheSnowyChickens** [comment] 2019-07-25 17:43
It is difficult to reproduce it, because we don't know how we trigger this bug.

I created a new world and placed many machines, but all was okay.
I continue testing ...

**Comment by Wuestengecko** [comment] 2019-07-30 01:26
After some more organized testing on my previously mentioned creative world, it appears I have misremembered the part about vanilla forge + IE. I apologize for that.

I have isolated the glitch to be caused by ImmersivePetroleum, which is present in all mod packs mentioned in this issue. Removing all mods except IE + IP makes it reliably appear (as reliable as it can get - it's still random after all), removing IP from the pack makes it reliably not appear anymore. I'll try to get the ball rolling over on the ImmersivePetroleum Github, so you can close the issue here.

It might be worthwile for the other participants here to verify that it is indeed caused by ImmersivePetroleum; just remove the mod from your pack and load into your world (after making a backup), then go around and look if these glitches still occur or not.

**Closed** 2019-07-30 02:21 UTC
