### ISSUE TITLE
[1.10.2] Crash when clicking Squeezer or Lightning Rod in manual v0.10-50

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1717] opened 2016-11-22 11:49 UTC
[1.10.2] Crash when clicking Squeezer in Manual v0.10-50
See crash report here for Squeezer:
http://pastebin.com/UBNBf9sD
And here for Lightning Rod:
http://pastebin.com/qRxdNecu

**Comment by BluSunrize** [comment] 2016-11-22 12:12
Wait what? No chisel?

Well shit. That makes that issue a lot worse.

**Comment by VallenFrostweaver** [comment] 2016-11-22 12:46
Added Lightning Rod too.

**Comment by VallenFrostweaver** [comment] 2016-11-22 12:52
Here you go. Clicking Squeezer with only Vanilla, IE, and JEI: http://pastebin.com/uzLw3EEe

**Comment by BluSunrize** [comment] 2016-11-22 14:54
Except that the instance very obviously includes Roots and and One Probe and the crash is quite visibly caused by 
"    at elucent.roots.tileentity.TileEntityImbuer.func_73660_a(TileEntityImbuer.java:139)"

>___________>

**Comment by VallenFrostweaver** [comment] 2016-11-22 17:22
o.o  oh my. Ok then. Strange. I guess I'll let Elucent know. Wowsers...
-____-

**Comment by VallenFrostweaver** [comment] 2016-11-22 17:55
Nope. I was a total derp and posted the wrong crash log. Pls forgive.

Here you go: http://pastebin.com/8GmZe5ar

**Comment by malte0811** [comment] 2016-11-22 19:46
Blu, have you looking into this yet? If not, I would like to do that since I can try to fix this without having proper internet access (the router or the connection from the router to the internet broke and I have only non-high-speed mobile internet at the moment).

**Comment by BluSunrize** [comment] 2016-11-22 20:11
@malte0811 we have another issue on this, #1704
And yeah, though I was briefly able to replicate it, I no longer can. Any help on it is welcome.
(btw if you do figure it out, I'd love to hear the reasoning ^^)

In fact, I will close this one, all further discussion on the matter should be moved to #1704

**Closed by BluSunrize** 2016-11-22 20:11 UTC
