### ISSUE TITLE
1.15.2 Hemp plant white textures BluePrint crashes game.

### ISSUE THREAD

**Issue by Tryonus** [BluSunrize/ImmersiveEngineering#3974] opened 2020-06-13 16:23 UTC
Currently Playing All The Mods 5 pack on curse.
Resently been updated with IE, but when i have planted hemp the seeds don't have normal texture. see Image.
![2020-06-13_13 58 08](https://user-images.githubusercontent.com/29674418/84573677-e615a080-ad99-11ea-979f-61aee214ebfd.png)

Also when i crafted the Work Station and placed in a blueprint, it crashes the game to desktop and have too use a world backup to fix.

below is a link to my video on utube, i am not advertising my channel or video, but it shows you what happens when i place blueprint in. Go to roughly 26 mins 20 seconds to show crafting of blueprint and crash when put in table.

https://www.youtube.com/watch?v=GIOK7627PBk

Thank you.

**Comment by malte0811** [comment] 2020-06-13 17:13
Duplicate of #3955 for the hemp and #3908 for the crash.

**Closed as completed by malte0811** 2020-06-13 17:13 UTC
