### ISSUE TITLE
(Issue(...?)) Wiring

### ISSUE THREAD

**Issue by genthug** [BluSunrize/ImmersiveEngineering#503] opened 2015-10-14 01:25 UTC
So, I'm new to the mod and thus far loving it. However, I'm not entirely sure if I've run across a bug or not... If I log out for an extended period of time, I come back and my wiring will occasionally be gone. Entirely. Not dropped on the ground or anything, just gone. I realize this mod is supposed to be realistic so I wasn't sure if this was intentional or not, but it's starting to get slightly frustrating having to replace my connections every 2-3 times that I log into a world. If this is supposed to happen, how might I fix this/what are the wire interactions causing this?

**Comment by theunkn0wn1** [comment] 2015-10-14 04:35
Can we get pictures of your setup please?
What version of IE are you using?
what amounts of RF are you passing through what kind of lines?
 we will need more information in order to determine if it is a software or user error.

**Comment by genthug** [comment] 2015-10-14 05:03
![ie1](https://cloud.githubusercontent.com/assets/15116431/10475191/a6c8e2be-720e-11e5-9114-e93fa5284851.png)
![ie2](https://cloud.githubusercontent.com/assets/15116431/10475196/ab2e292c-720e-11e5-8ae5-b206515b8135.png)
![ie3](https://cloud.githubusercontent.com/assets/15116431/10475200/aed0f9a6-720e-11e5-991d-ae4c9e9b814f.png)
Immersive Engineering 0.5.4
I am not sure how to tell exactly how much RF/tick I'm passing through the wires but the fisher takes 20RF/tick and is constantly stocked, my MineChem machines are not running at 1096RF/tick with the MV connectors/electrum wires, it runs about 2000RF per second, so not even close. The MFR Harvester I believe takes up the whole chunk of 1096/t when it's running on full chopping down trees, as it never drops in RF unless the capacitor attached to it runs out of energy. All of the wires (save for the fishery wiring) that run to my machines are MV, with MV capacitors. The wires running from my energy generation to the capacitors and to the fishery are LV wires. I've had to replace every single wire that I've put down at least once, usually fairly soon after I've placed it.
Does that suffice or is there more needed?

**Comment by theunkn0wn1** [comment] 2015-10-14 05:37
Hm.. so 0.5.4 and earlier has a known bug, documented well in #461. A world-save corruption bug (affecting IE only as far as I can tell) exists where wires will randomly fail to be correctly loaded by IE and thus they disappear. I would suggest updating to the latest 0.6.0_pre builds as they have resolved this particular bug among adding new features :3
iirc MV can carry up to 2048 Rf/t/c in 0.5.4 and earlier, you might want to move your minechem machines to their own circuit Hv circuit as soon as you can as they chew through quite the power load when active.
HV can carry up to 4096 Rf/T/c in 0.5.4 and earlier. (default values)

Other than that, i see no reason your setup would keep breaking.

**Comment by genthug** [comment] 2015-10-14 05:44
Alright, will do! Thank you very much!

**Comment by theunkn0wn1** [comment] 2015-10-14 05:56
No problem, its not hard to compile IE from its source :3

though it will be a while yet before 0.6 hits release ;3

**Comment by Moustik2002** [comment] 2015-10-14 13:14
Hi, i've encountered the same isue on my World. Unfortunately, i'm not able to find where latest 0.6.0_pre builds are hosted. Any tips to put me in the right direction ?

**Comment by BluSunrize** [comment] 2015-10-14 13:15
No, because there are no 0.6-pre builds. Only builds made from this git are labelled that.
That being said, it's release is not far off now.

**Comment by Moustik2002** [comment] 2015-11-01 21:20
Hello Again, Any news about Wiring fix ?

**Comment by theunkn0wn1** [comment] 2015-11-01 21:27
the root cause of your issue,if it is as i have stated above, has been fixed in 0.6.x builds.
@BluSunrize plans to release 0.6 within really soon (today or next few days) provided no major issues materialize.

**Comment by cobra** [comment] 2015-11-01 23:39
0.6 is out now!

**Comment by theunkn0wn1** [comment] 2015-11-01 23:47
0.o When did the release to Curse occur? 
@BluSunrize, Can we get a Github release as well please?

**Comment by cobra** [comment] 2015-11-01 23:52
half an hour ago.

**Comment by BluSunrize** [comment] 2015-11-02 15:21
Yeah I meant to do a release here last night, I just blanked. Done now ^^

**Comment by Moustik2002** [comment] 2015-11-11 02:42
Hello, obviously wiring still have issue with release #0.6.1. Since i've rebooted my modpack, LV wires have disappeared. :'(

**Comment by theunkn0wn1** [comment] 2015-11-11 02:44
0.o

you sure you haven't overloaded them? their capacitance is no longer unlimited since 0.6

Please remind me, what modpack (if any) are you using?

**Comment by Moustik2002** [comment] 2015-11-11 02:47
iIt is a custom pack compiled by myself. It is strange because the only thing powered by the missing lv wires was a crusher. the source of power is a P2P RF Tunnel form AE2. Do i have done something wrong ?

**Comment by theunkn0wn1** [comment] 2015-11-11 02:50
Well, the P2P/transparent bug was fixed well before 0.6 was released. Do you have ChickenChunks mounted?

Can we please get a few pictures of the setup and a modlist with version numbers?

**Comment by Moustik2002** [comment] 2015-11-11 02:58
ChunkLoading is performed by Immibis Dimensional Anchor. You'll find the mod list in the following Puush:

http://puu.sh/lhaTw/17da196d26.png

And my installation where the wires are M.I.A :)

http://puu.sh/lhaZt/1e022ef7d6.jpg

**Comment by cobra** [comment] 2015-11-13 13:28
What is powering the other end of the P2P RF tunnel?

I just tested your setup with a crusher and then even used the "evil" cryo-stabilized fluxduct with a creative energy cell on the input end and dumped all the energy into an ExU energy trashcan at the output. Nothing is breaking, no wires are disappearing. Could you please tear down the affected connectors and replace and rewire them? If you still have issues, please post screenshots of the whole setup: RF generation, input P2P tunnel, output P2P tunnel and RF consumption. Use the latest IE version 0.6.1 if possible - there shouldn't have been any energy changes from 0.6.0, but using the latest version makes things a bit easier to debug.

**Comment by Moustik2002** [comment] 2015-11-13 15:06
I will post screenshot of my installation, meanwhile just a word about what happens. There is no fried wires at all, just disapeared ones each time server is rebooted.

**Comment by Alaberti** [comment] 2015-12-02 07:28
I also had a similar issue, only with the decorative steel wires vanishing after a world restart. They were only being used to skyhook around. Nothing remotely fancy. There is a chickenchunks chunkloader in the area with them. This is on 0.6.1 on a functional dedicated server.

**Comment by Moustik2002** [comment] 2015-12-02 15:25
Glad to see i'm not the only one :)

**Comment by theunkn0wn1** [comment] 2015-12-02 16:05
There is a known incompatibility with chickenChunks. Wires can disappear in
both ssp and dedicated server instances during world reload on chunks force
loaded by a chickenChunk chunk loader. See #589

**Closed** 2017-05-12 10:20 UTC
