### ISSUE TITLE
[1.15.2] [0.15-105 #10] Buzzsaw modification disappear after adding blade or a shader

### ISSUE THREAD

**Issue by Fakeowo** [BluSunrize/ImmersiveEngineering#4024] opened 2020-06-23 13:57 UTC
### Description of the issue:
As mentioned in the title, Buzzsaw modification disappear after adding or removing any blade or a shader, but the modifications still are with the buzzsaw after placing it again in the engineer workbench.

Screenshots:
https://imgur.com/a/IWLOBlR

### Versions & Modlist
forge-1.15.2-31.2.20
ImmersiveEngineering-0.15-105-a2b2b71a

Other mods:
https://pastebin.com/rXCuMbP3

**Comment by BluSunrize** [comment] 2020-06-28 13:37
Can't reproduce this. Probably related to other issues with the workbench.
This is quite potentially fixed by Malte's recent work on it.
See if you can reproduce this on the latest Jenkins build.

**Comment by Mohl97** [comment] 2020-08-04 20:30
I'm having a similar issue, except that this only occurs when playing on a dedicated server (though fakeowo didn't specify if their problem was singleplayer or not). Went looking through and from my horribly uneducated guess it looks a good deal like #2587, although that was  fixed in 2017.

**Closed as completed** 2020-11-04 12:06 UTC
