### ISSUE TITLE
Gun Turret does not save cartridges stored in it when exiting game and reloading.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#2009] opened 2017-04-11 00:14 UTC
IE 0,.10.57
MC 1.10.2

Start a single player game, place a Gun Turret, put some cartridges in it, exit the game.

Start the saved game again, check Gun Turret, no cartridges. Seems like that info is not being saved.

**Comment by malte0811** [comment] 2017-04-11 05:18
Duplicate of #1978, the fix will be included in the next release.

**Comment by BluSunrize** [comment] 2017-04-11 06:03
^ this

**Closed by BluSunrize** 2017-04-11 06:03 UTC

**Comment by calloatti** [comment] 2017-04-11 11:08
I searched for Gun Turret and did not find it. Any ETA on new release?

**Comment by BluSunrize** [comment] 2017-04-11 11:39
it gets released when I'm not teetering on the edge of modding burnout. Check twitter for details.
