### ISSUE TITLE
Version 6.0 is crashing with foresty.

### ISSUE THREAD

**Issue by mostwanted12354** [BluSunrize/ImmersiveEngineering#598] opened 2015-11-05 04:45 UTC
I was updating this in my pack and when i loaded up with the new v0.6.0 I receive this crash log. once I downgrade Immersive Enineering back to v0.5.4 everything boots and runs perfectly. Here is the paste bin for it.

http://pastebin.com/E2Rtyyuq

i have the most recent version of Forestry v3. so not sure what exactly the issue is.
Thanks

**Comment by theunkn0wn1** [comment] 2015-11-05 04:52
there is your problem.. Ie is built against Forestry 4. Disable forestry compat or update Forestry.

Duplicate of #559 and others...

**Closed** 2015-11-05 07:54 UTC
