### ISSUE TITLE
[1.14] Issues with the feed-through connector entry on the Engineer's Manual

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4006] opened 2020-06-18 17:33 UTC
### Description of the issue:
In the said page, under "Basic Wiring", of the Manual there's an animation on how to form them which if stopped, will display a pink and black pattern.
Also, hovering to get the tooltip for the list of ingredients, displays a code variable instead of the actual name for a block.
![2020-06-18_18 32 45](https://user-images.githubusercontent.com/52493793/85053298-2efe9800-b192-11ea-954e-07afc0a6be6e.png)
### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.102

**Comment by BluSunrize** [comment] 2020-06-28 09:08
Can't reproduce this in my current version

**Comment by malte0811** [comment] 2020-06-28 14:02
> Can't reproduce this in my current version

The description isn't ideal, but the missing model is there for me. It's not about stopping the animation, it's showing the formed multiblock that causes it, since the feedthrough item currently doesn't have a model. I'll look into it later if you haven't fixed it by that point.

The translation issue is fixed already.

**Comment by BluSunrize** [comment] 2020-06-28 14:26
I'll assign this one to you, Malte, I've moved over to 1.15 to fix the shield render and merge in the 1.14 work I've done so far

**Closed as completed** 2020-06-28 15:59 UTC
