### ISSUE TITLE
[1.16.5] [Minecolonies Official Modpack v3.5] Posts are rendering very oddly

### ISSUE THREAD

**Issue by Vekzie** [BluSunrize/ImmersiveEngineering#5087] opened 2021-11-26 00:31 UTC
I have not see any posts quite like this one. I saw the post about posts rendering incorrectly under y 64 or so, but that doesn't seem to be the case for me since I tested in different y-levels, and my rendering bug? glitch? whatever it is doesn't look like them. 

The issue: 

### Description of the issue:
Soon after I place any form of post, wooden, steel, aluminum,  they'll get a bunch of .. notches? As if it's trying to show every possible connection at once or something. Here's a screenshot of what I mean, https://imgur.com/gallery/Mn94P6s
it doesn't matter if I have anything placed on it or not, though in the screenshot the wooden post does show a relay on it, it still shows up like that without anything on it at all, and even if I don't extend out the 'arm' at the top of the post as well. The good news is that this doesn't seem to affect anything mechanically, only visually. This -does- happen both single player and multiplayer for me. I noticed one of the mods in the modpack (posted in the title) is on your list of what may cause problems, performant. Is that the cause?

### Crashlog:
I'm not having any crashes so there isn't really any problem here.

### Versions & Modlist
Here is a link to what i'm using, https://www.curseforge.com/minecraft/modpacks/minecolonies-testpack/files/3504496
Though, it might be better to search "Minecolonies Official" on the curseforge desktop app, since that's specifically where I got the pack.

**Comment by malte0811** [comment] 2021-11-26 06:00
Duplicate of #5069, fixed for the next release. It's an interaction with xaero's world map, I assume they changed something recently since the relevant code did not change on our end.

**Closed as completed by malte0811** 2021-11-26 06:00 UTC
