### ISSUE TITLE
1.12.2 Crash when trying to disassemble Automated Workbench

### ISSUE THREAD

**Issue by Xenos13** [BluSunrize/ImmersiveEngineering#2585] opened 2017-10-31 11:05 UTC
When I try to disassemble this device, the game crashes with the report about illegal conveyor facing:

Description: Tesselating block model
java.lang.IllegalStateException: Unable to get CCW facing of down
Block: immersiveengineering:conveyor[facing=down,type=conveyor]

The only decision I have found is 4 TNTs above 4 conveyors)

MC 1.12.2
Forge 2515
IE 0.12-74
CTM-MC1.12-0.2.3.9

**Comment by malte0811** [comment] 2017-10-31 14:40
Duplicate of #2560 and some others.
Should be fixed for the next release. For future reports please include a full crashlog on pastebin/gist, not just the first line.

**Closed by malte0811** 2017-10-31 14:40 UTC
