### ISSUE TITLE
[1.10.2] crash while crafting the voltimeter

### ISSUE THREAD

**Issue by ZeroNoRyouki** [BluSunrize/ImmersiveEngineering#1599] opened 2016-10-16 13:42 UTC
http://pastebin.com/TYanpdi4

http://pastebin.com/C14EwEVW

I've just tried to craft the voltimer in a vanilla crafting table with IE 0.10-44

Z

**Comment by malte0811** [comment] 2016-10-16 13:55
Duplicate of #1549 and a ton of other issues, please search for existing reports before posting.

**Comment by BluSunrize** [comment] 2016-10-16 13:58
^ what he said

**Closed by BluSunrize** 2016-10-16 13:58 UTC
