### ISSUE TITLE
[1.8.9] Waila info window makes cables invisible.

### ISSUE THREAD

**Issue by DestinyPlayer** [BluSunrize/ImmersiveEngineering#1130] opened 2016-05-15 13:15 UTC
Waila-1.6.0-B3_1.8.8
Wawla-1.8.9-1.1.4.171
ImmersiveEngineering-0.8-26

Basically that. When Waila's block info window appears, all IE cables become transparent.

Here's a video of that bug in action.
https://www.youtube.com/watch?v=olpJMwEjkXg

**Comment by malte0811** [comment] 2016-05-15 15:40
This is probably a waila bug, I'll look at their code to try to understand what is going on. The bug is not (really) caused by my new wire rendering system, HV relays show a similar bug with both the current version and the initial 1.8 version. It seems like this only affects static rendering, the old TESR wires did not have this problem.

**Comment by malte0811** [comment] 2016-05-15 18:59
I have found a way for WAILA to fix this and have explained it [here](https://bitbucket.org/ProfMobius/waila/issues/260/189-waila-info-window-makes-ie-cables). This bug will probably be fixed in the next release of WAILA, IE can't really do anything about this without either using a TESR (which would cause performance issues) or ASMing into WAILA which is a possibility I don't even want to think of.

**Comment by DestinyPlayer** [comment] 2016-05-15 21:02
Thanks! I guess I was right in posting this bug in both mods' issues after all. I hope.

**Closed** 2016-05-22 08:14 UTC
