### ISSUE TITLE
1.12.2 External Heater Not Rendering With CTM Installed

### ISSUE THREAD

**Issue by Laton95** [BluSunrize/ImmersiveEngineering#2577] opened 2017-10-24 05:04 UTC
### Description of the issue:
The external heater block is not rendering when placed, it is still visible in the hand. This only occurs when the Connected Textures Mod is installed, although even without this mod the sides of the heater are rendered black though still visible.

### Versions & Modlist
Minecraft Version 1.12.2
Forge 1.12.2-14.23.0.2512
IE 0.12-74
CTM MC1.12-0.2.3.9

**Comment by malte0811** [comment] 2017-10-24 05:19
Duplicate of #2552.

**Closed by malte0811** 2017-10-24 05:19 UTC

**Comment by Xenos13** [comment] 2017-10-31 10:25
Bug is still actual.
With CTM installed, heater has no textures, looks transparent.
Without CTM, only connector side looks correctly, other sides are black (or orange if working).
I use CTM and I tried to edit some files in /assets/immersiveengineering/textures/blocks/
I removed lines "layer":"CUTOUT" from 3 files:
metal_device1_furnace_heater.png.mcmeta,
metal_device1_furnace_heater_active.png.mcmeta,
metal_device1_furnace_heater_socket.png.mcmeta
Now heaters look fine.

**Comment by Duqino** [comment] 2017-11-01 19:53
Looks like this bug is not yet fixed 

[![Screenshot from Gyazo](https://gyazo.com/5dc7daffe7e2e2c2ec3b88385be6bb54/raw)](https://gyazo.com/5dc7daffe7e2e2c2ec3b88385be6bb54)

The server is running version Immersive Engineering 0.12 - 74

[![Screenshot from Gyazo](https://gyazo.com/eb23f3f34afec637af9c900350dcedbb/raw)](https://gyazo.com/eb23f3f34afec637af9c900350dcedbb)

**Comment by malte0811** [comment] 2017-11-01 20:10
@Xenos13 Duplicate doesn't mean that it isn't an actual bug. Duplicate means that someone else reported the issue before and that any news/discussion on the bug will be on the other report. And if the other report is closed, it usually means that the bug has been fixed, but it doesn't mean that there are builds on Curse that contain the bugfix.
@Duqino I never said it was fixed in 0.12-74, that's the version it was reported in. It is fixed for the next release (0.12-75). Don't ask when that will be, both @BluSunrize and I are a bit busy with Uni and live right now.

**Comment by Duqino** [comment] 2017-11-01 20:51
Maybe a hot fix ?

**Comment by BluSunrize** [comment] 2017-11-02 08:09
I'm going to release it when I have time for it. Badgering either of us doesn't help.

**Comment by Duqino** [comment] 2017-11-02 10:47
I dont wanna be a ass. Just asking. Because i cant use the item.
