### ISSUE TITLE
Crashing and rendering issues with the Red Orchid from EU2

### ISSUE THREAD

**Issue by MardiGraskid** [BluSunrize/ImmersiveEngineering#2172] opened 2017-06-13 06:48 UTC
I attempted to place a red orchid in the garden cloche to hopefully farm some redstone, only to find out that it crashes my client due to rendering issues, and it does the same for anyone who gets close to it.

**Comment by malte0811** [comment] 2017-06-13 06:53
Duplicate of #2071.
Update Immersive Engineering. @BluSunrize published a new build (for 1.10) 9 hours ago, that should have a fix for your crash. If you're on 1.11 (which I don't think) also update IE, this has been fixed for 1.11 quite long ago.

**Closed by malte0811** 2017-06-13 06:53 UTC

**Comment by MardiGraskid** [comment] 2017-06-13 07:00
Thank you, kind sir!
