### ISSUE TITLE
HV Relays Only Support a Single Connection

### ISSUE THREAD

**Issue by CJL48** [BluSunrize/ImmersiveEngineering#1097] opened 2016-05-05 20:34 UTC
HV Relays in 0.8-23 only support a single connected wire. This makes high voltage wiring...difficult. Hv transformers seem to be suffering from a similar issue, I'll post more information after testing.
![2016-05-05_16 28 18](https://cloud.githubusercontent.com/assets/8433790/15056332/06932fa8-12df-11e6-8991-485be4e33f64.png)
Forge 11.15.1.1764

**Comment by BluSunrize** [comment] 2016-05-05 20:47
I can't replicate this .-.

**Comment by CJL48** [comment] 2016-05-06 01:28
...I thought that it might have been a mod compat thing, but no, the bug is still present in an instance with IE as the only mod installed (other than forge, obviously). Can anybody else try and replicate the bug? It's been pretty consistent for me- I can't connect more than one hv wire to the hv relays at all.

**Comment by XFactHD** [comment] 2016-05-06 02:10
Can you reproduce this if the HV relay is hanging down for a post?

**Comment by malte0811** [comment] 2016-05-06 04:41
@BluSunrize you can't replicate it because I fixed it :)

**Comment by BluSunrize** [comment] 2016-05-06 06:01
fair point. Fixed in the latest release then.

**Closed by BluSunrize** 2016-05-06 06:01 UTC
