### ISSUE TITLE
[1.12.1] Chute Glitch on SMP on FTB Revelations 3.2.0

### ISSUE THREAD

**Issue by Meserion** [BluSunrize/ImmersiveEngineering#3580] opened 2019-10-08 06:17 UTC
Initially placing Chutes in Multiplayer works fine, can be adjusted as work as intended. However, upon relogging the Chutes seem to glitch out losing both functionality and their appearance. Issue seems to only be in multiplayer, on creative singleplayer the chutes work fine. I've only tested Iron Sheetmetal Chutes.

I will note when placing the Chutes it seems to, "refund", the chutes placed as though they where not placed at all.  

![image](https://user-images.githubusercontent.com/56290582/66371348-e3dc8600-e970-11e9-8194-70f61fadfc0c.png)

**Comment by Halo3fanz** [comment] 2019-10-09 11:11
I am also getting this issue on 0.12-92 in multiplayer except that the functionality is not present at all after placement. Breaking the chutes yields the broken conveyor belts shown in the photo by OP as an item with the name

> tile.immersiveengineering.conveyor..name

**Comment by BluSunrize** [comment] 2019-10-09 17:30
FTB Revelations is using an outdated version of IE, this bug was fixed in build 92.

@Halo3fanz are you sure that you are running that version on client and server, and the chutes were placed *after* updating to 92? Because the bug should be gone.

**Comment by Halo3fanz** [comment] 2019-10-10 12:06
@BluSunrize I have confirmed with the server host that it is 0.12-92. FWIW we upgraded from 0.12-89 straight to 0.12-92 while chutes were added in 0.12-90 according to the changelog. I crafted the chutes after the upgrade.

**Comment by Jordanb716** [comment] 2019-10-18 00:23
I'm getting a similar glitch, running 0.12-92 on client and server, When I place a steel chute and break it instead of giving the chute item it gives a "tile.immersiveengineering.conveyor..name" item, with a conveyor belt icon. When I place that item it looks like that purple and black tiled item in the picture.

**Closed** 2019-10-27 18:45 UTC

**Comment by Gunner76th** [comment] 2020-03-29 08:09
@malte0811 I see where you closed this issue back on October 27 2019 with commit 67c74c2, however the version on Curseforge has not been updated since September 2019 and is still version 92. Is there any plans to push the update for the chute fix,  or is IE for 1.12.2 dead as far as updates go? I ask since this was reported,  fixed,  committed,  and closed 5 months ago,  with no update having been posted to Curseforge.
