### ISSUE TITLE
[1.17.1] HOP Graphite JEI

### ISSUE THREAD

**Issue by JStocke12** [BluSunrize/ImmersiveEngineering#4961] opened 2021-09-07 22:25 UTC
In 1.17.1, JEI displays the squeezer recipe as blank when viewed from the products of coke dust, and fails to find the recipe when looking for HOP Graphite dust recipes.

![2021-09-07_18 25 08](https://user-images.githubusercontent.com/56052177/132418317-a076f30f-33be-43d2-9f68-cb2f35f54339.png)

**Comment by BluSunrize** [comment] 2021-09-08 06:05
Duplicate of #4954

**Closed as completed by BluSunrize** 2021-09-08 06:05 UTC
