### ISSUE TITLE
[1.12.2] Wire Connector Crash

### ISSUE THREAD

**Issue by MasterEnderman** [BluSunrize/ImmersiveEngineering#3022] opened 2018-05-31 06:39 UTC
### Description of the issue:
If you place or break a wire connector the game crashes.

### Crashlog:
https://paste.dimdev.org/elijivonec.txt

### Versions & Modlist
Forge: 14.23.4.2705
Immersive Engineering: 0.12.83.396 (latest version on the maven)

Modlist: https://pastebin.com/8Lqktp2V

**Comment by mindforger** [comment] 2018-05-31 12:18
try it without optifine it is part of the stacktrace

**Comment by MasterEnderman** [comment] 2018-05-31 13:00
Sure here is it without Optifine:

https://paste.dimdev.org/cedeporewo.txt

**Comment by mindforger** [comment] 2018-05-31 13:12
thx, because now blu can trace it better

**Comment by malte0811** [comment] 2018-05-31 19:46
Just to get this clear: To replicate the crash, you start the client, join a multiplayer/dedicated server without joining a singleplayer world first and immediately break the connector (without flying a large distance from it and back first)? Could you post some screenshots of the setup (the connectors right before you break them)? The code involved has a few issues, but none that should cause this (fixing the crash itself would be trivial, but the situation that is the root cause shouldn't ever happen).

**Comment by MasterEnderman** [comment] 2018-06-01 07:06
I made a Modpack and have it tested by a few people on a server. The crash report was send to me by one of them. He replicated it multiple times by joining directly on the server without joining a singleplayer first, flew over to his water wheels and by breaking a connector his game crashes. He tried different connectors in his base, but all of them are causing a crash. But i looks like it only happens with the connectors in his base, because other testers don't have a problem with breaking or placing a connector in there base.

**Comment by malte0811** [comment] 2018-06-01 21:29
I'm unreliable today, and I didn't even notice. This should be fixed in the latest maven builds (CF build will come at some future time), the relevant commit is 4d6a391764027fc12abf2b8a57ce3f5d5ae627a7. I was going to give you a debug build that would have given a more useful crash, but when I was just messing around after checking that the debug build worked I accidentally triggered the crash myself.

**Closed by malte0811** 2018-06-01 21:29 UTC
