### ISSUE TITLE
"Client crash when looking how to make lightning rod in manual"

### ISSUE THREAD

**Issue by tekman123** [BluSunrize/ImmersiveEngineering#1750] opened 2016-11-28 23:35 UTC
Client crashes to desktop when opening the engineering manual to look up how to make the lightning rod and the Arc Furnace.  Does the same thing when other players open it as well.

[crash-2016-11-28_16.39.08-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/617746/crash-2016-11-28_16.39.08-client.txt)

**Comment by Cloudhunter** [comment] 2016-11-28 23:36
Can confirm, happened on the AwarenessCraft community server. If you need anything else feel free to poke me on slack ;)

**Comment by BluSunrize** [comment] 2016-11-29 06:18
Hi Cloudy!

What I need is for people to use the search function, as asked by the contribution guidelines that noone reads.
This is a duplicate of #1704, which has been fixed already.
Wish github had a pinning function for reports because this is like the 12th I've gotten.

**Closed by BluSunrize** 2016-11-29 06:18 UTC

**Comment by mindforger** [comment] 2016-11-29 07:12
you could probably propose a pinning funtion to the github devs :)

**Comment by Cloudhunter** [comment] 2016-11-29 17:12
I forgot to search and I am a derp face :D Thank you, @BluSunrize

**Comment by BluSunrize** [comment] 2016-11-29 18:34
I called you something considerably more rude on slack, but yeah, let's go with that :D
