### ISSUE TITLE
support for IC2 Uranium and TechReborn Bauxite

### ISSUE THREAD

**Issue by Hypsellis** [BluSunrize/ImmersiveEngineering#1406] opened 2016-09-08 09:04 UTC
It seems that the Uranium from IC2 can't be melted into Uranium ingot like the ImmersiveEngineering one, I don't think it's the only bug of compatibility between the two ores. It happens exactly the same thing with the Bauxite of TechReborn which can't be melted into Aluminium.

**Comment by mindforger** [comment] 2016-09-08 09:29
i don't see a bug here, the feature you describe is Ore Dictionary, ores and ingots are registered via common defined names and almost all mods use this dictionary to check wheter an ore can be smelted or not and also if the ingredient can be replaced by some foreign mod counterpart .. so i don't understand exactly what the issue is.

**Comment by mindforger** [comment] 2016-09-08 09:31
i totally misunderstood your issue on the first glance ... 
can you povide us which versions you are running?

**Comment by Hypsellis** [comment] 2016-09-08 09:37
The last one, the 40, but the version doesn't change anything. 
And it's pretty simple to understand, the Uranium from IC2 and Bauxite from TechReborn aren't totally compatible with their counterpart from ImmersiveEngineering. Some recipes misses in both cases, notably the melting recipes. The IC2 Uranium can't be melted into Uranium ingot, and TechReborn Bauxite can't be melted into Aluminium.

**Comment by kane-thornwyrd** [comment] 2016-09-08 09:43
Some devs from IC² and TR may have considered adding these to their respective ore dictionary entries may be harmful for the balance of their mod… I'm not sure, it's just a guesswork.

**Comment by Hypsellis** [comment] 2016-09-08 10:01
I'm not sure neither, but it doesn't seem to come from the ore dictionnary because the ores are registered inside because a big part of recipes work with both versions of the ores. The problem seems a bit more complex. 
Anyway I never understood modder who don't add their ores into ore dictionnary for "the balance" of their mod. It always made me laugh so much it's stupid. There aren't any problems of balance when the mod is standalone. And it will unbalance even more all the mods if they refuse to register their ores because it won't have more continuity and compability between them. It's for preventing that all the kinds of one same ore are totally incompatible, because everybody use only type of the same ore from one particular mod in the world generation for preventing the duplications, and use it in all the recipes of all the mods which interact with this ore in particular. It's why the ore dictionnary has been created.

**Comment by BluSunrize** [comment] 2016-09-08 10:53
So how does TechReborns Bauxite work? Does it need special smelting, to get Aluminium Ingots?
Because Furnace Recipes are never oredicted. So if you smelt a mod's ore, you get that mod's results. IC2 ores turn into IC2's uranium clumps, knobs, whatever they are. As for TechReborn: I have not the slightest how their ore is processed.

This is not really a compat issue, but more a "those two mods are working as intended"
If TR includes Aluminium Ingots and /they/ are not compatible, /then/ we have a problem.

**Comment by modmuss50** [comment] 2016-09-08 14:06
When I get power back, I will look into this. I forget how bauxite is used in TR off the top of my head.

**Comment by modmuss50** [comment] 2016-09-08 14:07
But as a rule all of our ores should be in the ore dic

**Comment by modmuss50** [comment] 2016-09-08 20:34
Ok, so we do have an issue:

Our bauxite is used in an industrial grinder(Mid-Game multiblock), to make 2 bauxite dust, 4x Small Pile of Grossular Dust and 4 Pieces of Small Pile of Titanium dust. So no aluminum.

In FTB Inventions your bauxite was renamed to aluminum ore, but this wouldnt be a great overall fix for this. 

We could rename our ore when your mod is installed. 

If you can think of a better way to fix this, I would love to hear it.

**Comment by BluSunrize** [comment] 2016-09-08 20:36
Is Bauxite Dust not oredicted to "dustAluminum" then? I assume you have more complex processing?
I mean that's fine by me, and personally I don't mind users having to deal with this issue. but I will absolutely not rename my ore, and I would encourage you to not do so either. There is no Aluminium Ore, and the fact that FTB inventions does that is a blatant mistake on the pack developers side.
I'd say we just roll with it!

**Comment by modmuss50** [comment] 2016-09-08 20:37
I agree, and I dont like renaming things.

Close the issue and be done with it, I have more important things to be doing.

**Comment by Hypsellis** [comment] 2016-09-08 21:51
I suppose that for the Bauxite it's not really important since the TechReborn Bauxite isn't registered as Alumium and isn't used for getting Aluminium but Titanium. But for Uranium with IC2, it's pretty annoying that it can't melted into Uranium ingot like its ImmersiveEngineering counterpart.

**Comment by BluSunrize** [comment] 2016-09-09 05:16
Because Aluminium is never really found as an ore. Bauxite contains both Aluminium and Titanium, hence why two different mods use it for a source of those metals.
The Uranium thing is something you can gladly take up with the IC2 team, it was their choice not to add ingots, and I can't do anything about that.

Issue closed.

**Closed by BluSunrize** 2016-09-09 05:16 UTC

**Comment by Hypsellis** [comment] 2016-09-10 12:15
For the Uranium compatibility problem, I reported it on the IC2 issue tracker. http://bt.industrial-craft.net/view.php?id=1996
