### ISSUE TITLE
[1.15.2] Sync List crashing dedicated server

### ISSUE THREAD

**Issue by kreezxil** [BluSunrize/ImmersiveEngineering#4308] opened 2020-09-19 15:25 UTC
### Before reporting:
- [x] searched for sync list error
- [x] gave a descriptive title

### Description of the issue:
I've asked my players what they are doing and i've got nothing other than "we got some ore from it in our bases"

### From Console, likely related (spamming too, in the latest.log below):
```
[19Sep2020 10:13:32.605] [Server-Worker-16/WARN] [com.mojang.datafixers.types.templates.TaggedChoice/]: Unsupported key: immersiveengineering:shaderbanner in TaggedChoiceType[id, minecraft:shulker_bo
x -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:mob_spawner -> MuType[V1931_4], 
minecraft:dispenser -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:jigsaw -> NilSave, 
minecraft:end_gateway -> NilSave, 
minecraft:bell -> NilSave, 
minecraft:smoker -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:furnace -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:jukebox -> ((Tag["RecordItem", MuType[V1931_3]] | NilDrop), NilSave), 
minecraft:ender_chest -> NilSave, 
minecraft:comparator -> NilSave, 
minecraft:hopper -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:beacon -> NilSave, 
minecraft:end_portal -> NilSave, 
minecraft:bed -> NilSave, 
minecraft:brewing_stand -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:lectern -> ((Tag["Book", MuType[V1931_3]] | NilDrop), NilSave), 
minecraft:enchanting_table -> NilSave, 
minecraft:barrel -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:sign -> NilSave, 
minecraft:conduit -> NilSave, 
minecraft:banner -> NilSave, 
minecraft:campfire -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
DUMMY -> NilSave, 
minecraft:piston -> ((Tag["blockState", NamedType["block_state", NilSave]] | NilDrop), NilSave), 
minecraft:structure_block -> NilSave, 
minecraft:trapped_chest -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:dropper -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:skull -> NilSave, 
minecraft:chest -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave), 
minecraft:command_block -> NilSave, 
minecraft:daylight_detector -> NilSave, 
minecraft:blast_furnace -> ((Tag["Items", List[MuType[V1931_3]]] | NilDrop), NilSave)]
```

### Crashlog:
[server crash report](https://gist.github.com/6de47cdea5b0a77b237259f1f145a3e8)

### Latest Log from Server:
[latest.log](https://gist.github.com/4e3e12e8cfc47e1f092b629c891c174c)

### Versions & Modlist
- **IE**: 1.15.2-4.0.0-117
- **FORGE**: 1.15.2-31.2.41

[Modlist with versions](https://gist.github.com/e34383497f1e4207a3df68ea130c8bd5)

**Comment by malte0811** [comment] 2020-09-19 15:35
The console extract you posted is not related to the crash, it's normal. I may look into fixing that at some point, but it's related to [DFU](https://github.com/Mojang/DataFixerUpper), which means it's probably not fixable.

The crash doesn't really point to any specific mod. I know of one cause of this crash in 1.12 (a vanilla bug), but that's fixed in 1.15. I'm going to close this issue, if you have more evidence that the crash is caused by IE in some way please put it here as a comment.

**Closed as completed by malte0811** 2020-09-19 15:35 UTC
