### ISSUE TITLE
not sure if this is a bug or not (mc version 1.12.1 IE version 0.12.72

### ISSUE THREAD

**Issue by CharCharthemonkey** [BluSunrize/ImmersiveEngineering#2512] opened 2017-09-18 22:50 UTC
![zeldo 20](https://user-images.githubusercontent.com/30783285/30568266-cb64a1d2-9c99-11e7-8879-0783449d34d9.JPG)
![zeldo 21](https://user-images.githubusercontent.com/30783285/30568270-d25f4578-9c99-11e7-8c62-f5d5198c3cb4.JPG)
the top one shows for 1.12.1 the bottom is 1.12 where i coppied the mdos from so umm is this a bug or new feature?

**Comment by KnightMiner** [comment] 2017-09-18 23:09
Duplicate of #2509 and many others. It is simply the Forge convention for distributing core mods and many mods launchers have not updated to support that yet.

**Closed** 2017-09-18 23:16 UTC
