### ISSUE TITLE
HV Wiring loses damaging capability after a while (+suggestion) [v0.12-89]

### ISSUE THREAD

**Issue by YoItSoul** [BluSunrize/ImmersiveEngineering#3538] opened 2019-08-16 13:52 UTC
So, there I was, finished building a proper high powered wiring electric fence...

Everything worked %100 okay - mobs, as well as myself, went flying every time they touched the fence. But after a while, I noticed that any mob could walk through it unscathed! I went to check the input of the wire, fine, had full power, but the receiving HV Connector had 0% power held in it, whilst the capacitor it was attached to was actively supplying and receiving power.

Yes, I checked the config, and yes, wires still have their killing capabilities.
Yes, replacing the wires/connectors fixes the issue, but only for about 30 minutes before everything goes dead again. Let me know if I'm missing something :/

---

!%Suggestion: Players that are in water/are wet after leaving water (or getting sprayed by a chem turret) receive more damage when being electrocuted (via wires, or tesla coils).

---

![2019-08-16_23 35 47](https://user-images.githubusercontent.com/54139289/63172033-1f995480-c080-11e9-88a1-f5ff3f56fb59.png)  -- Me standing like an idiot inside of a fully powered HV wire, without harm.
![2019-08-16_23 35 38](https://user-images.githubusercontent.com/54139289/63172034-2031eb00-c080-11e9-89df-cf51efef546d.png)-- Receiving end capacitor not receiving "ghost" power

**Comment by BluSunrize** [comment] 2019-08-16 13:58
Receiving connectors always have 0 in them. That's a buffer to send with, not receive.

Where is the power from your fence going?

**Comment by YoItSoul** [comment] 2019-08-16 14:00
To other HV capacitors and a couple of tesla coils.
![2019-08-16_23 59 50](https://user-images.githubusercontent.com/54139289/63172889-0c878400-c082-11e9-96c8-a40bb86af977.png)

**Comment by BluSunrize** [comment] 2019-08-16 14:48
Now I may be misremembering but I believe the damage done by wires is dependent on what they have been transferring. So unless your Tesla Coils are using a bunch of energy consistently, I don't think this fence idea will work as well.
I need to defer to @malte0811 here (who is currently on holiday and won't be able to respond for a while), he'll need to confirm my assumption.

May I suggest using multiple layers of electrified razor wire in the meantime?

**Comment by YoItSoul** [comment] 2019-08-16 14:52
The tesla coils are typically on High mode and run pretty consistently, but I can do the razor wire idea, that was my alt idea anywho :)

**Comment by malte0811** [comment] 2019-08-16 16:43
> Now I may be misremembering but I believe the damage done by wires is dependent on what they have been transferring. So unless your Tesla Coils are using a bunch of energy consistently, I don't think this fence idea will work as well.

You are misremembering, or I am. Wires are supposed to cause damage based on what sources they're connected to, not on what's being transfered. I'm pretty sure my standard test setup is just a wire and a creative cap.

I'm currently on holiday (as Blu noted), but from a quick glance at the code there isn't any obvious cause. A few questions that may help in narrowing this down: Singleplayer or a dedicated server (or LAN, which would be interesting)? Do you have any IE addons (or other mods that interact with IE wires) installed? Does this affect all wires in the dimension you're in? Maybe build some wires with a capacitor at an outpost to test. Is this triggered by you moving far away from the wiring setup (or any other common cause you can think of)?

**Comment by OLogizO** [comment] 2019-08-22 23:30
you can reproduce this bug if you exit and re-enter the world in single player. 
(freshly placed setup)
https://gyazo.com/823ad8c1f3fb76f7230cde331845f87d
as you can notice everything is working as intended. 
(after re log)
https://gyazo.com/b822a33c8f4224cd58cd852466406d68
as you can see the monsters don't take damage but the lantern is still getting power

this is tested in a mod pack with the following mods.
![image](https://user-images.githubusercontent.com/38345570/63556499-633f0300-c545-11e9-8ada-062726d057f1.png)

hope this helps.

**Comment by malte0811** [comment] 2019-08-23 07:45
This is caused by Immersive Tech. They call a method in IE on startup that should only ever be called by IE because they copied code without understanding what it does. The issue is supposed to be fixed in the latest release of IT, but it looks like the author uploaded a wrong build that still contains the bug.

**Closed by malte0811** 2019-08-23 07:45 UTC
