### ISSUE TITLE
[0.12-81] Wire Cutters Disappear After One Use

### ISSUE THREAD

**Issue by EvilDylan** [BluSunrize/ImmersiveEngineering#2981] opened 2018-05-02 20:27 UTC
### Description of the issue:
When crafted with copper plates to produce copper wires, the wire cutters vanish after just one use. No breaking sound is heard, and before that point the cutters are still shown to have the proper durability. This is true for all plates that can be made into wires.

This only happens with the wire cutters, shears work as intended.
It should be noted that the wire cutters work as intended when used to strip wires from connectors.

Reproduction steps:
1- Place multiple plates in player crafting inventory alongside wire cutters.
2- Click or shift-click the resultant wire.
3- Marvel at the incredible disappearing tool!

### Versions & Modlist
Forge 14.23.3.2672
Immersive Engineering 0.12-81
Immersive Petroleum 1.1.9
Singleplayer & Multiplayer

**Comment by BluSunrize** [comment] 2018-05-02 21:18
Duplicate of #2966, use the search function next time please ^^

**Closed by BluSunrize** 2018-05-02 21:18 UTC

**Comment by EvilDylan** [comment] 2018-05-03 13:48
In my defense, I did--Just forgot to delete the word "is:open".
