### ISSUE TITLE
NPE on-load crash in multiple event handlers

### ISSUE THREAD

**Issue by Baughn** [BluSunrize/ImmersiveEngineering#587] opened 2015-11-04 01:29 UTC
As it says... this is also 0.6.0.

```
[01:25:30] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingSpawnEvent$CheckSpawn@112de422:
java.lang.NullPointerException
        at blusunrize.immersiveengineering.common.EventHandler.onEntitySpawnCheck(EventHandler.java:213) ~[EventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1168_EventHandler_onEntitySpawnCheck_CheckSpawn.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:112) [ForgeEventFactory.class:?]
        at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:169) [aho.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

**Comment by theunkn0wn1** [comment] 2015-11-04 03:00
If this is a crash, can you please pastebin the full crash log and link it here? What exactly did you do to induce this?

**Comment by Baughn** [comment] 2015-11-04 13:58
Right, sorry; it's a crash. I'll get you that particular crash log once I get home today.

Meanwhile, I found another one. It seems to be a general problem affecting several event handlers. I'd bisect it, but the repository doesn't build; expect a bug for that shortly.

Here's the second crash report for you. I don't need to do anything to get this, it crashes almost immediately after loading up the world, or creating a new one.

http://sprunge.us/CiEc

**Comment by mindforger** [comment] 2015-11-04 14:20
looks like "just" a few null checks, but i could not track them down, the CME commit has shifted all lines :P

**Comment by XFactHD** [comment] 2015-11-04 14:27
The crash report mentions the ender teleport event, maybe there is a problem with enderman teleporting into or out of the zone of the flood light.

**Comment by cobra** [comment] 2015-11-04 14:44
*pokes @malte0811*

**Comment by Baughn** [comment] 2015-11-04 14:47
@XFactHD There are no floodlights on the world; in fact this still happens with an entirely empty world.

**Comment by theunkn0wn1** [comment] 2015-11-04 15:13
The source will compile, provided you have all the right deobf libraries in the right place. Just rebuilt IE myself.

**Comment by BluSunrize** [comment] 2015-11-04 15:20
pretty sure that @malte0811 dealt with this already?

**Comment by theunkn0wn1** [comment] 2015-11-04 15:31
Didn't he fix  this in #583 ?

**Comment by malte0811** [comment] 2015-11-04 15:35
I am pretty sure I did not fix this, I experienced this crash with pretty final code, but could not make any sense of that crash. The lines it is crashing on are [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/EventHandler.java#L180) and [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/EventHandler.java#L216) in the new code.

**Comment by mindforger** [comment] 2015-11-04 15:52
@theunkn0wn1 no, this just fixed the concurent modification, this is something unrelated, there are some call chains with prop1.prop2.prop3.prop4.prop5.meth6().prop7 ... where one of them fails .. just a little bit work to fiddle the actual null and skip it

**Comment by theunkn0wn1** [comment] 2015-11-04 15:53
Ah. Sorry for reading out of context, I shall return to lurking ;)

**Comment by cobra** [comment] 2015-11-09 12:27
Can't reproduce with the latest version (3259195ab2ff8b553d530c2602b24d5b0cc2303f). I left a superflat world at night with doDaylightCycle=false running in the background for a while with and without electric lanterns and floodlights, including rain and lots of endermen. Not a single crash. Idea also doesn't see any potential null issues, so I think this has been solved.

**Comment by cobra** [comment] 2015-11-10 00:18
b0bst3r on IRC narrowed it down to immibis microblocks in combination with buildcraft compat and even found a workaround: set B:ImmibisMicroblocks to false to avoid this crash. I'll investigate this tomorrow unless someone else wants to do that before I get to it.

**Comment by b0bst3r** [comment] 2015-11-10 00:59
that config option is in config\buildcraft\compat.cfg

**Comment by cobra** [comment] 2015-11-10 11:08
I'm finally crashing and getting somewhere. Seems like the interdictor object is broken (wtf?!).

**Comment by cobra** [comment] 2015-11-10 12:50
Fix implemented, tested, committed and PR'd. In the meantime, disable Immibis Microblock compatibility in Buildcraft Compat.

**Closed** 2015-11-10 16:20 UTC
