### ISSUE TITLE
IE 0.12-75 crash to load from the forge version 14.23.1.2576 to 14.23.1.2581 at least

### ISSUE THREAD

**Issue by Unsomniaque** [BluSunrize/ImmersiveEngineering#2687] opened 2017-12-23 20:43 UTC
https://gist.github.com/Unsomniaque/a879a215633da2e968c30b576b4a3643
good luck and happy holidays

**Comment by malte0811** [comment] 2017-12-23 20:55
Duplicate of #2672 and a few others. Fixed for the next release, use forge 2575 for now. This is the 4th report of this today.

**Closed by malte0811** 2017-12-23 20:55 UTC
