### ISSUE TITLE
[0.12-77] Blast Furnace, Improved Blast Furnace not creating steel

### ISSUE THREAD

**Issue by Luke616** [BluSunrize/ImmersiveEngineering#2823] opened 2018-02-24 20:16 UTC
### Description of the issue:
When using coal coke and iron in the blast furnace, steel is not created. The fire icon will tick down and coal coke will continue to be consumed but the arrow will never progress and steel is never made. Happens for both iron and iron block steel crafting recipes, and in both the crude blast furnace and improved blast furnace.

### Crashlog:
N/A

### Versions & Modlist
Minecraft ver 1.12.2
Immersive ver 0.12-77
Forge ver 14.23.2.2611

Modlist: Immersive Engineering, JEI

**Comment by malte0811** [comment] 2018-02-24 20:38
Duplicate of #2803. Fixed for build 78.

**Closed by malte0811** 2018-02-24 20:38 UTC
