### ISSUE TITLE
[1.10.2] Hard crash when making Wire Cutters.

### ISSUE THREAD

**Issue by OscarXcore** [BluSunrize/ImmersiveEngineering#1633] opened 2016-10-24 02:28 UTC
The Wire Cutters in IE v0.10-44 hard crash the game when being crafted in a Tinkers Crafting Station. 
http://pastebin.com/TQzGZQZ6 If something can be done about this that would be great! If it has been fixed, please reply with the version that fixed it. Thanks in advance!

**Comment by theunkn0wn1** [comment] 2016-10-24 04:51
Looks like a Duplicate of #1549 and others, please note you are several versions out of date (build 44, current is 47)

**Comment by mindforger** [comment] 2016-10-24 06:03
sorry to bering bold at this but
>If it has been fixed, please reply with the version that fixed it

if you have minimum typing and reading skills, please use the search first before a) posting an issue report about something already solved and b) demanding other to give you advice for which version to use ... the only thing missing was to ask for a download link to make yourself look like a real lazy yerk :(

**Comment by BluSunrize** [comment] 2016-10-24 06:06
I'm inclined to agree with mind here, though I'll phrase it nicer: Next time you have an issue: Make sure you're on the latest version first.

**Closed by BluSunrize** 2016-10-24 06:06 UTC
