### ISSUE TITLE
Client crashed after crusher & other machines duplicate appearance

### ISSUE THREAD

**Issue by SpartanSamuel** [BluSunrize/ImmersiveEngineering#1166] opened 2016-05-29 16:49 UTC
In a SMP that I host, I was doing some inventory in my base. While I was doing that, I had severe FPS hits (from ~32 to <10) any time I was near an IE machine. All of my IE machines tripled in appearance; the coke oven and improved blast furnaces had duplicates on their right and left, but the crusher was duplicated in place yet rotated. All of the duplicates were rendered partly in the original and the meshes flickered constantly. Shortly after, my client crashed. The server log shows nothing during the time frame, but below is the pastebin of the client crash log.

http://pastebin.com/jjkhAX76

I think this is definitely related to issue #1125 raised a couple weeks ago. My arc furnace and squeezers weren't affected and I think it's because they were more than a chunk radius away from nearby water wheels (and their associated kinetic dynamos).

MC: 1.8.9
Forge: 11.15.1.1855
IE: 0.8-27

**Comment by SpartanSamuel** [comment] 2016-05-29 18:06
Whoops, forgot a critical detail. I died from a fall in the area, and upon clicking 'Respawn' the client crashed. Sorry for not mentioning that earlier...

**Comment by malte0811** [comment] 2016-05-29 18:18
The crash is known and was meant to be fixed in the latest version, but isn't because I used `World.isBlockLoaded(pos)` instead of `World.isBlockLoaded(pos, false)`. The first one allows "empty" chunks, which is what unloaded chunks become in client worlds from what I understand.
Just to make sure that I didn't misunderstand what you said: the multiblocks close to the dynamos derped, but the ones further away from them didn't? That is good, I will push an potential fix in a bit and we will have to see whether the problem is solved after that.

**Comment by SpartanSamuel** [comment] 2016-05-29 18:33
That is correct. Looks like I'm beating a dead horse here if you already knew, haha. Let me know if you need me to test anything after the fix.

**Comment by malte0811** [comment] 2016-05-29 18:51
When the next version of IE is out and this happens again (either the crash or the multiblock duplication), please say so here. If you don't report back, I will assume that my fix works.
Neither of these reports was useless: The crash was, as I said, meant to be fixed and I wouldn't have looked at it again if you hadn't reported it. The multiblock thing was known, but I wasn't sure that it is caused by the dynamos yet, now I am sure enough to try to fix it.

**Comment by SpartanSamuel** [comment] 2016-05-30 04:13
Just a heads up, it might not be specific to the kinetic dynamo. I'm testing out the new 1.8.9 Ender IO for compatibility with other mods and it happened again. See the screencap below.

What's going on here is I have a set of Storage Drawers just off screen to the left that's inputting seeds, carrots, potatoes, saplings and bone meal into the Ender IO Farming Station. The Wooden Posts are rendering a few duplicates in place, but dispersed vertically. Same issue as before, except this time I don't have any machines or power gen from IE at all. Just the posts to transfer power from a creative capacitor off screen a handful of chunks away. I was configuring the storage drawers and ender conduits running to/from them when it happened so I can't pinpoint when exactly it's occurring. (I can't definitively prove it's the bone meal particles, plants growing, other block updates...)

https://i.imgur.com/yE8Xk7B.png

Edit: Upon taking down the posts and replacing and wiring them, I waited to see what caused the issue. The second closest post bugged out when a tree grew. The closest post bugged out when the potatoes were auto-harvested.

**Comment by elkillo** [comment] 2016-05-30 16:40
i have reported a similar issues and i to am also getting the Wooden post issues along side my press. I did move the Press away from the dynamo, and the issue persists

**Comment by malte0811** [comment] 2016-05-30 19:05
My fix does not work, so don't shout at me if it isn't fixed in the next release. On the positive side I have been able to replicate this bug in my dev-environment and am working on fixing it.

**Comment by SpartanSamuel** [comment] 2016-05-30 19:49
Hey, no shouting here. I'm just glad I'm not crazy and you're able to replicate it.

**Comment by malte0811** [comment] 2016-05-30 20:04
The "please don't shout at me" part was meant to stop people from saying "you said you fixed it, it's still boken. FIX IT". Nobody shouted at me about this bug (yet?). And I can confirm that big oak trees are a good way of triggering this, even though I don't know why.

**Comment by elkillo** [comment] 2016-05-30 21:44
Bug fixing isna long process, most of the people who yell probably havint coded or bug fixed before. I personally am more surprised at how fast alot of these bugs get fixed.

**Comment by XFactHD** [comment] 2016-05-31 05:27
Thanks @SpartanSamuel and @elkillo, I would love it if everyone thought the way you two are thinking, but having some people think this way already feels good. 😏

**Comment by malte0811** [comment] 2016-05-31 16:10
Apparently Botania had a similar problem,  williewillus/Botania@a9291566266807cf73802bb742a19e6f12ca8d7c. The commit above basically copies their fix into IE's system, but I am not sure that this won't break other stuff.

**Closed** 2016-06-05 19:54 UTC

**Comment by SpartanSamuel** [comment] 2016-06-12 14:25
Hey, I'm not trying to force anyone into working on an update but it's been a week since this issue's been closed now and there's not been an update to the mod on Curse.

If Life happened, that's fine. I get that; I'm just trying to keep the line of communication open. Does anyone have an ETA on when this fix is going to be pushed?

**Comment by malte0811** [comment] 2016-06-12 14:46
1. The issue is closed when the fix is pushed to Github. It would be possible to work on a second branch, in that case issues would be closed when the release is published/the branch is merged into master. But being able to see the issues that still need to be fixed seperate from the fixed issues is quite helpful.
2. There has been a small misunderstanding. I said I wanted to add Faraday suits. @BluSunrize thought that I wanted to put them into the next release (I didn't really care about which release they are in, because in the rare case that I actually play MC I compile IE from master). The problem is that the suit still needs a texture, which would look shit if I made it. The next release will probably be published once @BluSunrize finishes the textures, but I don't know how long that will be.

**Comment by BluSunrize** [comment] 2016-06-12 15:18
Also, pro tip: Being impatient isn't helping your case. I build when I'm done with a version. I'm not done yet. So I'm not building.

**Comment by SpartanSamuel** [comment] 2016-06-12 15:41
Sorry guys, I don't intend to sound imposing or demanding. It's unfortunate that you think I'm being impatient with the caveats I put into that comment like, "If life happened that's fine", "not forcing anyone." As I mentioned, I'm simply trying to keep the lines of communication flowing here. I understand that no one's paying you for doing this and it's in your free time and I wholly appreciate y'all for doing this.

From my end, someone who's still learning how GitHub works, closing the issue with no further communication for a week kind of left me in the dark so I thought I'd simply reach out. I'm by no means demanding anything here other than the occasional, "Hey, I haven't forgotten about you or moved on to other projects."

Again, thank you for making this mod, and I hope the update and new textures go well.
