### ISSUE TITLE
[1.16.1] chemical thrower crash

### ISSUE THREAD

**Issue by huntzilla360c** [BluSunrize/ImmersiveEngineering#4145] opened 2020-07-29 00:56 UTC
chemical thrower crashes client (not server) 
there is the tripple tanks, only one is filled with lava. i can toggle to the other tanks and click and nothing happens but when i actually try to use the thrower it crashes upon right-click

https://pastebin.com/55kZ5HyQ

IE: 0.16-109
Forge: 32.0.75
Modlist: https://github.com/The-Nexus-Project/Limitless-3/blob/master/modlist

**Comment by BluSunrize** [comment] 2020-07-29 07:42
Duplicate of #4104

**Closed as completed by BluSunrize** 2020-07-29 07:42 UTC
