### ISSUE TITLE
Creosote oil cannot be extracted via pipes unless it is processing an item

### ISSUE THREAD

**Issue by astrutzenberg** [BluSunrize/ImmersiveEngineering#518] opened 2015-10-20 08:15 UTC
Setup: 
Resonant Rise server using 
* Immersive engineering v0.5.2
* Ender IO v1.7.10-2.2.8.381
* Extra Utilities v1.2.6

Reproduction

1. Create a coke oven
2. Insert coal to be processed (to build up a reserve of creosote oil, and make sure there is no additional coal to be processed
3. attach either an ExUtil Fluid transfer pipe to the oven, extracting it into a drum, or an EnderIO pressurized fluiduct

Result:
The creosote oil is not extracted into the drum

Next:
4. Insert another piece of coal into the oven

Result:
The creosote oil is extracted

Expected Results:
The oil should be extract into the external container regardless of the state of the coke oven

**Comment by cobra** [comment] 2015-10-21 19:31
Could not reproduce exactly. I used TE's hardened fluiduct and a servo. It extracted the creosote oil correctly (rendered inside the pipe and the barrel I connected received it), but the GUI still showed the old amount until I put a piece of coal into it. (I already know why it doesn't update.)

**Comment by astrutzenberg** [comment] 2015-10-21 19:36
Ok, I have a further experiment I'd like to try (on my end)....

If this is a glitch with the GUI, if I were to disconnect the drum, and then connect it to a separate fluid system (in other words an (empty) drum with a fluid transport pipe), would it transport the correct amount to the new system?

**Comment by cobra** [comment] 2015-10-21 19:41
I did not try this, but as far as I can see, this is just outdated data shown in the GUI, the internal tank logic is working fine and you can drain a certain amount only once, despite the GUI telling you something else.

**Comment by cobra** [comment] 2015-10-21 19:50
Consider this bug fixed unless you can find something else than outdated GUI values. Thanks for reporting this!

*(for Blu and the rest: I'll PR this with a bunch of other fixes later.)*

**Comment by astrutzenberg** [comment] 2015-10-21 19:51
awesome (and kind of exciting as this is my first official "FTB" bug report :D)

**Comment by BluSunrize** [comment] 2015-10-21 20:46
The lack of GUI update is obvious, I'm just missing a markBlockForUpdate. Feel free to do that @cobra 
As for the broken CokeOven: this is IE 0.5.2, which is way out of date to the 0.6-pre we're working on, so that's probably all fixed by now.

**Comment by cobra** [comment] 2015-10-21 20:51
Already fixed when I saw it, that's why I added the hint. btw, there are more instances of this problem - also fixed on my side.

**Comment by mindforger** [comment] 2015-10-22 07:42
could this also explain why (in 0.5.4) the fermenter and the squeezer sometimes do not update their GUI when the TPS on the server is low ?

**Comment by cobra** [comment] 2015-10-22 19:31
I don't know what you mean. Low TPS causes fewer update packets per second, but that should only cause minor lags unless the server is really badly bogged down or you've got a really bad network connection. I didn't examine the GUI code though.

**Comment by mindforger** [comment] 2015-10-23 07:46
let's say ... mekanism can be a bitch when you got a few people "overscaling it" ... so yes it was pretty bad at some point in terms of TPS befor we flipped the table, so this issue became lost at some point since then we did not have any major problems, just now and then maybe a short moment of "WTF? ... close ... open ... hm, must have been my imagination!"

**Closed** 2015-10-24 14:03 UTC
