### ISSUE TITLE
[1.12] Missing textures

### ISSUE THREAD

**Issue by votex09** [BluSunrize/ImmersiveEngineering#2707] opened 2017-12-30 02:43 UTC
### Description of the issue:
![image](https://user-images.githubusercontent.com/10671494/34450724-176a3b9a-ecd7-11e7-8d85-0729afb0addd.png)

Briefly scanning over the log, found this.  Probably more of these in there as well.
---Snip---
`==================================================
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:   DOMAIN immersiveengineering
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]: --------------------------------------------------
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:   domain immersiveengineering is missing 3 textures
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:     domain immersiveengineering has 1 location:
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:       mod immersiveengineering resources at Z:\Documents\Curse\Minecraft\Instances\ZombehZ\mods\ImmersiveEngineering-0.12-75.jar
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]: -------------------------
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:     The missing resources for domain immersiveengineering are:
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:       textures/blocks/wooden_device_barrel_top_out.png
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:       textures/blocks/wooden_device_barrel_top_in.png
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:       textures/blocks/wooden_device_barrel_top_none.png
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]: -------------------------
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]:     No other errors exist for domain immersiveengineering
[18:18:59] [main/ERROR] [TEXTURE ERRORS/]: ==================================================`
---Snip---

### Versions & Modlist
ImmersiveEngineering-0.12-75
forge-14.23.1.2582

Addons:
ImmersiveCables-1.12.2-1.2.0.1
immersivepetroleum-1.12.2-1.1.5
IndustrialWire-1.6.23
[Full modlist](https://gist.github.com/08d0883878bbecba86cb0bbd8243c13dl)

**Comment by malte0811** [comment] 2017-12-30 08:24
Duplicate of #2672 (sort of). It is the same issue, they just catch the exception now and replace it with a missing model. Fixed for the next release.

**Closed by malte0811** 2017-12-30 08:24 UTC
