### ISSUE TITLE
[1.19.3] Blast furnace will not output to conveyors/containers

### ISSUE THREAD

**Issue by EvergreenSystems** [BluSunrize/ImmersiveEngineering#5624] opened 2023-03-19 20:28 UTC
### Minecraft Version

1.19.3

### Immersive Engineering Version

1.19.3-9.3.0-163

### Expected Behavior

The blast furnace should output its products (steel and slag) to containers such as barrels, conveyor belts, item routers, etc automatically.

### Actual Behavior

The blast furnace does not output on its own, nor can things such as extracting conveyor belts pull things out. 
![2023-03-19_15 17 16](https://user-images.githubusercontent.com/23658767/226206989-366d639e-ac93-4805-ac80-49429b40b271.png)
![2023-03-19_15 26 23](https://user-images.githubusercontent.com/23658767/226207008-71ce2f82-14fb-4cfb-84de-7b1cc734860c.png)

### Steps to reproduce

1. Assemble an improved blast furnace
2. Attempt to extract its products with conveyor belts, item routers, or have it just dump into a chest or barrel

### Debug Crash Log

https://gist.github.com/Shedao-Shai/27aaa46266b37fb91c17845f2ee2c770

**Comment by BluSunrize** [comment] 2023-03-19 22:50
Issue does **not** occur on 1.19.2

@malte0811 pretty high chance this is related to multiblock refactors, right?

**Comment by malte0811** [comment] 2023-03-20 07:12
Duplicate of #5611. I've fixed this on 1.19.4, since I was planning to make 1.19.3 critical-fixes-only (same as 1.18.2).

**Closed as not planned by malte0811** 2023-03-20 07:12 UTC
Labels: bug 🐛
