### ISSUE TITLE
[1.16.1] game crash when mining (only vanilla ?) ores.

### ISSUE THREAD

**Issue by Bass2style** [BluSunrize/ImmersiveEngineering#4075] opened 2020-07-14 14:39 UTC
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
when mining ores (got issues with gold, redstone and diamond, but not with iron and/or modded ores, but idk if it's random), game is (randomly ?) crashing, when reloading world, you get a huge rollback. (something like 1/2 minutes ?)
i've removed IE, and this issue is no more happening.
when it's crashing, it's not always on the first ore, i mined some diamonds before it crashes.

### Crashlog:
https://pastebin.com/SuFFvWe1
https://pastebin.com/STpz7ubN

### Versions & Modlist
Forge 32.0.66
IE 0.16.-106
modlist (IE isn't in it because i removed it for test purposes.) https://pastebin.com/hvmbtGfn

i have not tested this in a limited mod instance, but it's what i'm planning now, i'm coming back editing this when done.

edit : tested in a restricted modlist environment, with only JEI, IE, TheOneProbe and Ma Essentials (mainly for quick commands), and in a new generated world, and i got two crashes with similar issues, here are the crashlogs :
https://pastebin.com/r5pY8vxU > this one is particular, because it crashed when switching from GM3 to GM0, not when mining.
https://pastebin.com/XpdgCkPD > this one is more classic, a random crash when mining ores. (coal this time if i remember, i'm not sure anymore, and due to massive rollbacks, i can't check where i stand last time.)

**Comment by BluSunrize** [comment] 2020-07-14 19:04
duplicate of #4067

**Closed as completed by BluSunrize** 2020-07-14 19:04 UTC

**Comment by Bass2style** [comment] 2020-07-14 19:32
oh, it's a worldgen issue, whaw, not noticed that like this, always happened when i whas mining. glad to see it's fixed, thanks.
