### ISSUE TITLE
Bug; Minecraft crash when loading

### ISSUE THREAD

**Issue by Xzardas** [BluSunrize/ImmersiveEngineering#1936] opened 2017-03-05 14:30 UTC
Minecraft crash when loading Immersive engineering all the other mods are working properly.

There is any new library that i need to download or something like that?
https://gist.github.com/Xzardas/78aa8d1827a6364a7de62045efaa2129

**Comment by malte0811** [comment] 2017-03-05 14:42
Aside from the fact that logs belong on Gist or Pastebin (as stated in the [contributing guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/6a5adc5eb15749efc12918a11ca4d806639c7e3f/CONTRIBUTING.md)) this log does not contain any (relevant) errors. If MC crashes, there should be a proper crashlog in the `crash-reports` folder of your MC instance which would contain actual useful information about the crash. The log you posted is a general log, those usually contain far more information than needed to fix a crash.

**Comment by BluSunrize** [comment] 2017-03-05 14:57
^ What he said. There is no error in that log, This issue is invalid until you provide an actual crashlog.

**Comment by Xzardas** [comment] 2017-03-05 17:59
here it is
[<script src="https://gist.github.com/Xzardas/21a0eb1cb815663a2cfc66e9618c52d1.js"></script>](url)
[https://gist.github.com/Xzardas/21a0eb1cb815663a2cfc66e9618c52d1](url)

**Comment by BluSunrize** [comment] 2017-03-05 20:47
The log we are looking for is in the "crash-reports" folder. Neither of those are crash reports.

**Comment by Xzardas** [comment] 2017-03-05 21:16
there is nothing more than this, folder is empty

**Comment by Dwarfy-Dwarftins** [comment] 2017-03-06 04:11
im having the same exact problem it stops working at v54 anything higher and it crashes the only other mod ive had this problem with is thuamic horizons
Trust me its this mod that is causing the error because ive tested every other mod alone and together and ive been playing with all these other mods for weeks now and everythings been just fine.
I understand if you cant help me but id really like to enjoy playing your mod 
Hardware is not an issue nor is ram(32gb using 6gb for game) and java is on latest version 64 bit
https://gist.github.com/Dwarfy-Dwarftins/ef690077db3ad7b5cf31043ec5700999

**Comment by Xzardas** [comment] 2017-03-06 05:53
It's good that it's not my hallucinations
Well actually bad for us

there is something new that is causing the problem
some entities or textures?

**Comment by XFactHD** [comment] 2017-03-06 06:38
@Dwarfy-Dwarftins in your case the crash is either caused by an outdated forestry version or an outdated integration with forestry on IE's side.

**Comment by BluSunrize** [comment] 2017-03-06 09:29
@Dwarfy-Dwarftins You're no even on the same version. You're on 1.7.10, which is not being supported anymore. The crash you linked is entirely unrelated to the issue at hand.

And @Xzardas, I honestly cannot see an error in your log. It just stops, but there is no error or crash.
Can you try starting the instance without HardcoreDarkness and Quark?

**Comment by Xzardas** [comment] 2017-03-06 18:23
https://gist.github.com/Xzardas/b0e0777014a5ec53cc4f19d0809885fb

**Comment by BluSunrize** [comment] 2017-03-06 19:09
Running out of ideas here.
Can you check in your launcher where the java executable is set? If it's "javaw.exe", try changing it to "java.exe"?

**Comment by Xzardas** [comment] 2017-03-06 19:54
same
https://gist.github.com/Xzardas/e648ed2dd6416c5baf721a0d5e055d3f

**Comment by BluSunrize** [comment] 2017-03-06 19:55
You're not using a resource pack, are you?

**Comment by Xzardas** [comment] 2017-03-06 19:57
i never use resource packs, there is no other mods and i reinstal Minecraft, i try use 32 and 64bit java and allways is that same

**Comment by theunkn0wn1** [comment] 2017-03-07 02:51
```
...
Memory: 93224776 bytes (88 MB) / 309792768 bytes (295 MB) up to 1060372480 bytes (1011 MB)
...
```

@Xzardas 
Silly question, but have you tried running Minecraft with more than 1 GB of ram allocated? Based on your above logs, it appears you only have 1GB allocated, which can be woefully insufficient for many modpacks.
Minecraft can appear to hang while loading, or take its sweet time crashing when it runs out of RAM, based on my experience

**Comment by Xzardas** [comment] 2017-03-07 05:52
nope
https://gist.github.com/Xzardas/d7294973aba3d3838cf68bb787bd247b
https://gist.github.com/Xzardas/95b88d0331925d77b78dd1619d6589ca

**Comment by mindforger** [comment] 2017-03-07 06:36
it is always the same line, either it crashes silently while loading the entity renderer or something is derped up with your system

can you **tell exactly how** it is crashing? i mean, is it showing a messagebox like "java does not respond" or does it plainly crash to desktop? maybe increasing the loglevel might help at that point, but i honestly don't know how to set the parameter for fine logging

**Comment by AEnterprise** [comment] 2017-03-07 08:34
are you using the new MC launcher or the old one? the new one has some issues with logging done by forge sometimes

**Comment by Xzardas** [comment] 2017-03-07 15:43
I use Titan Minecraft launcher 3.6.1
I think that was not even crash, FML window says
**Loading-Initializing Minecraft engine
Rendering Setup-Loading Entity renderer**
And stops like frozen, few seconds and "No response" message is appear
I say again all mods works fine only Immersive engineering make that issue

**Comment by Dwarfy-Dwarftins** [comment] 2017-03-08 00:17
i couldnt install a newer version of forestry it wold just kick me back to launcher instantly.

**Comment by theunkn0wn1** [comment] 2017-03-08 00:31
@Dwarfy-Dwarftins :
```
-- System Details --
Details:
	Minecraft Version: 1.7.10
...
```
Your Minecraft Version ( **1.7.10** ) is **NOT supported**! please update your minecraft installation to **_AT LEAST_ 1.10**.
Also... Your issue is completely unrelated to this thread, please use the search function of the issue tracker... looks to be related to #559

**Comment by Joshwoo70** [comment] 2017-03-08 02:12
@Xzardas sorry your minecraft version is pirated.

**Comment by BluSunrize** [comment] 2017-03-08 07:50
@Joshwoo70 source?

**Comment by malte0811** [comment] 2017-03-08 08:08
Googling titan minecraft launcher (or something like that) spits out some videos about free MC and some stuff about a cracked launcher called TLauncher which I asume to be the same as Titan launcher.

**Comment by mindforger** [comment] 2017-03-08 08:31
it is indeed the so called TLauncher (if you watch the previous videos about his how to download closely).. it advertises itself as the best pirate launcher and hides well it's nature in logfiles .. HenryLoenwind seemed to be able to spot the difference on the crashlog somehow

**Comment by BluSunrize** [comment] 2017-03-08 08:34
Ah! Interesting.
Learned something new today.

Well, I generally don't cater to pirates. @Xzardas any rebuttle/proof towards the opposite before I close this issue (and thank fuck for that, because I really had no idea what was causing this)

**Closed** 2017-03-28 10:01 UTC
