### ISSUE TITLE
Crash on load...

### ISSUE THREAD

**Issue by Keetarin** [BluSunrize/ImmersiveEngineering#2681] opened 2017-12-20 20:13 UTC
I just tried to make a test pack with IE on its own and well, the title pretty much says it all...
Here's the crash log: [crash-2017-12-20_13.10.27-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1576887/crash-2017-12-20_13.10.27-client.txt)
Edit: Forgot to mention which version of IE & forge *smacks head*
IE 0.12 - 75
Forge-14.23.1.2578

**Comment by malte0811** [comment] 2017-12-20 20:26
Duplicate of #2672. Fixed for the next release, use forge 2575 for now.

**Closed by malte0811** 2017-12-20 20:26 UTC
