### ISSUE TITLE
[Medium] Charging station rendered nonfunctional after power loss

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#939] opened 2016-02-03 02:19 UTC
Issue: When the Charging station's energy buffer is fully depleted while attempting to charge any valid item then receives power at any later point the machine refuses to charge any item until it is broken and replaced.

Steps to reproduce:
[1] Place Charging station in world
[2] Provide a valid power source Via IE cables (or any RF conduit...)
[3] Place valid target item for charging into station via right-click
[4] Terminate power source, allow internal buffer to zero; observe lack of particle effects.
[5] Reapply power source.

![image](https://cloud.githubusercontent.com/assets/3110986/12770896/5d58e980-c9d9-11e5-8120-65bfd09aa45a.png)

IE build 8b379db

**Comment by malte0811** [comment] 2016-02-03 06:29
I think the problem is in the power supply. For some reason it is filling the charging station to 1 RF below max energy. If the station was filled completely, it would probably restart as intended. This was implemented to prevent flickering.

**Comment by theunkn0wn1** [comment] 2016-02-03 06:45
Why the heck is it doing that? The RF provider on the circuit is an MV capacitor that is at full capacity and is correctly configured. But, to be certain, I took some further steps to debug my circuit:
```java
 string CS = "Charging Station";
```
- Isolated the capacitor so it accepts no further charge from generators
- Isolated the capacitor so it ONLY outputs to the MV line in question. This line has **no other** consumers on the line that unsatisfied excluding the CS itself
- Drained the CS of all energy with an IC2 item (the `OV Scanner` `itemID= 4156:2 `
- Reapplied RF flow from capacitor, noted only the RF draw required to charge the CS back to near capacity, then no more. It never finished charging and I have no idea why :/ 

Perhaps resistance on the line is causing that last RF to be dropped and consequently ignored? I would rather take some minor flickering rather than a non-functional device that requires me to burn ~32 KiRf to replace... kinda hurts early game when RF is expensive comparative to mid-game....
What can I change to correct/work around this issue besides replacing the Charging station *every time* i want to use it?

**Comment by malte0811** [comment] 2016-02-03 09:17
I could make the charging station "restart" if it filled to more than 95% of energy, but that wouldn't fix the underlying problem. Could you try whether the station fills up properly if you set energy loss to 0 in the config? That would confirm that the loss calculation is breaking.

**Comment by malte0811** [comment] 2016-02-03 17:25
Just did some testing and looked at the code for power loss, is it possible that you have a very long power line/very high losses? If that is the case, this is sort of an unintended consequence of intended behavior: Wires loose more power if they are transferring very little energy, so it is possible that some power is going through your line when it is near it's max transfer rate, but all power is being lost when it is transferring 1 RF at a time.

**Comment by theunkn0wn1** [comment] 2016-02-03 17:38
The latter is most likely. The line is operating, with only one output as
it is isolated, at 12.5% capacity maximum. I have neither the power nor the
means on the world in question to max the capacitance of that line. And IE
refuses to transmit one RF but happily transmits larger chunks. Like I
said, the capacitor is not losing charge attempting to push one RF into the
network, it just gives up.

Lowering the minimum reactivation energy from 100% might resolve the issue
if your theory is correct.

**Comment by theunkn0wn1** [comment] 2016-02-04 01:29
@malte0811  Yeah, if i set cable resistance to `0.0` then the charging station works as soon as power is restored without even waiting for a full charge. When i regenerate the modified keys back to their defaults the issue manifests itself again.

**Comment by malte0811** [comment] 2016-02-04 07:29
You can either change to the branch which I hava PRed, it changes the "reactivation energy" to 31400 RF/95% (but don't checkout master again :)). If you don't want to use my version, you can use the workaround i mentioned (an lv capacitor next to the charging station)

**Comment by BluSunrize** [comment] 2016-02-28 14:08
Shoudl be fixed with next release.

**Closed by BluSunrize** 2016-02-28 14:08 UTC
