### ISSUE TITLE
Server crash on Release 47

### ISSUE THREAD

**Issue by gdude2002** [BluSunrize/ImmersiveEngineering#1638] opened 2016-10-25 21:40 UTC
Forge 2106.

```
java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.getMatrix(Lnet/minecraft/util/EnumFacing;)Ljavax/vecmath/Matrix4f;
	at blusunrize.immersiveengineering.common.util.chickenbones.Matrix4.<init>(Matrix4.java:87)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityBreakerSwitch.getBlockBounds(TileEntityBreakerSwitch.java:252)
	at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.func_185496_a(BlockIETileProvider.java:331)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
	at net.minecraft.block.Block.func_180646_a(Block.java:375)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
	at net.minecraft.pathfinding.PathWorldListener.func_184378_a(SourceFile:59)
	at net.minecraft.pathfinding.PathWorldListener.func_184376_a(SourceFile:25)
	at net.minecraft.world.World.func_184138_a(World.java:415)
	at net.minecraft.world.World.func_72939_s(World.java:1873)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

Found while flying around, no idea what's in the chunk.

**Comment by gdude2002** [comment] 2016-10-25 22:02
Looks like this is related to #1620 - guess the build is still coming :P

**Comment by MCTyler** [comment] 2016-10-26 10:21
Same Here...Happend when I added a Circuit Breaker to try to fix the floodlight...gonna paste my error log in case it might contain some other detail....
`[05:16:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[05:16:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.getMatrix(Lnet/minecraft/util/EnumFacing;)Ljavax/vecmath/Matrix4f;
        at blusunrize.immersiveengineering.common.util.chickenbones.Matrix4.<init>(Matrix4.java:87) ~[Matrix4.class:?]
        at blusunrize.immersiveengineering.common.blocks.metal.TileEntityBreakerSwitch.getBlockBounds(TileEntityBreakerSwitch.java:252) ~[TileEntityBreakerSwitch.class:?]
        at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.func_185496_a(BlockIETileProvider.java:331) ~[BlockIETileProvider.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443) ~[art$a.class:?]
        at net.minecraft.block.Block.func_180646_a(Block.java:375) ~[akf.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433) ~[art$a.class:?]
        at net.minecraft.block.Block.func_185477_a(Block.java:355) ~[akf.class:?]
        at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.func_185477_a(BlockIETileProvider.java:353) ~[BlockIETileProvider.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:438) ~[art$a.class:?]
        at net.minecraft.world.World.func_184144_a(World.java:1252) ~[aid.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:639) ~[rw.class:?]
        at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:115) ~[yk.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1964) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) ~[ls.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1750) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
        ... 4 more
[05:16:50] [Server thread/ERROR]: This crash report has been saved to: /home/steve/10.2/./crash-reports/crash-2016-10-26_05.16.50-server.txt
[05:16:50] [Server thread/INFO]: Stopping server
[05:16:50] [Server thread/INFO]: Saving players
[05:16:50] [Server thread/INFO]: Saving worlds
[05:16:50] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[05:16:51] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[05:16:51] [Server thread/INFO]: Saving chunks for level 'world'/The End
[05:16:51] [Server thread/INFO]: Saving chunks for level 'world'/Deep Dark
[05:16:51] [Server thread/INFO]: Saving chunks for level 'world'/ExtraUtils2_Quarry_Dim
[05:16:51] [Server thread/INFO] [FML]: Unloading dimension 0
[05:16:51] [Server thread/INFO] [FML]: Unloading dimension -1
[05:16:51] [Server thread/INFO] [FML]: Unloading dimension 1
[05:16:51] [Server thread/INFO] [FML]: Unloading dimension -11325
[05:16:51] [Server thread/INFO] [FML]: Unloading dimension -9999`

**Comment by MCTyler** [comment] 2016-10-26 10:23
Now I gotta figure out how to remove that block so I can load my World, Hate to have to start all over again....The Server will not load, just a endless error loop when it loads the World.

**Comment by gdude2002** [comment] 2016-10-26 10:27
Seems my email reply didn't get through. 

I compiled the latest version of the code myself, and can confirm that this issue is fixed. 

If you can't wait for a release, then download a copy of this repository, create a `libs` folder, grab the latest CraftTweaker and put it inside the libs folder, then run `gradlew build`. 

It takes a while, but assuming you have a working and up to date JDK installed, it should produce a plugin jar in `build/libs`.

**Comment by MCTyler** [comment] 2016-10-26 10:50
Got it! Will do after work tonite....Thanks!

**Comment by mindforger** [comment] 2016-10-26 11:56
>Now I gotta figure out how to remove that block so I can load my World

go into your config folder, search for your forge.cfg open it and set the options for "removing erroring TE" (and BE) to true, once started the TE or BE in question is deleted and the options are set back to false automatically :)

**Comment by gdude2002** [comment] 2016-10-26 11:58
I actually tried this on my server, but it didn't help. Best thing to do is MCEdit it out or compile yourself a preview build.

**Comment by marcin212** [comment] 2016-10-26 13:50
http://hastebin.com/kemakuyaso.scala

**Comment by gdude2002** [comment] 2016-10-26 15:42
I decided to compile the latest version of the code manually. I can confirm
that it fixes this problem.

**Comment by gdude2002** [comment] 2016-10-26 17:30
@marcin212 Please read the rest of the issue here.

**Comment by MCTyler** [comment] 2016-10-26 23:24
If any of you use Linux like I do just type....
`sudo apt-get install gradle`
Then in the directory you unzipped the file in....
`gradle`
and off she goes! Thanks for fixing this...I hope ;)

**Comment by MCTyler** [comment] 2016-10-26 23:36
`Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6 mins 7.715 secs`

**Comment by MCTyler** [comment] 2016-10-26 23:37
Is this Java 7 only?

**Comment by gdude2002** [comment] 2016-10-27 06:38
It can't be closed until a release is made with the fix.

**Comment by BluSunrize** [comment] 2016-10-27 08:31
Well actually it can, since this is a duplicate of #1620

**Closed by BluSunrize** 2016-10-27 08:31 UTC
