### ISSUE TITLE
[1.15.2] Charging Station has no texture

### ISSUE THREAD

**Issue by ocram9** [BluSunrize/ImmersiveEngineering#3956] opened 2020-06-12 00:43 UTC
### Description of the issue:
The charging station does not have a texture.

![Screenshot_4](https://user-images.githubusercontent.com/49008532/84452585-7cd94480-ac56-11ea-9162-4143173c178a.png)

### Versions:
- Minecraft 1.15.2
- Forge 31.2.9
- Immersive Engineering 0.15-99

**Comment by malte0811** [comment] 2020-06-12 04:46
Can you post a full modlist (and ideally a debug crashlog, triggered by holding F3+C for 10 (?) seconds)? I'm pretty sure it has a texture/model for me.

**Comment by ocram9** [comment] 2020-06-12 14:42
I didn't think mod compatiblility could be an issue with texture so that's why I didn't include it in the original report, sorry about that. Anyway, here is the log:

- Crashlog: https://gist.github.com/ocram9/f0f1f4f9987581e6c3a42d2a7a68303a
- Latest: https://gist.github.com/ocram9/ab90d890782fc2b03ae0340651a6fdbe
- Debug: https://gist.github.com/ocram9/b88b694527ba62e77b5c7befec52d0a0

**Comment by BluSunrize** [comment] 2020-06-12 15:16
Please try to replicate this issue without optifine.

**Comment by malte0811** [comment] 2020-06-12 19:30
I've done some debugging on this, it's caused by OF but should be easily fixable on our side. They change the implementation of `RenderType$Type#toString`, we currently expect that to be just the render type name. Adding an AT for the actual name field and using that instead of `toString` should fix it, I'll do that tomorrow.

**Comment by BluSunrize** [comment] 2020-06-12 19:44
...
urgh.
Do I even want to know how Optifine broke that?

**Comment by malte0811** [comment] 2020-06-13 19:52
Fixed in 750aabd

 >  Do I even want to know how Optifine broke that?

I think it's just debug code (they're adding the texture to the end of `toString` or something), and they didn't expect anyone to expect `toString` to be just the name.

**Closed as completed by malte0811** 2020-06-13 19:52 UTC
