### ISSUE TITLE
[1.12] Server crash on start (client seems to work)

### ISSUE THREAD

**Issue by fampat** [BluSunrize/ImmersiveEngineering#2272] opened 2017-07-09 12:06 UTC
Hi!

ive trying to add this mod (1.12) to my server (forge 14.21.1.2404), without any luck, also tried to add this mod alone was not successfull, on the client-side it seems to work well, at least the game loads without issues in singleplayer i was able to see the new recipes and was able to build the stuff.

Here is the server error log:
https://pastebin.com/UdP60WSG

Would be nice if someone can help me out, maybe there is a separate server-mod-file?

**Comment by BluSunrize** [comment] 2017-07-09 12:08
Duplicate of #2270, fixed already, expecting a new release later today.

**Closed by BluSunrize** 2017-07-09 12:08 UTC
