### ISSUE TITLE
Rail Craft creosote issue 

### ISSUE THREAD

**Issue by infernopuppet** [BluSunrize/ImmersiveEngineering#101] opened 2015-06-26 02:24 UTC
IE is overriding Rail Craft's creosote oil. Witch is not allowing the crafting of wooden ties so there is no way to make any of the tracks form Rail Craft. using the latest IE version o.2.4, Rail Craft 9.6.1.0, and the latest forge 10.13.4.1481.

**Comment by iTpyn** [comment] 2015-06-26 07:36
Yes, it's definitely very annoying
For the time being I use MineTweaker's script to allow new creosote buckets and bottles to be used in wooden tie crafting

recipes.addShaped(<Railcraft:part.tie>,
 [[null, <ImmersiveEngineering:fluidContainers>, null],
  [<ore:slabWood>, <ore:slabWood>, <ore:slabWood>]]);
  
  recipes.addShaped(<Railcraft:part.tie>,
 [[null, <ImmersiveEngineering:fluidContainers:1>, null],
  [<ore:slabWood>, <ore:slabWood>, <ore:slabWood>]]);

**Comment by BluSunrize** [comment] 2015-06-26 13:19
That makes no sense. the IE CokeOven produces the exact same fluid.
And from what I can see, Railcraft adds its recipe for all valid fluidcontainers.
@CovertJaguar any ideas?

**Comment by 3TUSK** [comment] 2015-06-26 14:24
I asked my friend to help to test it, and the result shows that wooden tile is craftable.
Under Railcraft 9.6.1.0,  Immersive Enginnering 0.2.4.

**Comment by Alex-R3CONN3R** [comment] 2015-06-26 23:55
The problem is not the fluid that comes out. It mixes fine with "railcrafts" creosote oil. The problem is the item (i.e. the IE bucket and bottle) that is not working in the recipe. ~~Maybe oredict it? Or check for railcraft and add a recipe to make the railcraft stuff.~~ (I have no clue how fluid registry works).

**Comment by iTpyn** [comment] 2015-06-27 07:44
to be more specific - right now, when you right click any tank containing creosote oil from Railcraft or IE with bucket/bottle, you get bucket/bottle added by IE, not Railcraft one. And they cant be used to craft wooden ties, because there is no recipe, unless you add it using minetweaker.

**Comment by BluSunrize** [comment] 2015-06-27 09:22
I know /what/ the issue is. The thing is, that I register my items as valid fluid containers. I don't know why Railcraft doesn't see them when adding recipes.

**Comment by Mrkeserian** [comment] 2015-07-01 14:00
I've been running into a similar issue with Railcraft and Gregtech / IC2. Minecraft is defaulting to IC2 creosote, which is unusable in any recipes, or boilers. If I was to hazard a guess, I'd say that Railcraft isn't handling the changes to the Fluid Registry that went in a month or so ago. So basically, my guess is that this is on Railcraft's side.

**Comment by Voxel-Friend** [comment] 2015-07-05 22:16
just wanted to weigh in this. when using railcraft's config option to use other mods creosote (steam is also an option) instead of its own, it causes a crash. I do not currently have a log, but I will recreate if requested.

**Comment by BluSunrize** [comment] 2015-07-06 13:30
Take this as a request. Because the basic rule is "logs or it didn't happen"

**Comment by Voxel-Friend** [comment] 2015-07-06 18:16
Here you are Blu. Brand new MultiMC instance with:
- CoFHCore-[1.7.10]3.0.3B2-294
- ImmersiveEngineering-0.3.3
- Railcraft_1.7.10-9.6.1.0

http://pastebin.com/jfrBfz3E

**Comment by BluSunrize** [comment] 2015-07-06 19:52
Go report that to @CovertJaguar, that seems to be entirely RC's fault .~.

**Comment by AEnterprise** [comment] 2015-07-07 07:16
on the compat note: the odd thing is that the bottles from IE are used by the game, but if you put the fluid in a tank then it uses the RC texture

**Comment by BluSunrize** [comment] 2015-07-07 08:39
because RC registers its fluid first. So I just use theirs, however, the fluid containers are a single texture created by Damien. Hence the difference.

**Comment by MrCaracal** [comment] 2015-07-08 19:00
This is a load-order issue and not a bug introduced by either party as both mods are behaving as intended.

Railcraft defines recipes by polling the Forge Fluid container registry and searching for all relevant containers, as can be seen here -> https://github.com/CovertJaguar/Railcraft/blob/060c69a439d817affd63da44af3f254a8d05c8f8/src/main/java/mods/railcraft/common/items/ItemTie.java#L92 and here -> https://github.com/CovertJaguar/Railcraft/blob/060c69a439d817affd63da44af3f254a8d05c8f8/src/main/java/mods/railcraft/common/fluids/FluidHelper.java#L271

If ImmersiveEngineering loads after Railcraft, Railcraft will not find any fluid containers registered by ImmersiveEngineering because they don't exist yet. The result of this is Railcraft creosote fluid containers can be used in Immersive Engineering recipes but Immersive Engineering creosote fluid containers cannot be used in Railcraft recipes.

Railcraft also polls the Fluid Registry for containers when filling from its devices, such as the coke oven. The Forge Fluid registry consistently returns the ImmersiveEngineering containers because ImmersiveEngineering re-registers a container for the same fluid Railcraft uses (since ImmersiveEngineering also looks in the Fluid Registry for a fluid called "creosote"), making Railcraft fluid containers unobtanium.

Possible fixes include separating the fluids altogether, not registering a fluid container if the RC fluid container is found, or having the mod dynamically add additional recipes for Railcraft's items using the ImmersiveEngineering creosote containers if Railcraft's is detected.

**Comment by BluSunrize** [comment] 2015-07-08 19:45
Or by Railcraft doing recipes in init rather than preinit, like every other mod =)

**Comment by MrCaracal** [comment] 2015-07-08 21:03
Railcraft does in fact perform it's recipe stuff in init.

See the following areas: https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/core/Railcraft.java#L177
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/modules/ModuleManager.java#L181
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/modules/ModuleManager.java#L270

Because Railcraft's init occurs before ImmersiveEngineering's init, the issue I described above occurs.

**Comment by mallrat208** [comment] 2015-07-08 21:31
That seems reversed

**Comment by BluSunrize** [comment] 2015-07-09 07:41
But my fluid containers are registered in pre-init. If RC does its recipe in init, it should find the registered containers .-.

**Comment by malte0811** [comment] 2015-07-11 14:02
@MrCaracal The code you referenced is apparently not used, at least for wooden ties.
Here are the calls that cause the recipe for the wooden tie to be registered in preinit:
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/core/Railcraft.java#L166 (preInit)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/modules/ModuleManager.java#L174 (calls initFirst in the core module)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/modules/ModuleCore.java#L259 (requests wooden railbed item)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/items/RailcraftItem.java#L110 (registers wooden railbed)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/items/RailcraftItem.java#L60 (requests recipe for wooden railbed to be registered)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/items/ItemRailbed.java#L85 (requests wooden tie item)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/items/RailcraftItem.java#L110 (registers wooden tie)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/items/RailcraftItem.java#L60 (requests recipe for wooden tie to be registered)
https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/items/ItemTie.java#L92 and following (register recipe for wooden ties for each creosote container)

**Comment by MrCaracal** [comment] 2015-07-11 18:18
I see, thanks.

**Comment by JonathanMH** [comment] 2015-07-28 16:27
@iTpyn Your fix doesn't work for me, I'm on the DNS Techpack 7.7.1.1, I have tried reloading through minetweaker, restarting server now

**Comment by iTpyn** [comment] 2015-07-29 17:06
@JonathanMH we shouldn't discuss it here, so i'll just say that according to your script bottle/bucket must be in the top row, so you won't be able to craft ties with bottle/bucket in the middle row.
![untitled-1](https://cloud.githubusercontent.com/assets/10965662/8964246/2a382d4e-362d-11e5-9271-0ea96edfb3b9.png)

Just tested and script works flawlessly in the latest FTB Infinity 1.9.0 with MineTweaker3-1.7.10-3.0.9C

**Comment by mindforger** [comment] 2015-08-07 06:42
@iTpyn maybe you can edit your script in your early post and insert the missing \<> brackets (write an backslash infornt of the opening bracket to escape the sequence) github markup has also fooled me on this but now your script really works like a charm :)

**Comment by JonathanMH** [comment] 2015-08-07 13:56
@mindforger, @iTpyn: I know mine isn't implementing the recipe correctly with the positions, but for some reason I couldn't get Minetweaker to parse it without it. It would be great to have a script people could just drop in

**Comment by iTpyn** [comment] 2015-08-07 14:44
https://www.dropbox.com/s/5qa0fspyac875ib/ImmersiveEngineeringcreosote_Railcraftwoodentie.zs?dl=0

**Comment by cobra** [comment] 2015-10-03 07:25
This has now been fixed in Railcraft, we just need to wait for a new railcraft update.

**Closed** 2015-10-12 11:42 UTC

**Comment by cobra** [comment] 2015-10-29 21:09
Railcraft 9.8.0.0 has now been released, including this fix. I have just tested it in my dev environment with the current IE dev version and could successfully craft a wooden tie with a creosote oil bottle (brown IE version) produced by IE's coke oven. RC's coke oven also produces IE creosote oil bottles. The creosote oil itself is the one from RC.

**Comment by MrPurple6814** [comment] 2015-11-01 18:37
Even though this has been fixed other ways I just want to point out that using the carpenter from forestry works for creating the ties as it uses the liquid form and as such it is RC version of the oil.

**Comment by MrPurple6814** [comment] 2015-11-01 18:40
Just thought someone might like to know there was a workaround without altering the mods themselves. Although I am still waiting for the infinity modpack to update as going through forestry is a bit annoying but still not hard.
