### ISSUE TITLE
Railgun and Chemthrower not firing projectiles

### ISSUE THREAD

**Issue by EpicDanger2015** [BluSunrize/ImmersiveEngineering#2781] opened 2018-02-15 00:24 UTC
The Railgun charges and consumes ammo, but does not fire, same with the Chemthrower, it makes sound and uses fuel but does not shoot out the fluid.. I am using the most recent release of this mod from CurseForge, and it still doesn't work even by itself.
EDIT: I forgot to mention this is with the 1.12.2 version

**Comment by malte0811** [comment] 2018-02-15 07:16
Duplicate of #2736. There's another one for the railgun, it's the same problem though.

**Closed by malte0811** 2018-02-15 07:16 UTC

**Comment by mindforger** [comment] 2018-02-15 07:26
@EpicDanger2015 just for future reports, there are dozends of revisions for 1.12.2, please specify the exact version of IE, forge and other mods installed when making a report 

like instructed in the contribution guidelines above your "new issue window" to enable the devs to sort your issue out more easily please :)

**Comment by JoshuaSpencer** [comment] 2018-02-15 12:17
Alright, sorry about that guys!
