### ISSUE TITLE
[1.15.2] [0.15-105 #10] Engieneer's workbench items

### ISSUE THREAD

**Issue by Arathorne** [BluSunrize/ImmersiveEngineering#4029] opened 2020-06-23 17:52 UTC
### Description of the issue:
I added items into engie workbench, and tried the duplication glitch, after taking weapon it looked like this
![xDD](https://user-images.githubusercontent.com/60345302/85437485-f2181400-b58a-11ea-83ce-e449afc71360.PNG)
and i tried to add something into those slots and it crashed. 
### Crashlog:
[crash-2020-06-23_19.43.52-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4821018/crash-2020-06-23_19.43.52-client.txt)
### Versions & Modlist
forge 31.2.9 , IE [1.15.2] [0.15-105 #10] and basic, not modified modlist of the server

**Comment by BluSunrize** [comment] 2020-06-28 12:47
Duplicate of #4028 in its cause, should be resolved by the same fix.

**Closed as completed by BluSunrize** 2020-06-28 12:47 UTC
