### ISSUE TITLE
[1.10.2] Wires not rendering after game re-launch

### ISSUE THREAD

**Issue by grabvba** [BluSunrize/ImmersiveEngineering#1376] opened 2016-09-03 08:24 UTC
After four hours of troubleshooting I am at a loss. 

Wires created on an online server are perfectly visible upon creation and subsequent playtime. After closing the minecraft client to desktop and re-opening it/joining the server, the wires are no longer visible however the power is still be transferred. The wire visibility does survive logging out and logging back in to the server. The wires only fail to render when the game is completely closed and restarted.

The online server and clients are running forge 1.10.2-12.18.1.2076 and IE 10-38. There are no other mods installed on the server or client. The server is hosted by CreeperHost. This issue has been confirmed by all users on the server. 

Interestingly, I downloaded the world from the server and loaded it in offline mode - wires appear as they should and their visibility survives a game restart. This appears only to happen online. The server is hosted by CreeperHost. 

I have tested this issue on a fresh forge server and client installation running creative mode (same versions listed above) and the problem persists. 

I have used default server settings for all testing. New wire was placed for each test conducted. I tried forcing the server to save the world from console prior to closing the game, problem persisted. 

I have read all past bug reports of similar type and attempted various fixes and work-arounds to no avail. 

Tomorrow I will be attempting to re-produce the problem on a locally hosted online server (not CreeperHost). Update to follow.

There is nothing jumping out to me as related to the issue in any game log files generated but I will happily provide files in a followup as requested and with some instruction as I am not 100% sure what anyone would want to look at.

**Comment by BluSunrize** [comment] 2016-09-03 09:21
Yeah, known issue btw. Should be fixed for future releases.

**Comment by grabvba** [comment] 2016-09-03 09:31
Interesting. I didn't see a report of this issue for this version combination - unless of course I missed it. Sorry for the false report. Thanks for your work!

**Comment by BluSunrize** [comment] 2016-09-03 09:41
Well I am at least quite /confident/ that this is fixed. Otherwise, poke me and I'll reopen the issue if this persists in the upcoming version 39 ^^

**Comment by mindforger** [comment] 2016-09-03 10:37
@grabvba check if you filtered out closed issues while searching, some issues just got fixed and you just did not know about the update :)

**Comment by grabvba** [comment] 2016-09-03 20:03
@mindforger I found a reference to the problem buried with another open bug report. Open or closed I didn't see any specific documentation of this problem by itself. I'm new to github, I'm sure i'll get the hang of it sooner or later. :)

**Comment by grabvba** [comment] 2016-09-03 20:37
So I built the latest version of the mod, some fixes work, it's obviously a work in progress, I just wanted to see if the wires had been fixed. Doesn't look like it. 

Again, thanks for your work on this great mod, I'm anxiously awaiting the wires to be visible. :)

**Comment by BluSunrize** [comment] 2016-09-04 10:48
Apparently still a persisting issue then. Reopened.

**Comment by Bitterholz** [comment] 2016-09-04 17:33
Can confirm, still happening even on latest Changeset

**Comment by BluSunrize** [comment] 2016-09-05 16:40
If anyone is able to build off of this git, try a build after this commit:

https://github.com/BluSunrize/ImmersiveEngineering/commit/0852ae2313ee3fe9b02f10b549baf6a4c98c21dd

It adds a command, "/ie resetrender" which clears the render caches. If wires don't render on login, use that command and then force a blockupdate (by placing a block next to the connector) and see what happens.

**Comment by Bitterholz** [comment] 2016-09-05 17:59
Commencing Testing Operations!

**Comment by Bitterholz** [comment] 2016-09-05 18:26
Test did reveal the issue not reproducable anymore, but command has no impact on pre Update wires

**Comment by BluSunrize** [comment] 2016-09-05 18:42
Wait, so you can't produce hte issue anew? .-.
Well that's a partial fix? x3
The command still stays however, a render reset function is useful for me working in dev.

**Comment by Bitterholz** [comment] 2016-09-05 18:46
Exactly. Newly placed wires do not suffer the issue as of the use of 38.5
Wires coming from pre 38.5 are still not rendering

**Comment by BluSunrize** [comment] 2016-09-05 18:49
Odd.

**Comment by Bitterholz** [comment] 2016-09-05 18:57
Odd indeed

**Comment by Bitterholz** [comment] 2016-09-05 18:58
maybe some change did silently affect the issue...though i can hardly think of wich it is

**Comment by Bitterholz** [comment] 2016-09-05 19:05
Didnt you say Wire renders changed to ItemType rendering?
Could this change maybe have affected it? https://github.com/BluSunrize/ImmersiveEngineering/commit/3a818fb32de169e1ff44a3f202247e59cec8bf40

**Comment by grabvba** [comment] 2016-09-06 02:22
I have not had a chance to build the last 1.10 repository and test, I will update when I do.

**Comment by grabvba** [comment] 2016-09-06 23:06
10-40 tested, wires are still not persistent online. This is true for newly placed wire as well as already in-place wire.

There is a new symptom, when a new wire is made to a relay, the wires that were all ready connected to that relay become partially visible.

**Comment by calloatti** [comment] 2016-09-09 15:42
Tested with ImmersiveEngineering-0.10-40.dda19ef

Wires still invisible in multiplayer after restart/logout/etc.

In single player wires do show up every time.

One thing I noticed is that redstone wires are initially invisible also, but when a lever is flipped to ON, the redstone wires become visible or partialle visible (half the wire segment). Placing a block fixes partial visibility.

The other wires stay invisible, and "/ie resetrender" seems to do nothing to make them visible.

So check the code of what happens when redstone wire gets a redstone signal that makes them visible again, replicate that code to make the other wires visible.

**Comment by guachitonico** [comment] 2016-09-12 11:49
I can also confirm this issue. The cables stay connected to their respective relays / machines and transfer energy, but they become invisible after relaunch (not after re-login to server). Replacing them works; /ie resetrender doesn't.
Hope you can reproduce the issue with @calloatti 's procedure, and it's fixed soon!
Great mod btw, I love it.

**Comment by BluSunrize** [comment] 2016-09-15 07:13
@malte0811 I'm a bit at a loss here. You got any idea?
Sounds to me like the render is cached like it should be, but too early which makes it cache without the wires rendered. But the command I wrote should clear the caches, in theory :V

**Comment by Bitterholz** [comment] 2016-09-15 07:27
@BluSunrize Could it be that this is actually caused by the Connectors? 

Strangely i was not able to reproduce the bug wich connectors and Wires newly placed after you implemented that command.
Only Cables and connectors previously placed still suffer the Problem.

The command itself has no impact on the old connectors. Neither with or w/o a block update triggered.

**Closed** 2016-09-15 16:52 UTC

**Comment by Bitterholz** [comment] 2016-09-15 17:05
NICE great fix @BluSunrize ! Runs perfectly

**Comment by BluSunrize** [comment] 2016-09-15 19:41
Wasn't me! This is @malte0811 's wizardry at work! :V

**Comment by grabvba** [comment] 2016-09-16 22:23
Can confirm build 42 fixes the wires, great job guys!
