### ISSUE TITLE
 Permanent crash IE x.x.x - Registering texture

### ISSUE THREAD

**Issue by TigerChaos** [BluSunrize/ImmersiveEngineering#1007] opened 2016-03-11 13:12 UTC
Hello,

so far I have several versions package tested from the Infinity as well as my own packet and repeatedly dipped the error "Registering texture" on.

The Infinity package I have previously stated when I add a mod from me this error occurs.

Hardware can think I exclude, as this is sufficient. The allocation of RAM is sufficient to 5GB.

So far, unfortunately, I could not determine why this occurs repeatedly when I add one of my mods.

Report:
[https://gist.github.com/TigerChaos/90035a3bdcd57f075515](url)

[13:04:20] [Client thread/ERROR] [FML/]: Caught exception from ImmersiveEngineering
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:111) ~[bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:71) ~[bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:58) ~[bqf.class:?]
	at blusunrize.immersiveengineering.client.ClientProxy.init(ClientProxy.java:252) ~[ClientProxy.class:?]
	at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:103) ~[ImmersiveEngineering.class:?]

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11.03.16 13:04
Description: Registering texture

java.lang.ArrayIndexOutOfBoundsException: 94
	at gcewing.sg.BaseModClient.onTextureStitchEventPre(BaseModClient.java:657)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_829_BaseModClient_onTextureStitchEventPre_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:271)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:109)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:97)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:71)
	at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:58)

**Comment by malte0811** [comment] 2016-03-11 17:05
(I am not too experienced with rendering, so this may not be completely correct)
`at gcewing.sg.BaseModClient.onTextureStitchEventPre(BaseModClient.java:657)`
I assume that this is the mod you added? IE uses a separate texture map for the revolver skins. You have to check that `event.map.getTextureType()` is 0 or 1 (There may be other default values, those are the ones used by IE) in the `TextureStitchEvent` listener, other values are for custom maps from other mods.
Also your link to the complete crash report is giving me githubs 404 page.

**Comment by Berserker66** [comment] 2016-03-12 11:44
http://pastebin.com/z0QBhY7v

Here is one I got.
It's Greg's SG Craft. However, I run a server and we all added SG Craft, one out of 3 so far gets this crash, the others don't.

**Comment by malte0811** [comment] 2016-03-12 18:19
That means that optifine somehow breaks texture stitch events, good to know. And it currently isn't possible to disable the revolvers texture map, only thing I can think of would be setting the map id to 0 or 1 in the config, but I am pretty certain that doing so would cause other, possibly hard to track down crashes/bugs, so I don't recommend it (I haven't ever tried doing that, so I don't know whether the game would even start with that change). The crash should be fixed in the latest or next version of SG craft.

**Comment by BluSunrize** [comment] 2016-03-12 18:37
My texturemaps work flawlessly. Stop using Optifine and if SGCraft stitches into the wronh sheet that's on them, not me.

**Closed by BluSunrize** 2016-03-12 18:37 UTC

**Comment by Berserker66** [comment] 2016-03-12 19:34
Ehm "Stop using Optifine" - that would make us all crash.
It's optifine that's the workaround that makes it work.

**Comment by BluSunrize** [comment] 2016-03-12 19:36
It's still a terrible mod that breaks everything else. SG Craft is obviously the core issue here, but that doesn't mean that optifine is good. xD

**Comment by Berserker66** [comment] 2016-03-12 19:40
Ok, one last thing, Malte said "The crash should be fixed in the latest or next version of SG craft." Does that mean I don't need to report this to SG Craft, as you did it?

**Comment by malte0811** [comment] 2016-03-12 19:48
You don't need to report it, it has been fixed already: https://github.com/gcewing/SGCraft/commit/c67556d462fb9daf642c348c0475a5686bd9b357

**Comment by TigerChaos** [comment] 2016-03-13 17:04
First, I'm irritated that my link is not working, but in the post of "Berserker66"

I'm from Germany and effortless me often from the English language use.

If I understand correctly you think that it is up to Optifine? What I do not use.

That with the fix of SGcraft I did not know on the website:

there is no hint on the I had found, or simply overlooked.
to test some I had to bring MineTweaker 3 on the latest stand ..... now it seems to be, for the time being.

Thanks for the note.

here is a list of mods used

AdvancedSolarPanel-1.7.10-3.5.1.jar
ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar
AOBD-2.9.0.jar
appliedenergistics2-rv2-stable-10.jar
Aroma1997Core-1.7.10-1.0.2.14.jar
AromaBackup-1.7.10-0.0.0.5.jar
backpack-2.0.1-1.7.x.jar
bdlib-1.9.2.104-mc1.7.10.jar
BiblioCraft[v1.10.5][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.3A.jar
BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
BloodMagic-1.7.10-1.3.3-4.jar
buildcraft-7.1.15.jar
buildcraft-compat-7.1.3.jar
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel2-2.3.10.37.jar
CodeChickenCore-1.7.10-1.0.6.43-universal.jar
CoFHCore-[1.7.10]3.1.2-325.jar
CompactSolars-1.7.10-4.4.39.315-universal.jar
CompactWaterTurbines-1.7.10-1.1.1.jar
ComputerCraft1.73.jar
CustomMainMenu-MC1.7.10-1.5.jar
Decocraft-2.0.2_1.7.10.jar
denseores-1.6.2.jar
Draconic-Evolution-1.7.10-1.0.1c.jar
DragonAPI 1.7.10 V11b.jar
ElectriCraft 1.7.10 V11b.jar
EnderIO-1.7.10-2.2.8.381.jar
EnderStorage-1.7.10-1.4.7.33-universal.jar
EnderTech-1.7.10-0.3.2.388.jar
EnderZoo-1.7.10-1.0.11.28.jar
ExtraCells-1.7.10-2.2.73b129.jar
ExtraDoors-1.7.2-1.5.1.jar
ExtraPeripherals-1.7.10-0.3.0.jar
extrautilities-1.2.5.jar
Factorization-1.7.10-0.8.88.8.8888g.jar
fastcraft-1.21.jar
FlatSigns-1.7.10-universal-2.1.0.19.jar
forestry_1.7.10-4.2.5.53.jar
FTBLib-1.7.10-1.0.17.6.jar
FTBTweaks-1.0.1.jar
FTBUtilities-1.7.10-1.0.17.6.jar
funky-locomotion-1.7.10-beta-5c.jar
gendustry-1.6.2.127-mc1.7.10.jar
GraviSuite-1.7.10-2.0.3.jar
growthcraft-apples-1.7.10-2.1.0.jar
growthcraft-bamboo-1.7.10-2.1.0.jar
growthcraft-bees-1.7.10-2.1.0.jar
growthcraft-cellar-1.7.10-2.1.0b.jar
growthcraft-core-1.7.10-2.1.0a.jar
growthcraft-fishtrap-1.7.10-2.1.0a.jar
growthcraft-grapes-1.7.10-2.1.0.jar
growthcraft-hops-1.7.10-2.1.0.jar
growthcraft-rice-1.7.10-2.1.0a.jar
Guide-API-1.7.10-1.0.1-20.jar
HelpFixer-1.0.7.jar
IC2NuclearControl-2.2.5a-GoingForTheKill.jar
iChunUtil-4.2.2.jar
IGW-Mod-1.7.10-1.1.11-32-universal.jar
ImmersiveEngineering-0.7.3.jar
immersiveintegration-0.6.7.jar
Immibis-Core-1.7.10.jar
industrialcraft-2-2.2.736-experimental.jar
InfiniBows-1.7.10-universal-coremod-1.3.0.20.jar
INpureCore-[1.7.10]1.0.0B9-62.jar
InventoryTweaks-1.59-dev-152.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
journeymap-1.7.10-5.1.0-unlimited.jar
magicalcrops-1.7.10_0.1.jar
magicbees-1.7.10-2.4.3.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-8.1.9.266.jar
MekanismGenerators-1.7.10-8.1.9.266.jar
MekanismTools-1.7.10-8.1.9.266.jar
minefactory-magicalcrops-compatibility-1.1.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
MineTweaker3-1.7.10-3.0.10B.jar
MobiusCore-1.2.5_1.7.10.jar.disabled
ModularPowersuits-0.11.0.178.jar
Morph-Beta-0.9.1.jar
Morpheus-1.7.10-1.6.4.jar
natura-1.7.10-2.2.0.1.jar
neiaddons-1.12.11.36-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.0.12.jar
NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar
NotEnoughItems-1.7.10-1.0.4.107-universal.jar
NotEnoughKeys-1.7.10-1.0.0b29.jar
NotEnoughResources-1.7.10-0.1.0-121.jar
Numina-0.4.0.100.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
OpenBlocks-1.7.10-1.4.3.jar
OpenComputers-MC1.7.10-1.5.22.46-universal.jar
OpenModsLib-1.7.10-0.7.3.jar
OpenPeripheralAddons-1.7.10-0.3.1.jar
OpenPeripheralCore-1.7.10-1.1.1.jar
OpenPeripheralIntegration-1.7.10-0.2.2.jar
Opis-1.2.5_1.7.10.jar.disabled
PneumaticCraft-1.7.10-1.9.15-104-universal.jar
PortalGun-4.0.0-beta-4.jar
PortalGunSounds.pak
ProjectBlue-1.1.4-mc1.7.10.jar
ProjectRed-1.7.10-4.6.1.80-Base.jar
ProjectRed-1.7.10-4.6.1.80-Compat.jar
ProjectRed-1.7.10-4.6.1.80-Integration.jar
ProjectRed-1.7.10-4.6.1.80-Lighting.jar
ProjectRed-1.7.10-4.6.1.80-World.jar
Railcraft_1.7.10-9.8.0.0.jar
RandomThings-2.2.4.jar
ReactorCraft 1.7.10 V11b.jar
RedstoneArsenal-[1.7.10]1.1.2-92.jar
ResourceLoader-1.2.jar
rftools-3.10.jar
RotaryCraft 1.7.10 V11b.jar
SGCraft-1.11.1-mc1.7.10.jar
slick-util.jar
StevesCarts2.0.0.b18.jar
StevesFactoryManagerA93.jar
TConstruct-1.7.10-1.8.5.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThaumicExploration-1.7.10-1.1-37.jar
ThaumicTinkerer-2.5-1.7.10-502.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.1.2-240.jar
ThermalFoundation-[1.7.10]1.2.3-112.jar
TiCTooltips-mc1.7.10-1.2.4.jar
TMechworks-1.7.10-0.2.14.100.jar
tubestuff-59.0.0.jar
twilightforest-1.7.10-2.3.7.jar
universal-electricity-4.0.0.88-core.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar

**Comment by malte0811** [comment] 2016-03-13 17:18
We do not think that this crash is caused by OptiFine, but OptiFine only "fixes" it because it prevents some code from running.
Optifine is not able to predict if the code is going to crash (since that is impossible, generally speaking), and it wouldn't just catch the exception thrown in that code because catching an exception without knowing EXACTLY what said exception is is stupid and dangerous, so the fact that the code doesn't crash means that it is never run.
We are not particularly happy about that since code not running when it should can and will cause bugs of some description, even if, like in this case, it sometimes fixes a crash (which is very rare).

**Comment by Berserker66** [comment] 2016-03-13 20:56
Since he's German, I'll just translate the important bits for him.

Es ist nicht Optifine, sondern die, die Optifine haben, haben das Problem nicht, da Optifine den bug einfach unterdrückt. Dies kann aber zu späteren Darstellungsfehlern führen.

SG Craft hat den Bug bereits gefixt, aber die neue Version noch nicht veröffentlicht, bis dahin, kann Optifine als workaround benutzt werden.

**Comment by Robijnvogel** [comment] 2016-03-16 22:18
I came here to report this crash that I got half an hour ago, just to ask you if it was your fault or not. I already reported it to Greg Ewing. And I already found out that Optifine "fixes" it.

I guess it doesn't help if you're faster if you're already too late to contribute.

Thank you for answering the questions that I still had.
