### ISSUE TITLE
[1.12.2] Unable to attach drill head

### ISSUE THREAD

**Issue by mangefox** [BluSunrize/ImmersiveEngineering#2752] opened 2018-01-24 09:36 UTC
### Description of the issue:
I'm unable to attach any drill head to the mining drill. If drill is fueled made no difference.
Happened initially in survival mode (which was a huge bummer) and then replicated in creative.

I've tried this on forge 2568 and then on the most recent forge 2604. Tried in both ImmersiveEngineering 0.75 and 0.76 with no other mods installed.

[See video for a demonstration](https://youtu.be/pXXRVHyfEhg)

### Versions & Modlist
IE 0.76 and 0.75 (tried both)
Forge 2568 and 2604 (tried both)
No other mods installed

**Comment by malte0811** [comment] 2018-01-24 09:54
Duplicate of #2709, fixed for the next release.

**Closed by malte0811** 2018-01-24 09:54 UTC
