### ISSUE TITLE
Game crashing when I click on "Assembler" in the manual

### ISSUE THREAD

**Issue by WillCon** [BluSunrize/ImmersiveEngineering#1731] opened 2016-11-25 11:08 UTC
Pastebin of crash report: http://pastebin.com/pxi1s1Q1

Tried three times. thought maybe it was Akashic tome so I tried one not in the tome, still crashed. Not sure what else to say, let me know if you need more information. I am also having some multiblocks not render when looked at in certain ways. 

1.10.2 Would it help if I included my mod list?

**Comment by BluSunrize** [comment] 2016-11-25 11:47
Duplicate of #1704, please use the search function next time =)

**Closed by BluSunrize** 2016-11-25 11:47 UTC
