### ISSUE TITLE
Sources from github?

### ISSUE THREAD

**Issue by lucemans** [BluSunrize/ImmersiveEngineering#824] opened 2015-12-29 22:23 UTC
can anybody please help me with my server log
it takes like 5 minutes before it continues from here

Log:
http://pastebin.com/YjszetjR

**Comment by BluSunrize** [comment] 2015-12-29 22:25
No.
Not until you give us the /whole/ log, you upload it to pastebin or gist, rather than posting it unspoilered, which makes reading it almost impossible, and you give us the version number you are running.

**Comment by lucemans** [comment] 2015-12-29 22:28
it doesnt realy crash it just takes like 5 minutes till it goes further

**Comment by BluSunrize** [comment] 2015-12-29 22:29
Then it's not a crash and you are effectively reporting nothing.

**Comment by lucemans** [comment] 2015-12-29 22:30
do you have any ideas what this means?

**Comment by BluSunrize** [comment] 2015-12-29 22:33
What? You aren't REPORTING anything. You also still haven't told me what version of IE you are using!
The last message of your log shows the downloader thread starting which is perfectly fine and I can't tell you what happens after that because you damn log is incomplete.
I can't analyse what I can't see. Give me the whole log!

**Comment by lucemans** [comment] 2015-12-29 22:34
can you please explain me how i can gather the whole log cause it doesnt save it in a crash report but its just like freezing in the console

**Comment by lucemans** [comment] 2015-12-29 22:34
and i copied the console

**Comment by lucemans** [comment] 2015-12-29 22:35
IE 0.6.2

**Comment by BluSunrize** [comment] 2015-12-29 22:37
Well you wait till it has actually finished loading and then you either copy the console contents, or, if your console has a fixed size and the first part of the log is missing, you go into "logs" and grab the file called "latest".

**Comment by lucemans** [comment] 2015-12-29 22:40
m im getting confused, sorry my latest log is extremly short and i am rebuilding my modpack cause there was an error so im retrying mod by mod to see what mod glitches but when i check latest i see a older log

**Comment by lucemans** [comment] 2015-12-29 22:42
is it ok if i send  you the server files and you know what to do then?

**Comment by BluSunrize** [comment] 2015-12-29 22:42
No. I will not go through your sever files for you. Either you give me the logs or I can't help you.

**Comment by lucemans** [comment] 2015-12-29 22:43
latest.log: http://pastebin.com/9BrQ2RRp

**Comment by lucemans** [comment] 2015-12-29 22:45
latest crash report: http://pastebin.com/DJdLn7Dj

**Comment by BluSunrize** [comment] 2015-12-29 22:47
Those logs are entirely unrelated to the issue at hand >_<
Obviously you have to give me logs that were generated while producing the issue.

**Comment by lucemans** [comment] 2015-12-30 07:12
yes and they are not here i just dont see them

**Comment by lucemans** [comment] 2015-12-30 07:13
i may have a idea what is going on cause IE says something about that it can recognize Wyvrn armor from Draconic Evolution before it starts to say this, and it is like giveing information about denseores

**Comment by lucemans** [comment] 2015-12-30 08:50
wait i found a way to get the whole log
log: http://pastebin.com/Sfwdxy46

**Comment by theunkn0wn1** [comment] 2015-12-30 08:54
Just looking at that log.... Retrogeneration....
That was not caused by IE and certainly will severely impact server startup time. It's this retrogen occurring EVERY time the server starts up?

**Comment by BluSunrize** [comment] 2015-12-30 09:25
Yeah the retrogen is one thing, and that log also contains no 5 minute wait. The entire startup takes 2 minutes.
I'm closing this issue now. Even with the lack of information it seems quite clear to me that no issue with IE is present.

**Closed by BluSunrize** 2015-12-30 09:25 UTC

**Comment by lucemans** [comment] 2015-12-30 09:34
can you guys please explain me what retrogeneration means? so i can continue?

**Comment by BluSunrize** [comment] 2015-12-30 09:37
It means that some mod (I suspect one that is being developed by MrTJP) is retro-actively adding ores or other features to te world. An example would be Thaumcraft which can generate nodes in a world that has already been created. Retrogen is used when you want to allow players to add ores to a world that was created before that mod was installed.

**Comment by theunkn0wn1** [comment] 2015-12-30 09:38
What Blu said. Also, the process can be as resource expensive as when the chunks where originally generated depending on the implementation.

**Comment by lucemans** [comment] 2015-12-30 09:40
so its trying to regenerate the chunks?

**Comment by lucemans** [comment] 2015-12-30 09:40
but what mod could cause this issue

**Comment by BluSunrize** [comment] 2015-12-30 09:42
Dude. We're not your google.
I already told you, it's some mod by MrTJP. And might I point out that your server started in 2 minutes? That's perfectly acceptable time. There is no issue here.

**Comment by lucemans** [comment] 2015-12-30 10:11
ok

**Comment by lucemans** [comment] 2015-12-30 10:16
mctjp and project red removed, server now working perfectly
thanks for your initialization of the problem

**Comment by mindforger** [comment] 2016-01-04 13:26
as an help for you, i only only left out project red "world" ingame known as "exploration" part of the mod, but i added replacement recipes for the missing ores to compensate (electrotine made from 1 redstone dust, 1 lapis and one gloswstone dust f.E. and reused the emeralds from Biomes o Plenty for their recipes)

this way we can use everything besides their marble and their volcanos ... but this mod part very hardly impacts server performance even when generating a new wolrd you'll have disconnects every 300m explored
