### ISSUE TITLE
[1.20.4] model for offhand Revolver and Railgun look inside out

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5949] opened 2024-06-15 17:27 UTC
### Minecraft Version

1.20.4

### Immersive Engineering Version

6e50a71f0c141dea10452fd00e2808b41c167b0c

### Expected Behavior

They look the same as when in the main hand, but mirrored.

### Actual Behavior

They look inverted. Everything is mirrored?
This affects both first and third person offhand models.

### Steps to reproduce

Place Revolver/Railgun in offhand.

### Debug Crash Log

N/A

**Comment by BluSunrize** [comment] 2024-06-16 08:16
Technically a duplicate of #5943, but that issue is compounding three different things

**Closed as completed** 2024-06-16 08:16 UTC
Labels: bug 🐛
