### ISSUE TITLE
[1.16.1]Buzzsaw use on trees crashes the game

### ISSUE THREAD

**Issue by Alex34fggh** [BluSunrize/ImmersiveEngineering#4206] opened 2020-08-13 12:47 UTC
When I use the Buzzsaw on a tree,it cuts it,but it crashes the game,even after a second login into the world.

Pastebin crash log: https://pastebin.com/Veb1T6WL (Modlist is in crash log as well)

**Comment by BluSunrize** [comment] 2020-08-13 12:51
Duplicate of #4179, will be fixed by the next release.

**Closed as completed by BluSunrize** 2020-08-13 12:51 UTC
