### ISSUE TITLE
guide book 

### ISSUE THREAD

**Issue by TweekinDragon** [BluSunrize/ImmersiveEngineering#2527] opened 2017-09-26 21:10 UTC
### Description of the issue:
looking in the book i was looking at the flood light page when i clicked the arrow to go to the next page it crashed the game. reloaded the game went to put the book back in the box and missed, it tried to open the book and crashed

### Crashlog:
https://gist.github.com/TweekinDragon/8e0d6066016be3fa0d831b824b605e34
### Versions & Modlist
Minecraft 1.12.1
ImmersiveEngineering-0.12-72 
forge-1.12.1-14.22.1.2485

**Comment by BluSunrize** [comment] 2017-09-26 21:24
But you didn't provide a crashlog or care for the issue template, so I might as well close this...

**Comment by TweekinDragon** [comment] 2017-09-26 22:45
Was in a hurry had a kid to track down, fixed the post

**Comment by mindforger** [comment] 2017-09-27 06:02
update IE, already fixed

**Comment by TweekinDragon** [comment] 2017-09-27 14:06
update it to what?

**Comment by malte0811** [comment] 2017-09-27 14:14
Don't update. @mindforger is partially right: This is fixed, but there isn't a public/official build including the fix yet. Also this is a duplicate of #2496.
When you tried to put the book into the toolbox it didn't try to open the book. WAILA/HYWLA saw the box, which caused the crash.

**Closed by malte0811** 2017-09-27 14:14 UTC

**Comment by mindforger** [comment] 2017-09-27 16:13
oh sorry, i was under the impression you already put 73 out :D my fault

**Comment by TweekinDragon** [comment] 2017-09-27 19:00
oh ok thank you i had to encase that tool box in obsidian so i didnt look at it again it crashes every time
