### ISSUE TITLE
[1.16.1] Crash after world generation

### ISSUE THREAD

**Issue by schan-99** [BluSunrize/ImmersiveEngineering#4088] opened 2020-07-16 21:07 UTC
### Description of the issue:
Crash after success world generation. After removing all other mods this one has to be "broken".
The same issue was in Mekanism mod - **NoSuchMethodError** ([It is fixed already](https://github.com/mekanism/Mekanism/issues/6340)).

### Crashlog:
[SERVER]
[crash-2020-07-16_23.58.25-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4934149/crash-2020-07-16_23.58.25-server.txt)
[debug.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4934150/debug.log)
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4934151/latest.log)

[CLIENT]
[crash-2020-07-17_00.20.13-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4934228/crash-2020-07-17_00.20.13-server.txt)
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4934232/latest.log)
(It's strange but there is no debug.log)

### Versions & Modlist
Forge: 32.0.67
Minecraft: 1.16.1
ImmersiveEngineering: 0.16-106

**Comment by steelfoot** [comment] 2020-07-17 02:33
Getting this one, with the same crash, on Forge 32.0.68 as well.  In my case, it crashes after both creating a new world and loading worlds created and played on in Forge 32.0.66.

**Comment by ChiKitsune** [comment] 2020-07-17 05:40
That is happening because as of Forge 32.0.67 how commands are registered has slightly changed.

**Comment by BluSunrize** [comment] 2020-07-17 05:51
This is also already fixed for IE.
Duplicate of #4083

Please search next time.

**Closed as completed by BluSunrize** 2020-07-17 05:51 UTC
