### ISSUE TITLE
Core  Samples have no texture 1.12

### ISSUE THREAD

**Issue by darkcloud784** [BluSunrize/ImmersiveEngineering#2467] opened 2017-09-04 15:59 UTC
All core samples taken from the core sample drill, are invisible in your inventory. When holding them they also do not show the chuck that was just analyzed like they used to.

**Comment by BluSunrize** [comment] 2017-09-04 16:47
Read the contribution guidelines and try again.

**Comment by Zebaoth** [comment] 2017-09-07 18:15
Do you run optifine by any chance? Get rid of this first since it changes how things are rendered.

**Comment by BluSunrize** [comment] 2017-09-07 18:46
See that's why I asked them to read the contribution guidelines, because they might see that Optifine isn't supported and that they should provide a modlist and shit, but I guess it's not that important?

**Comment by BluSunrize** [comment] 2017-09-09 14:54
Closing this due to lack of input.

**Closed by BluSunrize** 2017-09-09 14:54 UTC

**Comment by MauveCloud** [comment] 2018-03-01 18:17
FWIW, I am able to reproduce this, but only with Shaders active, which keeps the wooden frameworks for placed core samples visible, but turns the samples themselves invisible, and they're also invisible in my inventory, which is confusing, since I thought shaders only affected in-world blocks, not the inventory.  

Anyway, 1. I _do_ see details of the analyzed chunk when hovering the invisible core samples in inventory with the mouse (just having the core sample "in hand" doesn't provide details even in a pure-IE instance, I checked) as well as when looking directly at placed core samples, and 2. turning off shaders is sufficient to make the core samples visible again.

Note: I am okay with leaving this closed, since I am well aware that Optifine and shaders aren't supported by the mod, but I thought the extra information might be helpful for darkcloud784.
