### ISSUE TITLE
Crash start server

### ISSUE THREAD

**Issue by diaverso** [BluSunrize/ImmersiveEngineering#3247] opened 2018-10-06 16:00 UTC
### Description of the issue:
When the server is starting with some mods, an error occurs and it closes.

### Crashlog:
https://pastebin.com/TL6M6YMi
### LOG: 
https://pastebin.com/f1r5dR60

### Versions & Modlist
https://i.imgur.com/A6uPPUY.png
Version 1.12.2

**Comment by BluSunrize** [comment] 2018-10-06 16:31
Duplicate of #3241, please use the search function next time.

For a temporary fix, downgrade your Forge version.

**Closed by BluSunrize** 2018-10-06 16:31 UTC
