### ISSUE TITLE
Blast Furnaces doesnt seem to work

### ISSUE THREAD

**Issue by Wotzinator** [BluSunrize/ImmersiveEngineering#2809] opened 2018-02-21 17:27 UTC
since  version 0.12-77 the blast furnaces (normal and improved)don't seem to work anymore.
the furnaces still using fuel but don't make any progress .

i just used :
forge (newest version)
immersive engineering (0.12-77)

**Comment by MauveCloud** [comment] 2018-02-21 17:41
Duplicate of #2803.

**Comment by malte0811** [comment] 2018-02-21 17:45
^

**Closed by malte0811** 2018-02-21 17:45 UTC
