### ISSUE TITLE
Mining Drill unable to mine stone and other blocks. MC 1.10.2 IE Build 58

### ISSUE THREAD

**Issue by Matikari** [BluSunrize/ImmersiveEngineering#2147] opened 2017-06-03 01:04 UTC
Currently playing "A Grim Life" modpack [V0.5] on curse on a server. I just made the mining drill and was about to go crazy with it. But it can't mine through stone, cobblestone, polished andesite, obsidian or RC quarried stone. That's the extend of the variety of blocks I had in my vicinity to try. Currently equipped with a steel head, larger tank, and lubrication system.

**Comment by BluSunrize** [comment] 2017-06-03 07:21
and it's got fuel in it as well, I presume?

**Comment by Matikari** [comment] 2017-06-04 13:54
yes, its filled up. I can mine through dirt, get khndrel knghts. and other various stone types. But i'm assuming one of the mods edited vanilla stone and made it incompatible with the drill. making it completely useless as stone is the majority to dig through.

**Comment by malte0811** [comment] 2017-06-04 14:21
I think this is caused by Realistic Survival, AA seems to have (had?) a similar issue. I'll take a look at that mod later. It says it is licenced as GPL, so from my understanding of the licence decompiling should not be a problem (especially since it is causing issues with interoperatibility/compatibility).

**Comment by Matikari** [comment] 2017-06-04 16:06
thank you for taking a look. even tho it might not be a problem on your side.

**Comment by malte0811** [comment] 2017-06-04 17:00
Turns out I didn't need to decompile this at all, the download jar file contains the code.
@DBurgdorf I had a look at `EventHandlerCommon#isMissingTool`. I am not exactly sure what you are trying to do there, a big part of it seems to mimic part of the vanilla logic, missing the parts necessary for the drill to work. Specifically you would need to check `Item.canHarvestBlock(IBlockState, ItemStack)` to make the drill work. I don't know whether that would make the method completely useless, you will probably know though.
An unrelated potential bug I noticed: You are comparing strings using == (in line 586). You should be using .equals, Java is not C++/C#/any language with operator overloading.

**Comment by BluSunrize** [comment] 2017-06-13 12:31
Any further input on this, or shall I close the issue?

**Comment by malte0811** [comment] 2017-06-13 12:41
I don't think there is anything we can do about this that doesn't involve hacky high priority event handlers and breaking a lot of other stuff. This is on @dburgdorf's side to fix, he is cancelling the harvest event if the tool does not pass his harvest check which does not include `canHarvestBlock`.

**Closed by malte0811** 2017-06-13 12:41 UTC
