### ISSUE TITLE
[1.16.5] Immersive Engineering crash

### ISSUE THREAD

**Issue by GeorgeOrwell1** [BluSunrize/ImmersiveEngineering#4669] opened 2021-02-23 09:35 UTC
### Description of the issue:
When I launch the game, after a while, the game crashes and I get this screen:
![bild](https://user-images.githubusercontent.com/72312697/108821568-17e43580-75be-11eb-80f9-8713a0fd8f85.png)
However, when I start Minecraft again, the crash disappears and I can play as usual.

### Crashlog:
[Crash](https://pastebin.com/0Sfg1uAK)

### Versions & Modlist
Mods in Crashlog (see above) + Forge 36.0.40
ImmersiveEngineering-1.16.5-4.2.1-131

**Comment by malte0811** [comment] 2021-03-01 10:41
Duplicate of #4636

**Closed as completed by malte0811** 2021-03-01 10:41 UTC
