### ISSUE TITLE
1.11.2 Modpack - Assembler Crashing Game

### ISSUE THREAD

**Issue by Branjoman** [BluSunrize/ImmersiveEngineering#2276] opened 2017-07-09 13:55 UTC
Using the assembler to perform any crafting function (in my case, converting pumpkins to pumpkin seeds) causes the game to crash, and leaves that save completely inoperable, as when you try to open the world, it just hangs at "building terrian".

[https://pastebin.com/rC0GN8XM](url)

**Comment by malte0811** [comment] 2017-07-09 14:14
Known, duplicate of at least 5 other reports, probably more and fixed in build 63.

**Closed by malte0811** 2017-07-09 14:14 UTC
