### ISSUE TITLE
[1.14.4] Latest version incompatible with cooking for blockheads

### ISSUE THREAD

**Issue by facetorched** [BluSunrize/ImmersiveEngineering#3896] opened 2020-06-02 19:13 UTC
I updated to the latest beta version of IE and my game crashes whenever I try to open a world while both Immersive Engineering and cooking with blockheads mods are installed. Seems like an issue with multiblocks.

Crashlog:
https://pastebin.com/JzrJhpNK

Mods:
forge-1.14.4-28.2.16
ImmersiveEngineering-0.14-96
CookingForBlockheads_1.14.4-7.4.4

**Comment by BluSunrize** [comment] 2020-06-02 20:03
Duplicate of #3884, fixed for next release

Please use the search function next time =)

**Closed by BluSunrize** 2020-06-02 20:03 UTC

**Comment by facetorched** [comment] 2020-06-02 22:06
Oops I only looked through the open issues
