### ISSUE TITLE
[CRASH] [11.2 0.11-62] Assembler crashes when crafting melon seeds

### ISSUE THREAD

**Issue by Ryusabre** [BluSunrize/ImmersiveEngineering#2224] opened 2017-06-25 02:43 UTC
The assembler crashes every time I try to turn melons into seeds. I haven't tried other recipes yet, so I don't know if it's the assembler in general, just shapeless recipes, or just melon seeds.

Crash report: https://pastebin.com/ENANF5Fs

Mods: Just IE and JEI

**Comment by malte0811** [comment] 2017-06-25 07:57
Duplicate of #2196. Fixed for the next release.

**Closed by malte0811** 2017-06-25 07:57 UTC
