### ISSUE TITLE
Crash while reading manual

### ISSUE THREAD

**Issue by Thyriel** [BluSunrize/ImmersiveEngineering#1916] opened 2017-02-27 08:02 UTC
I was reading somewhere on the site about alloys (got there by the alloy link on the hammer site)
http://pastebin.com/5XDcVj9D

**Comment by malte0811** [comment] 2017-02-27 13:18
Try removing OptiFine. It is not supported (though I might try fixing interaction bugs when I am very bored). Also, what have you done to that crash log? It looks to me as if the first stacktrace has been cut out?

**Comment by Thyriel** [comment] 2017-02-27 18:13
That's the full crash report as saved in the textfile.
And well, removing optifine is not an option because of shaders ;)

**Comment by BluSunrize** [comment] 2017-02-27 21:19
Optifine isn't supported though. The contribution guidelines quite clearly state this, I would recommend taking a look there.
If the issue isn't reproducable without Optifine, it is not a valid issue.

**Comment by mindforger** [comment] 2017-02-28 07:39
@Thyriel just try it without optifine to check if that may be the issue, he does not want you to not use it in general, but you can not expect for him to solve an issue that is caused by optifine

**Comment by Thyriel** [comment] 2017-02-28 16:26
Somehow i can't reproduce the crash now, not with nor without optifine.

**Comment by BluSunrize** [comment] 2017-02-28 20:58
Guess I'll close this then .-.

**Closed by BluSunrize** 2017-02-28 20:58 UTC
