### ISSUE TITLE
[1.8.9][bug] Shift clicking wand into tool box causes crash

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#1168] opened 2016-05-31 12:44 UTC
If there is a slot in the engineers tool box and you shift click a wand (thaumcraft) it crashes the client, cant seem to find the crash log will. will reproduce once i'm home and post CL.

IE: 0.8-27
Forge 11.15.1.1902

**Comment by XFactHD** [comment] 2016-05-31 13:46
There is a pending PR with a fix for this.

**Comment by malte0811** [comment] 2016-05-31 14:22
Duplicate of #1164. Any non-block item will cause this crash.

**Comment by elkillo** [comment] 2016-05-31 22:26
I see feel free to close this one.

**Comment by BluSunrize** [comment] 2016-05-31 23:29
You can do that yourself, you know...

**Closed by BluSunrize** 2016-05-31 23:29 UTC
