### ISSUE TITLE
HV cables with Thermal Dynamics Cryo-Stabilized Fluxducts

### ISSUE THREAD

**Issue by MikrySoft** [BluSunrize/ImmersiveEngineering#385] opened 2015-09-03 09:40 UTC
I was doing tests on IC2 power transfer capability of IE, when I noticed that I can push 50k EU/t (MFSU from 0 to 100% in 40s) through a single HV connection if I use Cryo-Stabilized ducts.
My setup was literally like this:
[HUGE EIO capacitor bank][Duct][HV Connector][HV Connector][MFSU]. 

Capacitors were pushing out 200kRF/t through a single HV link. Later tests (with much beefier power source) showed that I could push 2MRF/t through a single connection. 

This happens only with Cryo-Stablized ducts (which I know are coded to ignore power transfer limits), replacing the duct powering the HV connector with any other one gave me proper 4kRF/t transfer rate.

Mods installed: FTB Infinity 1.10.1 
IE version 0.5.1

**Comment by theunkn0wn1** [comment] 2015-09-04 05:50
Yeah, was able to do something like this a while back in those older versions, can you reproduce this with the latest IE builds? 

Current builds are 0.6.0_pre if you build it from source, and 0.5.4 in curse iirc

**Comment by malte0811** [comment] 2015-09-04 05:57
I am able to reproduce in the latest version as of 12 hours ago. I added some debug output, when there is more than one side of the fluxduct touching the capacitor bank, `transferEnergy` gets called that amount of times on the same connector. However it happens at apparently random times qith only one connection as well

**Comment by theunkn0wn1** [comment] 2015-09-04 06:27
I can reproduce this intermittently, Though is more frequent if i have the below setup

HV mains line, can carry over 10KiRf/T (4096 per connection).
Hv mains feeds into a transformer. HV-> Mv, the output of the transformer directly connects to the cryo duct. The duct connects directly to the storage device. Sometimes i get the full max load of the circuit, others at the correct rate

**Comment by BluSunrize** [comment] 2015-09-04 15:36
We'll see if this persists after the switch to the new energy system.

**Comment by cobra** [comment] 2015-09-12 19:09
It still happens. My setup: current IE master branch, latest EnderIO beta dev, Thermal Dynamics 1.1.0, two 4x3 vibrant capacitor banks, one full, one empty, cryo-stabilized fluxducts on top, HV connector and wire between them. *I'm also getting a shitton of lag (including 0 fps) once I put a HV connector on something powered, so testing is not really fun. Will investigate the lag issue first.*
Screenshot of the receiving end:
![](https://cloud.githubusercontent.com/assets/163331/9833301/d35d1236-5991-11e5-86e8-8f003f7f889a.png)

**Comment by mindforger** [comment] 2015-09-14 12:27
which exact version are you running on? this sounds like the memory leak from earlier that should have been fixed. 
By the way, did you configure the output faces of the capacitor to be in OR out ? having them on bipolar mode produced very strange issues for XHFactHD and me with cryoducts

**Comment by cobra** [comment] 2015-09-14 14:25
Must have been 41cf1bb8ffa37765a8bcfdb81d4487725689cd98.
I configured all 8 faces to be "in" for the empty (shown) bank or "out" for the full one. nothing and "in/out " did strange things, looked somehow oscillating.
I've just started looking into the lag issue with opis (which won't run from idea, damnit) and it's still noticable. I'll do some systematic testing to collect numbers for this. I feel like the bad lag in this specific case is caused by the excessive transfers multiplying the already existing lag.

**Comment by cobra** [comment] 2015-09-16 21:24
Found the cause of the massive lag. It's the insane debug logging. -.-
After removing all IELogger.debug calls from transferEnergy it's running very smoothly.

**Comment by cobra** [comment] 2015-09-20 17:05
It's fixed now! Errr, okay… not in the most desirable way. The wire just burns up.

I'm currently digging into the decompiled thermal dynamics code and trying to figure out how to stop this. All other high-power transport methods I tested so far (resonant fluxducts, ender energy conduits) are working fine.

**Comment by malte0811** [comment] 2015-09-20 17:23
Have you tried storing the world time of the last non-simulate transferEnergy call in the tile entity and returning 0 in transferEnergy if that time is the current world time, therefore preventing more than one call per world tick? From what i saw when debugging from ie's side thermal dyn. is calling transferEnergy on the hv connector once for each connection to an energy source. The reason this is not noticable with most other transfer systems might be that they either have unlimited transfer rate or have buffers that limit the transfer rates.

**Comment by BluSunrize** [comment] 2015-09-20 17:29
I talked to Lemming, they just insert multiple times per tick, that's what's causing it.

**Comment by cobra** [comment] 2015-09-20 18:03
Yep, exactly this. Why do they do multiple insertions per tick? I guess this could break other mods as well.

I also thought about using world time to limit the transfers to 1 per tick earlier. Something like "time==storedtime → abort" shouldn't be that susceptible to breaking even in weird environments, right? Either doing that or detecting that this transfer is already in the queue, but this would need more changes to the energy net code (blergh).

BTW, slightly OT, but relevant for you two: I experienced some more or less weird issues and an NPE (at [ImmersiveNetHandler.java:220](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/energy/ImmersiveNetHandler.java#L220) when using the wire on a connector where a wire burnt up before) with wires burning up, but couldn't reproduce them reliably. Not yet - I'll do my best at testing when I notice something odd.

**Comment by BluSunrize** [comment] 2015-09-20 18:20
They do this to simulate infinite transfer. Lemming's statement was: "Nowhere on that method it says that it may only happen once per tick", and he's got a point with that.
Anyway, wires burn, issue solved. Just don't try to input infinite power into a limited system. xD

**Closed by BluSunrize** 2015-09-20 18:20 UTC

**Comment by cobra** [comment] 2015-09-20 18:38
Technically, he's absolutely right - but I wouldn't want to bet that everyone else realizes this. I guess most people think in rf/t and will implicitly limit that to one transfer per tick.

The timing "hack" is working as far as I tested and shouldn't have a noticeable impact. What are your thoughts on this? Add this or just let the wires burn up in these rather weird setups?

**Comment by BluSunrize** [comment] 2015-09-20 18:43
let them burn. I don't want to hack against TD. Lemming and Tema knew what they were doing.

**Comment by cobra** [comment] 2015-09-20 19:08
Also, whoever tries to do this is wasting these ducts when a cheap redstone fluxduct is more than sufficient.
