### ISSUE TITLE
Can u help me?

### ISSUE THREAD

**Issue by HurtsAsHell** [BluSunrize/ImmersiveEngineering#2933] opened 2018-04-10 18:24 UTC
I just need to know what I skipped, following the guide I do not understand what is missing;

mods.immersiveengineering.Excavator

//Exavetor addRecipe
//mods.immersiveengineering.Excavator.addMineral(String name, int mineralWeight, double failChance, String[] ores, double[] chances, @optional int[] dimensionWhitelist, @optional boolean blacklist);
mods.immersiveengineering.Excavator.addMineral("Iron Ore", 25, 0.5,["btt:deep_iron_ore"], [0.02]);

**Comment by BluSunrize** [comment] 2018-04-10 22:48
You will need to specify your issue a bit more than that, I'm afraid. Version numbers, what you are trying to do, what errors you are getting, log files, all that stuff.

**Comment by HurtsAsHell** [comment] 2018-04-11 20:50
I would like to add a mineral to the exavator;
added the string above, it does not happen except for a minetweaker error; I have the Immersive Engineering version 0.12 - 80

craftweaker
https://pastebin.com/qwA7YJ6d

fml
https://pastebin.com/FUC5beAV

**Comment by PrincessRTFM** [comment] 2018-04-12 04:14
Line 83:

> [INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing Immersive_Eng.zs:5 -- ; expected

You're missing a semicolon around line five in `Immersive_Eng.zs` and it can't process the file.

**Comment by bookerthegeek** [comment] 2018-04-12 05:08
The issue is the code is escaped.

**Comment by HurtsAsHell** [comment] 2018-04-13 17:57
This is the file .zs [https://pastebin.com/NwTRN8C8](url)

**Comment by BluSunrize** [comment] 2018-04-13 22:32
Ores should have OreDictionary names, not registry names.

**Comment by HurtsAsHell** [comment] 2018-04-13 23:34
For example oreIron?

**Comment by HurtsAsHell** [comment] 2018-04-14 10:58
do you have a guide that explains better than the wiki?

**Comment by BluSunrize** [comment] 2018-04-14 16:04
Well I didn't write the wiki, so no =P

But yes, only OreDictionary names work (if I remember my own code here). So "oreIron", "nuggetGold", that sort of stuff. You can usually figure those out with the ```/mt hand``` command

**Comment by HurtsAsHell** [comment] 2018-04-14 18:09
So I need to create one OreDictionary?

**Comment by BluSunrize** [comment] 2018-04-14 21:35
No you need to use items that are already registered or use Minetweaker to register them (if that option still exists)

I'll be closing this for now, since it's a question of Minetweaker functionality.

**Closed by BluSunrize** 2018-04-14 21:35 UTC
