### ISSUE TITLE
Multiblock duplication issue 

### ISSUE THREAD

**Issue by Bertieio** [BluSunrize/ImmersiveEngineering#2025] opened 2017-04-19 18:48 UTC
Every multiblock I create seems to create ghost blocks all around it. 

I am running the latest stable FTB Beyond Build on a server
 
![2017-04-19_19 43 50](https://cloud.githubusercontent.com/assets/9221294/25196546/eaace7bc-2538-11e7-91ae-552d95a6fc82.png)

**Comment by malte0811** [comment] 2017-04-19 19:15
I guess you are running SpongeForge on said server? If that is the case, this is a duplicate of #1941 and a few others. You can work around this by disabling `optimizations` (or something like that) in the SpongeForge config.
The deeper cause of this is the multithreaded lighting Sponge adds interfering with `TileEntity` creation, there is a comment with some technical details in the SpongeForge issue linked in #1941. In my opinion this is a bug in SpongeForge (and I am not sure whether this is even fixable in IE without an insane amount of work), so we can't do much about that.

**Comment by bloodmc** [comment] 2017-05-11 15:50
@malte0811 I fixed this in a recent SpongeForge commit. You can close this ticket.

**Comment by malte0811** [comment] 2017-05-11 16:48
I can't, I am just a contributor, not a collaborator. @BluSunrize could close this issue though.

**Comment by BluSunrize** [comment] 2017-05-11 18:53
Yay! Glad to see that fixes were found ^_^

**Closed by BluSunrize** 2017-05-11 18:53 UTC

**Comment by darthvader45** [comment] 2018-05-14 17:04
This probably should be reopened.  I'm testing this with 0.12-82 in singleplayer, and it randomly happens when either loading a world or teleporting around via VoxelMap.  Might be some issue between this mod and Liteloader, as VoxelMap's teleport function seems to call directly on the vanilla Minecraft /tp command.
