### ISSUE TITLE
[1.16.4] HV transformer doesn't work

### ISSUE THREAD

**Issue by Railroadactive** [BluSunrize/ImmersiveEngineering#4546] opened 2020-12-31 17:24 UTC
It appears that the HV transformer doesn't work. I tried to power my refinery setup from my LV windmills and routing the power through it but no power went through, then I tried to power my garden cloches that receive LV power. HV power is getting to the transformer but no power is coming out the LV side.

**Comment by BluSunrize** [comment] 2021-01-03 10:18
An HV transformer does not miraculously increase the power. A windmill is far too weak to power a refinery. This is not an issue, you are merely providing far too little power.

**Comment by Railroadactive** [comment] 2021-01-03 13:57
Yes, I understand that, However, it still doesn't work. I've attached a current transformer between the HV transformer with two diesel generators running on the HV side and load on the LV side and it is reading 0 RF/T so there is something wrong it it @BluSunrize

**Comment by BluSunrize** [comment] 2021-01-03 14:21
Provide pictures of your setup, and tell me how you measured the power. Especially since IE doesn't use "RF/t" as a designation.

**Comment by Railroadactive** [comment] 2021-01-03 14:33
#
![Screenshot (18)](https://user-images.githubusercontent.com/41083589/103481086-718e6780-4da6-11eb-999f-04be96223454.png)

First off, I realized I got the units wrong, 
Second, all other loads on the HV system are turned off and all loads on LV side turned on. After right clicking numerous times, there is no power being transferrered from HV to LV.

**Comment by BluSunrize** [comment] 2021-01-03 15:19
Do you have anything actually *using* the power? It's only transferred if you have something on the other side that accepts that power.

Please provide pictures of your energy generation, as well as your energy usage.

**Comment by Railroadactive** [comment] 2021-01-03 15:40
Yes, like I said, all loads (28 garden cloiches) on the LV side are on, when I apply power from my windmill farms, everything works fine, when I disconnect the LV line from the windmills and only get power from the two diesel generators on the HV side, nothing works. Will post pictures of generator outputs and garden cloche setups

**Comment by Railroadactive** [comment] 2021-01-03 15:51
![Screenshot (19)](https://user-images.githubusercontent.com/41083589/103482868-67be3180-4db1-11eb-86ca-6f8829bc3e38.png)
![Screenshot (20)](https://user-images.githubusercontent.com/41083589/103482871-6c82e580-4db1-11eb-89d7-57a1620e3a0c.png)
![Screenshot (21)](https://user-images.githubusercontent.com/41083589/103482875-7278c680-4db1-11eb-9b58-878943e57839.png)
![Screenshot (22)](https://user-images.githubusercontent.com/41083589/103482883-799fd480-4db1-11eb-84d1-6fd5fdef28e1.png)
![Screenshot (23)](https://user-images.githubusercontent.com/41083589/103482893-8290a600-4db1-11eb-89da-e70bda1ab038.png)

**Comment by BluSunrize** [comment] 2021-01-03 16:19
Are your capacitors set up to output on the side where you are trying to take your power from?

**Comment by Railroadactive** [comment] 2021-01-03 16:29
Yes, I have my refinery and excavator hooked up the HV system. Everything on my HV and LV works fine until I try to power my LV from the HV through the HV transformer.

**Comment by BluSunrize** [comment] 2021-01-03 20:02
Now, if I understand you corrrectly, your path (after the generators) is
HV Capacitor -> HV Wire -> HV Transformer -> MV Wire -> Cloche?

If so, can you wire the same thing up in creative and see if you come to the same issue?

**Comment by AllThatJazz139** [comment] 2021-01-05 20:20
Hello, I am also having this issue with the HV Transformers in the 1.16.4 build atm. My setup currently is using 6 windmills and 4 Thermoelectric generators (Blue Ice and Uranium) connected with MV wires --> 1 HV Transformer --> HV Capacitor --> Another (Different) HV Transformer --> back to MV wires hooked up to 20 Garden Cloches and 1 Fluid Pump with an MV Capacitor acting as a buffer. None of the machines past the Transformer receive power. 

I have tried simplifying the overall circuit and double and triple checked inputs and outputs as well using Generators (HV Wires) --> HV Transformer -->(MV Wires) Cloche and still experience the same issue both on the server I run and on a single-player test world.

(Pictures included below, sorry if I was supposed to make a new thread about this I haven't used GitHub much before this.)

![2021-01-05_12 13 44](https://user-images.githubusercontent.com/77024394/103694806-6d05b280-4f50-11eb-8c28-21f90f6d8d2d.png)
![2021-01-05_12 13 33](https://user-images.githubusercontent.com/77024394/103694811-6ecf7600-4f50-11eb-9601-ba7dbf14591c.png)

**Comment by smoothuk** [comment] 2021-01-19 19:16
I had this problem and managed to fix it by breaking and re-placing the HV Transformers, so try that if you didn't already.

**Comment by Aticius** [comment] 2021-03-27 03:28
Reproduced on version 4.2.4-134.

**Comment by BluSunrize** [comment] 2021-03-27 10:12
> 
> 
> Reproduced on version 4.2.4-134.

Pictures please?

**Comment by GaviGuy** [comment] 2021-04-19 02:11
I have the same issue. Breaking and replacing fixes, but that's a big pain when the wires break too, especially with how often it happens.

Setup is as simple as they get:
HV Cap -> HV Trans -> MV Cap
![IE bug](https://user-images.githubusercontent.com/32558961/115171874-46900100-a081-11eb-9481-db81688b6d24.png)

In the pic, the HV Cap has 522.2 kIF, HV Conn has 4.1k, the MV Conn has 0, and the MV Cap has 138.2k.
Breaking and replacing the transformer and wires returns operation to normal.
Unsure what causes it to stop working.

Minecraft 1.16.5
Immersive Engineering 4.2.4-134

**Comment by ALEXTHENINJA007** [comment] 2021-05-17 12:12
Hi I also had this issue,
**Cause:** Unknown (I'd test chunk loading/world loading first)
**Problem:** HV Transformer stops working  
**Temporary solution:** Breaking HV transformer and associated wires fixes.
**Version:** ImmersiveEngineering-1.16.5-4.2.4-134
**Multiplayer: ** true
**Other Mods:** true (Immersive Engineering is the only one doing power stuff however) [Mod List](https://pastebin.com/0Z5x5xRg)  Version Numbers can be requested
**Description**: 
On the Medium Voltage side: 
HV Transformer was (in order) x1 Transformer (Output),  x1 LV Capacitor, 4x LV Relays, 3x LV Capacitors to 3x (Uranium Blue Ice) Thermoelectric generators one of the generators has Blue Ice and Uranium block but not on opposite sides (awaiting materials to complete.)
On the High Voltage side: 
HV Transformer was (In order) x1 HV Capacitor (Input this is how I knew it wasn't working), A bunch HV relays to Transformers then to LV Grid with 1x Crusher, 1x External Heater (4x) Furnaces 1x WaterMill (x3 Mills),  A bunch of HV relays to Transformers to LV relays to 1x Blast Furnace Pre-Heater.
![image](https://user-images.githubusercontent.com/1555247/118485857-435d6300-b75c-11eb-9a78-e64cef308a3d.png)

**Comment by alex36917** [comment] 2022-09-06 01:21
I would like to add something to this. Here is a setup I have.

high voltage wire (always on) -> HV transformer -> MV relay -> transformer -> double LV connector block -> lantern

This all works out fine at first, and the lantern turns on. But if I use wire cutters on the double LV connector block and then reconnect the two wires as they were, power does not go from the double LV to the lantern. (It does go from the transformer to double LV connector block though.

                                             on                         on                on                    on                                          off!
high voltage wire (always on) -> HV transformer -> MV relay -> transformer -> double LV connector block -> lantern


I have a video here:   https://drive.google.com/file/d/1VXJIqv4pPBj28xRmgLfldAhb_YK0MWf6/view?usp=sharing

This may also happen if you break one of the other wires. Also note that when I do this, sometimes the transformers also stop working, meaning only the HV wire works and I have to break and replace the transformers and connector block.

details================
mod version: ImmersiveEngineering-1.18.2-8.2.2-154
singleplayer
forge: 1.18.2-forge-40.1.69

**Comment by BluSunrize** [comment] 2022-09-18 09:51
Support for 1.16 has ended a while back.
If you can reproduce this for 1.18, please open a new issue with detailed setups.

**Closed as not planned by BluSunrize** 2022-09-18 09:51 UTC
