### ISSUE TITLE
[1.12-77] Blast furnace consumes fuel without making steel.

### ISSUE THREAD

**Issue by Flanks255** [BluSunrize/ImmersiveEngineering#2821] opened 2018-02-24 18:12 UTC
In IE 77, in MC 1.12.2 with fore 14.23.2.2611
The blast furnace consumes fuel, without actually producing steel.
tried with multiple versions of forge, and a test pack with only IE
IE 76 works, IE 77 does not.

**Comment by malte0811** [comment] 2018-02-24 18:57
Duplicate of #2803. Fixed for build 78.

**Closed by malte0811** 2018-02-24 18:57 UTC
