### ISSUE TITLE
[1.16.4] Rendering overlay crash when using any resource pack or OF shader.

### ISSUE THREAD

**Issue by KohlrabitoDev** [BluSunrize/ImmersiveEngineering#4508] opened 2020-12-18 18:23 UTC
### Description of the issue:
When enabling a resource pack or OF shader it crashes the entire game. I've identified it's ImmersiveEngineering because I took the mod out and enabled a pack & shader and it worked just fine. When I put it back in, it crashes.

### Crashlog:
https://pastebin.com/GtF7Avau

### Versions & Modlist
Forge: minecraft forge: 35.1.0
Mod List: 
		forge-1.16.4-35.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		fullbrightnesstoggle_1.16.3-1.1.jar               |Full Brightness Toggle        |fullbrightnesstoggle          |1.1                 |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.1-128.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.1-128    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.16.4-13.0.0.422-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.422   |DONE      |NOSIGNATURE
		dungeons-plus-1_16_4.jar                          |Dungeons Plus                 |dungeons_plus                 |1.1.0               |DONE      |NOSIGNATURE
		CreativeCore_v2.0.7_mc1.16.2.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		Guide-API-VP-1.16.4-2.2.0.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.0               |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |DONE      |NOSIGNATURE
		Botania-1.16.3-409.jar                            |Botania                       |botania                       |1.16.3-409          |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		Mantle-1.16.3-1.6.40.jar                          |Mantle                        |mantle                        |1.6.40              |DONE      |NOSIGNATURE
		collective-1.16.4-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		ReAuth-1.16-Forge-3.9.3.jar                       |ReAuth                        |reauth                        |3.9.3               |DONE      |3d:06:1e:e5:da:e2:ff:ae:04:00:be:45:5b:ff:fd:70:65:00:67:0b:33:87:a6:5f:af:20:3c:b6:a1:35:ca:7e
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		rats-7.0.1-1.16.3.jar                             |Rats                          |rats                          |7.0.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		champions-forge-1.16.3-2.0.0.1.jar                |Champions                     |champions                     |1.16.3-2.0.0.1      |DONE      |NOSIGNATURE
		Vampirism-1.16.4-1.6.3.jar                        |Vampirism                     |vampirism                     |1.6.3               |DONE      |NOSIGNATURE
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		iceandfire-2.1.3-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.3-1.16.4        |DONE      |NOSIGNATURE
		BetterPvP_20.28.2_Forge_1.16.4.jar                |Better PVP Mod                |xaerobetterpvp                |20.28.2             |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.0-universal.jar                 |Forge                         |forge                         |35.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		inventoryhotswap-1.16-1.0.jar                     |Inventory Hotswap             |inventoryhotswap              |1.0                 |DONE      |NOSIGNATURE
		Quark-r2.4-278.jar                                |Quark                         |quark                         |r2.4-278            |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		Aquaculture-1.16.4-2.1.6.jar                      |Aquaculture 2                 |aquaculture                   |1.16.4-2.1.6        |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0-beta.10.jar           |GeckoLib                      |geckolib3                     |3.0.0-beta.10       |DONE      |NOSIGNATURE
		ars_nouveau-1.16.3-1.8.1.jar                      |Ars Nouveau                   |ars_nouveau                   |1.8.1               |DONE      |NOSIGNATURE
		structure-gel-api-1.16.4-1.7.2.jar                |Structure Gel API             |structure_gel                 |1.7.2               |DONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		farlanders-1.16.4-1.3.5.jar                       |The Farlanders                |farlanders                    |1.3.5               |DONE      |NOSIGNATURE
		BetterAdvancements-1.16.3-0.1.0.102.jar           |Better Advancements           |betteradvancements            |0.1.0.102

**Comment by malte0811** [comment] 2020-12-18 21:10
Does this happen without Optifine? If it does, please upload log without OF. If it doesn't: OF is not supported exactly because it causes a lot of issues (and because it's not really possible to see *how* OF is causing them since it's closed-source).

**Comment by KohlrabitoDev** [comment] 2020-12-18 21:49
Yep, still happens without OF.
https://pastebin.com/MFgpTBuP

Doesn't happen if I take out all of my other mods besides Immersive Engineering, I'd like to test it by just adding in mods slowly but I really don't have the time at the moment, it could be an issue of conflicting with other mods but since it seems I can enable resource packs without IE, I'm, unfortunately, gonna have to remove it, but I hope these logs can help you identify any problems! Please ping me if there's a bug fix for this!

**Comment by XFactHD** [comment] 2020-12-19 00:10
This is a bug in Ars Nouveau and has been fixed [here](https://github.com/baileyholl/Ars-Nouveau/commit/8d14be3936561ef9491d297f4648f43ed11f108f#diff-8da7d92e0ae2a94f6aee346fd2a5eaaf60c66d30182e97b7aed36024fff70a05R62). Please check if there is a new version of Ars Nouveau.

**Comment by Svangen** [comment] 2020-12-19 10:22
I had the same problem. I tried it in both All the Mods 6 and the DW20 pack. The issue is with Ars Nouveau and Immersive Engineering. The same issue came up when I loaded an instance with just IE and AN and loaded a resource pack. Any resource pack seems to do it. I used Faithful, and a bunch of other ones as well. Oddly enough it worked fine if I disabled AN or IE, loaded the resource pack, and then enabled the mod and restarted the instance. However, I didn't have sound when I did that, but it could have been unrelated.

Here's my crash report from ATM6: https://pastebin.com/4R17tHfU

Ars Nouveau 1.16.3 1.8.1 (newest)
Immersive Engineering 1.16.4 4.1.1-128 or 4.1.2-129
Forge 35.1.13

**Comment by XFactHD** [comment] 2020-12-23 22:52
A new version version of Ars Nouveau has been released, please check if that fixes it @Svangen @KennethRhodes8213.

**Comment by Taeleus** [comment] 2020-12-27 22:21
> I had the same problem. I tried it in both All the Mods 6 and the DW20 pack. The issue is with Ars Nouveau and Immersive Engineering. The same issue came up when I loaded an instance with just IE and AN and loaded a resource pack. Any resource pack seems to do it. I used Faithful, and a bunch of other ones as well. Oddly enough it worked fine if I disabled AN or IE, loaded the resource pack, and then enabled the mod and restarted the instance. However, I didn't have sound when I did that, but it could have been unrelated.
> 
> Here's my crash report from ATM6: https://pastebin.com/4R17tHfU
> 
> Ars Nouveau 1.16.3 1.8.1 (newest)
> Immersive Engineering 1.16.4 4.1.1-128 or 4.1.2-129
> Forge 35.1.13

I am having a similar issue trying to run SEUS PTGI or BSL shaders with Valhelsia 3 modpack. Error is as follows.
"The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Immersive Engineering (immersiveengineering) encountered an error during the done event phase
Exit Code: -1"

This happens anytime I try to load a shader in the game. Did as much looking around online as I could and just came to this. Anyone else have any kind of resolution? Also I checked and Valhelsia does not have the Ars Nouveau mod.

**Comment by Svangen** [comment] 2020-12-27 22:28
> A new version version of Ars Nouveau has been released, please check if that fixes it @Svangen @KennethRhodes8213.

Yes. This issue has been fixed in Ars Nouveau 1.9.2. Try DW20 pack has updated for his version, but maybe the ATM6 pack has not, so people are still having the issues. It was an Are Nouveau issue and should be all fixed tho, so you can close this issue :)

**Comment by Svangen** [comment] 2020-12-27 22:30
> > I had the same problem. I tried it in both All the Mods 6 and the DW20 pack. The issue is with Ars Nouveau and Immersive Engineering. The same issue came up when I loaded an instance with just IE and AN and loaded a resource pack. Any resource pack seems to do it. I used Faithful, and a bunch of other ones as well. Oddly enough it worked fine if I disabled AN or IE, loaded the resource pack, and then enabled the mod and restarted the instance. However, I didn't have sound when I did that, but it could have been unrelated.
> > Here's my crash report from ATM6: https://pastebin.com/4R17tHfU
> > Ars Nouveau 1.16.3 1.8.1 (newest)
> > Immersive Engineering 1.16.4 4.1.1-128 or 4.1.2-129
> > Forge 35.1.13
> 
> I am having a similar issue trying to run SEUS PTGI or BSL shaders with Valhelsia 3 modpack. Error is as follows.
> "The game crashed whilst rendering overlay
> Error: net.minecraftforge.fml.ModLoadingException: Immersive Engineering (immersiveengineering) encountered an error during the done event phase
> Exit Code: -1"
> 
> This happens anytime I try to load a shader in the game. Did as much looking around online as I could and just came to this. Anyone else have any kind of resolution? Also I checked and Valhelsia does not have the Ars Nouveau mod.

I think that that is a different issue. Valhesia is a 1.15.2. The issue was with Are Nouveau for version 1.16.4. I would start a separate issue on GitHub because this is about a different minecraft and mod version

**Comment by Taeleus** [comment] 2020-12-28 03:05
Valhesia that I am running is Valhesia 3. which is on 1.16.4 as seen here
https://www.curseforge.com/minecraft/modpacks/valhelsia-3

So the same version of minecraft talked about here. Valhesia is also not running Are Nouveau on their modlist. checked online and in the game. Also, using the immersive engineering mod listed here. ImmersiveEngineering-1.16.4-4.1.2-129.jar. Any ideas anyone?

**Comment by XFactHD** [comment] 2020-12-28 17:50
@Taeleus that is a completely different issue, please open a new issue and provide a crash report.

**Comment by Taeleus** [comment] 2021-01-02 19:28
I have followed your instructions and created a new topic as seen above. I still dont see how its a different issue. The OP said that when they loaded shaders it crashed the game and they narrowed it down to ImmersiveEngineering. My game is crashing anything I load shaders and its due to ImmersiveEngineering. Not trying to be any kind of way when I ask this, but can you specify how my issue is different than the OP? There are other mods on the list yes but its all on version 1.16.4 and we both pegged it down to ImmersiveEngineering.

**Comment by XFactHD** [comment] 2021-01-03 02:43
The reason is that your crash is completely different from the one the OP posted. Yours looks like a startup crash, the one the OP posted is while the game is running. Can't say much more because you have still not provided a complete crash report, please do that your new issue.

**Comment by Taeleus** [comment] 2021-01-03 02:46
The game crashes when I load the shader. from main menu, or from in multiplayer, or from in single player. I can load up and play the game perfectly fine. But whenever I load up the shader the game crashes.  Where would I find a complete crash report? All it gives me is that error after the client completely closes. If I can find one I will gladly include it on the other post.

**Comment by xDragonxBornx** [comment] 2021-04-12 22:38
I was having the same issue as you. Changing the immersive engineering config seemed to fix the issue

#Disables most lighting code for certain models that are rendered dynamically (TESR). May improve FPS.
#Affects turrets and garden cloches
disableFancyTESR = true

#Set to false to disable the stencil buffer. This may be necessary on older GPUs.
stencilBufferEnabled = false

**Comment by dkaloger** [comment] 2021-05-06 11:25
> I was having the same issue as you. Changing the immersive engineering config seemed to fix the issue
> 
> #Disables most lighting code for certain models that are rendered dynamically (TESR). May improve FPS.
> #Affects turrets and garden cloches
> disableFancyTESR = true
> 
> #Set to false to disable the stencil buffer. This may be necessary on older GPUs.
> stencilBufferEnabled = false

Works like a charm. Ty

**Closed as completed** 2021-05-06 11:39 UTC

**Comment by Barerock** [comment] 2021-05-27 21:24
Sorry to comment on this again, but those cfg changes didn't fix the crash for me. Still fully due to IE - remove it and it functions, add it on and it doesn't.

**Comment by BluSunrize** [comment] 2021-05-27 21:32
It's an optifine issue and optifine is not supported.
