### ISSUE TITLE
[1.14.4] crash help :/

### ISSUE THREAD

**Issue by dankdan02** [BluSunrize/ImmersiveEngineering#3710] opened 2020-03-26 16:18 UTC
[crash-2020-03-26_11.01.29-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4388383/crash-2020-03-26_11.01.29-client.txt)

**Comment by basilserpent** [comment] 2020-03-26 16:23
This is a duplicate of issue #3678

**Comment by BluSunrize** [comment] 2020-03-26 19:50
Indeed.

**Closed by BluSunrize** 2020-03-26 19:50 UTC
