### ISSUE TITLE
[1.16.4] Game crash after fired Phail cartridge by turret.

### ISSUE THREAD

**Issue by YoussefEl457** [BluSunrize/ImmersiveEngineering#4540] opened 2020-12-28 14:51 UTC
i have tested this twice but everytime a turret fires a phial cartridge that is effected by a lingering potion of instant damage 2, the game crashes 
crash log: https://pastebin.com/tZa2hqLQ
maybe it has to do with the lingering effect but you can never be sure.

**Comment by Moleculor** [comment] 2021-01-12 19:54
Probably similar to #4530

**Comment by BluSunrize** [comment] 2021-01-24 21:14
Duplicate of #4520

**Closed as completed by BluSunrize** 2021-01-24 21:14 UTC
