### ISSUE TITLE
Mining drill game crash

### ISSUE THREAD

**Issue by TopNeppu** [BluSunrize/ImmersiveEngineering#4204] opened 2020-08-12 21:04 UTC
### Description of the issue:
I crash the moment I attempted to use the mining drill in a multiplayer server. I tried again in a singleplayer world but it crashed me when I tried to attack a zombie with the drill, but the mining worked for some time.

### Crashlog:
https://gist.github.com/TopNeppu/2033832cb73d553c811aa5030c8637b9

### Versions & Modlist
Forge: 32.0.106
IE: 1.16.1-3.1-112

**Comment by Lendysawk** [comment] 2020-08-12 21:52
Can confirm, got the same crash, and was able to repeat the crash by attempting to mine a Botania Mana Pool with the Mining Drill on both a single player world and a server. Attempting to load back into the world results in an instant crash so the world is forfeit. Same forge and IE builds, much bigger modlist, but seeing as it happens with just IE I don't think that matters.

[crash-2020-08-12_16.41.03-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5066022/crash-2020-08-12_16.41.03-client.txt)

**Comment by malte0811** [comment] 2020-08-13 05:59
Duplicate of #4179

**Closed as completed by malte0811** 2020-08-13 05:59 UTC
