### ISSUE TITLE
[1.16.1] Crash to desktop IE mentioned in Crash Log.

### ISSUE THREAD

**Issue by MikeRootch** [BluSunrize/ImmersiveEngineering#4076] opened 2020-07-14 19:48 UTC
[1.16.1] Crash to desktop.

### Description of the issue:
Crash to desktop during normal gameplay.

Exception in server tick loop
at immersiveengineering.api.excavator.MineralVein.
 
### Crashlog:
https://pastebin.com/2QQdAQqL

### Versions & Modlist used

ImmersiveEngineering-0.16-106
Forge 32.0.66
MC version 1.16.1

###Issue happens with following mod list:

https://pastebin.com/CtPgPG1W

###Issue tested in clean instance with IE, Mekanism and JEI, but could not be reproduced.

ImmersiveEngineering-0.16-106
jei-1.16.1-7.0.0.6
Mekanism-1.16.1-10.0.1.424
Forge 32.0.66
MC version 1.16.1

Hope you can shed some light on this.

Thank you.

**Comment by BluSunrize** [comment] 2020-07-14 19:53
duplicate of #4067, please search next time.

**Closed as completed by BluSunrize** 2020-07-14 19:53 UTC

**Comment by MikeRootch** [comment] 2020-07-14 20:00
Thanks.

Did not know that it wasworld gen i tought i was a mekanism incompatibility.
