### ISSUE TITLE
Crash upon world loading

### ISSUE THREAD

**Issue by Rongmario** [BluSunrize/ImmersiveEngineering#1344] opened 2016-08-28 13:40 UTC
http://hastebin.com/dinehotobu.coffee

**Comment by kane-thornwyrd** [comment] 2016-08-28 15:20
[Please read the guidelines for contributing :smile: 
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by kane-thornwyrd** [comment] 2016-08-28 15:22
Moreover you have 151 mods, is that a modpack you made yourself ?

**Comment by BluSunrize** [comment] 2016-08-28 15:41
Kane, can you please stop copy-pasting this under every issue? I can manage perfectly fine myself, thank you.
In fact, the title of this issue, combined with the given complete log, tells me everything the guidelines ask for, and also make this an easy issue to resolve.

@Rongmario Please update EvilCraft, this issue was caused by them and fixed in latest release =)

**Closed by BluSunrize** 2016-08-28 15:41 UTC

**Comment by kane-thornwyrd** [comment] 2016-08-28 15:45
Okay, sorry
