### ISSUE TITLE
Server(?) crash from Ticking Entity from turret fire (revolver shot)

### ISSUE THREAD

**Issue by Moleculor** [BluSunrize/ImmersiveEngineering#4530] opened 2020-12-24 01:38 UTC
### Description of the issue:
This is in a single player game, but the crash logs are labeled as `crash-2020-12-23_19.28.27-server.txt`, so I'm guessing this *might* impact servers, too? 

Steps to reproduce:

1. Start a fresh world with only JEI and IE installed.
2. Place down a creative capacitor, a turret, wire them both up, and then either supply the turret with redstone power or shift-click it with a screwdriver to turn it 'on'. 
3. Load it up with buckshot.
4. Using a husk spawn egg, spawn as many husks as you can on the same block in rapid succession. 

The game (or server?) should crash in... probably less than ten seconds?

That last step isn't strictly *necessary*, and you can still get the same crash from just a Casull cartridge. I've seen this crash happen with the turret only shooting a single time at a single zombie that wandered close. In fact the fourth crash log provided is from just that. It's just that spamming a bunch of husks in rapid succession and using buckshot instead of Casull seems to really help guarantee the crash, which is otherwise intermittent.

### Crashlog:
https://gist.github.com/Moleculor/4a358b2a605c6872e5e1df47b243dd3e

### Versions & Modlist
```
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		jei-1.16.4-7.6.0.62.jar           
```

**Comment by BluSunrize** [comment] 2021-01-24 21:14
Duplicate of #4520

**Closed as completed by BluSunrize** 2021-01-24 21:14 UTC
