### ISSUE TITLE
[suggestion] Nerf Garden Cloche and add a more fitting upgrade

### ISSUE THREAD

**Issue by Umber0010** [BluSunrize/ImmersiveEngineering#2422] opened 2017-08-14 12:47 UTC
so let's all be honest here, the Garden Cloche is possably the most powerful thing in IE. sure, there are the railguns which can OHKO any basic mob, the excavator which can get you ores at the cost of only power, or the biodeisle generator which can make a healthe 4k RF/T on nothing but wheat, But for it's intended purpose, it's In-godly powerful compared to other alternatives on the market. They're extramly fast, being able to output stacks of items within half an hour, they're cheap, only really taking some basic metals and glass to make, they're eaisier to maintain, only taking a pathetic 8rf/t to function and only needing water to be pumped in. and they're more compact, taking up a fraction of the space that any other farming station would need.

 So, my suggestion is to, first off, nerf the cloche. i would make it so that it grows 50-75% slower, i think that would make other methods of farming a bit more viable.

 the second part of my suggestion is to add an "industrial grower", my idea is for a 5x4 machine that would function similarly to the cloche. however, there are 3 noticeable differences. First, it would have 6 slots for soil and seeds, of course they could be mixed and matched so you could have 3 for wheat and 3 for potatoes. The second difference is that by default it would be about 50% faster to grow than my suggested cloche (so if it gets the 50% reduction it would be about 75% the speed of the current cloche) But the third major difference, and probably the most important one, is that the growth speed could be increased from external sources. for example, placing some greenhouse glass above the grower could increase growth speed by .25, or a fully maxed out rustic beehive could increase it by .50, worms could increase it by .10, ect. 

personally, i think this would be a good way to balance the cloche and add an alternative that fits the general style of the mod IMO. Or i could be stark-raven mad and have no idea what i'm talking about, your pick.

**Comment by HappyPineapple** [comment] 2017-08-15 09:21
i like this part not much else allthough i 

> could be stark-raven mad and have no idea what i'm talking about, your pick.

"industrial grower"

**Comment by codewarrior0** [comment] 2017-08-16 03:07
I feel like the Cloche is only super strong when growing things other than food crops. And even then, the growth rate for crops in the Cloche varies according to the crop - Ender Lillies, for example, take 40 times longer to grow than food crops. Maybe the other resource crops just need to have their growth rates tuned down?

**Comment by BluSunrize** [comment] 2017-08-16 13:41
I'm not going a "bigger" version. No industrial farming machine will happen.

The cloche will probably get nerfed a bit though. Multiple people seem to consider it too powerful.

**Comment by BluSunrize** [comment] 2017-08-16 19:09
^ I halved its speed for now. If someone wants to experiment with it, Jenkins is building a test version rn (build 215)

**Comment by Zebaoth** [comment] 2017-08-17 09:18
Sounds good, the output was way above the usual perfectly fine balance in this mod.
I'd go as far and suggest putting the output to 30% of what it is now.

Make one unit of fertilizer last for at least growing a half stack and improve output by 30%. so it would run at roughly 39% with fertilizer of what it is now.

My thought behind this is that with immersive engineering you get the excavator for basically infinite supply of ores, automated workbenches and assemblers and metal presses for mass production.
Having to get this mass production rolling so you can build garden cloches in bulk to guarantee a steady supply for the squeezer and fermenter would just add a fine end game goal to this mod.

**Comment by codewarrior0** [comment] 2017-08-17 09:33
When I first tried out the Cloche with a few friends, we were surprised that it would run with only water as fertilizer. The guys were all getting set to build a skeleton farm, too. Maybe what it needs is a much lower base speed and a much greater speed gain from fertilizers?

**Comment by xenxero1** [comment] 2017-08-17 13:44
Honestly for balance it might make more sense for it to go to 1.5x normal crop growth speed, and then require fertilizer of some sort (Looking at you, stacks and stacks of forestry fertilizer) to operate at a higher speed. Higher quality fertilizer=better speed?

**Comment by HappyPineapple** [comment] 2017-08-18 06:11
make it only aply in survival mode though cause in creative mode it takes up space

**Comment by XFactHD** [comment] 2017-08-18 10:10
As far as I know it is almost impossible to limit a certain behaviour of a block to a certain game mode.

**Comment by AEnterprise** [comment] 2017-08-18 11:06
making it faster when placed in creative would only cause trouble i think. if you want to make a test setup in a creative test world to see how many you actually need for a build it would be realy annoying if you constantly have to swap to survival to place them so they have the right speed

**Comment by BluSunrize** [comment] 2017-08-18 12:12
Yeah what they said.
Creative gets no speedboosts, that's hilariously impractical.

**Comment by BluSunrize** [comment] 2017-08-18 12:12
Yeah what they said.
Creative gets no speedboosts, that's hilariously impractical.

**Comment by Umber0010** [comment] 2017-08-20 23:35
perhaps it could be only 1.25-1.5x the growth speed, but blocks or items that effect growth seed, such as Actually Additions Greenhouse glass, can effect crops inside the cloche, no idea how hard that would be to implement though

**Comment by BluSunrize** [comment] 2017-08-21 06:40
Basically impossible.

**Comment by PrincessRTFM** [comment] 2017-08-22 14:01
Huh. I would have though it would be relatively easy, if perhaps not a good idea. Each time the cloche goes to advance growth, check above it (perhaps within a certain distance so you don't check a hundred or more blocks every growth tick) to see if AA Greenhouse Glass is there.

Of course, as I wrote this, I realized: blocks like that probably have their own checks that you can't just jump into, and even if you did this you'd need an internal list of applicable blocks because you probably can't the modifier programmatically from whatever happens to be in place. And that only applies to AA GG, which is directly above the cloche.

No disrespect, you say it can't/won't be done and I accept that, but can I get a short technical explanation as to why you can't do that, or... I dunno, implement fake the cloche being a plant and intercept the effects of growth accelerants to affect the cloche's plant? I used to do a bit of modding on 1.7.10, and I'm just a little curious.

**Comment by xenxero1** [comment] 2017-08-22 14:13
inexperienced here; can't you theoretically code the multiblock to pickup on checks/events that SHOULD affect crops, and then subsequently respond by firing certain events or changing variables within the system? Almost treat the multiblock (or parts of it) as a crop itself, with internal number handling for how to deal with things like GH glass, worms, sprinklers ect? Just a thought.

**Comment by BluSunrize** [comment] 2017-08-22 14:18
There are many different things that affect growths in plenty different ways.
AA's Greenhouse Glass is only *one* example.

Also, the whole point of this issue was pointing out that hte cloche is OP as is, having it stack with other means of speeding up growth would only worsen the issue O_o

**Comment by EvilCooky** [comment] 2017-08-23 09:43
Here's an idea concerning fertilizer.

Instead of putting Fertilizer directly into the Cloche, why not use the mixer to mix water with different fertilizer items and create "Fertilized Water", using that to increase growth speed in Cloches.

There could be different types of liquids that speed up the process further but are also more expensive to produce.
Maybe we can even have fertilizer liquids that are especially efficient for one type of crop.

**Comment by mindforger** [comment] 2017-08-23 10:09
@BluSunrize i don't know how familliar you are with the torcherino and if it made it's way to 1.12 yet but i wanted you to be aware of it, because as far as i understand it, it is creating fake ticks on TileEntitys inside it's AoE

i tested it with the excavator and it did nothing because the wheel rendering decided when an block of ore is generated as far as i understood it, while the power demand increased because the power is calculated in the tile tick or something like that

you should maybe check what happens to your devices (especially this one) when there are fake ticks generated from somewhere else

**Comment by malte0811** [comment] 2017-08-23 10:21
I'd say just add 'Torcherino and similar mods' to the unsupported section of the contributing guidelines. Those mods are quite hacky AFAIK and break balance quite badly. 
That section needs to be updated anyway, KCauldron no longer exists and was somewhat replaced by SpongeForge.

**Comment by BluSunrize** [comment] 2017-08-23 10:39
Anything that causes extra ticks on tile entities is terrible and can fuck off <3

**Comment by mindforger** [comment] 2017-08-23 10:50
well ... the torcherino could interfere by accident 
i just wanted you to know that such trickery exists and could potentially lead to fatal effects ... so a simple test against multi ticks would be not bad to guard against a dozends "game is crashing when machine is next to torcherino" 

i am still amazed that nobody complained yet about the fact the generator is producing n-times the power when used with a torcherino while the excavator is just consuming more but not producing more

**Comment by codewarrior0** [comment] 2017-08-23 10:55
The excavator is actually two machines. You would have to place the torcherino(es) so both the excavator and its bucket wheel are getting boosted.

**Comment by EvilCooky** [comment] 2017-08-23 11:01
I like how Extra Utilities deals with tick speedups.
When the Quantum Quarry detects it's being sped up, it will simply explode :P

**Comment by dannydjdk** [comment] 2017-08-26 15:40
I like the idea of 1.5x base growth rate. That seems very reasonable considering the cost.
However, I haven't seen any discussion of cost yet. The thing that troubles me most about the cloche isn't just that it's OP, but that it's OP and cheap. It would feel more balanced if it required significantly more resources to use and more expensive materials to craft.
Farms offered by Forestry, EnderIO and a few other mods, are all more expensive and challenging to make and maintain than the cloche, yet the cloche is stupendously more powerful. While I'm not usually one to complain about OP things, I think they are better when gated for late game in order to prevent making all other solutions obsolete. Even greenhouse glass from Actually Additions (which some have complained is OP) is expensive and requires significant infrastructure to craft, yet it's pointless compared to the cloche.

**Comment by kane-thornwyrd** [comment] 2017-08-26 16:04
So, your point is that because some mods' solutions to grow plants are expensive, Blu should feel compelled to change his perfectly acceptable mechanics ?

Okay He should somehow take the ecosystem of Modded MC in account, but he never pledged and oath  to impair any feature that would not be appraised by a very small fringe of its players for the sake of the ecosystem.

@dannydjdk you want more expensive stuff, then learn Crafttweaker and tweak the crafting recipes !

**To those who want to nerf the cloche**, did you pay attention to the config available ? I mean, with that:

        # The Flux per tick the belljar consumes to grow plants
        I:belljar_consumption=8

        # The amount of ticks one dose of fertilizer lasts in the belljar
        I:belljar_fertilizer=6000

        # The amount of fluid the belljar uses per dose of fertilizer
        I:belljar_fluid=250

You should be able to achieve any balance you need for your modpack ! Right ?!

**Comment by codewarrior0** [comment] 2017-08-26 17:08
Wrong! The missing config is a multiplier for the belljar's growth rate!

CraftTweaker can make the Cloche more expensive to build, and the configs you listed can make it more expensive to operate, but those two options lack granularity - if you decide the Cloche's power means it needs to cost 100 ingots to build, you don't have the option of making it 1/10 as powerful and only cost 10 ingots.

**Comment by kane-thornwyrd** [comment] 2017-08-26 17:56
Ok, sorry, not wrong but incomplete.

Right, it lack the growth multiplier, but the background grief remain the supposed unbalance of it, without even questioning the analysis grid of this "unbalanced feel".

More parameters are missing, like:

- What are the possibilities of the cloche: because you can't grow trees inside, the mod support is, most of the time, fortuitous.
- The power network required: You can't simply plug rows of them to your power source, you have to use transformers to build a proper grid, except if you use conduit of a third party which is an issue at the modpack level.
- The versatility: You can only grow one plant at a time.
- The outputs are not filtered.
- It consume water at a decent rate, which require at least to maintain a pump and a pipe network.

My point is that all the grief toward the cloche come from large modpack players, modpacks which doesn't take the power of the cloche in account in their configurations. But if you play with a very lightweight modpack the issue is not the same, or to be fully honest there is no issue.

**Comment by BluSunrize** [comment] 2017-08-26 20:04
I *nerfed* the growth rate. That is what people were asking for. I halved it. It's a lot less OP now.

I'm not going to *buff* it again now and increase the cost. What's the point?

**Comment by kane-thornwyrd** [comment] 2017-08-26 20:23
Having the rate as a conf entry ?

**Comment by BluSunrize** [comment] 2017-08-26 20:38
Not everything needs to be configurable.

Both here and reddit were asking for a nerf. This in itself is a rarity, given how reddit is mostly the very vocal, hilarious FTB powergamers. My approach to nerfing it was for now flat out cutting its speed in half.
The commit regarding that had a positive reception and then nothing. Now, a while after release, people are suddenly asking for boosts, compat with other accelerators (AA glass) and configs.
Honestly, I'm quite content with leaving it like that. People don't seem to think it stupidly OP anymore, and I'm totally fine with that.

**Comment by dannydjdk** [comment] 2017-08-26 22:29
@kane-thornwyrd, my point was simply that the reason it feels unbalanced to me is because the low cost does not seem to match the high output. I mention other mods as examples of farms that are balanced very differently, not to suggest that every mod maker has to comply with that balance.

Balance is not black and white. Every mod has it's own balance and changes the balance of the game. It's up to modpack makers to decide how they want to balance their packs through mod selection and configuration adjustments. Yes, crafttweaker and the configuration options you mentioned are indeed sufficient to fully address the issue of cost.

But, since this issue had not been closed yet, I assumed the issue of "unbalance" was still an open one looking for solutions. And, since cost had not yet been discussed, I brought it up as an alternative to exclusively nerfing the cloche.

**Comment by kane-thornwyrd** [comment] 2017-08-26 22:53
@BluSunrize said:
> Not everything needs to be configurable.
Duly noted. After all you're not paid for. I guess we meet the full measure of your devotion, until that point.
I adjust my contributions.

**Comment by Zebaoth** [comment] 2017-08-28 11:22
The garden cloche is in a pretty good place now, decreasing its speed to 30% would have been fine as well.
With the new settings you need to build at least 12 cloches to keep one squeezer and fermenter busy.
On top of having to build more garden cloches to keep up you also need to make more connectors and wires, which further help balancing out the garden cloche.

All in all pretty satisfied with the new settings.

**Comment by BluSunrize** [comment] 2017-09-09 15:47
Closing this, since for now a reasonable ballance seems to have been reached

**Closed by BluSunrize** 2017-09-09 15:47 UTC
