### ISSUE TITLE
TileEntityMultiblockMetal - Exception (Crash)

### ISSUE THREAD

**Issue by Rob5Underscores** [BluSunrize/ImmersiveEngineering#1844] opened 2017-01-09 11:20 UTC
Running SpongeForge 1.10.2-2171-5.1.0-BETA-2010 and Immersive Engineering 0.10-53

http://pastebin.com/zWeFmmXK

**Comment by BluSunrize** [comment] 2017-01-09 13:34
Duplicate of #1816

**Closed by BluSunrize** 2017-01-09 13:34 UTC
