### ISSUE TITLE
Assembler Crash 1.11

### ISSUE THREAD

**Issue by waddon1** [BluSunrize/ImmersiveEngineering#2203] opened 2017-06-21 18:28 UTC
I'm hosting a 1.11 server, and whenever I connect an Assembler to power and it begins crafting, the server crashes. The crash has occurred every time I've done this.
[crash-2017-06-21_20.35.21-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1092507/crash-2017-06-21_20.35.21-server.txt)

**Comment by malte0811** [comment] 2017-06-21 19:51
Duplicate of #2196. Fixed for the next release.

**Closed by malte0811** 2017-06-21 19:51 UTC
