### ISSUE TITLE
[1.10.2-0.10 - 44] CTD on Craft of Engineer's Wirecutters

### ISSUE THREAD

**Issue by staticextasy** [BluSunrize/ImmersiveEngineering#1567] opened 2016-10-11 04:56 UTC
MC Version 1.10.2 
Immerssive Engineering v 0.10 - 44
Forge Version: Build 1.10.2-12.18.2.2099

**What Happens**:
When attempting to craft Engineer's Wirecutters in crafting bench, CTD occurs when pulling item from the bench.

**Reproducible**: Yes, this happens in Vanilla crafting benches as well as TiCo Workbenches.

Crash Log:
http://pastebin.com/pws00mCa

**Comment by croftyraider** [comment] 2016-10-11 05:45
Can confirm that it does it from the Tinkers bench as well.

**Comment by BluSunrize** [comment] 2016-10-11 07:49
Duplicate of #1549
Please use the search function next time.

**Closed by BluSunrize** 2016-10-11 07:49 UTC
