### ISSUE TITLE
[1.12.2] Wires visually disappear on client restart.

### ISSUE THREAD

**Issue by Nibbler230** [BluSunrize/ImmersiveEngineering#2922] opened 2018-04-01 05:44 UTC
When ever I login to my world for the first time all the wires have visually disappeared. They are still there and not burning up due to high voltage, and power is still being transferred. This is especially annoying for trying to avoid HV or un-insulated wires from zapping you.
![2018-03-31_23 28 14](https://user-images.githubusercontent.com/20622057/38170227-bfa46c7e-353c-11e8-9295-61390367b380.png)

![2018-03-31_23 28 50](https://user-images.githubusercontent.com/20622057/38170229-c647ac3a-353c-11e8-8e5c-cf45d9c7db7d.png)

Connecting another wire to a relay will make every wire connect on that particular relay re-appear. Also logging out and back in without restarting the client seems to fix it.
I am playing on Modern Skyblock 3.2.0.1 on a server, the server doesn't get restarted, just my client.
Forge-14.23.2.2634, Immersive Engineering 0.12-80
Optifine is not installed.

I hope that is enough information. If you need anything else please let me know.

**Comment by malte0811** [comment] 2018-04-01 05:47
Duplicate of #2893, fixed for the next release.

**Closed by malte0811** 2018-04-01 05:47 UTC
