### ISSUE TITLE
[Feature Request] Metal Press Mold: Packing/Splitting 

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2482] opened 2017-09-11 16:22 UTC
The Packing Mold would come in 2 variants, large and small, and would try to craft any 9 or 4 of the same input item in a 3x3/2x2 recipe.
The Splitting Mold would try to craft any single item in a 1x1 recipe.

Assemblers don't offer this kind of "don't care about what item" approach, and the task feels dumb enough to hand to rather hand to the less advanced press. Also this might well lead to seeing more presses around, and they look awesome :)

Also could allow for "non-crafting recipe spawned" custom recipes, say give a recipe to split water melons from the cloche into slices so it might be used for further autocrafting (biofuel production aside, this would be nice for use with i.e. harvestcraft). Or uh... packed ice? idk.

Hope this wouldn't be too much of a pain, since it deviates from the way the mold recipes usually work.

**Comment by BluSunrize** [comment] 2017-09-12 13:55
With the limit of "same input" this could be doable.
I kinda like the idea, I'll take a look.

**Comment by BluSunrize** [comment] 2017-09-12 17:32
It turned out to be a bit more difficult than expected, since it required dynamic recipe generation as well assyncing those to the client, but I got it working.

I will not be adding an "unpacking" mold, as that would allow uncrafting items like craftign tables and stuff, which is a thing mods generally shouldn't enable. Also, checking for uncrafting is way more complex.

What is currently missing are recipes for the two molds, and I'm very open to suggestion, because I have no idea myself. Doing the usual mold recipe with a crafting table in the middle seemed sensible, but only  for the 3x3.

**Comment by MalkContent** [comment] 2017-09-12 21:27
Just to be sure, have you considered not doing reverse crafting, but single item crafting? .. :D

**Comment by BluSunrize** [comment] 2017-09-12 21:29
Single item? Like...what? xD

I like "packing" for a name, I'm definitely going with it. Just missing recipes.

**Comment by MalkContent** [comment] 2017-09-12 21:30
Like, how you can craft a single block of iron into 9 ingots. A 1x1 grid craft. A single item :)

**Comment by BluSunrize** [comment] 2017-09-12 22:02
Ooooh, right.
Hrrm, that brings up odd edgecases though.

Does one only allow things that craft into 4 or 9 pieces, to serve as an "unpacking" mold? Or would it allow any single item input? Also what would it look like and be named?
Definitely the trickiest out of the three.

**Comment by MalkContent** [comment] 2017-09-12 22:25
I had called it "splitting" because it splits one thing up into more things. And you are right about the edge cases, but actually the only things that i could come up with were logs into planks (which i found fitting enough), flowers to dye and harvestcraft's crop-to-seed.

**Comment by BluSunrize** [comment] 2017-09-13 07:04
I was thinking of Tema's Ender Pearl splitting recipe for instance, since that makes 8 shards.
Wood is also definitely a problem, because that would be a 1 to 4 ratio for the sake of allowing it in, but I want to make a sawmill at some point.

**Comment by mindforger** [comment] 2017-09-13 07:17
well .. ingots sawn from a block seem legit imho :) 

would not be an issue in my opinion to let the whole "unpacking" happen in the saw mill in the end while the compacting mold only is for the other way around
but i still think this would be more likely a job for the squeezer as you could get around logic inconsistencys of a mold beeing unable to withstand the pressure to compress any material harder than the mold ... the suqeezer is already having a job besides pressing seeds, it is already used for hop graphite, so combining recipes would work well inside it

**Comment by BluSunrize** [comment] 2017-09-13 07:38
Squeezer has a rather different process handling though, due to allowing multiple at the same time. Additionally the point was that the cheap metal press could do this, rather than the assembler. Squeezer is also more expensive and takes up more space.

Oh and I already wrote all the code for the press and don't want to rip it all out again. x3

**Comment by mindforger** [comment] 2017-09-13 07:41
yeah sure i just wanted to hand in another perspective :D but i would LOVE to see a sawmill in IE

**Comment by MalkContent** [comment] 2017-09-13 07:43
I am not sure if I get the point with the amount of output items. Are you not getting the number of output items from the crafting recipe?
And I thought the implication of the sawmill was to offer slightly higher yield or some other benefit.

**Comment by MalkContent** [comment] 2017-09-13 08:45
For the recipe, maybe the 2x2 mold could just have a log (aka a raw crafting table x) ) in the middle. I tried to think of the basest items you can harvest without needing to get a crafting table for tools, and the wooden ones have a connection to the crafting table, because they're made from wood. Still not terribly intuitive.
Had a thought with the crafting table in the middle and 4 pistons in the outer corners for the 3x3 mold and for the 2x2 just 2 pistons in opposing corners. Kind of feels off, because of using "active" components in a mold, on the other hand it might be more intuitive.
As for the potential unpacking/splitting mold (sorry, I am feeling bad and pushy by now, I am perfectly fine without it ^^), I had imagined kind of a slicy thing in the middle, like an X from two blades. Ideas to suggest that would be an Iron Axe (because splitting), any other blade, or steel wire arranged as an X.

**Comment by EvilCooky** [comment] 2017-09-13 09:17
I think that "unpacking" mold would be best used for crafting recipies that craft a single item.
I remember a situation from the old 1.7 days where I had a bunch of Pams Harvestcraft crops, but I only needed the seeds. So I either had to set up a crafter for each type of crop, or find a solution that doesn't care about what item comes in and just attempts to craft it by itself.

**Comment by BluSunrize** [comment] 2017-09-13 10:29
Malk the problem was that the "unpacking" mold was designed to just unpack things that could be packed.
One block back into 9 ingots, for instance. If it allowed for 1 log to be turned into 4 planks (which isn't an unpacking, since you can't make logs out of planks) that's taking the functionality of a possible sawmill in the future.

So I would have to effectively check if an item crafts into 9 or 4 pieces, and if it does, if those 9/4 pieces make the correct result again.

**Comment by MalkContent** [comment] 2017-09-13 11:25
Oh, if you really want to do unpacking only, you just wrote it yourself basically :D

```
ItemStack getUnpackOutput(inputstack) {
	directRecipes = getRecipesOf1x1Craft(inputstack)
	for(Recipe curRecipe : directRecipes) {
		possibleOutput = curRecipe.getOutput()
		packedRecipes = getRecipesOf3x3Craft(possibleOutput)
		for(Recipe curPackedRecipe : packedRecipes) {
			if(curPackedRecipe.getOutput() == intputstack) {
				return possibleOutput();
			}
		}
		packedRecipes = getRecipesOf2x2Craft(possibleOutput)
		for(Recipe curPackedRecipe : packedRecipes) {
			if(curPackedRecipe.getOutput() == intputstack) {
				return possibleOutput();
			}
		}
	}
	return null;
}
```

**Comment by BluSunrize** [comment] 2017-09-13 11:41
I wasn't being lazy about the code was simple enough to write. It was more the case of "how do we specify unpacking", if you catch my drift.

**Comment by MalkContent** [comment] 2017-09-13 13:08
"Unpacks things that can be packed with packing mold, if they are able to be unpacked by regular crafting (i.e. no crafting table back to planks)."
Would be my go at it

**Comment by PrincessRTFM** [comment] 2017-09-13 18:45
Alternatively, instead of basically blacklisting things that don't fit, whitelist the things that do. Check that the input item is registered in the oredict as `block*` AND that the items it produces are registered as `ingot*` or `gem*`. For more strict recipes, also require that the bit after `block` in the oredict name matches the bit after `ingot` or `gem` for the output.

Additionally, another alternative is to only implement "splitting" or whatever it gets called for specific oredict entries and leave everything else up to the user via Minetweaker/Crafttweaker integration.

**Comment by MalkContent** [comment] 2017-09-13 19:56
\o/ hooray! once again, sorry for being a nag.

@PrincessRTFM
The way it's done now, there is no blacklisting. Its crafting is dynamically limited to recipes that undo unpacking, but no fuss with lists :)

**Comment by PrincessRTFM** [comment] 2017-09-13 21:17
Oh cool! That sounds like probably the best way to do it. Question though: what if recipes are added via MT/CT scripts that make new pack/unpack recipes that would be considered valid by whatever check is currently implemented? Are they also supported? If so, how well: can you reload scripts and have the changes reflected, or is it limited to whatever is set on world load?

**Comment by BluSunrize** [comment] 2017-09-13 23:29
Reloading scripts is something you don't generally do in gameplay, but with a script that was present upon starting the instance, it works.

I don't actually check all recipes at startup. I just check for the specific ones when people try to insert into the machine. Saves me having to crawl through the entire registry at game launch.

**Comment by BluSunrize** [comment] 2017-09-14 10:23
This is a thing now, so I'll close this ^^

**Closed by BluSunrize** 2017-09-14 10:23 UTC
