### ISSUE TITLE
[1.16.1] Treated Wood Recipe

### ISSUE THREAD

**Issue by benmontour** [BluSunrize/ImmersiveEngineering#4277] opened 2020-09-05 23:12 UTC
### Description of the issue:
The recipe for treated wood, 8 planks around a bucket of creosote, no longer works in 1.16.1-4.0.0-118. Does not show in JEI either. 

I am playing using the Valhelsia 3 modpack. They suggested opening an issue with you as their latest update included the Immersive Engineering 1.16.1-4.0.0-118 update.

### Versions & Modlist:

**Minecraft:**  `1.16.1`
**Valhelsia 3:**  `3.0.15`
**Immersive Engineering:**   `1.16.1-4.0.0-118`
**Forge:**   `32.0.108`

**Comment by CBINKERTOP68** [comment] 2020-09-06 06:36
Hello, just downloaded the pack today and am having the same exact issue. Thought I was crazy bc it works in creative mode. Without the treated wood the pack can’t progress, please help!

**Comment by Shikareth** [comment] 2020-09-08 11:10
Same issue on Valhesia3-3.0.15 [IE-1.16.1-4.0.0-118]

`[m[1;31m[13:05:48] [Render thread/ERROR] [KubeJS Server/]: Parsing error loading recipe immersiveengineering:crafting/treated_wood_horizontal: java.lang.IllegalStateException: Tag forge:creosote used before it was bound`

**Comment by malte0811** [comment] 2020-09-08 11:42
Does it work if you remove KubeJS?

Edit: Or if you update it? According to https://github.com/KubeJS-Mods/KubeJS/issues/14 it should be fixed.

**Comment by bsx** [comment] 2020-09-08 12:42
Removing KubeJS restores the recipe. Updating is not an option as kubejs-2.7.2.59 contained in Valhelsia3 is already the latest version available for 1.16.1. It also already contains the fix for KubeJS-Mods/KubeJS#14, so this new issue seems unrelated.

Edit: Downgrading ImmersiveEngineering from 4.0.0-118 to 3.2.0-115 also restores the recipes, even with KubeJS present.

**Comment by BluSunrize** [comment] 2020-09-13 14:43
Closing this, due to it being caused by KubeJS interaction. Monitor their issue & updates for a fix.

**Closed as completed by BluSunrize** 2020-09-13 14:43 UTC

**Comment by dylan-grafmyre** [comment] 2021-01-09 09:04
for posterity try a /reload on a live server, it might fix the recipe
