### ISSUE TITLE
[1,12.2] Alloy Kiln performance issue when not working - only one input slot occupied.

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#2960] opened 2018-04-23 06:03 UTC
### Description of the issue:

When you put anything in one input slot, the Kiln starts to tick very hard when it isn't doing any work at all.  This continues until you remove the items from the Kiln.

Find attached samper nps file.
[kilnoneinportslot.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1936854/kilnoneinportslot.zip)

Contents
![2018-04-22_23 57 31](https://user-images.githubusercontent.com/4427684/39109320-a6fa77aa-4689-11e8-8203-e00b8d0574a0.png)

Bad kiln straight ahead in red, empty kiln to the left.
![2018-04-22_23 56 19](https://user-images.githubusercontent.com/4427684/39109322-ab977182-4689-11e8-805d-cec1c5b27b4a.png)

### Versions & Modlist

Mod list- https://minecraft.curseforge.com/projects/towncraft

ImmersiveEngineering-0.12-80.jar

**Comment by ProsperCraft** [comment] 2018-04-23 19:56
I started a new pack with only the immersive suite of mods, and here are the results from a single player game.  It is far less drastic but nonetheless if you have things in it, even if it isn't cooking, it ticks 24 times harder then the kiln next to it with nothing in it.  Is it trying to auto output or something? 
Why is it ticking when not doing work?

Kiln full not cooking-
![2018-04-23_11 23 49](https://user-images.githubusercontent.com/4427684/39149957-05e1148a-46fe-11e8-9068-aa0c924bc667.png)
Inventory-
![2018-04-23_11 27 43](https://user-images.githubusercontent.com/4427684/39149969-0df6e1b8-46fe-11e8-943c-e4c4169eda1f.png)

NPS-
[kilnsingleplayer.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1939788/kilnsingleplayer.zip)

**Comment by BluSunrize** [comment] 2018-04-23 20:01
Okay, performance drop seems to be caused by ItemStack init calling Capability events.
I believe Malte had mentioned this on a previous occasion, I don't quite know what his fix was for that, so I'm leaving this open to be fixed in IE build 82.

**Comment by malte0811** [comment] 2018-04-23 20:05
I don't have a fix for that besides trying to reduce item stack allocations. And probably talking to the guy who takes up so much time in initCapabilities, but I'll do that when I'm on my laptop and have the data to prove they're causing lag with their profiling mod.

**Comment by BluSunrize** [comment] 2018-04-23 20:17
Hmm.
Well we can at least look into making the Alloy Kiln not search for recipes when only one item is in there, that should cut down on impact a bit.
It's for makign alloys, it should never have a single-input recipe anyway.

**Comment by ProsperCraft** [comment] 2018-04-23 20:25
If output= full then complete shutdown as well?

When you say the guy? who are we talking about @malte0811 ?

**Comment by malte0811** [comment] 2018-04-25 15:07
@aikar Is `TimingHandler.stopTiming` supposed to take 4-5% of CPU time (About 4% in this snapshot, I think I saw 5.something% in another snapshot from the same server)? Most of the performance issues reported by @ProsperCraft boil down to `ItemStack` initialization being a lot slower than usual, mostly due to the timings event handler. Is that a known issue/normal?
The profiling data in the screenshot below is from Player's sampler mod, viewed in VisualVM. The percentage in the total time column doesn't really matter, as it's relative to the sum of all total times, which is obviously much more than the total CPU time (about 45 seconds).
![image](https://user-images.githubusercontent.com/10406104/39254146-b7104f3a-48a9-11e8-8b2b-aded1f03ea0e.png)

**Closed** 2020-06-06 11:49 UTC
