### ISSUE TITLE
[1.16.1] Crash when opening main menu and/or breaking blocks

### ISSUE THREAD

**Issue by TheVillageid10t** [BluSunrize/ImmersiveEngineering#4092] opened 2020-07-17 13:50 UTC
### Description of the issue:

Single player

World loads up, run around for a bit so that render distance can catch up and fps can attempt to stabilize, attempt to open a menu (inventory/main ESC menu) crash or attempt to interact with a block (break dirt, break sand, break sugarcane)

P.S. i know there's a new Forge version 32.0.67, but it doesn't work for a good majority of the mods i have in this current pack (mainly because they're gamerule related mods and because forge 32.0.67 broke all of those type of mods) and if possible would rather not update until at least 3/4 of what i'm running gets updated to it.

### Crashlog:
https://paste.ee/p/WLEeG

### Versions & Modlist

net.minecraftforge:32.0.63

NetherPortalFix_1.16.1-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 DONE}
		petnames-
		curiousshulkerboxes-
		HealthOverlay-
		vanillaboom-
		paperbooks_
		pitg-
		guildedarmor-
		BetterCaves-
		BetterTitleScreen-
		XaerosWorldMap-
		CookingForBlockheads-
		Controlling-
		Placebo-
		NoFog-
		Simple_Tweaks-
		Powah-
		rangedpumps-
		Bookshelf-
		guardvillagers-
		u_team_core-
		randompatches-
		cryingghasts-
		mcw-doors-
		MekanismGenerators-
		shulkerbox-
		Ma-Essentials-
		CubicVillager-
		NoIncreasingRepairCost-
		refinedstorage-
		SimpleOres2-
		structure-gel-api-
		ClearView-
		PackMenu-
		BladeCraft-
		improved-stations-
		enchantingcmds-
		ToolStats-
		MekanismAdditions-
		valhelsia_structures-
		Lollipop-
		curios-FORGE-
		Patchouli-
		leap-
		rndbmflowers-
		collective-
		Clay+WorldGen-
		doomangelring-
		gk_unbreakable-
		EndReborn-
		betbeacpl-
		lottaterracotta-
		expandedstorage-
		buildersaddition-
		MekanismTools-
		nametagtweaks-
		curiouselytra-FORGE-
		cherishedworlds-FORGE-
		cloth-config-forge-
		InventoryEssentials-
		BetterBurning-
		MoreThanAPickaxe-
		SurvivalPlus-
		BiomesOPlenty-
		infinitetrading-
		FastLeafDecay-
		ServerTabInfo-
		BetterMineshaftsForge-
		Random-Fhings-
		dwarfcoal-
		ClientTweaks-
		doubledoors-
		TrashSlot-
		torchslabmod-
		mining-helmet-
		jei-
		JEIEnchantmentInfo-
		FallingTree-
		the-conjurer-
		Abnormals-Core-
		Fruitful-1.16.1-
		Bamboo-Blocks-
		Berry-Good-
		Enhanced-Mushrooms-
		Mekanism-
		caelus-FORGE-
		invtweaks-
		Rotten+Flesh+to+Leather+
		Waystones_
		RingOfRepair-
		light-overlay-
		sweetconcrete-
		comforts-FORGE-
		NaturesCompass-
		NetheriteOre-
		decorative_blocks-
		BotanyPots-
		curioofundying-
		snowundertrees-
		bedspreads-FORGE-
		additional_lights-
		ToastControl-
		JEITweaker-
		CraftTweaker-
		extradisks-
		Waddles-
		dash-
		ironchest-
		CraftingTweaks_
		theoneprobe-
		sillystuff-
		MouseTweaks-
		ImmersiveEngineering-
		inventorytotem_
		forbidden_arcanus-
		Savage-and-Ravage-
		betconduitpl_
		Xaeros_Minimap
		RefinableResources
		pamhc2foodcore-
		serverconfigupdater-
		lava-monster-
		FastWorkbench-
		StorageDrawers-
		DoubleSlabs-
		lanterncolors-
		InventoryHud_
		structurize-
		yisthereautojump-
		WorldHandler-
		FastFurnace-
		AppleSkin-
		engineersdecor-
		aawitherskull_
		randomblockplacement-
                refinedstorageaddons-
		CraftingCraft
		CosmeticArmorReworked-
		overloadedarmorbar-
		step-
		DefaultOptions_
		alllootdrops-

**Comment by BluSunrize** [comment] 2020-07-17 13:58
Duplicate of #4067

Please search next time

**Closed as completed by BluSunrize** 2020-07-17 13:58 UTC
