### ISSUE TITLE
[Suggestion]Make the Trident a powerful reusable and configurable ammunition for railgun

### ISSUE THREAD

**Issue by MasterIMLG** [BluSunrize/ImmersiveEngineering#4866] opened 2021-06-22 16:44 UTC
The vanilla Trident is so lack of lethality as a weapon wether used as melee weapon or ranged weapon. 
What's more, under the circumstance that multiple mods installed, the Trident is also replaceable by various of means of transport or lightning summoning, losing its last unique feature as a tool.
So if I may ask, would you please to make the Trident an railgun ammunition that can be affected by railgun damage modifier in configure file, and increase its range while launched by a railgun?

**Comment by BluSunrize** [comment] 2021-06-22 17:06
Duplicate of #4865

**Closed as completed by BluSunrize** 2021-06-22 17:06 UTC
